kata-containers/tests

.pullapprove.yml, CODE_OF_CONDUCT.md
* Add the OpenStack Foundation CoC
* Add pullapprove support
=> Code of Conduct and pullapprove

integration/docker/attach_test.go, integration/docker/commit_test.go, integration/docker/cp_test.go, integration/docker/create_test.go
These commits will test docker attach, docker commit, docker cp and
docker create functionality.
Fixes #38
=> tests: Add docker integration test for attach, commit, cp and create.

integration/docker/diff_test.go, integration/docker/env_test.go, integration/docker/exitcode_test.go, integration/docker/export_test.go
This will test docker integration functionality for export, diff, env and
exit code.
Fixes #44
=> tests: Docker integration tests for export, diff, env and exit code.

.ci/go-test.sh, .ci/static-checks.sh
Correct issues found by `shellcheck(1)`.
Fixes #47.
=> Clean up ci scripts

integration/docker/docker.go, integration/docker/info_test.go, integration/docker/inspect_test.go, integration/docker/load_test.go
Add docker load, inspect, info test.
Fixes #49
=> tests: Add docker integration test for info, inspect and load.

integration/docker/logs_test.go, integration/docker/package_manager_test.go, integration/docker/pause_test.go, integration/docker/port_test.go
Also add a test to verify that apt and dnf work
correctly inside a container.
Fixes #55.
=> tests: Add docker logs, pause and port tests

integration/docker/user_test.go, integration/docker/volume_test.go
Add docker integration tests for docker volume, docker search.
Fixes #66
=> tests: Docker integration tests for volume, search.

.ci/install_qemu_lite.sh, .ci/install_runtime.sh, .ci/setup.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh, cmd/container-manager/manage_ctr_mgr.sh
This will install Kata Containers on Fedora
Fixes #79
=> ci: Setup scripts for Fedora

command.go, integration/docker/docker.go, integration/docker/run_test.go
This will test stdin with docker run.
Fixes #74
=> tests: Add docker run stdin integration test.

integration/docker/terminal_test.go, integration/docker/top_test.go
This commit adds tests to verify the `docker top`
command and tests to verify terminal is properly
set.
=> tests: Add terminal and top tests

Dockerfiles/BuildTest/Dockerfile, integration/docker/build_test.go
This test the docker build command.
Fixes #96
=> tests: Add docker integration build test.

.ci/run.sh, Makefile, cmd/log-parser/Makefile
Run the unit tests under JenkinsCI and add a few messages showing what the CI run script is doing
Fixes #104.
=> CI: Run unit tests under Jenkins

.ci/go-test.sh, bundle.go, functional/main_test.go, integration/docker/docker.go
Fix the issues found by `.ci/static-checks.sh` plus skip testing test packages which need special setup.
Fixes #138.
=> Lint fixes

.ci/static-checks.sh
Don't ignore a repository just because it contains sub-modules - filter
the packages those sub-modules provide out of the list of all packages
and run the static checks on the remaining packages.
This is specifically for the https://github.com/kata-containers/runtime
repo. It used to contain simply submodule references to other
repositories. However, now it contains actual code content (`cli/` and
`virtcontainers/`) but the original check script logic was ignoring
*all* packages below runtime. This is incorrect since (now) both the
`cli` and `virtcontainers` packages should be checked when a runtime PR
is raised.
Fixes #136.
=> CI: Fix handling of sub-modules in static checks script

cmd/log-parser/README.md
Fixes #154
Signed-off-by: Ruidong Cao <caoruidong@huawei.com>
=> docs:Correct file name in log-parser final step

Makefile, integration/docker-compose/Dockerfile, integration/docker-compose/app.py, integration/docker-compose/docker-compose.bats, integration/docker-compose/docker-compose.yml, integration/docker-compose/requirements.txt
Test docker-compose functionality by running a REDIS application.
Fixes #108
=> tests: Add docker-compose tests.

.ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh, .ci/static-checks.sh
Validity check any versions databases found.
Fixes #160.
=> CI: Validate versions database

.ci/jenkins_job_build.sh
Test to see if codecov.io works without a token with Jenkins.
Fixes #132.
=> CI: test adding codecov

integration/docker/cap_test.go
This will test the --cap-add and --cap-drop capability with
docker run.
Fixes #165
=> test: Add docker --cap-add and --cap-drop test.

integration/docker/exec_test.go
Add docker integration for exec command.
Fixes #169
=> test: Add docker exec integration test.

.ci/jenkins_job_build.sh, .ci/run.sh
Run the unit tests for the repo under test.
Fixes #202.
=> Fix running unit tests

integration/cri-o/cri-o.sh
Now that Ubuntu 17.10 has been added to the CI,
we can make use of this job to test CRI-O using overlay
storage driver.
Fixes: #204.
=> CI: run cri-o tests using overlay on ubuntu 17

.ci/run.sh, .ci/teardown.sh
Only call the collect script if it exists.
Fixes #206.
=> CI: Don't assume collect script exists

.ci/setup_env_centos.sh, integration/cri-o/cri-o.sh
Fix how to enable EPEL repositories in CentOS.
Fixes #222
=> ci: Fix repo installation CentOS

integration/docker/kill_test.go
Add docker integration test for kill command.
Fixes #209
=> test: Add docker kill integration test

.ci/static-checks.sh
Add a check to ensure that all files where possible contain the
required SPDX license header.
Fixes #240.
=> CI: Add check for SPDX license headers

.ci/install_kata_image.sh, .ci/install_qemu.sh
- Build image in a tmp directory 
- clone need qemu sub-modules.
=> ci: Minor CI fixes.

.ci/lib.sh
get_version function is used by the install_go.sh script, but this
function uses go to know the versions. Remove that the go dependency.
Fixes: #246
=> ci: lib: get_version does not depend on go

.ci/install_go.sh, .ci/jenkins_job_build.sh, .ci/lib.sh
Check if go is installed.
- If go requested version is installed, then do nothing.
- If go is installed with other version, fail requesting remove it first.
- Clone repository using git
- Install go
=> CI: Use install_go.sh  script

integration/docker/cpu_test.go
once all vCPUs have been connected, the agent updates the cpuset cgroup
of each container allowing them to access to these resources
fixes #250
=> integration/docker: Fix CPU hotplug tests

.ci/run_metrics_PR_ci.sh, metrics/density/memory_usage_inside_container.sh
This will measure memory free, memory available and total memory
inside the container with /proc/meminfo.
Fixes #287
=> metrics: Add memory measurement inside the container.

integration/popular_docker_hub_images/popular_docker_images.bats
This will test kata-runtime with the most popular images from
Docker Hub.
Fixes #278
=> tests: Add test for the most popular images from Docker Hub.

integration/docker/pause_test.go
Check that yamux connection write timeout never occurs.
Connection write timeout occurs only if yamux default
configuration is used to create the client.
Depends-on: github.com/kata-containers/proxy#71
fixes #310
=> integration/docker: add test to check yamux IO keep alive

.ci/static-checks.sh
Run a known version of `gometalinter` to avoid new lint tests from
breaking valid PRs.
Fixes #299.
=> CI: pin go linter version to avoid new lints failing PRs

integration/docker/cpu_test.go
next condition is used to wait until all vCPUs are visible in the container
```
while [[ "$(cat "/sys/fs/cgroup/cpuset/cpuset.cpus")" != "2" ]] && [[ $c < 5 ]]
```
and that condition fail in sh
```
Stderr: sh: can't open 5: no such file
```
to avoid random failures when CPU tests are running, this patch change the container image
to debian + bash and the command to check the number of vCPUs.
fixes #291
=> integration/docker: don't use sh to check vCPUs

integration/docker/cpu_test.go
This test is to ensure constraints are honoured when a parent
cgroup is specified.
fixes #339
=> integration/docker: add test for containers with parent cgroup

integration/popular_docker_hub_images/popular_docker_images.bats
Fix aerospike test for popular docker hub images as there were changes at the Docker Hub image.
Fixes #347
=> tests: Fix aerospike test

integration/kubernetes/k8s-uts+ipc-ns.bats, integration/kubernetes/run_kubernetes_tests.sh
This verifies that the UPC and IPC namespaces are the same.
Fixes #332
=> tests: Add Kubernetes test to check UPC and IPC namespaces.

.ci/install_cri_containerd.sh, .ci/lib.sh, .ci/setup_env_centos.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh, Makefile, integration/containerd/cri/integration-tests.sh
- Add integartion tests
- Add basic critools tests
=> tests: Add integration test for cri-containerd

integration/docker/cpu_test.go, integration/docker/docker.go
check the number of vCPUs and the CPU cgroups are updated
in running container.
fixes #349
=> integration/docker: add test for docker update

cmd/checkcommits/README.md
Fixes: #377
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
=> tests: Update checkcommits README

integration/kubernetes/k8s-pid-ns.bats, integration/kubernetes/pod.yaml, integration/kubernetes/run_kubernetes_tests.sh
This will check PID namespace is shared between containers in a pod.
Fixes #336
=> test: Add k8s test to check that PID namespace is shared.

integration/docker/cpu_test.go
Add test to ensure the number of vCPUs can be changed and
a cpuset constraint can be applied over those new resources.
Depends-on: github.com/kata-containers/agent#260
fixes #362
fixes #359
=> integration/docker: add cpu + cpuset test

.ci/static-checks.sh
Alert users to TODO/FIXME comments that tend never to get fixed by
failing the CI *unless* those comments also refer to a github issue
where the problem is being tracked.
Fixes #444.
=> CI: Add TODO/FIXME checker

.ci/README.md, .ci/kata-find-stale-skips.sh
Created a simple script that looks for test skips that are no longer
valid as the issue they are referencing is closed.
Fixes #422.
=> CI: Add stale skip utility

.ci/install_kata.sh, .ci/setup.sh, .ci/setup_env_centos.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
This PR add a logic to make kata installation optional, this would help to test if kata was installed with packages.
=> CI: setup: Make kata installation optional

.ci/install_kata_image.sh, .ci/install_kata_kernel.sh, .ci/install_kubernetes.sh, .ci/install_qemu.sh, .ci/setup_env_ubuntu.sh
Add chronic to reduce the log size of our builds.
Fixes: #479.
=> CI: add chronic to more apt/dnf/yum commands

cmd/checkmetrics/README.md, cmd/checkmetrics/baseline/checkmetrics_json.toml, cmd/checkmetrics/compare.go, cmd/checkmetrics/compare_test.go, cmd/checkmetrics/main.go, cmd/checkmetrics/metric.go, cmd/checkmetrics/metric_test.go, cmd/checkmetrics/round_post9_test.go, cmd/checkmetrics/round_pre10_test.go
Add the ability to:
- show the results as percentages, not raw values
- set the check ranges in the config file as percentages
=> checkmetrics percent modes

metrics/network/lib/network-common.bash, metrics/network/network-metrics-iperf3.sh
This test measures bandwidth, jitter, multiqueue and bidirectional
bandwidth using iperf3.
Fixes #509
=> metrics: Iperf3 bandwidth, jitter, multiqueue and bidirectional tests

integration/swarm/swarm.bats
This will check that processes are not left behind before it runs
the integration swarm tests.
Fixes #544
=> tests: Check that processes are not left behind before running swarm

integration/docker/volume_test.go
Fixes #546
This test case addresses this situation:
```
Terminal 1:
$ docker run -ti -v /tmp/a/hello:/hello --runtime kata busybox sh
/
Terminal 2:
$ rm -fv /tmp/a/hello
Terminal 1: exit the container
/ exit
```
Even we removed the volume source file, there shouldn't be any kata-proxy
or kata-shim or qemu process left behind.
Signed-off-by: Wei Zhang <zhangwei555@huawei.com>
=> tests: test for leaking processes

integration/kubernetes/k8s-cpu-ns.bats, integration/kubernetes/k8s-memory.bats, integration/kubernetes/k8s-uts+ipc-ns.bats, integration/kubernetes/pod-memory-limit.yaml, integration/kubernetes/run_kubernetes_tests.sh
These tests when we are trying to launch a pod exceeding
memory limit and within memory limit.
Fixes #533
=> tests: Add k8s memory constraints tests

.ci/kata-doc-to-script.sh
=> kata-doc-to-script: Remove duplicate warning from help message

.ci/install_qemu.sh
Apply required patches before building
qemu.
Fixes: #587.
=> CI: qemu: apply required patches

metrics/network/iperf3_dockerfile/Dockerfile, metrics/network/network-metrics-iperf3.sh
This will build an image with iperf3.
Fixes #553
=> metrics: Add dockerfile for iperf3 tests

integration/docker/docker.go
Use --cidfile to save container ID and use it later to check if kata
components are still running.
Container's name can't be used since it's not present in the process
command line.
fixes #598
=> integration/docker: save container ID to check kata components status

integration/stability/soak_parallel_rm.sh
Obtain from the configuration file the name for the hypervisor,
proxy, and shim.
Fixes #609
=> test: Improve stability test

integration/docker/docker.go
On nested environments the kata components (shim, proxy, qemu) don't finish
inmediately after calling `docker rm`. If `docker ps` doesn't show the container
we have to wait for kata components to finish.
fixes #621
=> integration/docker: wait for kata components to finish

.ci/go-test.sh
Add a `--package $package` CLI option to allow `go-test.sh` to run the
tests for a single package rather than all packages.
Also added a `--list` option to list the available packages.
Fixes #627.
=> CI: Allow go-test.so to test a single package

metrics/network/README.md, metrics/network/network-latency.sh
Add network latency test using ping.
Fixes #579
=> metrics: Add network latency test

integration/docker/docker.go, integration/docker/run_test.go, integration/docker/volume_test.go
If the test can not be run then skip it asap
fixes #637
=> integration/docker: skip test at the beginning of the function

.ci/install_openshift.sh, .ci/jenkins_job_build.sh, .ci/lib.sh, .ci/run.sh, .ci/static-checks.sh, .ci/teardown.sh, integration/docker/cpu_test.go
These changes are needed to be able to test stable-1.1 branch.
CI: adapt jenkins_job_build to support multiple branches
CI: use correct branch for testing stable branches
CI: checkout to correct branch when building kata-containers repos
=> Backport CI fixes to stable-1.1

.ci/jenkins_job_build.sh
Fix variable name that prevents checkout to stable tests branch.
=> ci: Fix checkout to stable branch.

.ci/kata-arch.sh, .ci/lib.sh
Fixes #669
Signed-off-by: Yash Jain <ydjainopensource@gmail.com>
=> tests : Add support for Z

integration/kubernetes/nginx.bats, integration/stability/soak_parallel_rm.sh, metrics/network/network-metrics-nginx-ab-benchmark.sh
Currently the latest nginx image from docker hub is not working so we
will use a stable working version.
Fixes #674
=> tests: Support working nginx image

.travis.yml
travis: Add variable needed to run static checks
travis: bump golang version to 1.10.x
=> travis: Add variable needed to run static checks and bump golang version

.ci/lib.sh
Update yq package download function to support all combinations of {GOOS, GOARCH}.
Fixes #558
=> Fix yq package download for macOS

metrics/network/network-metrics-nginx-ab-benchmark.sh
Currently this test only handles 100 as concurrency level, with these
modifications we will be able to run other concurrency levels.
Fixes #653
=> metrics: Add more concurrency levels to network nginx test

.ci/lib.sh
This change now verifies if a repository is already
checked-out to the correct branch when there is a
Depends-on tag.
Fixes #707.
=> CI: Fix branch management when using Depends-on tag

integration/docker/mem_test.go
Add test to check kernel memory constraints
fixes #710
=> integration/docker: Check kernel memory constraints

.ci/setup.sh, .ci/setup_env_centos.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
Add haveged will allow have entropy for PR.
https://github.com/kata-containers/runtime/pull/676
Fixes: #712
=> ci: Add haveged to generate entropy in CI.

integration/docker-compose/docker-compose.bats
This test is referring to an old issue, this will update the issue so the
kata-find-stale-skips.sh tool does not identify it as it was solved.
Fixes #717
=> tests: Update issue for docker compose

metrics/density/docker_memory_usage.sh
This will be able to store all the memory results for each individual
container for qemu, shim and proxy and for runc.
Fixes #686
=> metrics: Support individual results for memory

Makefile, integration/vm_factory/vm_templating_test.sh, metrics/lib/common.bash
To test vm template init and destroy.
Depends-on: kata-containers/runtime#684
Fixes: #577
=> integration: add vm factory integration test

integration/docker/mem_test.go
Modify update memory constraints tests to test adding memory
constraints and removing memory constraints and neither.
Fixes #756
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
=> integration/docker: add tests to update memory constraints.

Makefile, pentest/all.sh, pentest/dirtycow.sh, pentest/lib.sh
Add security tests for:
* dirtycow
Add `security` Makefile target
fixes #750
=> security: Add security tests

integration/docker/cp_test.go
host's files shouldn't be modified after running `docker cp` and finishing
the container.
fixes #771
=> integration/docker: Add test to check host's integrity after `docker cp`

.ci/aarch64/clean_up_aarch64.sh, integration/kubernetes/cleanup_env.sh, integration/kubernetes/init.sh, integration/openshift/init.sh, integration/openshift/teardown.sh, integration/popular_docker_hub_images/popular_docker_images.bats, integration/swarm/swarm.bats, lib/common.bash, metrics/lib/common.bash, metrics/network/cpu_statistics_iperf.sh, metrics/network/network-latency.sh, metrics/network/network-metrics-iperf.sh, metrics/network/network-metrics-iperf3.sh, metrics/network/network-metrics-memory.sh, metrics/network/network-metrics-nginx-ab-benchmark.sh, metrics/network/network-metrics-nuttcp.sh
We need to check that processes like shim, proxy and hypervisor are not
running before and after running the network metrics.
Fixes #731
=> metrics: Check processes in network metrics

integration/docker/cp_test.go
While running a docker with volume and then performing a docker cp, we
need to check that mount points are removed correctly.
Fixes #781
=> test: Verify that mount points are removed after docker cp

.ci/resolve-kata-dependencies.sh
When the CI runs on master (after merging a PR), the
resolve_dependencies.sh was trying to fetch an unexisting
(pr) branch from the remote. This change adds a validation
to only do this when testing a PR.
Fixes: #803.
=> CI: do not pull PR Branch when testing a branch

.ci/static-checks.sh
Fix logic to check if Gopkg.lock file was updated.
Fixes: #820
=> static: fix vendor test

.ci/aarch64/clean_up_aarch64.sh
The former clean-up work was sort of broken by pr#732, here to fix
related codes.
Fixes: #816
Signed-off-by: Penny Zheng penny.zheng@arm.com
=> ci: fix broken clean-up work for building up CI on aarch64

Makefile, integration/ramdisk/ramdisk.sh, lib/common.bash
This will ensure that we can run with DOCKER_RAMDISK and than --no-pivot
flag is supported.
Fixes #429
=> test: Add ramdisk test

cmd/kata-manager/kata-manager.sh
Make kata-manager able to run on base non development systems,
where git, golang and kata local repos may not be available.
Fixes: #828 
=> kata-manager: do not depend on git,go or local repos

integration/popular_docker_hub_images/popular_docker_images.bats, versions.yaml
Docker hub is not supporting the manifest for rails. Update kibana working version.
Fixes #831
=> tests: Update popular docker images tests

integration/vm_factory/vm_templating_test.sh
To make sure that we have properly configured network endpoints for
vm factory.
Fixes: #874
Depends-on: github.com/kata-containers/runtime#872
Signed-off-by: Peng Tao <bergwolf@gmail.com>
=> vm_factory: check network setup

Makefile, integration/netmon/netmon_test.bats
Enable netmon at the configuration.toml and then exercise docker network
connect and docker network disconnect.
Fixes #728
=> test: Add test to exercise netmon

integration/kubernetes/run_kubernetes_tests.sh
As #335 is already closed, these tests should work.
Fixes: #942.
=> kubernetes - unskip tests when running with initrd

cmd/log-parser/README.md
Fix link to "Enable full debug"
Fixes: #951
=> log-parser: Fix link to "Enable full debug"

integration/kubernetes/k8s-env.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/untrusted_workloads/pod-env.yaml
This will expose the pod information to containers through
environment variables.
Fixes #933
=> tests: Add K8s test for environment variables

README.md
Document how to to prepare a test environment and how
to execute the tests.
Fixes: #919.
=> docs: Document how to run the tests

integration/docker/mem_test.go
Fix "hotplug memory when create containers" test, define variables before
running the tests and use the right types to compare the values, for example
int64 with int64.
fixes #830
=> integration/docker: fix memory test

integration/kubernetes/k8s-qos-pods.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/untrusted_workloads/pod-besteffort.yaml, integration/kubernetes/untrusted_workloads/pod-burstable.yaml, integration/kubernetes/untrusted_workloads/pod-guaranteed.yaml
Add a test that configure Pods with an assigned particular
Quality of Service (QoS) class.
Fixes #972
=> test: Add K8s test to check quality of service for pods

integration/network/disable_net/net_none.bats
Create a test to run without network and configure disable_new_netns
to false at the configuration.toml.
Fixes #978
=> test: Test for disable_new_netns=false

integration/kubernetes/k8s-pod-quota.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml, integration/kubernetes/runtimeclass_workloads/resource-quota.yaml, integration/kubernetes/untrusted_workloads/pod-quota-deployment.yaml, integration/kubernetes/untrusted_workloads/resource-quota.yaml
This will set a quota for the total number of pods.
Fixes #980
=> test: Add K8s test to set quota for a pod

integration/kubernetes/k8s-credentials-secrets.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/inject_secret.yaml, integration/kubernetes/runtimeclass_workloads/pod-secret-env.yaml, integration/kubernetes/runtimeclass_workloads/pod-secret.yaml, integration/kubernetes/untrusted_workloads/inject_secret.yaml, integration/kubernetes/untrusted_workloads/pod-secret-env.yaml, integration/kubernetes/untrusted_workloads/pod-secret.yaml
This test will distribute credentials securely using secrets.
Fixes #976
=> test: K8s test to distribute credentials using secrets

integration/kubernetes/k8s-pod-quota.bats, integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml, integration/kubernetes/untrusted_workloads/pod-quota-deployment.yaml
Add time to wait to kubernetes deployment in order to fix the pod
quota test.
Fixes #1010
=> test: Fix K8s pod quota test

.ci/setup_env_debian.sh
With this we are updating the OBS url for the debian
packages.
Fixes #1022
=> ci: Fix OBS url for debian packages

.ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
flex package is needed by the 4.19.10 kernel
Fixes: #1031.
=> CI: install flex

.ci/resolve-kata-dependencies.sh
Packaging repository variable is incorrect.
Fixes: #1024
=> CI: Fix CI testing for packaging

integration/kubernetes/k8s-projected-volume.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-projected-volume.yaml, integration/kubernetes/untrusted_workloads/pod-projected-volume.yaml
This test configures a pod to used a projected volume.
Fixes #1004
=> test: Add k8s test for projected volumes

.ci/aarch64/lib_install_qemu_aarch64.sh, .ci/install_qemu.sh
Insert Eric Auger's latest PCDIMM/NVDIMM patches for supporting nvdimm
on aarch64.
Fixes: #961
=> qemu: Insert Eric Auger's latest PCDIMM/NVDIMM patches for aarch64

lib/common.bash
We need to modify the common.bash in order to check for the Firecracker
path as well to check the processes that run with Firecracker and Kata.
Fixes #1070
=> test: Modify common to support Firecracker

integration/stability/soak_parallel_rm.sh
This will enable and modify the soak test to run with Firecracker.
We need it to skip checking the processes of proxy and netmon as they
are not present when running with Firecracker.
Fixes #1053
=> test: Modify soak test to support Firecracker

config.go, process.go
We need to add Firecracker as a hypervisor in order that the
docker functional and integration tests work.
Fixes #1096
=> test: Modify process.go and config.go to handle Firecracker

.ci/lib.sh, .ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
"release" is not longer maintained.
Fixes: #1106
=> ci: Update obs repos to master.

cmd/kata-manager/kata-manager.sh
The ability to remove Docker packages is useful so for parity with the
existing `remove-packages` command, the following new commands have been
added:
```
remove-docker
remove-docker-system
```
Also added an `install-docker` command for parity with the existing
`install-packages` command.
Fixes #1135.
=> kata-manager: Allow Docker removal

.ci/install_go.sh, .ci/install_qemu.sh, .ci/s390x/clean_up_s390x.sh, .ci/s390x/configuration_s390x.yaml, .ci/s390x/filter_docker_s390x.sh, .ci/s390x/filter_test_s390x.sh, .ci/s390x/lib_install_qemu_s390x.sh, .ci/s390x/lib_kata_image_s390x.sh, .ci/s390x/lib_setup_s390x.sh, .ci/setup.sh, arch/s390x-options.mk, integration/docker/docker.go, integration/docker/docker_arch_base.go, integration/docker/docker_s390x.go
Fixes: #1129
Further Todos:
- build and install qemu will be implemented as soon as the configure hypervisor script supports s390x
- currently the Hot Plug CPU Feature is not working on s390x
=> Add s390x support for CI scripts

integration/popular_docker_hub_images/popular_docker_images.bats
We need to remove the images after running the containers
of the popular docker hub images test as we are running out of space.
Fixes #1174
=> test: Update popular docker hub images test

.ci/install_kata_image.sh, .ci/install_qemu.sh, .ci/setup.sh, .ci/setup_env_opensuse.sh, cmd/container-manager/manage_ctr_mgr.sh
This add all the installation scripts for OpenSUSE Leap in order
to enable a Jenkins job.
Fixes #1148
=> ci: Add setup for OpenSUSE Leap

command.go, integration/docker/package_manager_test.go
reimplement package manager tests to improve reliability
fixes #264
=> integration/docker: package managers

integration/docker/cgroups_test.go
Add integration test to check whether cpu cgroups are updated after
calling `docker update`.
fixes #1185
=> integration/docker: add test to check whether cpu cgroups are updated

command.go, integration/docker/package_manager_test.go
reimplement package manager tests to improve reliability
=> stable-1.5: integration/docker: package managers

command.go, integration/docker/package_manager_test.go
reimplement package manager tests to improve reliability
=> stable-1.4: integration/docker: package managers

integration/docker/cgroups_test.go
Add test to check whether host's cpu and cpuset cgroups are set correctly
fixes #1199
=> integration/docker: add test to check whether cpu cgroups are set correctly

integration/kubernetes/k8s-limit-range.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/limit-range.yaml, integration/kubernetes/runtimeclass_workloads/pod-cpu-defaults.yaml, integration/kubernetes/untrusted_workloads/limit-range.yaml, integration/kubernetes/untrusted_workloads/pod-cpu-defaults.yaml
This is a test for LimitRange in a namespace.
Fixes #1220
=> test: Add K8s test for LimitRange in a namespace

.ci/aarch64/lib_install_qemu_aarch64.sh, .ci/install_qemu.sh, .ci/jenkins_job_build.sh, .ci/lib.sh, .ci/ppc64le/lib_install_qemu_ppc64le.sh, .ci/resolve-kata-dependencies.sh, .ci/static-checks.sh, .ci/teardown.sh, .travis.yml, CODEOWNERS, Makefile, bundle.go, container.go, functional/state_test.go, integration/docker/mem_test.go, integration/oci_calls/oci_call_test.sh, integration/vm_factory/vm_templating_test.sh, lib/common.bash, metrics/density/memory_usage_inside_container.sh
=> backport stable 1.4

integration/kubernetes/k8s-custom-dns.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-custom-dns.yaml, integration/kubernetes/untrusted_workloads/pod-custom-dns.yaml
This will configures a custom pod's dns config.
Fixes #1281
=> test: Add kubernetes custom dns test

.ci/install_qemu.sh, .ci/setup.sh, .ci/setup_env_sles.sh, cmd/container-manager/manage_ctr_mgr.sh
This will perform the installation for SLES.
Fixes #1262
=> ci: Add installation script for SLES

metrics/time/launch_times.sh
This will check the entropy level at the host before running the
boot time tests in order to ensure stability.
Fixes #1167
=> metrics: Check entropy for boot time tests

metrics/lib/common.bash
When we have enable KSM on density metrics we can skip the part where
we are waiting to KSM to settle down for runc or firecracker.
Fixes #1164
=> metrics: Skip KSM to settle down with runc or firecracker

.ci/install_kata_kernel.sh, .ci/install_qemu.sh, .ci/setup.sh, .ci/setup_env_rhel.sh, .ci/teardown.sh, cmd/container-manager/manage_ctr_mgr.sh
This will setup all kata dependencies and install the kata components.
Fixes #1359
=> ci: Add installation RHEL scripts.

integration/docker/run_test.go
Unskip dmesg test since dmesg errors were fixed.
fixes #1371
=> integration/docker: unskip dmesg test

integration/vm_factory/vm_templating_test.sh
Clean the vm_template dir before test executes.
Fixes: #1363
=> vm_factory: Add clean_vm_template in setup

.ci/install_runtime.sh
This will help us to create a CI for q35 testing.
Fixes #762
=> ci: Add q35 setup

.ci/ci_cache_image.sh, .ci/install_kata.sh, .ci/install_kata_image.sh, .ci/install_kubernetes.sh, .ci/install_nemu.sh, .ci/install_qemu.sh, .ci/install_runtime.sh, .ci/setup.sh, .ci/setup_env_centos.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_ubuntu.sh, cmd/container-manager/manage_ctr_mgr.sh, integration/docker/load_test.go, integration/docker/package_manager_test.go, metrics/storage/README.md
a73fef3 ci: k8s: install cni 0.6.0
f822d35 ci: image: get image from ci server if possible.
0694500 ci: Add setup for OpenSUSE Leap
=> Fixes for stable 1.5 branch

integration/docker/cpu_test.go, integration/docker/run_test.go
backports from master.  Without these, CPU hotplug tests are very noisy.
=> Stable 1.5 fixup cpu hotplug

integration/swarm/swarm.bats
This will fix the instability that we have on RHEL while running
docker swarm init.
Fixes #1420
=> test: Fix swarm test instability on RHEL

.ci/setup.sh, .ci/setup_env_rhel.sh
This fixes the setup for RHEL.
Fixes #1379
=> ci: Fix RHEL script

integration/vm_factory/vm_templating_test.sh
Clean the vm_template dir before test executes.
Fixes: #1363
=> [stable][1.6.x] vm_factory: Add clean_vm_template in setup

metrics/report/report_dockerfile/footprint-density.R
The footprint density report script did not know how to handle the
container version turning up in the results (which happens if we
pin a container rather than use 'latest', as we do with elastic).
Add wildcard file searching and the appropriate de-nesting of data
to the script to find and use all 'XXX.*\.json' results files it
finds for each container name.
Fixes: #1095
=> metrics: report: handle pinned container names

integration/docker/run_test.go
While running this docker integration test on RHEL, we have
random failures in the jenkins ci
https://github.com/kata-containers/tests/issues/1443.
Fixes #1450
=> test: Skip dmesg integration test for RHEL

.ci/install_kata_kernel.sh
=> kernel: Always build the kernel version found locally for CI

integration/kubernetes/k8s-empty-dirs.bats
Depends-on: github.com/kata-containers/runtime#1485
Fixes #1432
Signed-off-by: Alex Price <aprice@atlassian.com>
=> k8s: disable host cache empty dir test

.ci/jenkins_job_build.sh
50db368 test: Fix ci for RHEL
11b7cbb tests: Skip unit tests on RHEL
=> backport tests for stable branch 1.6

integration/kubernetes/k8s-volume.bats
backport of stability fixes for kubernets PV tests.
=> k8s: volume test: wait for physical volume to be available

.ci/jenkins_job_build.sh
run runtime's unit tests in centos
fixes #1413
=> ci: run runtime's unit tests in centos

integration/docker/vsock_test.go
Agent logs should be in the shim journal when `use_vsock` and
shim debug are enabled.
Depends-on: github.com/kata-containers/runtime#1597
fixes #1509
=> integration/docker: Add test to check agent logs if there is no proxy

integration/docker/cpu_test.go
Sometime the hypervisor/kernel is not able to allocate the vcpus,
the test waits for around 25 seconds, but the vcpus is never added.
To avoid random failures in the CI, the test run the container, start the
test that checks the actual number of vcpus, if it fails then the container
is removed and the loop starts again, until the test success or the maximum
number of retries have been reached.
fixes #1529
=> integration/docker: restart container if hotplug cpu test fails

Makefile, functional/debug_console/run.sh
Using socat, connect to console.sock and execute a command. Command's output
should be equal to the expected output.
fixes #1538
=> functional: add test to check debug console

.ci/s390x/configuration_s390x.yaml
Update list of working tests on s390x
Fixes: #1548
=> s390x: update s390x tests

.ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_rhel.sh, .ci/setup_env_sles.sh, .ci/setup_env_ubuntu.sh
=> Add systemd development packages

.ci/aarch64/lib_install_qemu_aarch64.sh, .ci/install_qemu.sh
For now, we often use one specific qemu-system-aarch64 version referred by `assets.hypervisor.qemu.architecture.aarch64.tag` in `version.yaml.`
we could use shadow clone to save time and bandwidth.
Fixes: #1554
=> qemu-aarch64: use shadow clone to save time and bandwidth

.ci/ppc64le/lib_install_qemu_ppc64le.sh, .ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_rhel.sh, .ci/setup_env_sles.sh, .ci/setup_env_ubuntu.sh, Makefile, integration/kubernetes/cleanup_env.sh, integration/kubernetes/k8s-pod-quota.bats, integration/kubernetes/k8s-shared-volume.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml, integration/kubernetes/runtimeclass_workloads/pod-shared-volume.yaml, integration/kubernetes/untrusted_workloads/pod-quota-deployment.yaml, integration/kubernetes/untrusted_workloads/pod-shared-volume.yaml, tracing/tracing-test.sh
This backport brings in the below changes.
#1514
#1520
#1534
#1545
#1553
#1559
#1563
#1573
#1574
Changes marked for backporting and not included are here.
#1528 <-- Missing base patches
=> backports: Bp 1.6.4 rel

integration/cri-o/cri-o.sh
Create a temporal loop device and use as LVM device to test crio+devicemapper,
if the default LVM device doesn't exist. This change is useful
to test crio+devicemapper in systems that don't have an extra block device.
fixes #1575
=> integration/crio: create a loop device if the LVM device doesn't exist

.ci/ppc64le/configuration_ppc64le.yaml
Add additional tests to filter list.
Fixes: #1564
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
=> test: Update filter docker tests

.ci/aarch64/lib_install_qemu_aarch64.sh, integration/docker/cpu_test.go
Missing backport patch to fix qemu builds for aarch64
#1532 
#1541
=> backport: 1.6.4 rel

README.md
Add the missing doc links that should have been part of PR #1587.
Fixes #1596.
=> docs: Add missing links

integration/kubernetes/k8s-expose-ip.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/deployment-expose-ip.yaml
This test exposes an external IP address to access a stateless aplication.
Fixes #1200
=> test: K8s test to expose an external IP address

Makefile, integration/entropy/entropy_time.bats
We need to measure the availability of random data.
Fixes #1543
=> test: Add /dev/random entropy measurement

.ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_rhel.sh, .ci/setup_env_sles.sh, .ci/setup_env_ubuntu.sh
To avoid issues like choosing the wrong package installator, this
change tries to install all the required packages into a single
transaction.
Fixes #1560
=> ci: Put all the packages to install in a single transaction

.ci/install_cni_plugins.sh, .ci/install_cri_containerd.sh, integration/containerd/cri/integration-tests.sh, lib/common.bash, tracing/tracing-test.sh
Lets use cri-container release tarball. If
the tarball installation fails build a release
tarball from source and install it.
Fixes: #1399
=> ci: Use cri-containerd release tarball.

.ci/resolve-kata-dependencies.sh
Fixes:
https://github.com/kata-containers/tests/commit/535eab927f0a5e4ac141affd109495f27d279808
https://github.com/kata-containers/tests/commit/c3b0b57743d7cfad8c528b542ab6afd978b80ee4
=> stable-1.6: backport fixes for Depends-on tool

.ci/README.md, README.md, cmd/checkmetrics/README.md, cmd/history/README.md, cmd/log-parser/README.md, kata-webhook/README.md, metrics/README.md, metrics/density/README.md, metrics/density/footprint_data.md, metrics/network/README.md, metrics/report/README.md
Correct spelling and formatting.
Fixes: #1632.
=> docs: Fix typos and formatting

.ci/static-checks.sh
Improve the URL checker by considering the HTTP status codes.
Fixes: #1642.
=> CI: Improve URL checker

.ci/static-checks.sh
This adds trap cleanup for the temporary files
used in static checks.
Fixes #1613
=> ci: Add trap to remove tmp files

.ci/README.md
Add links to the scripts the README summarises (where possible).
Fixes: #1656.
=> CI: Improve README

integration/vm_factory/vm_templating_test.sh
So we don't rely on yamux which seems flaky and sometimes
unable to clean itself up upon closing.
=> factory: use vsock to test vm template

.ci/aarch64/lib_install_qemu_aarch64.sh, .ci/install_qemu.sh, .ci/ppc64le/lib_install_qemu_ppc64le.sh
This will remove the ci installation for qemu-lite and this will
implement the installation for qemu.
Depends-on: github.com/kata-containers/runtime#1744
Fixes #1645
=> ci: Modify qemu installation

.ci/jenkins_job_build.sh
Static checks are executed on travis also and cover `x86_64`,
`ppc64le` and in some cases even `osx`. We can save VM resources
if we only run static-checks through jenkins only on architectures
that are not supported on travis, which currently are `aarch64`
and `s390x`.
Fixes: #1681.
=> CI: jenkins: only run static checks on some archittectures

integration/kubernetes/k8s-shared-volume.bats, integration/kubernetes/runtimeclass_workloads/pod-shared-volume.yaml
Modify the test to use busybox images instead of nginx and debian in order
to reduce the time of performing the testing.
Fixes #1680
=> test: Optimized k8s shared volume test

.ci/ci_cache_image.sh, .ci/ci_cache_kernel.sh, .ci/install_kata_kernel.sh
Kernel cache job will try to keep and up-to-date,
if the kernel is in the job is the latest we dont build it.
Fixes: #1218
=> ci: install kernel from cache job.

integration/kubernetes/k8s-job.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/job.yaml
This adds a test for a job that creates a pod and ensures that its
successful completion is reached.
Fixes #1634
=> tests: Add k8s test for job to completion

cmd/check-spelling/data/projects.txt
Add a few additional "project" terms to the CI dictionary.
Fixes: #1763.
=> dictionary: Add new terms

integration/kubernetes/k8s-port-forward.bats
This will update the k8s port forwarding test to perform correctly
the port forwarding operation. It also updates the bug issue.
Fixes #1731
=> tests: Update k8s port forwarding test

.ci/ci_cache_nemu.sh, .ci/install_nemu.sh
This will install nemu from cache job and will optimise the CI.
Fixes #1732
=> ci: Install nemu from cache job

Makefile, integration/time_drift/time_drift.bats
This will adds a test to make sure guest time is synced with the host.
Fixes #1488
=> test: Add test to measure time drift

.ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_rhel.sh, .ci/setup_env_sles.sh, .ci/setup_env_ubuntu.sh, .ci/static-checks.sh
Add a static analysis check for XML files.
Fixes: #1783.
=> CI: Add XML check

.ci/install_kubernetes.sh
`EOF` should be at the beginning of the line.
Fixes #1785.
=> k8s: removes indentation from EOF line in install script

.ci/ci-fast-return.sh, .ci/ci-fast-return.yaml, .ci/ci-fast-return/test.yaml, .ci/jenkins_job_build.sh, .ci/run.sh, .ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_rhel.sh, .ci/setup_env_sles.sh, .ci/setup_env_ubuntu.sh, integration/stability/soak_parallel_rm.sh, metrics/lib/common.bash
c63f4b1 tests: Fix soak tests
6e6291e tests: Skip soak test in firecracker
3f50f8b ci: fast path return check
8b3d1d2 ci: add ci fastpath check file
8a9ce4f ci: Remove installation from OBS
=> backport tests 1.8

.ci/install_cri_containerd.sh
Installing cri-containerd will fail on all non-amd64 machine.
```
$ .ci/install_cri_containerd.sh
Set up environment
Trying to install containerd from static tarball
Download tarball from https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.6.linux-arm6                                                                     4.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Failed to download tarball from https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.6.                                                                     linux-arm64.tar.gz …
```
=> cri-containerd: failure on building from scratch due to wrong version value

integration/stability/hypervisor_stability_kill_test.sh
Instead of taking the full path name of the hypervisors, we need to
change to use only the name of the process because with jailer we have
different path shown there.
Fixes: #1846
=> stability: fix fc name in hypervisor kill tests

integration/kubernetes/init.sh
We found that master components like `kube-apiserver`, `etcd`, `kube-system-controller` often take a while, including quite a few restarts, to be ready and running on aarch64.
Took one-run log and pasted here:
```
$ kubectl get pods -A
NAMESPACE     NAME                                              READY   STATUS    RESTARTS   AGE
kube-system   coredns-5c98db65d4-8g2ks                          1/1     Running   0          4m26s
kube-system   coredns-5c98db65d4-q8d7c                          1/1     Running   0          4m26s
kube-system   etcd-entos-thunderx2-desktop                      1/1     Running   35         3m43s
kube-system   kube-apiserver-entos-thunderx2-desktop            1/1     Running   35         3m40s
kube-system   kube-controller-manager-entos-thunderx2-desktop   1/1 …
```
=> system-pod: ensure k8s system pods readiness on aarch64

.ci/configure_crio_for_kata.sh
If you are running k8s integration tests with crio in bare-metal machine, you may encounter duplicated runtime configuration in `/etc/crio/crio.conf`, when invoking `configure_crio_for_kata.sh` script.
```
[crio.runtime.runtimes.runc]
runtime_path = "/usr/local/bin/crio-runc"
runtime_root = "/run/runc"
runtime_type = "oci"
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/kata-runtime"
runtime_root = "/run/vc"
runtime_type= "oci"
[crio.runtime.runtimes.runc]
runtime_path = "/usr/local/bin/crio-runc"
runtime_root = "/run/runc"
runtime_type = "oci"
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/kata-runtime"
runtime_root = "/run/vc"
runtime_type= "oci"
```
And that may lead to `crio.runtime.runtimes.runc has already been defined` error when launching crio service.
``` …
```
=> crio_config: avoid duplicated runtime configuration for crio on bare-metal

.ci/install_kata.sh, .ci/install_qemu_experimental.sh, .ci/install_runtime.sh
This will install qemu for virtiofs 3.0
Fixes #1963
=> ci: Install scripts for qemu experimental

.ci/install_kata_kernel.sh
This will allow us to build and install the experimental kernel
for the virtiofs 3.0
Fixes #1961
=> ci: Add setup scripts for experimental kernel

integration/kubernetes/k8s-copy-file.bats, integration/kubernetes/run_kubernetes_tests.sh
This will copy a file from the host to a pod.
Fixes #1968
=> k8s: Add k8s test for kubectl cp

.ci/ci_cache_components.sh, .ci/install_qemu_experimental.sh
This will build qemu experimental using a cache jenkins job.
Fixes #1967
=> ci: Add cache for qemu experimental

.ci/install_kata_kernel.sh
This script allows to build the cache for kernel experimental.
Fixes #1973
=> ci: Add cache for kernel experimental

.ci/install_cni_plugins.sh
Depends-on: github.com/kata-containers/runtime#2112
Fixes #1983
=> cni: Update the script called for newer version of cni repo

.ci/install_rust.sh
=> rust-agent: Need sudo to work correctly

.ci/setup_env_ubuntu.sh
=> ci: the test [] in setup_env_ubuntu.sh should be [[ ]]

integration/popular_docker_hub_images/popular_docker_images.bats
This will fix the matomo docker integration test.
Fixes #2023
=> tests: Fix matomo docker integration test

.ci/install_rust.sh
=> rust: Use version from versions.yaml or command line.

.ci/teardown.sh
This will enable to collect the tracing logs for debugging purposes.
Fixes #2027
=> ci: Collect tracing logs

Unit-Test-Advice.md
Add advice for writing unit tests in rust.
Fixes: #2038.
=> docs: Update unit test doc for rust

integration/popular_docker_hub_images/popular_docker_images.bats
This will fix the groovy docker integration test for the popular docker hub
images.
Fixes #2058
=> tests: Fix groovy docker integration test

integration/popular_docker_hub_images/popular_docker_images.bats
This adds a docker integration test for teamspeak image.
Fixes #2062
=> test: Add teamspeak docker test

integration/kubernetes/k8s-hugepages.bats
This will enable a kubernetes test for the hugepages configuration only.
Fixes #2070
=> test: Enable a kubernetes test for hugepages

.ci/install_crio.sh
We should only fetch and checkout to the cri-o version defined
in the version.yaml when we are not testing changes in the
cri-o repository.
When testing changes on cri-o repo, the cri-o directory will
already have the changes, so no need to checkout to another
branch/version.
Fixes: #2077.
=> ci: cri-o: Fix install_crio.sh for upstream job

versions.yaml
Update sonobuoy to 0.16.4 which contains stability fixes.
Fixes: #2086.
=> k8s: e2e: update sonobuoy version

integration/kubernetes/k8s-copy-file.bats
This will test that we are able to copy a file from a k8s pod to a host.
Fixes #2096
=> test: Add k8s test to copy file from pod to host

.ci/static-checks.sh
refactor how skip is done, to allow add more in the future in an easy way.
Aditionally skip go module from clh client.
Fixes: #2144
=> ci: static skip clh client code for linter

.ci/ci_cache_components.sh, .ci/install_cloud_hypervisor.sh
This adds the installation for cached cloud hypervisor.
Fixes #2120
=> ci: Add cache for cloud hypervisor

.ci/static-checks.sh
Function to skip paths takes a list of values separated
by spaces (space or new line), if it is just space separated values
grep will not filter values correctly, this commit
converts the list in to a bash array and then iterate the list to
ensure every item checked.
Fixes: #2163
=> fix: skip paths for static checks

.ci/install_kata.sh, .ci/install_kata_image_rust.sh, .ci/install_runtime.sh
This adds the installation scripts for rust agent.
Fixes #2154
=> ci: Rust agent installation scripts

integration/containerd/cri/integration-tests.sh
To ensure shimv2 process exits when vmm is killed.
Fixes: #2172
Depends-on: github.com/kata-containers/runtime#2346
=> integration: add shimv2 kill vmm tests

.ci/lib.sh
=> ci: add build_install_{cmake, musl} to lib.sh

Makefile, integration/vcpus/default_vcpus_test.sh
This will test that when we modify the default_vcpus at the configuration.toml,
this is working properly.
Fixes #2219
=> tests: Test default_vcpus functionality

functional/state_test.go
Currently we have random failures on CentOS 8 for the functional state test.
This PR skips that test until https://github.com/kata-containers/tests/issues/2264
is being fixed.
Fixes #2268
=> test: Skip functional state test

.ci/ci_cache_components.sh, .ci/install_cloud_hypervisor.sh
- Remove extra clh directory path
- Copy binary to assets directory
- Fix install function
Fixes: #2266
=> cache: fix clh path

.ci/configure_podman_for_kata.sh, .ci/install_kata.sh, .ci/install_kata_image.sh, .ci/setup_env_fedora.sh, versions.yaml
This PR setups podman with kata-runtime.
Fixes #2256
=> ci: Setup podman with kata-runtime

cmd/check-spelling/data/acronyms.txt
Add Virtio-mem to spell check dictionary.
Fixes: #2284
=> spelling: Add Virtio-mem to spell check dictionary

.ci/install_kata_image_rust.sh
=> rust-agent: use --release build for rust agent

cmd/kata-manager/kata-manager.sh
=> kata-manager: add enable-vsock/disable-vsock

.ci/ci-fast-return.sh
While running the ci-fast-return.sh script we found out that is complaining
that jq command is not found. This PR installs the jq package as a dependency.
Fixes #2308
=> ci: Install jq for ci-fast-return.sh

.ci/podman/configuration_podman.yaml
This PR enables more e2e podman integration tests.
Fixes #2319
=> test: Enable more e2e podman tests

.ci/jenkins_job_build.sh, .ci/run.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/run_kubernetes_tests.sh
Enable k8s for clh.
Fixes: #2318
=> test: enable k8s for clh

Makefile
Docker tests fail randomly in Centos 7 if they run in parallel.
The systemd service in the guest uses `fstat` to build a map of unit files.
For a strange reason, the `fstat` operation on pmem devices takes too much
time, looks like this could be a bug in the host kernel, because it is not
reproducible in CentOS 8.
Run docker test sequentially to avoid random failures.
fixes #2355
=> Makefile: Run docker tests sequentially in CentOS 7

.ci/setup_env_sles.sh
We need to update the setup script for SLES to work for SLES 15 SP1.
Fixes #2373
=> ci: Update setup script for SLES

cmd/check-spelling/data/main.txt
Fixes #2391
Signed-off-by: Jimmy Xu <junming.xjm@antfin.com>
=> spellcheck: add Nvidia

command.go, config.go, functional/main_test.go, functional/options_test.go, integration/docker/main_test.go
=> Fix functional and integration tests tu support golang 1.13

.ci/install_crio.sh
Fixes https://github.com/kata-containers/tests/issues/2400
=> Fix CRI-O configuration file location for newer versions

.ci/setup_env_sles.sh, integration/containerd/shimv2/shimv2-tests.sh
This PR performs modifications in order to fix the SLES
CI setup scripts.
Fixes #2380
=> ci: Fix SLES CI

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml
Add new metrics reference file to update the metrics CI node from Ubuntu 16.04
to Ubuntu 18.04
fixes #2456
=> cmd/checkmetrics: add reference file for new metrics slave

.ci/jenkins_job_build.sh, .ci/run.sh, .ci/vfio_jenkins_job_build.sh, .gitignore, Makefile, functional/vfio/config.json.in, functional/vfio/run.sh
Add functional VFIO test. The test will start a new VM with an extra ethernet
device that will be hotplugged (passthrough) in a kata container running in
the VM (nested virtualization).
Nested virtualization can be slow, hence a functional test was implemented
in order to avoid timeouts using container engines, for example docker.
fixes #2451
=> functional: add vfio test

cmd/kata-manager/kata-manager.sh
Add option to take argument for install-packages and
install-docker-system that specifies kata release to install. Default
branch remains the same as the branch specified in the install scripts,
which is master.
Fixes #2447
=> kata-manager: Add argument for kata release

.ci/setup_env_fedora.sh, integration/podman/run_podman_tests.sh
5cac2b6 ci: Build podman from source
=> backport podman fix for 1.11

Makefile, functional/vfio/run.sh
Run vfio test with sandbox_cgroup_only enabled and disabled
fixes #2484
=> vfio: test sandbox_cgroup_only

.ci/setup_env_ubuntu.sh, cmd/container-manager/manage_ctr_mgr.sh
This PR modifies the setup script to support ubuntu 20.04 by removing
a non existing package as well as to modify the addition of the repository
for docker.
Fixes #2497
=> ci: Modify ubuntu setup to support 20.04

.ci/setup_env_centos.sh
quote `yum repolist..` and run `yum install` with `-y`
fixes #2531
=> ci: fix centos 8 setup script

integration/pmem/pmem_test.sh
=> fix pmem test

.ci/jenkins_job_build.sh, .ci/run.sh, .ci/teardown.sh, Makefile, integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml, integration/kubernetes/e2e_conformance/run.sh, integration/kubernetes/e2e_conformance/setup.sh, integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml
Add k8s e2e test for clh.
Fixes: #2417
=> ci: Add k8s e2e test for clh

.ci/jenkins_job_build.sh, .ci/run_metrics_PR_ci.sh
This PR will add a new job for metrics which is the one that will run
in CLH as well as it enables which tests will run.
Fixes #2618
=> metrics: Add metrics CI CLH

.ci/vfio_jenkins_job_build.sh
Increase the number of tries to connect to the VM. Stop the VM and start a new
one if the first connection tries fail.
fixes #2628
=> vfio/ci: increase the number of tries to connect to the VM

integration/pmem/data/dbinsert.sh, integration/pmem/data/lib.sh, integration/pmem/data/users.txt, integration/pmem/pmem_test.sh
Run a postgres container using a pmem volume to save the data, create a
database and table, insert 1 million users and stop the container.
Start a new postgres container and check the data base.
fixes #2622
=> integration/pmem: add test to check data integrity

.ci/jenkins_job_build.sh, .ci/teardown.sh, .ci/vfio_jenkins_job_build.sh, Makefile, functional/vfio/run.sh
Modify vfio CI scripts to installl Cloud hypervisor and test its vfio
hotplug functionality
fixes #2548
=> ci/vfio: test Cloud Hypervisor

integration/kubernetes/k8s-expose-ip.bats
=> 2.0-dev: add retry for kubernetes service test case

.ci/jenkins_job_build.sh, .ci/run_metrics_PR_ci.sh, cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml, metrics/storage/blogbench.sh
This PR enables the metrics CI for virtiofs.
Fixes #2718
=> metrics: Enable metrics CI for virtiofs

metrics/lib/common.bash, metrics/storage/web-tooling_dockerfile/Dockerfile, metrics/storage/webtool.sh
This PR adds to the storage metrics the web tooling benchmark.
Fixes #2746
=> metrics: Add web tooling benchmark

.ci/teardown.sh
Log tag for `containerd-shim-kata-v2` is set to `kata` in journald, use this tag to get `containerd-shim-kata-v2`'s log.
Fixes: #2749
This pr depends on #2739 to be merged first.
=> ci: collect containerd-shim-kata-v2 log

metrics/storage/webtool.sh
This PR enables the possiblity to scale the number of containers that
will run the webtooling benchmark.
Fixes #2768
=> metrics: Scale webtool benchmark

.ci/install_runtime.sh
1484beac ci: support QEMU 5.0.0
=> backport for stable 1.11

metrics/storage/webtool.sh
This PR gets the TPS value for the web tooling benchmark as well as sets
the number of cpus which this benchmark needs to run.
Fixes #2776
=> metrics: Add TPS value and set number of cpus for webtool

.ci/jenkins_job_build.sh
Add lines back into jenkins script so that new repo coverage is
reported.
Fixes #2781
=> ci: Fix missing line so that codecov works

.ci/jenkins_job_build.sh
This reverts commit d2e77d29bb79727aaf64dac75da97c28b1b3f370.
Fixes #2790
=> Revert "ci: Fix missing line so that codecov works"

integration/kubernetes/k8s-copy-file.bats
=> k8s: enable copy file tests

integration/kubernetes/k8s-empty-dirs.bats
=> CI: enable k8s-empty-dirs.bats

integration/kubernetes/k8s-oom.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
=> k8s: add pod OOM test

.ci/configure_containerd_for_kata.sh, .ci/configure_crio_for_kata.sh, integration/kubernetes/k8s-cpu-ns.bats, integration/kubernetes/k8s-number-cpus.bats, integration/kubernetes/k8s-sysctls.bats
We should already support it.
Fixes: #2806
=> k8s: enable skipped bats for kata 2.0

.ci/static-checks.sh
Improve the license checker function to also check for a copyright
header.
Fixes: #2323.
=> CI: Check for copyright header

integration/kubernetes/k8s-block-volume.bats, integration/kubernetes/nginx.bats
We should pass them.
Fixes: #2865
=> k8s: enable skipped crio tests for kata 2.0

cmd/check-spelling/data/main.txt, cmd/check-spelling/data/projects.txt
Update 2.0-dev branch with main.txt and projects.txt from master.
Fixes #2897
=> spellcheck: Sync 2.0-dev with master

cmd/container-manager/manage_ctr_mgr.sh, integration/netmon/netmon_test.bats
30aee74a tests: Skip netmon test on CentOS 8
e02c7be8 ci: Fix docker installation for rhel 8
b77ac598 ci: Fix docker installation centos 8
=> Backport fixes 1.10

.ci/static-checks.sh
Make sure we include subdirectories...
Fixes: #2960
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>
=> ci: ignore files within kernel/configs directory

.ci/jenkins_job_build.sh, integration/kubernetes/vfio.sh
=> ci: vfio: fix cloud-hypervisor

.ci/aarch64/lib_install_qemu_aarch64.sh, .ci/install_qemu.sh, .ci/install_runtime.sh
=> Backport 2.0-dev commits

.ci/configure_containerd_for_kata.sh
Enable containerd debug to enable kata-shimv2 debug
fixes #3015
=> ci: Enable containerd debug

.ci/install_runtime.sh, .ci/openshift-ci/buildall_install.sh
This is going to build and configure with support to vsock for use on the OpenShift CI job.
=> Configure to use vsock on OpenShift CI

.ci/vfio_jenkins_job_build.sh
=> ci: vfio: bump fedora version

kata-webhook/main.go
Otherwise we'll just crash.
Fixes: #3111
Signed-off-by: Adel Zaalouk <azaalouk@redhat.com>
=> 1.x | webhook: Check whether Privileged is nil before accessing its value

integration/kubernetes/k8s-block-volume.bats
Wait on the created volume to be "Available" before proceed with
the remaining of the test; Also refactor the code to use variables
that hold the name of the resources.
Fixes #3123
=> integration/kubernetes: Strength the k8s-block-volume test

kata-webhook/main.go
Otherwise we'll just crash.
Fixes: #3111
Signed-off-by: Adel Zaalouk <azaalouk@redhat.com>
=> 2.x | webhook: Check whether Privileged is nil before accessing its value

.ci/kata-arch.sh
=> ci/kata-arch: Fix typo on help message

.ci/run.sh, Makefile, integration/stability/soak_parallel_rm.sh, lib/common.bash, metrics/lib/common.bash
This modifies the stability test to use ctr for kata 2.0
Fixes #3083
=> tests: Add stability test using ctr

Makefile, cmd/pmemctl/pmemctl.sh, integration/pmem/data/dbinsert.sh, integration/pmem/data/lib.sh, integration/pmem/data/users.txt, integration/pmem/pmem_test.sh
Run PMEM tests to check PMEM block devices support and compatibility
with the pmem-csi kubernetes plugin.
Depends-on: github.com/kata-containers/kata-containers#1290
fixes #3150
=> integration: Add PMEM test for 2.0

.ci/lib.sh, .ci/setup_env_centos.sh, .ci/setup_env_debian.sh, .ci/setup_env_fedora.sh, .ci/setup_env_opensuse.sh, .ci/setup_env_rhel.sh, .ci/setup_env_sles.sh, .ci/setup_env_ubuntu.sh, versions.yaml
From inspection looks like GNU parallel isn't actually used, although the scripts try to use it.  I also spotted some other shell functions in the scripts that are never invoked.  There might be more..
=> Remove some unnecessary code and dependencies from the test scripts

integration/stability/agent_stability_test.sh
This PR updates the agent stability test to use ctr instead of docker.
Fixes #3187
=> tests: Update agent stability test to use ctr

.ci/containerd_devmapper_setup.sh, .ci/install_firecracker.sh, .ci/install_kubernetes.sh, .ci/jenkins_job_build.sh, .ci/run.sh, .ci/setup.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/k8s-cpu-ns.bats, integration/kubernetes/k8s-credentials-secrets.bats, integration/kubernetes/k8s-projected-volume.bats, integration/kubernetes/k8s-volume.bats, integration/kubernetes/run_kubernetes_tests.sh
This PR enables FC CI for kata 2.x
Fixes #3076
=> ci: Enable FC CI for kata 2.x

.ci/run.sh
Pmem test is failing randomly, let's disable to unblock the PRs
fixes #3224
cc @fidencio @GabyCT 
=> ci: skip pmem test

.ci/install_kubernetes.sh, .ci/ppc64le/lib_install_qemu_ppc64le.sh
- kubenetes package installation for ppc64le
- virtiofsd installation
Fixes: #3185
Signed-off-by: Jing Wang <jing.wang4@ibm.com>
=> ci: updates to kata setup scripts for ppc64le

.ci/ci_entry_point.sh, .ci/vfio_jenkins_job_build.sh, integration/kubernetes/vfio.sh
The main goal of this PR was to fix the failure on vfio job due to missing ninja-build package on the ubuntu host. Then I noticed that the script was using code from the master branch. I changed it but that caused more failures, and more fixes were needed. Along the way I implemented changes to the vfio test script to increase its debuggability, this comes as a bonus commit.
=> ci: Fixes and improvements to the vfio job

metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR adds iperf3 utc jitter test using k8s for kata 2.0
Fixes #3313
=> metrics: Add iperf3 jitter test

metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR enables the cpu statistics for iperf3 metrics tests.
Fixes #3342
=> metrics: Enable cpu statistics for iperf3 metrics

.ci/install_runtime.sh, .ci/jenkins_job_build.sh, .ci/vfio_jenkins_job_build.sh, Makefile, functional/vfio/config.json.in, functional/vfio/run.sh
Don't use Kubernetes, fix VFIO CI
=> ci: vfio: reimplement VFIO test

.ci/ppc64le/lib_install_qemu_ppc64le.sh
Apply qemu patches to enable building virtiofsd and
fix the binary location.
Fixes #3340 
=> Fix qemu build for ppc64le

.ci/install_kata.sh, .ci/jenkins_job_build.sh
Enable DAX for experimental job.
Fixes: #3377
=> ci: qemu_experimental: enable DAX

metrics/density/footprint_data.sh
This PR updates the footprint metrics script to use ctr instead
of docker in order to work with kata 2.0
Fixes #3384
=> metrics: Update footprint metrics to use ctr for kata 2.0

metrics/density/fast_footprint.sh
This PR updates the fast footprint density metrics to use ctr
instead of docker in order to use it for kata 2.0
Fixes #3390
=> metrics: Update fast footprint metrics to use ctr for kata 2.0

.ci/lib.sh
This PR fixes the vfio CI for stable-2.0
Fixes #3261
=> ci: Fix vfio CI for stable-2.0

.ci/lib.sh, integration/kubernetes/k8s-attach-handlers.bats, integration/kubernetes/k8s-copy-file.bats, integration/kubernetes/k8s-cpu-ns.bats, integration/kubernetes/k8s-custom-dns.bats, integration/kubernetes/k8s-empty-dirs.bats, integration/kubernetes/k8s-liveness-probes.bats, integration/kubernetes/k8s-memory.bats, integration/kubernetes/k8s-parallel.bats, integration/kubernetes/k8s-pid-ns.bats, integration/kubernetes/k8s-projected-volume.bats, integration/kubernetes/k8s-security-context.bats, integration/kubernetes/k8s-shared-volume.bats, integration/kubernetes/k8s-sysctls.bats
5e181fc2 tests: Introduce more time for the pods to be ready in unstable k8s tests
a7dadb4d tests: Introduce more time for the pods to be ready in k8s
c5d0c98a tests: Wait for the pods to be ready
=> backport: Fixes for k8s tests for stable-2.0

.ci/run.sh, tracing/tracing-test.sh
Use ctr instead of docker for tracing test since 2.0 has no docker
support.
Fixes #3024
=> tracing: Change tracing test to use ctr

.ci/lib.sh
cleanup docker containerd files properly
fixes #3468
=> ci: metrics: cleanup system properly

.ci/run_metrics_PR_ci.sh, cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml, metrics/time/launch_times.sh
This reverts commit e0029ca049fad3b4b34532714fdb8cf0bc5bd0a4.
=> metrics: Revert "metrics: Fix boot times metrics baseline"

integration/kubernetes/k8s-credentials-secrets.bats, integration/kubernetes/k8s-exec.bats, integration/kubernetes/k8s-number-cpus.bats, integration/kubernetes/k8s-volume.bats
This PR puts a timeout in waiting to the pods to be ready as we
have random failures in these tests.
Fixes #3490
=> tests: Wait to pods to be ready

.ci/jenkins_job_build.sh, Makefile, integration/kubernetes/e2e_conformance/run.sh
The tests are not specific to conainerd, so let's also make the variable
name more generic.
Fixes: #3537
=> ci: Rename MINIMAL_CONTAINERD_K8S_E2E to MINIMAL_K8S_E2E

.ci/install_kubernetes.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/init.sh
#3493 fixed the issues we had with the ARM CI, but the changes done were done for any environment.
Let's restrict those changes a little bit and only run those on baremetal CIs.
Fixes: #3516
=> Restrict baremetal specific changes to baremetal CIs

.ci/install_kubernetes.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/init.sh
#3493 fixed the issues we had with the ARM CI, but the changes done were done for any environment.
Let's restrict those changes a little bit and only run those on baremetal CIs.
Fixes: #3516
=> [stable-2.1] Restrict baremetal specific changes to baremetal CIs

integration/kubernetes/run_kubernetes_tests.sh
=> ci: Reenable OOM and sysctl tests when using clh

README.md, cmd/check-spelling/data/main.txt
037c1cd4 docs: Update README to include Jenkins and github actions documentation
b3bc6ccd docs: Update README document
ca2adee0 docs: Include vfio tests in the documentation
=> backport fixes for stable-2.1

integration/containerd/cri/integration-tests.sh
Fixes #3580
Signed-off-by: Matthieu Sarter <matthieu.sarter@ibm.com>
=> containerd: disable memory update test on ppc64le

.ci/jenkins_job_build.sh
This PR fixes the indentation.
Fixes #3596
=> ci: Fix indentation for firecracker ci job

.ci/jenkins_job_build.sh, .ci/run.sh
This PR adds the CI job for the baremetal pmem platform.
Fixes #3594
=> ci: Add CI job for baremetal pmem

.ci/configure_containerd_for_kata.sh, integration/pmem/pmem_test.sh
Fix Pmem test.
data/lib.sh was removed in a previous commit, hece source it
is an error.
fixes #3652
=> integration: pmem: fix test

.ci/jenkins_job_build.sh, .ci/run.sh
Added an CI job configuration to test an initrd image with containerd
and Kubernetes.
Fixes #3676
=> ci: Add containerd+k8s+initrd CI job

integration/kubernetes/nginx.bats
Wait nginx service becoming ready and then run wget
command in the busybox pod. This can reduce the radio of
test failures.
Fixes: #3701
=> tests: run wget after service is ready

metrics/density/README.md
This PR updates the density README for metrics with the current
implementation that we have in kata 2.x
Fixes #3707
=> docs: Update density README

metrics/storage/web-tooling-dockerfile/Dockerfile, metrics/storage/webtooling.sh
This PR submits the webtooling benchmark script to work with
ctr instead of docker and to work with kata 2.x
Fixes #3722
=> metrics: Webtooling benchmark for kata 2.x

metrics/storage/webtooling.sh
This PR adds some fixes like indentation and definition of the
variables.
Fixes #3731
=> metrics: Webtooling script fixes

.ci/lib.sh
00025aeb ci: Also uninstall containerd non-.io in cleanup
/cc @fidencio
=> Backport containerd uninstall fix

.ci/configure_cni.sh, .ci/install_cri_containerd.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/init.sh
continuing https://github.com/kata-containers/tests/pull/3713 work
=> stable 2.1 | adapt to new cri containerd cni tarball link

metrics/report/report_dockerfile/metrics_report.Rmd
This PR updates and fixes with the current metrics scripts that are
being supported on kata 2.0 the metrics_report.rmd
Fixes #3783
=> metrics: Fix and update metrics report

cmd/check-markdown/README.md
This PR updates the current url for the Documentation Requirements
at the checkcommits documentation.
Fixes #3792
=> docs: Update checkcommits README information

.ci/install_kata_image.sh
Improve the code removing the kata image from the previous run.
fixes #3796
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>
=> ci: Delete the previous kata image

metrics/storage/webtooling.sh
* This PR breaks the code in functions that are executed with timeout
* Cleans the environment beforethe workload starts and at the end
Fixes kata-containers#3747
Signed-off-by: desparza <david.esparza.borquez@intel.com>
=> metrics/storage: Webtooling script improvements.

integration/pmem/pmem_test.sh
Fix  pull rate limit issue, don't build image from dockerhub
fixes #3832
=> integration/pmem: don't build image from dockerhub

.ci/install_cri_containerd.sh
There is no "cri-cni-release" targe in makefile before containerd 1.5.0,
and change it to "release".
Fixes: #3830
=> stable-2.1: fix no build target issue in containerd installation

integration/kubernetes/init.sh
Wait for registry container before pushing stress-kata image
fixes #3865
=> integration/kubernetes: wait for registry container

.ci/ci_job_flags.sh, .ci/run.sh, integration/pmem/pmem_test.sh
This PR adds the possibility to build PMEM to avoid regressions or failures,
however, it will not run the test as this needs a special hardware.
Fixes #3867
=> ci: Add pmem CI job

metrics/lib/json.bash
While running metrics tests we can use as a CTR RUNTIME io.containerd.runc.v2
and io.containerd.kata.v2, this PR is fixing the output that we got when
running metrics tests to fix the output. For example when running when kata
the runtime information, shim, etc will be visible but that is not important
when we are running for RunC.
Fixes #3908
=> metrics: Fix json format to support Kata and RunC results

integration/kubernetes/k8s-pod-quota.bats, integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml, integration/kubernetes/runtimeclass_workloads/resource-quota.yaml
Improves the resource quota test as discussed in #3857
=> integration/kubernetes: Improve the resource quota test

integration/kubernetes/k8s-pod-quota.bats, integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml, integration/kubernetes/runtimeclass_workloads/resource-quota.yaml
The introduced changes break the CI job on ARM.
This reverts commit 3622e70b6fd160573b1127ba1fe3bc1fb2198ddc.
Fixes #3932
=> Revert "integration/kubernetes: Add cpu/memory constraints in resource quota"

lib/common.bash
For heavy workloads the time out assinged to clean_env_ctr
was increased up to 90 seconds.
Fixes #3924
=> ci: increase the timeou for clean_env_ctr

.ci/ci_entry_point.sh, .ci/vfio_jenkins_job_build.sh
checkout the right tests target branch
fixes #3948
=> ci/vfio:  checkout the right tests target branch

integration/containerd/cri/integration-tests.sh
Add TestContainerSwap to test guest swap in integration-tests.sh.
Fixes: #3776
=> integration-tests.sh: Add TestContainerSwap to test guest swap

.ci/ci_entry_point.sh, .ci/vfio_jenkins_job_build.sh
checkout the right tests target branch
fixes #3948
=> [backport-2.2] ci/vfio: checkout the right tests target branch

metrics/storage/webtooling.sh
Strenght the webtooling bench by starting the workload at the
same time in all runninng containers.
The script verifies if a trigger-file exists in the filesystem.
Fixes #3952
=> CI: Synchronize n-containers to start webtooling bench

integration/qat/qat_test.sh
Add integration test to test Intel® QAT devices
fixes #3939
cc @GabyCT
=> integration/qat: add test to check QAT

.ci/aarch64/lib_install_qemu_aarch64.sh
remove this ugly way of applying patch in qemu build for arm64.
Fixes: #3994
=> qemu: using script to apply qemu patch

.ci/run.sh, Makefile, integration/rootless/rootless-pod.json, integration/rootless/rootless_test.sh
Add test to check rootles containers
Depends-on: github.com/kata-containers/kata-containers#2432
fixes #3845
cc @fengwang666
=> integration: add rootless test

integration/kubernetes/e2e_conformance/run.sh, integration/kubernetes/e2e_conformance/setup.sh
The main goal with this PR is to fix [kubernetes-e2e: cannot be executed more than one time](https://github.com/kata-containers/tests/issues/4037). I also included two improvements.
=> kubernetes-e2e: improvements to the cleanup()

lib/common.bash
- grep container for whole word in tasks. Otherwise, e.g. `test1` can be
caught when `test` is to be removed, and `test1` won't find anything.
- cut name out -- no point in killing `[PID] RUNNING`
- Rename this variable from `tasks` to `task` to avoid confusion. There
will be no more than one task associated with the container name.
Fixes: #3961
=> ci: Kill tasks by whole word in clean_env_ctr

.ci/lib.sh
This PR removes unnecessary steps in the clean up for the metrics CI
baremetal in order to avoid errors like ERROR: packages not installed or
removing CRI-O dependencies when CRI-O is not even install in the system
and so on. This PR only leaves the clean up that is necessary for the metrics CI.
Fixes #4059
=> ci: Fix cleanup for Metrics CI baremetal

.ci/ci_job_flags.sh, .ci/install_kata_kernel.sh, .ci/openshift-ci/build_install.sh
A number of small simplifications and cleanups to this CI script.
@marcel-apf, FYI
=> Cleanups and simplifications to .ci/install_kata_kernel.sh

lib/common.bash
This PR brings back the check dockerfiles images function as it needs
to be used for the make report script for the metrics CI.
Fixes #4136
=> metrics: Enable the check dockerfiles images for metrics Report

integration/qat/qat_test.sh
bump QAT driver version
fixes #4170
=> integration/qat: bump QAT driver version

cmd/container-manager/manage_ctr_mgr.sh
This PR removes the docker swarm installation as currently kata 2.0
is not working with docker and we do not have any tests or features
where we are using this type of installation.
Fixes #4218
=> ci: Remove docker swarm installation

.ci/ci-fast-return.sh, .ci/ci_cache_components.sh, .ci/configure_containerd_for_kata.sh, .ci/containerd_devmapper_setup.sh, .ci/go-test.sh, .ci/install_go.sh, .ci/kata-arch.sh, .ci/kata-doc-to-script.sh, .ci/kata-find-stale-skips.sh, .ci/kata-simplify-log.sh, .ci/set_kata_config.sh, .ci/static-checks.sh, cmd/check-spelling/kata-spell-check.sh, cmd/github-labels/github-labels.sh, cmd/kata-manager/kata-manager.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/k8s-exec.bats, tracing/test-agent-shutdown.sh, tracing/tracing-test.sh
uniformly changed to EOF to avoid confusion
Fixes: #4237
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>
=> docs: Moving from EOT to EOF

integration/kubernetes/e2e_conformance/setup.sh, integration/kubernetes/init.sh
https://github.com/kata-containers/kata-containers/pull/3068#issuecomment-972810503
=> k8s: cleanup environment before retry

.ci/ci-fast-return.sh, .ci/ci_cache_components.sh, .ci/configure_containerd_for_kata.sh, .ci/containerd_devmapper_setup.sh, .ci/go-test.sh, .ci/install_go.sh, .ci/kata-arch.sh, .ci/kata-doc-to-script.sh, .ci/kata-find-stale-skips.sh, .ci/kata-simplify-log.sh, .ci/set_kata_config.sh, .ci/static-checks.sh, cmd/check-spelling/kata-spell-check.sh, cmd/github-labels/github-labels.sh, cmd/kata-manager/kata-manager.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/e2e_conformance/setup.sh, integration/kubernetes/init.sh, integration/kubernetes/k8s-exec.bats, integration/kubernetes/k8s-nested-configmap-secret.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/kata-runtimeclass.yaml, integration/kubernetes/runtimeclass_workloads/pod-nested-configmap-secret.yaml, tracing/test-agent-shutdown.sh, tracing/tracing-test.sh
Weekly merge of new commits in `main` into `CCv0`
Fixes: #4255
=> CCv0: Merge `main` into `CCv0` branch

metrics/report/README.md
This PR updates the report metrics documentation with the supported
options that the grabdata.sh metrics is using for kata 2.0
Fixes #4270
=> metrics: Update report metrics documentation

cmd/check-spelling/data/projects.txt
Add the term "AppArmor" to the dictionary.
Fixes: #4277.
=> spell: Add AppArmor to dictionary

.ci/ci_entry_point.sh
Port https://github.com/kata-containers/tests/pull/4339 and https://github.com/kata-containers/tests/pull/4336 over to the CCv0 branch.
=> CCv0 | ci: Port ubuntu 18.04 fix to ccv0

.ci/static-checks.sh
ci: Add static checks for anchor 
Only this uses EOT, the others are EOF, uniformly changed to EOF to
avoid confusion
Fixes: #4102
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>
=> ci: Add static checks for anchor

.ci/resolve-kata-dependencies.sh
- Add logic to ignore multiple depends-on for CCv0 PRs, but just use the first one
Fixes: #4350
=> CCv0 | ci: Only use first depends-on tag

integration/kubernetes/init.sh
This refactor the kubelet restart code so that is given it more time
to start. Before we were using a loop with a small sleep time and very
often it was enough to ensure kubelet had started, resulting on the
error like:
21:37:13 Unable to connect to the server: net/http: TLS handshake timeout
21:38:04 Unable to connect to the server: net/http: TLS handshake timeout
21:38:55 Unable to connect to the server: net/http: TLS handshake timeout
21:39:47 Unable to connect to the server: net/http: TLS handshake timeout
21:40:40 Unable to connect to the server: net/http: TLS handshake timeout
21:41:34 [run_kubernetes_tests.sh:74] INFO: Environment initialization failed. Clean up and try again.
Fixes #4290
=> k8s: give more time to kubelet restart

.ci/jenkins_job_build.sh
until leftover shims under virtio-fs (#3998) are resolved.
Fixes: #4406
=> Switch to virtio-9p on s390x

cmd/check-spelling/data/acronyms.txt, cmd/check-spelling/data/main.txt, cmd/check-spelling/data/projects.txt
Added a few terms missing from the spell checker's data files relating
to Kata Containers and Confidential Containers.
Fixes: #4412.
=> spell: Add new terms to spell checker dictionary

.ci/README.md, .ci/setup_env_centos.sh
Tested and with CentOS Stream 8
Fixes: #4299
=> Adapt to centos stream

.ci/go-test.sh
in static tests. Required for basic KVM checks on some kernels (e.g. the
one RHEL is currently shipping), cf.
https://github.com/qemu/qemu/blob/6621441db50d5bae7e34dbd04bf3c57a27a71b32/target/s390x/kvm/meson.build#L15-L16.
Fixes: #4375
Related: https://github.com/kata-containers/kata-containers/pull/3470
=> ci: -Wl,--s390-pgste for s390x

functional/vfio/run.sh, functional/vfio/vfio.json.in
Addresses the problem described in #4432, and makes a couple of other small improvements along the way.
=> Add test for translation of PCIDEVICE_ environment variables

.ci/aarch64/lib_install_qemu_aarch64.sh, .ci/ci-fast-return.sh, .ci/ci_crio_entry_point.sh, .ci/install_cloud_hypervisor.sh, .ci/install_kata_kernel.sh, .ci/install_qemu.sh, .ci/install_qemu_experimental.sh, .ci/install_runtime.sh, .ci/jenkins_job_build.sh, .ci/lib.sh, .ci/openshift-ci/build_install.sh, .ci/openshift-ci/qemu-build-pre.sh, .ci/ppc64le/lib_install_qemu_ppc64le.sh, .ci/resolve-kata-dependencies.sh, tracing/test-agent-shutdown.sh
We need the function from https://github.com/kata-containers/tests/pull/4363 into CCv0 to help with the merge of main into CCv0
Fixes: #4457
=> CCv0 | ci: Cherry pick ignore-depends-on from `main`

.ci/install_kata_kernel.sh
=> improve install_kata_kernel.sh script

integration/containerd/cri/integration-tests.sh
Instead of blindly copying the default Kata config, use the existing if
it is available, and restore it afterwards; as there might be important
changes, e.g. #4407.
Also, do not change the default config.
=> integration/containerd: Do not override config

.ci/go-test.sh
in static tests. Required for basic KVM checks on some kernels (e.g. the
one RHEL is currently shipping), cf.
https://github.com/qemu/qemu/blob/6621441db50d5bae7e34dbd04bf3c57a27a71b32/target/s390x/kvm/meson.build#L15-L16.
Fix some related shell quoting problems.
Fixes: #4375
Backport of #4376
=> stable-2.3 | ci: -Wl,--s390-pgste for s390x

.ci/install_qemu.sh
Add options to enable bash debug and build/install different
qemu types, such as tdx and vanilla
fixes #4477
=> ci: install_qemu: improve script

.ci/ci_cache_components.sh
fixes ci_cache_components.sh script to support
cloud-hypervisor
fixes #4490
=> ci: ci_cache_components: fix cloud-hypervisor support

integration/nydus/nydus_tests.sh
update integration/nydus/nydus_tests.sh to support test nydus with clh
Depends-on: [github.com/kata-containers/kata-containers#3687](https://github.com/kata-containers/kata-containers/pull/3687)
Fixes #4481
Signed-off-by: luodaowen.backend <luodaowen.backend@bytedance.com>
=> tests: add test for nydus with clh

.ci/run.sh
correct the k8s cleaning so that IPerf can start.
Fixes: #4495
=> ci: fix Iperf bench

.ci/.golangci.yml, .ci/ci_cache_components.sh, .ci/ci_job_flags.sh, .ci/install_qemu.sh, .ci/lib.sh, .ci/run.sh, .ci/run_metrics_PR_ci.sh, .ci/static-checks.sh, cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml, integration/containerd/cri/integration-tests.sh, integration/kubernetes/k8s-number-cpus.bats, integration/nydus/nydus_tests.sh, metrics/storage/blogbench.sh
Merge remote-tracking branch 'upstream/main' into CCv0
Fixes: #4536
Depends-on: github.com/kata-containers/kata-containers#3808
=> CCv0: Merge main into CCv0 branch

metrics/README.md
This PR updates the README documentation for network metrics
with the tests that we have in kata 2.0 CI.
Fixes #4570
=> metrics: Update README for network metrics

.ci/install_kubernetes.sh, .ci/setup_env_alinux.sh, cmd/container-manager/manage_ctr_mgr.sh, cmd/kata-manager/kata-manager.sh, integration/containerd/cri/integration-tests.sh, metrics/lib/common.bash
Alibaba Cloud Linux seems to be a RHEL / CentOS like distro.  Let's try
to treat it the same as CentOS and hope for the best.
This is needed as it seems the ARM CIs switched to using Alibaba Cloud
Linux.
Fixes: #4518
=> setup: Add "alinux" support

functional/tdx/run.sh
add basic test to check TDX functionality
fixes #4530
=> tdx: add functional test

CONTRIBUTING.md
This PR updates the contributing document by fixing the
correct url.
Fixes #4613
=> docs: Update contributing document

functional/tdx/run.sh
Dump container's memory and validate that it is encrypted
fixes #4649
=> functional/tdx: improve tdx test

functional/sgx/run.sh, functional/sgx/sgx.json.in
implement functional test to validate if Intel SGX works in Kata Containers
with QEMU and Cloud Hypervisor
fixes #4656
=> functional/sgx: add test to validate SGX

cmd/check-spelling/data/main.txt
Adding scalability to the dictionary
Fixes: #4686
Signed-off-by: zvonkok <zkaiser@nvidia.com>
=> doc: Add "scalability" to the dictionary

cmd/log-parser/agent.go
and remove general non-agent fields
Fixes: #4679
=> log-parser: unpack all agent fields

metrics/disk/cassandra_kubernetes/cassandra.sh, metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-service.yaml, metrics/disk/cassandra_kubernetes/runtimeclass_workloads/cassandra-statefulset.yaml, metrics/disk/cassandra_kubernetes/runtimeclass_workloads/local-volumes.yaml
This PR adds the cassandra benchmark for metrics using k8s.
Fixes #4709
=> metrics: Add cassandra benchmark

.ci/install_kata.sh, .ci/install_runtime.sh
Fixes: #4667
Signed-off-by: Arron Wang <arron.wang@intel.com>
=> ci: Add TEE_TYPE flag for TEE enabled kernel/hypervisor

.ci/aarch64/configuration_aarch64.yaml, integration/kubernetes/k8s-qos-pods.bats
This PR enables the qos k8s test on x86_64.
Fixes #4725
=> tests: Enable qos k8s test on x86_64

.ci/aarch64/configuration_aarch64.yaml, .ci/aarch64/install_rom_aarch64.sh, .ci/ci_job_flags.sh, .ci/containerd_devmapper_setup.sh, .ci/install_firecracker.sh, .ci/install_go.sh, .ci/kata-simplify-log.sh, .ci/run.sh, .ci/setup.sh, .ci/vagrant-cleaner.sh, cmd/check-spelling/kata-spell-check.sh, cmd/container-manager/manage_ctr_mgr.sh, cmd/log-parser/agent.go, cmd/log-parser/agent_test.go, cmd/log-parser/logentry.go, cmd/log-parser/logentry_test.go, cmd/log-parser/main.go, cmd/log-parser/parse.go, cmd/log-parser/parse_test.go, cmd/pmemctl/pmemctl.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/k8s-qos-pods.bats, metrics/lib/common.bash
This round includes fixes for the following issues:
* #4688
* #4705
* #4725
* #4647
* #4630
* #4632
* #4679
* #4700
* #4702
=> stable-2.4 | First round of backports for the 2.4.1 release

integration/kubernetes/k8s-job.bats
This PR enables the job k8s integration test.
Fixes #4748
=> k8s: Enable jobs k8s integration test

README.md, lib/common.bash, lib/error.sh
This round includes fixes for the following issues:
* #4732
=> stable-2.4 | Second round of backports for the 2.4.1 release

integration/kubernetes/k8s-footloose.bats
This PR enables k8s footloose integration test.
Fixes #4773
=> k8s: Enable k8s footloose integration test

integration/kubernetes/init.sh
This PR avoids building the custom stress image which is being used
in the integration kubernetes tests in order to avoid delays while
we start kubernetes.
Fixes #4827
=> kubernetes: Do not build custom stress image for metrics CI

metrics/README.md, metrics/disk/README.md
This PR adds a README for Cassandra metrics test.
Fixes #4857
=> metrics: Add Cassandra README

.ci/install_kata.sh, .ci/install_runtime.sh
=> build rust runtime for dragonball hypervisor

.ci/jenkins_job_build.sh
This PR is to make the current test divided into 3 parts and triggered individually via a parameter.
The code changes do not break any existing CI configurations. Please look at the issue below for the detailed explanation. 
Fixes: #4925
=> build: Make test into several sub-tests

.ci/ci_job_flags.sh, .ci/run.sh, Makefile, integration/containerd/cri/integration-tests.sh, integration/kubernetes/run_kubernetes_tests.sh, lib/common.bash, stability/soak_parallel_rm.sh
=> ci: support CI test for dragonball hypervisor

.ci/run.sh, integration/nydus/nydus_tests.sh
Enable all debug flags to show more log for nydus test
Fixes: #4947
Signed-off-by: liubin <liubin0329@gmail.com>
=> nydus: upgrade nydus version

.ci/run.sh, functional/kata-monitor/run.sh, functional/tracing/test-agent-shutdown.sh, functional/tracing/tracing-test.sh, functional/vcpus/default_vcpus_test.sh, integration/ksm/ksm_test.sh, integration/kubernetes/k8s-hugepages.bats, integration/nydus/nydus_tests.sh
Fix tests that are failing with cgroupsv2 in ubuntu 22.04.
Fixes: #4922
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>
=> ci: Fix tests that are failing with cgroupsv2

metrics/network/latency_kubernetes/latency-network.sh, metrics/network/latency_kubernetes/runtimeclass_workloads/latency-client.yaml, metrics/network/latency_kubernetes/runtimeclass_workloads/latency-server.yaml
This PR adds a latency network metrics script so we in the future
enable this in our daily metrics CI.
Fixes #4987
=> metrics: Add latency network metrics script

.ci/install_runtime.sh
Installs agent-ctl in install_runtime.sh which allows better debugging
in the ci environment.
Fixes #4602
Signed-off-by: Derek Lee <derlee@redhat.com>
=> agent-ctl: Install agent-ctl in install_runtime.sh

.ci/ci_job_flags.sh, .ci/install_kata.sh, .ci/install_runtime.sh, .ci/run.sh, Makefile, integration/containerd/cri/integration-tests.sh, integration/kubernetes/run_kubernetes_tests.sh, lib/common.bash, stability/soak_parallel_rm.sh
This PR merges runtime-rs to main.
And we add depend-on for the PR that merge runtime-rs to main in Kata repo.
=> merge runtime-rs to main

metrics/network/README.md
This PR updates the network metrics document with the measurements
that we have available in our kata CI.
Fixes #5016
=> docs: Update network metrics document

.ci/jenkins_job_build.sh
setup.sh will do lots of work, including install runtime kata-image, which
take a long time. But it isn't needed in unit test and snap build test,
thus, move it into "run_main_test".
Fixes: #5024
=> ci: don't setup kata environment for unit test and snap test

metrics/README.md
This PR updates the readme for metrics by including some of the
network measurements that we currently have in kata metrics CI.
Fixes #5036
=> docs: Update main readme for metrics

functional/vcpus/default_vcpus_test.sh
=> ci: fix bug for default_vcpus_test.sh

functional/sev/run.sh, integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml, integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml, integration/kubernetes/confidential/sev.bats, versions.yaml
Added sev.bats test file.
Added k8s service yaml for encrypted image.
Fixes: #5129
=> sev: bats test for operator integration

.ci/run_metrics_PR_ci.sh
Enables the selective execution of metrics.
Fixes #5132
=> metrics: Add metric selection function

integration/kubernetes/run_kubernetes_tests.sh
Enable k8s inotify test
Depends-on:github.com/kata-containers/kata-containers#5220
=> runtime-rs: enable k8s inotify test

metrics/network/README.md
This PR updates the network readme with the current metrics that we are using in kata.
Fixes #5170
=> docs: Update network readme

integration/kubernetes/k8s-copy-file.bats
Fixes: #5219 
Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>
=> Cleanup temporary files during teardown for k8s-copy-files.bats

.ci/static-checks.sh, .github/workflows/main.yml, cmd/check-markdown/add_test.go, cmd/check-markdown/link_test.go, cmd/check-markdown/parse.go, cmd/checkmetrics/basefile.go, cmd/checkmetrics/basefile_test.go, cmd/checkmetrics/json_test.go, cmd/github-labels/yaml.go, metrics/storage/fio-k8s/cmd/fiotest/main.go, versions.yaml
Please, check each commit for more details.
=> Follow ups on the golang bump

.ci/run.sh, integration/nydus/nydus_tests.sh
Fixes:#5195
Signed-off-by: Zhongtao Hu <zhongtaohu.tim@linux.alibaba.com>
=> add nydus test for dragonball

integration/containerd/cri/integration-tests.sh
Add TestContainerSwap to integration-tests.sh
Fixes: #5247
=> tests: enable TestContainerSwap test

integration/containerd/cri/integration-tests.sh
Run multiple test cases once at a time for containerd cri-integration test make save times for building
containerd and test binaries.
Fixes: #5255
=> tests: run all test cases in one make command

integration/kubernetes/init.sh, metrics/density/k8s-sysbench.sh, metrics/density/runtimeclass_workloads/sysbench-pod.yaml, metrics/density/sysbench-dockerfile/Dockerfile
This PR adds the sysbench memory test.
Fixes #5279
=> metrics: Add sysbench memory test

.ci/install_cni_plugins.sh, .ci/install_cri_containerd.sh
- Ensure directory we are checking out to is deleted
- Attempt to build containerd with sudo permission
Fixes: #WIP
=> ci: Update permissions of containerd install

.ci/install_cloud_hypervisor.sh, .ci/install_kata.sh, .ci/install_qemu.sh
TDVF is already installed as part of the install_kata.sh
Fixes: #5304
=> CC | Avoid building TDVF twice

.ci/install_cri_containerd.sh
This is not needed anymore as we're releasing the containerd binaries from the confidential-containers/containerd fork.
Fixes: #5325
Depends-on: github.com/kata-containers/kata-containers#5895
=> ci: Remove containerd's install_from_branch()

.ci/run.sh, integration/nydus/nydus_tests.sh
We need this in order to have the 3.0.1 release out.
=> stable-3.0 | backport patches related to nydus tests

integration/kubernetes/k8s-ro-volume.bats, integration/kubernetes/run_kubernetes_tests.sh
add k8s-ro-volume.bats
Fixes:#5337
Signed-off-by: Zhongtao Hu <zhongtaohu.tim@linux.alibaba.com>
=> add k8s-ro-volume.bats

integration/kubernetes/k8s-file-volume.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-file-volume.yaml
Add test case for sharing host file into container.
Fixes: #5356
=> tests: add hostPath volume test for sharing files

.ci/ci_entry_point.sh, .ci/ci_job_flags.sh, .ci/install_kata_kernel.sh, .ci/install_runtime.sh, integration/containerd/cri/integration-tests.sh, integration/kubernetes/init.sh, integration/kubernetes/k8s-file-volume.bats, integration/kubernetes/k8s-ro-volume.bats, integration/kubernetes/run_kubernetes_tests.sh, integration/kubernetes/runtimeclass_workloads/pod-file-volume.yaml
Merge remote-tracking branch 'upstream/main' into CCv0
Fixes: #5368
Depends-on: github.com/kata-containers/kata-containers#6012
Signed-off-by: Megan Wright <megan.wright@ibm.com>
=> CC: Merge main into CCv0 branch

integration/kubernetes/run_kubernetes_tests.sh
add k8s-pid-ns.bats
Fixes:#5335
Signed-off-by: Zhongtao Hu <zhongtaohu.tim@linux.alibaba.com>
=> ci: add k8s-pid-ns.bats

integration/kubernetes/confidential/sev.bats
I think this will do it.
@ryansavino @fidencio
=> Fix SEV operator tests 

integration/kubernetes/init.sh, versions.yaml
Upgrade flannel in versions.yaml
Fixes: https://github.com/kata-containers/tests/issues/5332
Signed-Off-By: Ryan Savino [ryan.savino@amd.com](mailto:ryan.savino@amd.com)
=> versions: upgrade flannel to 0.20.2 - main

integration/kubernetes/init.sh, versions.yaml
Upgrade flannel in versions.yaml
Fixes: #5332
=> versions: upgrade flannel to 0.21.0 - stable-3.0

integration/kubernetes/run_kubernetes_tests.sh
Can we finally pass the last k8s ci?! 👀
Fixes: #5459
Depends-on: github.com/kata-containers/kata-containers#6300
=> ci: add k8s-footloose.bats to dragonball test

stability/scability_test.sh
This PR adds a scability test for kata containers.
Fixes #5423
=> tests: Add scability test

Makefile
This PR adds scalability testing as part of the baremetal CI.
Fixes #5475
=> makefile: Add scalability testing

integration/kubernetes/confidential/sev.bats
One minor fix to make things more clear and one bigger fix to make things actually work.
Hopefull will resolve https://github.com/kata-containers/kata-containers/pull/6360
Maybe also https://github.com/kata-containers/kata-containers/pull/5665
@ryansavino 
@stevenhorsman 
@jepio
=> SEV Test Fixes

.ci/run_metrics_PR_ci.sh
This PR fixes the iperf test path.
Fixes #5490
=> metrics: Fix iperf test path

metrics/network/nginx_kubernetes/nginx-network.sh
This PR adds the nginx benchmark based on phoronix metrics.
Fixes #5497
=> metrics: Add nginx benchmark

metrics/lib/common.bash
This PR uses sudo with ctr in common.bash as part of consistency as in other functions that are using ctr or docker.
Fixes #5495
=> metrics: Use sudo with ctr in common.bash

.ci/lib.sh
Remove coco artifacts.
Fixes: #5502
Signed-of-by: Unmesh Deodhar <udeodhar@amd.com>
=> Remove stale coco artifacts

metrics/disk/c-ray/Dockerfile, metrics/disk/c-ray/cray.sh
This PR adds the c-ray benchmark based on phoronix tests.
Fixes #5508
=> metrics: Add c-ray benchmark

cmd/check-spelling/data/projects.txt, metrics/disk/README.md
This PR adds C-Ray documentation to the README.
Fixes #5526
=> metrics: Add C-Ray documentation

.ci/ci_job_flags.sh, .ci/run.sh, Makefile, functional/vfio-ap/Dockerfile, functional/vfio-ap/run.sh
Add a test script to verify a funtionality of vfio-ap on s390x.
Add Dockerfile for a test image where s390-tools is installed.
Fixes: #5212
=> ci: Add test script for vfio-ap on s390x

.ci/.golangci.yml, .ci/aarch64/install_rom_aarch64.sh, .ci/aarch64/lib_install_qemu_aarch64.sh, .ci/ci_job_flags.sh, .ci/configure_for_sgx.sh, .ci/install_kata_kernel.sh, .ci/install_runtime.sh, .ci/jenkins_job_build.sh, .ci/run.sh, Makefile, cmd/check-spelling/data/projects.txt, functional/vfio-ap/Dockerfile, functional/vfio-ap/run.sh, lib/common.bash, metrics/density/memory_usage_inside_container.sh, metrics/disk/README.md, metrics/disk/c-ray/Dockerfile, metrics/disk/c-ray/cray.sh, metrics/network/README.md
Merge remote-tracking branch 'upstream/main' into CCv0
Fixes: #5538
Depends-on: github.com/kata-containers/kata-containers#6506
Signed-off-by: Megan Wright <megan.wright@ibm.com>
=> CCv0: Merge main into CCv0 branch     

metrics/time/launch_times.sh
This patch adds useful statistics to help to analyze collected data as the following:
- size: sample size
- avg: average
- sd: standard deviation
- cov: coefficent of variance
Fixes #5447
=> Add statistics on the data collected in boot times

metrics/time/launch_times.sh
The metrics gathered in boot times sometimes fail to report valid positive results.
This PR removes negative numbers results and repeat the run.
Fixes: #5580
=> [metrics]: Remove false positive results from boot-times

metrics/machine_learning/tensorflow.sh
This PR adds the AxelNet model for the tensorflow tests for kata metrics.
Fixes #5597
=> metrics: Add AxelNet model test for tensorflow

metrics/machine_learning/pytorch.sh, metrics/machine_learning/pytorch_dockerfile/Dockerfile
This PR adds the Dockerfile and the Pytorch script for kata metrics.
=> metrics: Add Pytorch benchmark

metrics/storage/webtooling.sh
This PR updates the webtooling script to use CTR_EXE a variable that is defined at common.bash to have uniformity across the metrics tests.
Fixes #5610
=> metrics: Update webtooling script

metrics/machine_learning/pytorch.sh
This PR adds Pytorch Isoneural benchmark test to the kata containers metrics.
Fixes #5630
=> metrics: Add Pytorch Isoneural test

integration/kubernetes/cleanup_bare_metal_env.sh
Removing stale apt file for kubernetes.
Fixes: #6666
=> integration: cleanup apt files

metrics/machine_learning/tensorflow.sh
This PR updates the Tensorflow model name instead of using the data format to have uniformity across the Tensorflow test that is using another model name like Axelnet.
Fixes #5677
=> metrics: Update Tensorflow model name

.ci/install_kubernetes.sh
=> CC | ci: Switch to http kubernetes mirror

cmd/check-spelling/data/main.txt, cmd/check-spelling/data/projects.txt
Add VRA related words to dictionary and update the database for spellcheck to succeed.
Fixes: #5702
Dependency of: https://github.com/kata-containers/kata-containers/pull/5444
=> gpu: Add VRA related words to dictionary

versions.yaml
=> versions: Update sonobuoy to latest v0.56.16

functional/vfio-ap/run.sh
This PR is to add a new e2e test for vfio-ap cold-plugin and supplement logging.
Fixes: #5732
=> vfio-ap: Add e2e test for vfio-ap cold-plugin

.ci/run.sh, .ci/run_metrics_PR_ci.sh, .ci/static-checks.sh, cmd/check-spelling/data/acronyms.txt, cmd/check-spelling/data/main.txt, functional/vfio-ap/run.sh, functional/vfio/run.sh, integration/kubernetes/e2e_conformance/run.sh, kata-webhook/README.md, kata-webhook/main.go, metrics/density/memory_usage_inside_container.sh, versions.yaml
This is the weekly's merge from `main` to `CCv0`, and this is a special
"Steve's vacation" edition.
Considering Steve is off, enjoying his well deserved PTO, I'm here to
bring this merge (and hey, expect this to be messier than usual).
There were **no** conflicts on this.
=> CC | Merge from `main`  to `CCv0` -  July 25th.

.ci/aarch64/install_rom_aarch64.sh
Building UEFI image from source take at least 5 min. We can build it
once and save it as backup then copy the UEFI image there to cancel the
build in the following UEFI image installation.
Fixes: #5022
=> fw/arm64: speed up installation of UEFI image

functional/tracing/test-agent-shutdown.sh, functional/tracing/tracing-test.sh
Ensure reproducible builds for cargo install
Fixes: #5756
=> tracing: ensure reproducible builds

functional/tracing/test-agent-shutdown.sh, functional/tracing/tracing-test.sh
Fixes: #5756
Signed-off-by: Alexandru Matei <alexandru.matei@uipath.com>
(cherry picked from commit 0faaa56)
=> backport 3.1 | tracing: ensure reproducible builds

functional/tracing/test-agent-shutdown.sh, functional/tracing/tracing-test.sh
Fixes: #5756
Signed-off-by: Alexandru Matei <alexandru.matei@uipath.com>
(cherry picked from commit 0faaa56)
=> backport 3.2 | tracing: ensure reproducible builds

Makefile, integration/confidential/fixtures/sealed-secret/offline-fs-kbc/aa-offline_fs_kbc-resources.json, integration/confidential/lib.sh, integration/kubernetes/confidential/fixtures/pod-config-secret.yaml.in, integration/kubernetes/confidential/sealed_secret.bats
Auto unseal secrets inside guest with KBS.
Fixes: #5753
=> ci: Add test cases for CoCo sealed secret feature
