- .ci/static-checks.sh
The static checks script was incorrectly assuming it was being run in
the tests repository. This "works", but then only runs the checks on the
`tests` repository, *not* those of the caller (which might actually be the
`tests` repository of course). Crucially, callers need to be able to
invoke the static check script without `cd`-ing to the `tests`
repository directory.
Fixes #13.
> CI: Fix static checks script for callers

- cmd/checkcommits/checkcommits.go
- cmd/checkcommits/checkcommits_test.go
Resolve issues reported by the gas and structcheck linters .
Fixes #12.
> CI: Fix linter errors for checkcommits

- .ci/static-checks.sh
Run a specified set of gometalinter checks as part of the static checks.
Fixes #10.
> CI: Run golang linters

- .ci/static-checks.sh
Stop `.ci/static-checks.sh` from calling `gometalinter` unconditionally.
That tool is clever enough to not error if there are no golang files to
check, but by having the script detect that scenario, the static checks
can been speeded up.
Fixes #18.
> CI: Only run go linters for golang projects

- .ci/go-test.sh
Add a generic 'go test' unit testing script that can be called
by the other repositories.
Fixes #16.
> CI: Add central 'go test' script

- .ci/static-checks.sh
The static checks script currently only runs a subset of linters under
the CI, but all linters by default otherwise.
Added a `KATA_DEV_MODE` variable that, if set, will run the same subset.
This is useful and crucially does not require the developer to pretend
to be running under a CI (which could be dangerous).
Fixes #24.
> CI: Support KATA_DEV_MODE to enable lenient linters

- .ci/static-checks.sh
`gometalinter` has a `--vendor` flag, but it doesn't appear to work so
exclude vendored code instead.
Fixes #20.
> CI: Make linters really ignore vendored code

- .ci/static-checks.sh
Protobuf-generated code cannot be changed by us so ignore lint warnings
on it.
Fixes #22.
> CI: Ignore lint warnings on auto-generated code

- README.md
Add a general `README.md` which also explains the usage of the
important `KATA_DEV_MODE` variable.
Fixes #31.
> docs: Add a README

- .ci/go-test.sh
Don't run the unit tests as root in developer mode (when
`KATA_DEV_MODE`) is set.
Fixes #29.
> CI: Disable root tests in dev mode

- .ci/go-test.sh
changes to modify go_test_flags depending on the arch
Fixes: https://github.com/kata-containers/tests/issues/40
Signed-off-by: Basheer K <basheer@linux.vnet.ibm.com>
> Enabling -race flag depending on arch

- cmd/checkcommits/checkcommits.go
When PR #37 landed, `checkcommits` started to log the internal commit
object at the start of an error. This is incorrect as it should just
log the commit hash.
Fixes #51.
> checkcommits: Fix error prefix to show commit hash

- .ci/static-checks.sh
If `checkcommits` fails, refer the user to the appropriate section of
the central contributing guide to help them to understand what needs
changing.
Fixes #53.
> CI: Point at contrib guide if checkcommits fails

- .ci/static-checks.sh
Stopped the static checks script from running golang checks on the
runtime repos submodules. The runtimes this repo imports are assumed to
be tested independently so do not (and should not) need to be (re-)tested
here.
Fixes #60.
> CI: Ignore golang checks on runtime submodules

- integration/docker/privileges_test.go
- integration/docker/restart_test.go
- integration/docker/search_test.go
Add docker integration tests for docker search, docker run with privileges flag,
and docker restart.
Fixes #57
> tests: Add docker search, privileges and restart.

- .ci/static-checks.sh
Don't run `gofmt` when testing with go tip.
Fixes #42.
> CI: Disable gofmt with go tip

- .ci/static-checks.sh
Add the following golang linters to the static checks script for stricter
checking:
- `staticcheck`
- `structcheck`
- `unused`
Fixes #72.
> CI: Add more golang linters

- .ci/install_agent.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_proxy.sh
- .ci/install_qemu_lite.sh
- .ci/install_runtime.sh
- .ci/install_shim.sh
- .ci/lib.sh
- .ci/setup.sh
- .ci/setup_env_ubuntu.sh
- cmd/container-manager/manage_ctr_mgr.sh
This will install runtime, shim, agent, proxy, qemu, and all dependencies
to run kata-containers.
Fixes #70
> ci: Add installation scripts

- integration/docker/run_test.go
- integration/docker/user_test.go
Failing tests that already have opened issues, should be skipped
until the issues are fixed.
This will help us have a stable CI.
Fixes #81
> Skip failing tests

- .ci/teardown.sh
Teardown script will collect all logs from the runtime,
proxy and shim.
Fixes #83.
> ci: Add teardown script

- .ci/go-test.sh
Fix the `go test` script to manually filter out vendor packages. This
is required for golang 1.8 and older which don't "prune" the output of
`go list` to remove vendor packages as golang 1.9 does.
Fixes #88.
> CI: Ignore vendor tests

- .ci/teardown.sh
The proxy is no longer a system service so don't select by systemd unit
if no log copy location is passed to `.ci/teardown.sh`.
Fixes #94.
> CI: Fix proxy log selector in teardown script

- .ci/static-checks.sh
Don't run static checks on the vendor packages.
Fixes #99.
> CI: Ignore vendor packages when running static checks

- .ci/jenkins_job_build.sh
Ensure Jenkins jobs call the static checks before running setup and the
tests.
Fixes #102.
> Jenkins call static checks

- .ci/jenkins_job_build.sh
The scripts called by the Jenkins script need to know they are running
in a CI environment.
Fixes #105.
> CI: Set CI variable for Jenkins

- .ci/jenkins_job_build.sh
When testing a PR from runtime, we need to update
the git submodule to get the correct changes.
This is because currently we have 2 runtimes as
git submodules in the kata-containers/runtime repo.
Fixes #113.
> CI: Update runtime git submodules.

- .ci/install_runtime.sh
Modify kata-runtime configuration to set:
block_device_driver = "virtio-blk"
Fixes: #107
> CI: use virtio-blk device driver

- .ci/run.sh
Look for evidence of panics and fatal signals in the component logs
and fail the CI run if found.
Fixes #115.
> CI: Look for fatal errors

- cmd/log-parser/hexbytes.go
- cmd/log-parser/hexbytes_test.go
- cmd/log-parser/logentry.go
- cmd/log-parser/logentry_test.go
- cmd/log-parser/main.go
Allow the `file` argument to be specified as "`-`" meaning
"read from standard input".
Fixes #111.
> log-parser: Support reading from stdin

- .ci/data/crio.service
- .ci/install_bats.sh
- .ci/install_cni_plugins.sh
- .ci/install_crio.sh
- .ci/setup.sh
- .ci/setup_env_ubuntu.sh
- Makefile
- integration/cri-o/cri-o.sh
- integration/cri-o/crio_skip_tests.sh
This will enable that is possible to run CRI-O tests as
well it adds the CI dependencies to install CRI-O.
Fixes #117
> tests: Add CRI-O tests.

- .ci/static-checks.sh
Add the `maligned` linter to the CI static checks to minimise
struct space.
Fixes #122.
> CI: Add maligned linter

- .ci/static-checks.sh
Add two additional linters, `varcheck` and `unconvert`, that check for
unused globals and unnecessary conversions respectively.
Fixes #124.
> CI: Add varcheck and unconvert linters

- integration/docker/run_test.go
currently kata agent does not have support for CPU hot plug,
CPU tests should be skipped until CPU hotplug support is added
in the agent
fixes #128
> integration/docker: skip CPU tests

- .ci/go-test.sh
Change the shebang `-e` to an explicit `set -e` to avoid the nasty shell
issue whereby the option can be defeated if the script is invoked by
calling it as:
```
bash .ci/go-test.sh
```
Fixes #130.
> CI: Enable "set -e" harder

- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/setup.sh
- README.md
Depends-on will allow the CI to test a patch together with
another one from other `kata-containers` repository.
This will be useful when compatibility is broken because
changes need to be done in different repos.
Fixes: #126.
> CI: Implements Depends-on

- .ci/go-test.sh
Ensure go test script runs `test_coverage()` function, not
`test_local()` when dev mode is enabled.
Fixed `test_local()` to consider each golang package
separately which was previously causing the function to fail.
Fixes #134.
> Fix tests for dev mode

- Makefile
Enable functional tests in the Makefile of Kata.
Fixes #140
> tests: Add functional tests to Makefile

- cmd/checkcommits/checkcommits_test.go
Fix the `structcheck` lint error by explicitly using the `TestCIEnvData.name` field.
Note that previously this *was* used implicitly in an error which
included the "`%+v`" format (which would have included the `name`
field), but `structcheck` is strict ;)
Fixes #147.
> checkcommits: Fix lint error

- cmd/container-manager/manage_ctr_mgr.sh
get system architecture and use it for adding the docker
repositories for Ubuntu.
Fixes: #76.
> manage_ctr_mgr: use system arch for installing repos

- .ci/install_crio.sh
- .ci/jenkins_job_build.sh
running static checks, including gometalinter fails because
it requires generated files to be present in the system.
We need to run .ci/static-checks.sh after the .ci/setup.sh
is executed, since it builds the kata containers components.
Fixes #152.
> CI: move static checks after setup is executed

- .ci/install_crio.sh
- Makefile
- integration/cri-o/cri-o.sh
- integration/cri-o/crio_skip_tests.sh
- integration/cri-o/versions.txt
This PR unskips the tests from CRI-O and adds the
crio tests to the `make tests` target.
As we now support a different version than CC does, a
temporal integration/cri-o/versions.txt was added.
Fixes #158.
> CI: Enable CRI-O tests

- .ci/install_crio.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
Some symlink installs did not use the `-f` force flag, which meant
they failed if we were installing over an already installed system.
Add the `-f` flag, and in the instance of the image code, replace
an explicit `rm -f` with the `-f` on the following `ln`.
Fixes: #150
Signed-off-by: Graham whaley <graham.whaley@intel.com>
> ci: installers: add force install to symlinks

- .ci/install_runtime.sh
Now that kata containers has proper scsi support, we
should use virtio-scsi instead of virtio-blk.
Fixes: #167.
> CI: Use virtio-scsi

- cmd/checkcommits/checkcommits.go
- cmd/checkcommits/checkcommits_test.go
`TRAVIS_COMMIT` is not reliable in travis. Let's try `TRAVIS_PULL_REQUEST_SHA`.
Fixes: #177
> checkcommits: use TRAVIS_PULL_REQUEST_SHA to get testing branch HEAD

- .ci/install_runtime.sh
Set the magic kernel command line variable the agent reads on startup to
enable its debug output.
Fixes #174.
> CI: Enable agent debug

- integration/cri-o/crio_skip_tests.sh
Kata Containers actually pass more tests than what is tested right
now. This commit removes those tests from the skip list.
Fixes #171
> integration: crio: Enable more tests from ctr.bats

- .ci/static-checks.sh
Don't call `yamllint` if it isn't installed.
Fixes #180.
> CI: Check if yamllint is available before calling

- .ci/static-checks.sh
If yamllint is not installed, the static-checks.sh
fails. Change the way we verify it is installed.
Fixes #180
> CI: Do not fail if yamllint is not installed.

- .ci/install_kata_image.sh
- .ci/install_runtime.sh
We can set TEST_INITRD=yes to enalbe it.
Fixes: #172
ref: kata-containers/runtime#98
> ci: enable initrd testing support

- .ci/go-test.sh
The https://codecov.io service seems to require the coverage file be
named `coverage.txt`.
Fixes #186.
> CI: Rename coverage file for codecov.io

- .ci/static-checks.sh
Improve the output of the static checks script by displaying each package
path on its own line.
Fixes #184.
> CI: Show package paths one / line in static check script

- .ci/run.sh
- .ci/teardown.sh
Now that we have a merged runtime, we should update the
name of the logs collected in the CI to kata-runtime.log
Fixes: #188.
> CI: Update logs name to match kata-runtime log

- .ci/run.sh
- .ci/teardown.sh
- Run the data collection script to see if it works.
- If the CI run fails, run the data collection script to help provide further clues on the failure.
Fixes #193.
> Run collect script under ci

- .ci/install_runtime.sh
- .ci/setup_env_fedora.sh
Update Fedora runtime installation to enable to verify kata-runtime
and kata-check.
Fixes #192
> ci: Update Fedora runtime installation

- .ci/install_cni_plugins.sh
- .ci/install_crio.sh
- .ci/install_kubernetes.sh
- .ci/lib.sh
- .ci/setup.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
- .ci/teardown.sh
- Makefile
- cmd/container-manager/manage_ctr_mgr.sh
- integration/cri-o/cri-o.sh
- integration/cri-o/versions.txt
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/data/kube-flannel-rbac.yml
- integration/kubernetes/data/kube-flannel.yml
- integration/kubernetes/init.sh
- integration/kubernetes/nginx.bats
- integration/kubernetes/run_kubernetes_tests.sh
tests: Add initial tests for kubernetes
This commit adds scripts to:
- install kubernetes v1.9.3
- Add cri-o as the runtime interfaces for running pods
- start kubelet service using kubeadm
- Run an nginx service pod
- Run a buxybox pod and communicate with the nginx pod.
Fixes: #161.
> Initial k8s tests

- integration/cri-o/crio_skip_tests.sh
Based on recent patches merged into Kata Containers, this patch
unskip 3 tests from ctr.bats, allowing for a better testing of
CRI-O on Kata Containers.
Fixes #200
> integration: crio: Enable more tests for ctr.bats

- .ci/install_kata_image.sh
We need to specify the ROOTFS_DIR that will be used to
build the image. If it is not specified, it will create
a directory with a name based on the distribution that
was used for creating the rootfs.
Fixes #211.
> ci: specify ROOTFS_DIR in install_kata_image script

- .ci/setup.sh
- .ci/setup_env_centos.sh
- cmd/container-manager/manage_ctr_mgr.sh
This will enable to setup and run kata-runtime in CentOS.
Fixes #197
> ci: Add CentOS setup script.

- .ci/go-test.sh
Virtcontainers unit tests only work if they are executed
using the root user.
Fixes #218.
Depends-on: github.com/kata-containers/runtime#193
> CI: run virtcontainers unit tests only as root

- .ci/install_crio.sh
- integration/cri-o/cri-o.sh
Avoid the error of `No package devmapper found` while doing the `make` of
CRI-O. This will disable the devmapper driver when the library it requires
is not installed.
Fixes #227
> ci: Enable CRI-O tests in centos

- .ci/install_crio.sh
- integration/cri-o/cri-o.sh
This change is needed because now that we plan to test
the changes in the cri-o repository, the CI needs to know
if the change being tested comes from the cri-o repository
or from our kata-containers repos. If it comes from the cri-o
repository, we should not use the version we support on our
versions.yaml. We should stick to the changes in the PR.
Fixes: #230.
> CI: add support for new cri-o job

- .ci/install_go.sh
This commit adds an script to be used by ci to run
the latest supported golange version.
Fixes: #233
> ci: Install go defined in versions.yaml

- metrics/time/launch_times.sh
We were not using the defined RUNTIME when launching the background
(scaling test) containers. This meant the scaling test only really
measured what we thought when the runtime we were testing was the
docker default one.
Explicitly state which runtime to use for the background containers
so we test what we expect for any setting of RUNTIME.
Fixes: #239
Signed-off-by: Graham whaley <graham.whaley@intel.com>
> metrics: launch_times: set runtime for background containers

- cmd/checkcommits/checkcommits_test.go
- cmd/log-parser/main.go
- cmd/log-parser/parse.go
- cmd/log-parser/parse_test.go
Both the agent and the kernel write to the console. The log parser
expects all writes to the console *by the agent* to be structured and
well-formed. However, if the kernel writes to the console at the same
time the agent is writing to it, the resulting log entry will appear to
the log parser as "corrupt".
Make the log parser warn if such issues are found rather than failing.
For the original behaviour, run the log parser with the new `--strict`
option. To hide warnings, specify the new `--quiet` option.
Fixes #228.
> log-parser: ignore badly formed agent messages by default

- integration/docker/cpu_test.go
when the container is created, it is placed inside a CPU cgroup
with the actual number of vCPUs, hence not all vCPU will be available
for the containers when they are created. For more info see #250.
fixes #252
> integration/docker: Skip CPU hotplug tests

- integration/docker/cpu_test.go
this test is to ensure `docker --cpuset-cpus=..` works properly
fixes #248
Depends-on: github.com/kata-containers/runtime#236
> integration/docker: add cpuset-cpus test

- integration/docker/package_manager_test.go
Skip this test until see why randomly is failing in the CI.
Fixes #267
> test: Skip yum test in package manager update.

- .ci/run_metrics_PR_ci.sh
- metrics/lib/common.bash
- metrics/storage/blogbench.sh
- metrics/storage/blogbench_dockerfile/Dockerfile
This test is designed to test storage for kata-runtime by performing
random reads and writes.
Fixes #244
> metrics: Add blogbench storage test.

- .ci/install_openshift.sh
- .ci/setup.sh
- Makefile
- integration/openshift/data/hello-pod-kata.json
- integration/openshift/hello_world.bats
- integration/openshift/init.sh
- integration/openshift/openshiftrc
- integration/openshift/run_openshift_tests.sh
- integration/openshift/teardown.sh
This change adds openshift installation into the CI process
and executes a simple test that verifies connectivity between
an openshift pod and the host.
Fixes: #220.
> tests: Add initial openshift testing

- .ci/install_kata_kernel.sh
- .ci/setup.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
Build and install kernel from source code by using kata patches and config.
Kata patches and config are located in the packaging repository.
fixes #262
> ci: build and install kernel from source code

- integration/kubernetes/cleanup_env.sh
Now that kubeadm reset works correctly, some of the commands
in the `integration/kubernetes/cleanup-env.sh` can now be removed.
Fixes: #272
> kubernetes: Remove unnecessary commands from cleanup

- functional/main_test.go
- functional/options_test.go
This is a standalone test for global options like help and version.
Fixes #274
> test: Add functional test for global options.

- integration/docker/docker.go
- integration/docker/run_test.go
- integration/docker/volume_test.go
This will check if a block device passed as a volume is passed to VM using a block driver as well as it adds a tests that checks if a text file under /dev is passed to a container and check that contents are the same.
Fixes #191
> tests: Add test to check if a block device is passed as volume.

- .ci/teardown.sh
Add sudo to the journalctl commands that collect the
logs from kata components, docker and kubelet.
Fixes #283.
> teardown: collect logs using sudo

- integration/docker-compose/docker-compose.bats
docker-compose test is currently being skipped, but the setup
of the test is being executed and it sometimes timeout.
This will skip the setup of the test also, there is no reason
to run the setup if the test is actually not executed.
Fixes #285.
> test: docker-compose, skip test from setup

- integration/docker/cpu_test.go
calculate the right number of vCPUs in "container with CPU constraint" test
use cpuset to know if all vCPUs have been connected
Once all vCPUs have been connected, the agent updates the cpuset cgroup
with the actual number of vCPUs, checking cpuset cgroup is more
reliable than checking the state of the latest vCPU.
fixes #281
> integration/docker: fix "container with CPU constraint" test

- integration/docker/cpu_test.go
We still have issues with the CPU hot-plug functionality.
Reported on https://github.com/kata-containers/agent/issues/232.
Fixes #294.
> tests: Skip CPU hot-plug tests

- .ci/install_crio.sh
- .ci/install_openshift.sh
- integration/cri-o/cri-o.sh
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/nginx.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/openshift/init.sh
- integration/openshift/run_openshift_tests.sh
As we need CRI-O 1.9 to run tests on openshift v3.9.0 (latest)
and CRI-O 1.10 to run Kubernetes 1.10, we need to make a
division in our CI, so that we can test both scenarios without
adding more execution time to the CI jobs.
Because of this, we will execute CRI-O 1.9 - openshift v3.9.0
tests under Fedora and CRI-O 1.10 - Kubernetes 1.10 tests
under ubuntu.
Fixes: #276.
Depends-on: github.com/kata-containers/runtime#278
> CI: Run k8s tests on ubuntu and Openshift tests on Fedora

- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
smem is needed for the memory footprint test and
jq to process the output of the metrics tests.
Add these tools in the setup of the CI.
Fixes: #297.
> CI: metrics: add installation of smem and jq

- .ci/setup_env_fedora.sh
Ensure the `losetup` command is available by installing the
`util-linux` package.
Fixes #289.
> CI: Install losetup for kata-collect-data.sh

- .ci/setup_env_centos.sh
libfdt-devel is a dependency to build qemu on CentOS.
Fixes: #305.
> centos: Install libfdt-devel

- .ci/install_qemu.sh
Now that qemu-lite has been packaged and the kata
documentation makes use of it, we need to change the
CI to run the tests using qemu-lite instead of qemu
vanilla.
Fixes: #307.
Depends-on: github.com/kata-containers/runtime#312
> CI: use qemu-lite for CI tests.

- integration/docker/pause_test.go
Add test to ensure a paused container can be removed
fixes #317
> integration/docker: add test to remove a paused container

- .ci/kata-doc-to-script.sh
- .ci/static-checks.sh
- README.md
Add a script to test documentation. The script is actually designed to make some
documentation "executable", but by hosting it in the tests repo:
- it can be used to perform (very) basic validation on all our docs.
- it can be used by other repos (such as osbuilder) to actually "execute"
our installation docs to install kata from binaries.
Fixes #315.
> CI: Add basic documentation test

- .ci/kata-doc-to-script.sh
Add the standard SPDX license header to the script generated by the
doc-to-script script.
Fixes #325.
> CI: Add license header to generated script

- .ci/install_kata_image.sh
In order to enable initrd Jenkins testing, we need to fix how to
retrieve the kata-agent commit version. The main reason is that with the
options AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine, the
$GOPATH/src/github.com/kata-containers/agent/kata-agent --version does
not exist.
Fixes #330
> ci: Fix how to retrieve kata-agent commit version

- .ci/kata-doc-to-script.sh
Improved `.ci/kata-doc-to-script.sh` to allow indented code blocks.
Fixes #337.
> CI: make doc-to-code script allow indented code

- .ci/install_crio.sh
We use a `runc_version` variable for building an specific
runc version, but there is no value assigned to that variable.
This fixes it by getting the value from versions.yaml in the
runtime repository.
Fixes #354.
> CI: specify runc version that we use for crio

- Gopkg.lock
- Gopkg.toml
- config.go
- integration/docker/cpu_test.go
- integration/docker/main_test.go
- vendor/github.com/BurntSushi/toml/COPYING
- vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
- vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
- vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING
- vendor/github.com/BurntSushi/toml/decode.go
- vendor/github.com/BurntSushi/toml/decode_meta.go
- vendor/github.com/BurntSushi/toml/doc.go
- vendor/github.com/BurntSushi/toml/encode.go
- vendor/github.com/BurntSushi/toml/encoding_types.go
- vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
- vendor/github.com/BurntSushi/toml/lex.go
- vendor/github.com/BurntSushi/toml/parse.go
- vendor/github.com/BurntSushi/toml/type_check.go
- vendor/github.com/BurntSushi/toml/type_fields.go
Read the default number of vCPUs from config file is more reliable
than runnning a container with nproc as workload
fixes #350
> integration/docker: read default number of vCPUs from config file

- .ci/install_kata_image.sh
In the initrd case, we use alpine image that cannot run outside of the
alpine container environment, due to missing libc.musl library.
> ci: get agent version from git

- integration/popular_docker_hub_images/popular_docker_images.bats
Fix the path for the mariadb.cnf file for docker hub popular images.
Fixes #357
> tests: Fix mariadb.cnf path for docker hub popular images.

- .ci/install_kata_kernel.sh
- .ci/setup.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
Instead of building the kernel from sources, we can
use the packaged version if there hasn't been any
changes. This will allow us to save time in the CI
jobs.
In addition, this PR contains two other changes:
- Install OBS repositories (needed to install kata packages).
- Move the kata image installation to the main setup script instead 
calling it on every distro setup.
>  CI: Install kernel from packages if up-to-date 

- integration/docker/pause_test.go
remove paused container test is to ensure paused containers
can be removed.
Depends-on: github.com/kata-containers/runtime#328
fixes #345
> integration/docker: unskip remove paused container test

- .ci/setup_env_ubuntu.sh
- integration/cri-o/cri-o.sh
Now that cri-o is deprecating the use of loop back
devices when using devicemapper driver, we need to
use a block device on the Azure VMs from our CI.
This fix assumes that the Azure VM will have an
/dev/sdb device and it will only be executed when
CI=true, to prevent from being executed on a
development machine.
Fixes: #341
> CRI-O: Use block device for devicemapper driver

- .ci/install_qemu.sh
If the qemu-lite package version on OBS is the same as the
one in the 'versions.yaml', we should install the package
from OBS instead of builing from sources.
This allows to save CI time.
Fixes #363.
> CI: Install qemu-lite from OBS if it is updated.

- cmd/kata-manager/kata-manager.sh
Fix assumption that the runtime config file will always contain both
`initrd=` and `image=` options (with one disabled).
Now, if the specified config command doesn't find the field in the
config file, it will add it.
Also, fixed bug stopping `kata-manager.sh -c $file` from using the specified `$file`.
Fixes #368.
> kata-manager: Fix config setting

- .ci/install_kata_image.sh
We need to specify the `AGENT_VERSION` to the osbuilder
script `rootfs-builder/rootfs.sh`. If that is not the case,
it will install master.
Fixes #374.
> CI: Install correct version of the agent.

- cmd/kata-manager/kata-manager.sh
The `configure-image` and `configure-initrd` `kata-manager.sh` commands
can now be run without specifying an image/initrd. With no file argument
they now configure the runtime using the default paths.
Fixes #383.
> cmd/kata-manager: make config filenames optional

- integration/kubernetes/run_kubernetes_tests.sh
- integration/openshift/run_openshift_tests.sh
As currently Kubernetes and Openshift tests are not working
with INITRD, we need to skip them in order to enable
a Jenkins job.
Fixes #380
> tests: Skip kubernetes and openshift tests for initrd.

- .ci/kata-arch.sh
The standard `arch(1)` utility is rather limited in that it only shows
the host architecture in a single format.
Various repos need to know the architecture in either "golang" format
or using the name the Linux kernel config system uses.
Created a new script that provides this information for the currently
supported architectures that can be used by repos without having to
hard-code the logic themselves (or download `golang`).
Fixes #382.
> scripts: Add kata arch script

- .ci/static-checks.sh
Don't complain if graphic files don't have a licence header.
Fixes #392.
> CI: Ignore graphic files when checking licenses

- integration/cri-o/cri-o.sh
Instead of using variable `block_device`, we need to use
`LVM_DEVICE` to match CRI-O tests script.
Fixes: #394.
> crio: Change block device variable used for cri-o tests

- metrics/storage/blogbench_dockerfile/Dockerfile
This will disable the auto updates in the ubuntu image.
Fixes #387
> metrics: Disable auto updates in Ubuntu.

- .ci/static-checks.sh
- cmd/log-parser/README.md
Added a new CI test that checks for invalid URLs in our documents.
Fixes #397.
> CI: Add URL check for documents

- .ci/run.sh
Check for segfaults in the log files after the tests have run. This is
particularly important when running with the agent as `init` inside
the image.
Fixes #399.
> CI: check for segfaults in logs

- .ci/kata-doc-to-script.sh
- cmd/kata-manager/README.md
- cmd/kata-manager/kata-manager.sh
Added a new `install-docker-system` command to the `kata-manager`
utility now that the container manager installation instructions are
being moved into separate files.
See:
- https://github.com/kata-containers/documentation/pull/145
Also includes some tidyup and refactoring to support this change and a `README` for `kata-manager`.
Fixes #390.
> Kata manager add docker install option

- .ci/static-checks.sh
The new Jenkins server requires the client to authenticate so just
ignore those URLs
Fixes #412.
> CI: Make URL checker ignore new Jenkins server

- integration/cri-o/cri-o.sh
Now that we changed the VMs used for the CI, the block
device assigned for these tests is `/dev/vdb`.
This patch also provides the option to specify another value
if it is needed.
Fixes: #416.
> CI: change block device used for cri-o

- .ci/static-checks.sh
When invalid URLs are found, ensure the list of files that contain such URLs are sorted uniquely to avoid duplication.
Also, improve the error message.
Fixes #407.
> Ci improve url checker

- integration/docker/cpu_test.go
Use /sys/fs/cgroup/cpu to check CPU constraints inside the container.
Systemd comounts cpu and cpuacct at /sys/fs/cgroup/cpu,cpuacct, but when
agent runs as init process those cgroups are not comounted, tests shouldn't
use comounted cgroups to check constraints.
fixes #425
> integration/docker: don't use comounted cgroups to check CPU constraints

- integration/docker/user_test.go
As the following issue kata-containers/shim#46 was solved,
we need to enable the user docker integration test.
Fixes #431
> test: Enable user docker integration test.

- .ci/static-checks.sh
Google Cloud Platform resources are identified by URLs under
https://www.googleapis.com that are only accessible with a valid OAuth2
token. This change suppresses validation of Google APIs URLs to allow GCP
resource references in Kata documentation.
Fixes: #433
Signed-off-by: Jon Olson <jonolson@google.com>
> Add googleapis.com to unchecked URL list.

- integration/docker/cap_test.go
Fedora image currently does not support "capsh", we need to use a Centos
container. As well we need to remove the skip as this issue was already
closed kata-containers/agent#190
Fixes #435
> test: Update docker integration test for cap --drop and --add.

- .ci/kata-doc-to-script.sh
Rather than just exiting non-zero, when `kata-doc-to-script.sh` fails,
display an informational error message.
Fixes #437.
> CI: Display error when kata-doc-to-script fails

- integration/kubernetes/k8s-cpu-ns.bats
Due the changes of https://github.com/kata-containers/agent/pull/260,
we need to update this test to check CPU constraints.
Fixes #440
> test: Update CPU k8s test

- .ci/install_kata_image.sh
This commit will install the packaged image
if it is up to date. And will also try to update
the agent by mounting the image in a local path.
If the process cannot be completed successfully,
the script will build the image from sources.
This approach should reduce the setup time spent
for setting up the environment.
Fixes #410.
> ci: install packaged image

- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/static-checks.sh
- .travis.yml
Change the URL checker to only check the URLs inside document files modified
by a PR. This is relatively difficult since if a PR adds a new document and
modifies an existing document that references that new document, the URL for
the new document will not be valid. The checker handles this by constructing
the correct URL for this new document which will be valid once the PR lands.
As long as the new-but-not-yet-valid URL referenced by the modified document
matches what the checker things the URL will be, the URL is accepted.
For the master branch, all doc URLs are checked.
This change necessitated modifying how the static check script is called by
the CI.
Includes refactoring commits.
Fixes #409.
> CI: Only check URL changed by PRs

- metrics/lib/common.bash
- metrics/storage/blogbench_dockerfile/Dockerfile
This will check that the image exists and in case that exists it will
check the dockerfile version as well as the test version in order to
build or avoid unnecesary rebuilds from the image.
Fixes #259
> metrics: Automate docker image builds to reduce unnecessary rebuilds

- .ci/install_kata_image.sh
Verify that `IMG_MOUNT_DIR` variable has a value before
trying to umount it.
Fixes #454.
> CI: Fix cleanup in install_kata_image.sh

- .ci/run_metrics_PR_ci.sh
- metrics/network/cpu_statistics_iperf.sh
- metrics/network/iperf_dockerfile/Dockerfile
This will retrieve cpu information like instructions,
cycles and instructions per cycle using perf while
running an iperf3 network benchmark.
Fixes #365
> metrics: Add cpu information test

- .ci/kata-arch.sh
The `kata-arch.sh` script was assuming the wrong output from `arch(1)`
on arm64.
Fixes #458.
> CI: Fix arch script for arm64

- .ci/static-checks.sh
As currently we are having issues in the CI with several PRs,
the tool should not run in order to have a healthy CI.
Fixes #463
> ci: Disabling TODO/FIXME checker

- integration/kubernetes/init.sh
- integration/kubernetes/nginx.bats
We need to increase timeouts as the CI environment might be slow to
setup all the pods.
Fixes #456
> tests: k8s: Increase timeouts for integration tests

- .ci/install_crio.sh
- integration/kubernetes/init.sh
We now need to use full url format:
"unix:///var/run/crio/crio.sock".
Fixes: #456.
Depends-on: github.com/kata-containers/runtime#454
> k8s: Update cri-o endpoint

- .ci/README.md
- .ci/kata-simplify-log.sh
Create a simple script that will convert standard patterns into fixed
strings so that two log files can be compared more easily using
`diff(1)`.
Fixes #451.
> CI: Add log simplification script

- .ci/setup.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
Disable the systemd-journald rate limit in the CI systems
to capture full logs from Kata Containers components.
This will help us ensure we can debug failed CI jobs.
Fixes: #466.
> CI: Disable systemd-journald rate limit

- .ci/static-checks.sh
Add command-line options to all individual test functions in the `static-checks.sh` script to be run, rather than all of the tests.
Also includes commits for improved messages, and an explicit "skip" for the `TODO`/`FIXME` checker that was disabled on #464.
Fixes #470.
> CI: Add options to static-checks script

- cmd/log-parser/agent_test.go
- cmd/log-parser/logentry.go
- cmd/log-parser/parse.go
Extract the container ID from the structured logs and add it to the
standard `LogEntry` type. This will allow (most of) the log entries to
be associated with individual containers, which will make debugging and
analysis easier.
Also, enhance some of the errors that are returned to make locating the issue
in the log file easier.
Fixes #453.
> cmd/log-parser: Add containerID and sandboxID to standard log entry

- integration/cri-o/cri-o.sh
Use a block device attached to the VMs for testing
CRI-O with devicemapper, instead of rely on loopback
devices.
Fixes #442.
Depends-on: github.com/kata-containers/runtime#454
> tests: Use block device for cri-o tests

- .ci/run.sh
- .ci/teardown.sh
The CI run script contained a couple of tests that need to be in the
teardown script since they:
- are not part of the test run itself.
- need to be run for all repos, not just `tests`.
Also required the teardown script to be reworked to put the existing code into its own function.
Fixes #449.
> CI: Move more tests to teardown

- integration/docker/docker.go
- metrics/density/memory_usage_inside_container.sh
latest version of alpine image is broken, use 3.7 which
is the last know working version.
Fixes: #481.
> CI: do not use latest version of alpine docker image

- integration/swarm/swarm.bats
Fix the way that we are doing the swarm init when we have
multiple interfaces with different addresses
Fixes #483
> tests: Fix Swarm integration test to fix swarm init

- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
We used `chronic` to wrap most package installs to keep them
quiet unless they failed, but seemed to have missed some
later additions. Wrap those with `chronic` as well.
Fixes: #479
> CI: Add more use of chronic

- .ci/jenkins_job_build.sh
It can be very helpful to know exactly which components we ran
the tests against. Log the output of `kata-runtime kata-env`,
which gives us all the pertinent information.
Fixes: #477
> CI: jenkins: log kata-env output

- .ci/jenkins_job_build.sh
Run kata-env only if the runtime is installed.
Fixes: #485
> ci: Get kata runtime env only if installed.

- metrics/density/docker_memory_usage.sh
The parallel `docker rm -f` in the test often runs into
the hang up detailed at:
https://github.com/kata-containers/runtime/issues/406
Until that is resolved, try to work around the hang with
some timeouts and serialisation of the rm's.
Fixes: #475
> metrics: density: serialise docker rm and stops

- integration/kubernetes/init.sh
When initializing k8s, a script deletes the cni interface
that we use for the cri-o tests, but if the interface does
not exist, the script fails. This change checks if it exists
before trying to delete it.
Fixes #490.
> k8s: check cni inteface exists before delete it

- .ci/install_qemu.sh
- .ci/lib_install_qemu_aarch64.sh
for now, default hypervisor would be qemu instead of qemu-lite in aarch64. packaged qemu has only be supproted in fedora and ubuntu for aarch64.
Fixes: #472
> ci: support install_qemu in aarch64

- .ci/lib_kata_image_aarch64.sh
patch #462(https://github.com/kata-containers/runtime/pull/462)has been restructured under upstream review, so refining image-type to follow change.
Fixes: #472
> ci: refine image-type for arm64

- integration/stability/agent_stability_test.sh
This stability test will run a container and the perform
several execs to that container.
Fixes #405
> test: Add stability test

- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/setup_env_centos.sh
Sometimes OBS services are down, so we cannot rely on
them all the time. If getting a package from OBS fails,
build and install it from sources instead of failing.
Fixes: #500.
> CI: Build from sources if packages couldnt be installed

- Makefile
- integration/cri-o/cri-o.sh
- integration/kubernetes/k8s-cpu-ns.bats
- integration/kubernetes/run_kubernetes_tests.sh
Changes:
- only export LVM_DEVICE when using devicemapper
- ensure crio service is stopped before running tests
> crio test fixes

- .ci/setup.sh
- Makefile
- cmd/container-manager/manage_ctr_mgr.sh
- integration/kubernetes/k8s-cpu-ns.bats
This PR contains 3 commits:
1. Fixes the container-manger.sh to install the correct docker version on centos. 
2. Adds a check to the setup.sh to install correct docker version if the installed one is different.
3. Re-enable cri-containerd and k8s tests
> Re-enable cri-containerd and k8s tests

- integration/docker/docker.go
- integration/docker/main_test.go
- integration/docker/mem_test.go
This will test the memory constraint of a container.
Fixes #496
> test: Add docker integration memory constraints test.

- .ci/run_metrics_PR_ci.sh
Enable checkmetrics percentage reporting mode in the
metrics CI run script.
Fixes: #517
> metrics: CI: enable percentage reporting

- .ci/jenkins_job_build.sh
Unit tests in centOS are failing.
Issue: https://github.com/kata-containers/runtime/issues/228
But we need to enable centOS as part of the runtime CI, in order
to prevent regressions. So this change will skip unit tests
of the runtime repo when running on centOS
Fixes: #537.
> CI: skip runtime unit tests if running on CentOS

- .ci/install_crio.sh
- integration/containerd/cri/integration-tests.sh
Now that docker-ce 18.06 was released, docker-containerd listens
by default on the port 10010, same that cri-o and cri-containerd
use. To avoid issues for using the same port, change the ports
of crio and cri-containerd.
Fixes: #520, #521.
> CI: change ports that crio and cri-containerd use

- .ci/install_kata_kernel.sh
The Kata packaging now provides an script to build a kernel.
Fixes: #531 
/cc Pennyzct.
> ci: Install kernel with new script.

- .ci/teardown.sh
If the CI is running in an environment where the runtime is available and if the runtime is configured to use an image (as opposed to an initrd), enable strict log checking.
Fixes #542.
> CI: Enable strict log checking for image testing

- metrics/network/README.md
- metrics/network/network-metrics-nuttcp.sh
- metrics/network/nuttcp_dockerfile/Dockerfile
Add network bandwidth tests for different buffer sizes with
nuttcp performance tool.
Fixes #540
> metrics: Add nuttcp bandwidth tests

- metrics/lib/common.bash
- metrics/lib/json.bash
Fix the proxy version extraction for the JSON metrics results data.
Add storage of the complete `kata-env` json output to the JSON metrics results data.
> metrics: fix proxy version and add kata-env to JSON results

- integration/docker/kill_test.go
As issue https://github.com/kata-containers/shim/issues/74 is already
solved, we can remove the skip.
Fixes #550
> tests: Enable docker kill SIGWINCH test

- metrics/density/docker_memory_usage.sh
- metrics/density/footprint_data.sh
- metrics/lib/common.bash
For many of our 'used' test containers, issuing a `docker stop`
actually results in the stop timing out (as it cannot signal the
container to stop for any one of a number of potential reasons),
and then docker reverts to a kill anyhow. The cost of this is a
10s delay per `stop`, whilst docker times out and then issues the
kill. That costs us heavily when we are doing multi-container tests
using say 20 or 100 containers, as each one takes a 10s overhead
on stop/kill/removing it.
Move all the metrics test `stops` to be `kills`.
Fixes: #561
> metrics: use docker kill rather than docker stop

- integration/docker/port_test.go
Former port "8080" is a frequently used user port, and could cause 'address already in use' err. 
Above error maybe would not occur where CI is set up in vm, but it's possible in bare machine.
So I think maybe using ephemeral port would be a better option.
Furthermore, I have considered that we could pick free port from 1024 to 49151, but it will need `netstat` or `lsof` to check port state, leading to extra dependency. 
sooooooo, wdyt?😅 @jodh-intel
> ci: using ephemeral port to avoid conflicting

- cmd/container-manager/manage_ctr_mgr.sh
Fix how get_docker_version is retrieving the
information from `docker version` command
Fixes: #572.
> manage_ctr_mgr: Fix get docker version

- .ci/setup.sh
In our .ci/setup.sh script, we make a comparsion of
the installed docker version. But we only need the major
and minor versions to make the correct comparison. This
change removes unneeded characters from the version
string.
Fixes #574.
> CI: compare only MAJOR.MINOR version of docker

- .ci/configuration_aarch64.yaml
For supporting filter scheme in arm64, configuration_aarch64.yaml file should be added to elaborate supported integration test components and which test suites under docker integrtion need to be skipped for now.
Fixes: #472
> ci: add configuration file for filter scheme

- .ci/filter_docker_aarch64.sh
- .ci/filter_test_aarch64.sh
- .ci/lib_setup_aarch64.sh
- .ci/setup.sh
- Makefile
- arch/aarch64-options.mk
1. Not all test components are supported in all archs, so adding filter scheme to select specific ones for different archs is necessary.
a few test components wouldn't be supported in aarch64 for quite a time(such like: swarm, etc.)
2. For supporting filter scheme in arm64, configuration_aarch64.yaml file should be added to elaborate specific test components in arm64 ci.
for now, this configuration file is just for elaborating whole filter frame.
@jodh-intel @weichen81
>  ci: add filter scheme for architecture-independent

- Makefile
- integration/stability/soak_parallel_rm.sh
- metrics/lib/common.bash
Add an 'rm' soak test. The test was originally written
to capture 'stuck' docker rm's of many containers, but
as it also does a lot of sanity checking of many other
parts of the system (checks for runtime/qemu/proxy/shims
running when they should, and not running when they should
not, and that 'kata-runtime list' matches what we have asked
docker to do, and check we don't leave dangling mounts around
etc.), it has also been useful for general stability checking.
Fixes: #195
> integration: soak: add rm soak test

- metrics/lib/common.bash
- metrics/lib/json.bash
- metrics/time/launch_times.sh
Under some conditions we generated invalid JSON for some launch time data.
The runtime 'path' was also the path to the config file, not the runtime itself.
Correct both of those.
> metrics: json: fix invalid and misleading JSON output

- .ci/install_openshift.sh
We do not use skopeo tool for openshift testing,
so lets remove this tool from our scripts.
Fixes: #612.
> openshift: remove skopeo tool

- .ci/kata-arch.sh
The arch program is disabled by default during the coreutils build
process.  To follow the project's recommendation for equivalent
functionality, switching to using the uname program as a more
forward-looking option for determining the architecture of a machine.
This change has been tested on Ubuntu, CentOS, Fedora, and OpenSUSE.
It enables Kata Containers tests to run on Clear Linux.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
> ci: Use uname program to determine machine architecture

- metrics/network/README.md
- metrics/network/network-metrics-iperf.sh
This will measures bidirectional bandwidth using iperf.
Fixes #583
> metrics: Add bidirectional iperf network bandwidth

- .ci/jenkins_job_build.sh
`jenkins_job_build.sh` script was designed to work with master
branch and with PRs that were going to be merged to master branch.
This patch adds support for testing branches different than master.
Fixes: #585.
> CI: adapt jenkins_job_build to support multiple branches

- metrics/network/README.md
- metrics/network/network-metrics-memory-pss.sh
Measures network PSS memory consumption using smem tool while
running a network workload with nuttcp.
Fixes #604
> metrics: Add network memory PSS consumption

- .ci/run_metrics_PR_ci.sh
- metrics/lib/common.bash
- metrics/report/README.md
- metrics/report/grabdata.sh
- metrics/report/makereport.sh
- metrics/report/report_dockerfile/Dockerfile
- metrics/report/report_dockerfile/dut-details.R
- metrics/report/report_dockerfile/footprint-density.R
- metrics/report/report_dockerfile/genreport.sh
- metrics/report/report_dockerfile/lifecycle-time.R
- metrics/report/report_dockerfile/memory-footprint.R
- metrics/report/report_dockerfile/metrics_report.Rmd
Add a set of scripts that can be used to gather metrics data and then generate a consumable report for 1-n sets of gathered data.
Can be used to assess a single setup, or to compare multiple setups or sets of gathered data.
> metrics: add data gathering and report generation scripts

- .ci/jenkins_job_build.sh
With this patch, we will use the correct branch of the
tests repository to test changes of other repositories,
as we cannot use master branch to test a stable branch from
another repository.
E.g. We must use 'kata-containers/tests' stable-1.1 branch
for testing changes of the 'kata-containers/runtime'
stable-1.1 branch.
Fixes: #625.
> CI: use correct branch for testing stable branches

- metrics/network/README.md
- metrics/network/network-metrics-memory.sh
Add support to Resident Set Size (RSS) and Virtual Set Size (VSS) of the
hypervisor footprint on the host using smem while running a transfer of one GB with nuttcp.
Fixes #623
> metrics: Add Resident Set Size and Virtual Set Size memory support.

- .ci/install_runtime.sh
- config.go
- integration/docker/vsock_test.go
- integration/stability/soak_parallel_rm.sh
- Add support for the CI to be able to configure kata-runtime with `use_vsock = true`
- Add test to verify that kata-proxy does not run when using vsock.
> Add vsock test

- metrics/network/README.md
- metrics/network/network-metrics-nginx-ab-benchmark.sh
This test uses an nginx container and runs the apache benchmarking tool
in the host to calculate the requests per second.
Fixes #629
> metrics: Add network nginx ab benchmark

- .ci/jenkins_job_build.sh
- .ci/lib.sh
When building and installing kata-containers components,
we need to checkout to the specific branch we are testing
instead of doing it with master.
Fixes: #633.
> CI: checkout to correct branch on kata-containers repos

- metrics/density/docker_memory_usage.sh
Now that this issue has been solved https://github.com/kata-containers/agent/pull/263,
it is necessary to remove the workaround of sleeping while shutting down containers.
Fixes #635
> metrics: Remove sleep while shutting down multiple containers

- .ci/teardown.sh
Undo part of [1] which erroneously enabled the log parsers strict mode:
this cannot be used (still) due to the kernel console output corrupting
the agent log output [2].
Fixes #640.
[1] - https://github.com/kata-containers/tests/pull/543
[2] - https://github.com/kata-containers/agent/issues/255
> CI: Don't run log-parser in strict mode

- metrics/density/footprint_data.sh
Now that this issue has been solved kata-containers/agent#263,
it is necessary to remove the workaround of sleeping.
Fixes #644
> metrics: Remove sleep for the footprint script

- .ci/install_openshift.sh
- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/static-checks.sh
openshift: remove skopeo tool
CI: adapt jenkins_job_build to support multiple branches
CI: use correct branch for testing stable branches
CI: checkout to correct branch on kata-containers repos
CI: skip checkcommits on travis for stable branch
> backport fixes 1.2

- .ci/static-checks.sh
checkcommits tool is not working on stable branches, when
runnint on travis. Disable until we find a way to run it.
We still run checkcommits on jenkins, then this can be safely
disabled.
> CI: skip checkcommits on travis for stable branch

- .ci/lib.sh
Depends-on tag was not working when there was a missing
space between the colon and repository name of the tag.
Fixes: #639.
> CI: Fix Depends-on feature

- .ci/jenkins_job_build.sh
- .ci/static-checks.sh
- integration/swarm/swarm.bats
This fix will allow static-checks.sh tool to compare
the file diffs with the correct branch instead of
doing it with master.
Fixes #651.
> CI: fix static-checks for stable branches

- .ci/lib.sh
Instead of making cc the default value of this environment
variable, the default must be kata-runtime.
Fixes #600.
> CI: KATA_RUNIME default must be kata-runtime

- .ci/jenkins_job_build.sh
- .ci/static-checks.sh
This fix will allow static-checks.sh tool to compare
the file diffs with the correct branch instead of
doing it with master.
Fixes: #651.
> CI: fix static-checks.sh for stable branch

- .ci/lib.sh
A trailing whitespace was preventing to clone the repo
and moving to the correct directory.
Fixes: #639.
> depends-on: remove trail whitespace from repo string

- integration/docker/mem_test.go
run a container, update its memory constraints and check if the
constraints are applied in the memory cgroup
fixes #655
> Test memory constaints

- metrics/time/launch_times.sh
Fix the to kernel period time to print valid json numbers.
Fixes #562
> metrics: Fix launch_times script to emit valid json numbers

- .ci/jenkins_job_build.sh
- .ci/static-checks.sh
This fix will allow static-checks.sh tool to compare
the file diffs with the correct branch instead of
doing it with master.
Fixes: #651.
> stable-1.2: CI: fix static-checks.sh for stable branch

- integration/docker/volume_test.go
Now that kata-containers/runtime#657 has been solved, the device passed as
volume should also needs to be passed as device.
Fixes #684
> tests: Fix docker volume test

- integration/kubernetes/k8s-memory.bats
Currenlty the test 'running within memory constraints' has
been frequently failing in the CI. Disable it for having a
working CI until we find the root cause.
More info on: https://github.com/kata-containers/tests/issues/680
Fixes: #689.
> k8s: skip k8s memory test

- integration/docker/volume_test.go
Now that this issue has been merged https://github.com/kata-containers/runtime/pull/686,
we can enable this volume test.
Fixes #694
> tests: Unskip volume test for passing a block device.

- cmd/log-parser/README.md
The README for kata-log-parser does not mention
how to install the tool before its usage. Improve the 
README by including those steps. 
Fixes: #696
> log-parser: Add installation steps before usage in README

- integration/docker/run_test.go
Add a docker integration tests that verifies than when a host
networking is requested the runtime fails.
Fixes #528
> tests: Add test to verify that host networking fails

- .ci/lib.sh
- .ci/run.sh
- .ci/setup.sh
With this we will fix that when running the setup.sh script (which is
calling functions from lib.sh).
Fixes #535
> ci: Check GOPATH exists

- .ci/run_metrics_PR_ci.sh
- cmd/checkmetrics/baseline/density-CI.toml
If we are on a known noisy/time variant system then we can still
run some metrics that are nominally time insensitive (like the
footprint/density tests). Modify the scripts so we can set an
env var to notify we are on such a system, and thus adapt the
tests we run, and how we locate a correct checkmetrics file to
use to check the results.
Fixes: #698
> metrics: ci: enable cloud instance metrics CI

- .ci/aarch64/clean_up_aarch64.sh
- .ci/jenkins_job_build.sh
We should provide clean environment for each build, when CI running on bare-metal, so a few clean-up work such as killing stale process, removing history data, etc, are needed.
Fixes: #671
Signed-off-by: Penny Zheng penny.zheng@arm.com
> ci: a few clean-up work for CI environment on bare-metal machine

- Gopkg.lock
- integration/docker/docker.go
- integration/docker/main_test.go
- stress/Dockerfile
- stress/main.go
- vendor/code.cloudfoundry.org/bytefmt/LICENSE
- vendor/code.cloudfoundry.org/bytefmt/NOTICE
- vendor/code.cloudfoundry.org/bytefmt/bytes.go
- vendor/code.cloudfoundry.org/bytefmt/package.go
`vish/stress` is a single-arch image for amd64, here are the outputs from `manifest-tool inspect vish/stress`:
```
vish/stress: manifest type: application/vnd.docker.distribution.manifest.v2+json
Digest: sha256:b6456a3df6db5e063e1783153627947484a3db387be99e49708c70a9a15e7177
Architecture: amd64
OS: linux
layer 1: digest = sha256:2ce2382a5646300744a450bcd4d7c0e279fa400c5133044e5398a6fe81b5f554
```
It is a single-arch image only for amd64. 
I found out the github repo for this project [vishh/stress](https://github.com/vishh/stress), and the code is a little stale, the dependency it used being invalidated.
Furthermore, since Arm.co has legal issue, it is complicated for us to load binary or image. the review procedure could be sooooooooooo long.😭  
That's why I include building-image process …
> ci: memory-tested image vish/stress is single-arch image for amd64

- .ci/go-test.sh
We've hit more go test timeout in CI. CI already cost 10s of minutes,
there is no reason not to tolerant a bit more time just for `go test`.
Fixes: #703
Signed-off-by: Peng Tao <bergwolf@gmail.com>
> ci: increase go test timeout

- integration/cri-o/cri-o.sh
- integration/cri-o/crio_skip_tests.sh
Now that this issue has been fixed kata-containers/agent#138,
we can enable the test 28 (ctr update) and test 31 (ctr resources) for our CRI-O testing.
Fixes #715
> tests: Enable two CRI-O tests

- .ci/install_cri_containerd.sh
- .ci/install_crio.sh
- .ci/install_kata.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_kubernetes.sh
- .ci/install_openshift.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/jenkins_job_build.sh
- .ci/setup.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
- cmd/container-manager/manage_ctr_mgr.sh
- cmd/kata-manager/kata-manager.sh
- integration/containerd/cri/integration-tests.sh
- integration/cri-o/cri-o.sh
- integration/kubernetes/run_kubernetes_tests.sh
- integration/openshift/run_openshift_tests.sh
Fixes #589
Low hanging fruit 😄  @grahamwhaley @jodh-intel @jcvenegas PTAL
Adding "|| source /usr/lib/os-release" to all the lines with "source /etc/os-release"
Signed-off-by: Ricardo Aravena <raravena@branch.io>
> CI: Fix optional /usr/lib/os-release

- integration/kubernetes/nginx.bats
- integration/stability/soak_parallel_rm.sh
- metrics/network/network-metrics-nginx-ab-benchmark.sh
- versions.yaml
With versions.yaml we will be able to specify which nginx version is
working.
Fixes #700
> tests: Add versions.yaml in order to support nginx working image

- integration/docker/mem_test.go
In test integration/docker/mem_test.go, we run a docker with
512M memory, and update it with 256MB. But we don't support
memory hot remove in kata-runtime update interface now. So we
should change the memory constraints update.
Fixes #723
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
> integration/docker: modify testcase of memory constraints update

- .ci/lib.sh
- .travis.yml
9f67682 CI: Fix branch management when using Depends-on tag
f0cb182 CI: dont checkout kata_repo to the target branch
6b6a812 travis: Add variable needed to run static checks
38c38ac depends-on: remove trail whitespace from repo string
c1c2ae1 CI: KATA_RUNIME default must be kata-runtime
c0552de CI: Fix Depends-on feature
> stable-1.2: port back CI fixes

- .ci/lib.sh
- .travis.yml
8a51752 CI: Fix branch management when using Depends-on tag
0f255eb CI: dont checkout kata_repo to the target branch
4e2b38a travis: Add variable needed to run static checks
c7c96ae depends-on: remove trail whitespace from repo string
d9babe7 CI: KATA_RUNIME default must be kata-runtime
38cf364 CI: Fix Depends-on feature
> stable-1.1: port back CI fixes 

- integration/cri-o/cri-o.sh
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/init.sh
- integration/openshift/init.sh
- integration/openshift/teardown.sh
- integration/popular_docker_hub_images/popular_docker_images.bats
- integration/swarm/swarm.bats
- metrics/lib/common.bash
Verify that processes (hypervisor, shim and proxy) are not running before
and after running tests like swarm, popular docker images, kubernetes,
cri-o and openshift.
Fixes #725
> tests: Verify processes (hypervisor, shim and proxy)

- .ci/static-checks.sh
- .travis.yml
- cmd/log-parser/Makefile
- integration/docker/kill_darwin_test.go
- integration/docker/kill_linux_test.go
- integration/docker/kill_test.go
Run statick checks on linux-ppc64le and osx.
Fixes: #691.
> travis: add linux-ppc64le and osx

- metrics/network/network-metrics-iperf3.sh
Currently the help function have the option -l for parallel tests,
however, this option has been removed as iperf3 does not handle
parallel testing.
Fixes #729
> metrics: Remove parallel test option in iperf3 tests

- metrics/report/README.md
- metrics/report/grabdata.sh
- metrics/report/report_dockerfile/fio-reads.R
- metrics/report/report_dockerfile/fio-writes.R
- metrics/report/report_dockerfile/metrics_report.Rmd
- metrics/storage/README.md
- metrics/storage/fio.sh
- metrics/storage/fio_dockerfile/Dockerfile
- metrics/storage/fio_dockerfile/init.sh
Add an `fio` based storage metrics test.
By default it will perform uncached (O_DIRECT) read and write tests.
It can be configured through environment variables to modify a number of
its parameters (including direct/buffered, random, linear, r/w/rw tests, number of jobs etc.
The one fixed parameter is that it always performs the tests upon a single file.
Also add invocation of the test and use of the resulting data to the report generation scripts.
> metrics: add fio storage metrics test

- cmd/log-parser/README.md
Add details of how to extract the KSM throttler logs and feed them to
the log parser tool.
Fixes #745.
> log-parser: Update doc for throttler

- metrics/lib/json.bash
- metrics/report/report_dockerfile/dut-details.R
- metrics/report/report_dockerfile/fio-reads.R
- metrics/report/report_dockerfile/fio-writes.R
- metrics/report/report_dockerfile/footprint-density.R
- metrics/report/report_dockerfile/memory-footprint.R
- metrics/report/report_dockerfile/metrics_report.Rmd
- metrics/storage/fio.sh
A series of metrics report related updates, including:
- Add stats tables to fio pages
- Improve colour usage on system density graph
- Enable system info tables for `runc`
- A couple of other minor related bug/warn fixes
> metrics report update series

- .ci/teardown.sh
Save kernel log messages in the teardown script.
Fixes #752.
> CI: Add kernel logs to teardown script

- .ci/static-checks.sh
The default concurrency is 16 and it is quite likely to oom even on
a system with 4GB memory. Set it to `nproc` so that it scales
automatically. And it allow `make check` to run on developer's
local environment more easily.
Fixes: #758
Signed-off-by: Peng Tao <bergwolf@gmail.com>
> static-checks: limit gometalinter concurrency

- .ci/static-checks.sh
`nproc` is not available in Darwin, instead
use `sysctl -n hw.cpu`
Fixes: #764.
> CI: do not use nproc for Darwin

- .ci/static-checks.sh
Update the static check script to ignore text files when looking for
files that require a license header.
The `*.txt` extension is a generic file type so we cannot require a header since:
- We don't know what the file represents - it might be human-readable text or some other format without a unique file extension.
- Existing `*.md` doc files don't require a license header.
Also, semi-sorted the list of file patterns.
Fixes #769.
> CI: Do not require license header for text files

- metrics/report/makereport.sh
To avoid the issue of ls: cannot access '*/': No such file or directory,
while running the ./makereport.sh, we need to check that there is a
subdirectory at least in metrics/results
Fixes #737
> metrics: Check subdir exists while running makereport script

- .ci/teardown.sh
Update `teardown.sh` to now use the full path of `kata-collect-data.sh` when it is called. This is needed on Fedora and Centos, otherwise a `command not found` error appears. 
Also add a change to create the directory (if it doesn't exists) where the log files will be stored.
> CI: teardown fixes

- integration/cri-o/cri-o.sh
When running on Zuul, we might not get a block device
for testing CRI-O using devicemapper driver. This depends
on the region where the zuul slave is launched. Instead,
use overlay storage driver.
Fixes: #779
> tests: Use overlay for CRI-O when running on zuul

- .ci/teardown.sh
the `teardown.sh` collects and compresses log files, so that
jenkins can archive them, but we are also archiving the
uncompressed files, meaning that we are using more space
than the needed. With this, we remove the uncompressed log
files and save more space in the jenkins master.
Also, kernel, kata-vc-throttler and kata-ksm-throttler logs
will now be compressed.
> teardown: Remove uncompressed log files before archiving them

- .ci/install_cri_containerd.sh
- .ci/install_crio.sh
- .ci/install_kubernetes.sh
- .ci/jenkins_job_build.sh
- .ci/run.sh
- .ci/setup.sh
- Makefile
- integration/kubernetes/init.sh
- integration/kubernetes/k8s-cpu-ns.bats
- integration/kubernetes/k8s-uts+ipc-ns.bats
Handle the case when `"$CI_JOB" == "CRI_CONTAINERD_K8S"` this should be set by the CI to indicate K8s + containerd testing should be done.
> ci: Add support  for new CI job (k8s + containerd)

- integration/docker/docker.go
- metrics/density/memory_usage_inside_container.sh
- versions.yaml
For docker integration tests and memory tests, we are using a specific version
for the Alpine image. This version should be placed at versions.yaml in our
repository.
Fixes #795
> tests: Define Alpine version in the proper versions.yaml

- metrics/README.md
- metrics/lib/json.bash
For some storage endpoints (such as the filebeat TCP), it is
much easier to use `socat` to send the data, rather than trying
to figure out how to get `curl` to do it.
Also, ideally we should send the results as a single line, so
add that capability as well.
And finally, document the hooks, and add a ToC to the README.
Fixes: #790
> metrics: json: enable socat and single line transmit for json

- metrics/density/README.md
- metrics/density/docker_memory_usage.sh
- metrics/density/fast_footprint.sh
- metrics/density/footprint_data.sh
- metrics/lib/common.bash
Add a system level footprint test, that should be faster to run than the
existing footprint_data.sh test. It should be faster as it:
- launches containers in parallel, not just linearly
- does not take measurements after each launch, just at the start and end
> metrics: fast footprint

- integration/stability/soak_parallel_rm.sh
- lib/common.bash
This will enable the network monitor process at the configuration file as
well that it will verify that the number of netmons that are being launched
by this test are properly deleted.
Fixes #727
> tests: Check netmon process for the soak parallel test

- Makefile
- lib/common.bash
- sanity/check_sanity.sh
This will verify that processes like shim, hypervisor and proxy are not
left as well as that we do not have pods or runtimes running after
running our functional and integration tests.
Fixes #800
> tests: Add sanity test after running integration and functional tests

- .ci/static-checks.sh
Add a new test (and `--vendor` option) to the static checks script that
detects if the user modified vendored files directly without updating
the vendor control file.
Also contains a few minor fixes, including one to set the crucial `$branch` variable when running standalone.
Fixes #818.
> CI: Add vendor check to static checks script

- integration/docker/mem_test.go
Modify test of memory hotplug when create container.
Depends-on:github.com/kata-containers/runtime#786
Fixes #812
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
> integration/docker:modify test of memory hotplug when create container

- .ci/install_runtime.sh
If/when https://github.com/kata-containers/runtime/pull/819
gets merged, kata-check will need to run with sudo as
it will try to load the kernel modules if they are not
already loaded.
Fixes: #822.
Depends-on: github.com/kata-containers/runtime#819
> CI: run kata-check with sudo

- .ci/static-checks.sh
Update the license checker function in the static checks script to
ignore `*.pub` key files.
Fixes #826.
> CI: Make license checker ignore public key files

- .ci/static-checks.sh
The `xurls` tool used by the static checker seems to have changed its
URL so switch to the (hopefully more reliable!) github one.
Fixes: #835.
> CI: Fix xurls URL

- .ci/static-checks.sh
Update the static check script to ignore `file://` URLs which won't
exist (since they only appear in examples).
Fixes #837.
> CI: Make static check ignore local URLs

- metrics/density/memory_usage_inside_container.sh
Set a memsize and store it in the results.
This helps for later comparison of density data.
> metrics: density: in-container: set and store memsize

- cmd/kata-manager/kata-manager.sh
Remove a stray `echo`.
Fixes #847.
> cmd/kata-manager: Remove debug output

- .ci/static-checks.sh
All *.pb.go files are generated files from *.proto files. There is no
reason to ignore only the ones from protocols/grpc subdirectory.
Fixes #851
> ci: Static checks for license should ignore any *.pb.go file

- .ci/static-checks.sh
Any *.pb.go file means auto-generated file. Therefore, there's no
reason to check the validity of those files with the gometalinter.
Fixes #853
> ci: Exclude all *.pb.go files from gometalinter checks

- .ci/lib.sh
Needed now that we have a travis job for ppc64le.
Fixes #859.
> CI: add support for ppc64le to install_yq

- .ci/install_go.sh
- .ci/jenkins_job_build.sh
force flag will be used in the CI scripts to remove the
current golang version and install the correct one.
This is useful on baremetal machines where golang is already
installed and versions differ from the one needed to test kata.
Fixes: #857.
> CI: add force flag to install_go.sh

- metrics/report/grabdata.sh
- metrics/report/report_dockerfile/lifecycle-time.R
- metrics/report/report_dockerfile/mem-in-cont.R
- metrics/report/report_dockerfile/metrics_report.Rmd
- metrics/report/report_dockerfile/network-cpu.R
Add the network-cpu and in-container-memory consumption tests to the reportgen.
This will allow us to try and identify any:
-  network CPU work related overheads
- in-container memory overhead changes.
> metrics: report: Add net-cpu and in-container-mem tests

- .ci/lib.sh
- .ci/static-checks.sh
- versions.yaml
Build the version of `xurls` specified in the runtimes versions
database to avoid problems; the latest version of `xurls` requires
golang 1.10.3 but that is not available in the stable branches.
Includes rework to the `.ci/lib.sh` functions to support building a particular version of a package.
Fixes #855.
> CI: Use specific version of xurls utility

- conformance/posixfs/Dockerfile
- conformance/posixfs/fstests.sh
Checks that the container's filesystem supports the most common filesystem
operations.
Fixes #814
> tests: Add posix filesystem conformance test

- .ci/go-test.sh
It is possible for the `go-test.sh` script to fail when attemping to
write to a file as it can already be closed. This problem seems to
relate to the golang `testing` package itself so work around the
problem by specifying an explicit temporary directory for `testing` to
create files in.
Fixes #869.
> CI: Specify tmpdir for running golang unit tests

- metrics/report/report_dockerfile/Dockerfile
We were creating the Rmarkdown processing docker image pretty
much by hand (with apt and R installs), but this takes a lot of
time, particularly for the R parts, as they install from source.
Change the Dockerfile to use the official 'tidyverse' base, and
then install the R parts using the install2.r, which uses binaries
where possible. This speeds up the first-time image build.
Fixes: #862
> metrics: report: optimise Dockerfile image creation

- metrics/report/grabdata.sh
- versions.yaml
Update working elasticsearch version in order to run the grab data
report generator.
Fixes #866
> metrics: Update working elasticsearch version.

- .ci/data/crio.service
- .ci/install_crio.sh
- .ci/static-checks.sh
- integration/cri-o/cri-o.sh
cri-o updated its location from the `kubernetes-incubator` org
to the `kubernetes-sigs`. Althogh the old org URL is
redirecting to the newest, lets update the location to avoid
future issues.
Fixes: #872.
> cri-o: update repository location

- .ci/install_kata_image.sh
- .ci/jenkins_job_build.sh
We were configuring docker to use runc very early on in the jenkins
run script, which would fail if docker was not already installed. And
then later we would install docker in setup.sh.
We only need to set runc as the default runtime if we are going to
do an osbuilder image build, so let's delay that setup until the
point where we need it, by which time docker should have been
installed.
Fixes: #878
> CI: setup: docker: Delay when we reconfig docker

- .ci/install_go.sh
- .ci/setup.sh
Fixes: #883
Signed-off-by: Sudeesh John sudeeshjohn@in.ibm.com
> Adding ppc64le support for CI

- metrics/report/report_dockerfile/fio-reads.R
- metrics/report/report_dockerfile/fio-writes.R
The fio 95/99 percentile boxplot fio results are quite hard
to read, especially if the data is noisy. Try to improve
the readability by joining the mean points across the
boxplot.
Fixes: #885
> metrics: report: fio latency: improve lat graph

- Makefile
- integration/network/ipvlan/ipvlan_driver.bats
Now that https://github.com/kata-containers/runtime/pull/852 has been merged,
we need to test docker integration tests with ipvlan driver with l2 and l3 mode.
Fixes #861
> tests: Add ipvlan driver tests

- Makefile
- integration/entropy/entropy_test.bats
The main purpose of this test is to print the entropy level
inside the container after we installed the haveged package.
We need to verify that the entropy level is not < 1000
https://wiki.archlinux.org/index.php/Haveged.
Fixes #734
> test: Add entropy test

- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/x86_64/clean_up_x86_64.sh
Enable the bare metal slave machine cleanup scripts to be
called from any arch (lifting out the good work done for the
ARM slave cleanups).
Fixes: #888
> CI: baremetal: make cleanup scripts more generic

- cmd/container-manager/manage_ctr_mgr.sh
use apt-cache madison to get docker version on ubuntu
- To get the proper docker version to install, we need to now use
`apt-cache madison` since `apt-cache show` is throwing an error.
- Stop the docker service before removing the
package.
- Do not quote `pkg_name` as it can contain more than
one package that we need to remove. e.g. `docker-ce` and
`docker-ce-cli`.
Fixes: #895
> Fix `manage_ctr_mgr.sh`

- .ci/jenkins_job_build.sh
The baremetal cleanup scripts use `tests_repo` to find the funcs
to call, but that is not currently propagated from the caller.
Rather than export or source, let's pass it on the commandline
when calling the sub-scripts.
Fixes: #897
> ci: cleanup: pass tests_repo to cleanup scripts

- .ci/resolve-kata-dependencies.sh
One more tab should be placed for the current_branch variable to fix
broken syntax.
Fixes #876
> .ci: Fix the indention for current_branch variable.

- Makefile
- integration/network/ipvlan/ipvlan_driver.bats
- integration/network/macvlan/macvlan_driver.bats
Now that macvlan and ipvlan has been merged
https://github.com/kata-containers/runtime/pull/852 and
https://github.com/kata-containers/runtime/pull/506, we
can enable the test to run in our CI.
Fixes #899
> tests: Enable macvlan and ipvlan tests

- .ci/setup.sh
If CI envar is not found, the `setup.sh` script fails
because of an unbound variable.
Add default value of CI=false
Fixes #911.
> setup: add CI default value on setup.sh

- .ci/aarch64/clean_up_aarch64.sh
- .ci/lib.sh
- .ci/x86_64/clean_up_x86_64.sh
We should probably never fail the cleanup script call, as we may be trying to clean
an unstable or part-cleaned system. Stop requiring `-e`, and add an `|| true` to the top
level call.
> ci: bare cleanup: never fail the cleanup

- .ci/install_qemu.sh
- .ci/lib.sh
We have a glitch where installing qemu from packages could silently fail under some circumstances.
This has been seen on a bare metal CI machine.
Improve the situation by:
- making the package install more robust
- removing the packages in the bare metal cleanup scripts.
> ci: ensure cleanup/install of packages

- integration/kubernetes/k8s-memory.bats
Update the value for allocated size memory for the k8s memory constraint test.  The amount of memory that can be allocated has decreased from 150M to 100M as it looks that the kernel is taking more memory.
Fixes #680
> test: Update k8s memory constraints tests

- .ci/aarch64/configuration_aarch64.yaml
Since the new feature: memory hotplug, which uses the `(qemu) device_add pcdimm,id=dimm1,memdev=mem1` to limit memory on runtime, is not availble on arm platform, for now we just have to resort to skip relevant tests in aarch64.
Fixes: #879
Signed-off-by: Penny Zheng penny.zheng@arm.com
> ci: skip memory integration tests on aarch64

- .ci/aarch64/filter_docker_aarch64.sh
- .ci/aarch64/filter_test_aarch64.sh
- .ci/lib.sh
Since that filter schme on aarch64 bare-metal machine would fail if it is lack of yq, we should detect the existence of yq before going into and also install it if it is really missing.
Fixes: #867
Signed-off-by: Penny Zheng penny.zheng@arm.com
> ci: detect the existence of yq before using filter scheme on aarch64

- .ci/install_kubernetes.sh
ci scripts fail when the system has a new version of kubernetes,
to fix this problem --allow-downgrades must be used.
fixes #927
> ci: allow downgrades to install kubernetes

- .ci/lib.sh
killall will only kill processes using the specified (exact)
binary. It will not kill off any processess running off a previously
unlinked binary (of the same name/path).
Replace the killall with a kill to clean up all processess of the
specified name.
Fixes: #92
> cleanup: don't use killall, replace with kill

- integration/kubernetes/k8s-liveness-probes.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/untrusted_workloads/pod-liveness.yaml
This will verify that kubelet is able to perform a liveness probe for an
amount of time.
Fixes #929
> tests: Add K8s test for Liveness probes

- .ci/configure_containerd_for_kata.sh
- .ci/configure_crio_for_kata.sh
- .ci/install_cri_containerd.sh
- .ci/install_crio.sh
- .ci/setup.sh
This PR seperates installation and configuration of CRI shim + kubernetes from configuration of CRI shim to make use of kata containers.
This'll allow for better re-use when we want to just bring up a kubernetes node with crio/containerd (example, if you want to make use of kata-deploy).
> Cri install then configure

- .ci/install_runtime.sh
We enable full debug in the CI install scripts, but that
costs us about 0.25s in boot time. Do not enable the debug
if we are doing a METRICS_CI build/run.
Fixes: #923
> ci: metrics: do not enable debug for metrics CIs

- integration/kubernetes/k8s-attach-handlers.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/untrusted_workloads/lifecycle-events.yaml
We create a Pod that has one container. The container has handlers for
postStart and preStop events and then we verify the message for the
postStart event.
Fixes #904
> tests: Add K8s test to check postStart handlers

- integration/kubernetes/untrusted_workloads/busybox-pod.yaml
- integration/kubernetes/untrusted_workloads/busybox-template.yaml
- integration/kubernetes/untrusted_workloads/nginx-deployment.yaml
- integration/kubernetes/untrusted_workloads/pod-cpu.yaml
- integration/kubernetes/untrusted_workloads/pod-liveness.yaml
- integration/kubernetes/untrusted_workloads/pod-memory-limit.yaml
We need to add headers to the kubernetes tests yamls in order to
have consistency.
Fixes #949
> test: Add headers to the kubernetes tests yamls

- metrics/density/memory_usage_inside_container.sh
We need a sleep before taking the measurement of the memory inside
of a container. This change is necessary as the kernel takes time
to hotplug the memory.
Fixes #931
> metrics: Add sleep before gathering memory inside the container

- bundle.go
- container.go
- functional/state_test.go
Following an issue that we found with the kata-runtime regarding
a wrong state being reported after the container workload terminated,
this patch introduces a test that runs a simple container workload
and validate that the value obtained after a few seconds is "stopped".
Previously, this test would have failed as we would have retrieved
"running", which is a wrong value in this case.
Fixes #956
> functional: Add test checking for container state

- Makefile
- integration/network/disable_net/net_none.bats
We are disabling networking at the configuration.toml as well as running
a container with the flag of --net=none.
Fixes #932
> test: Docker integration test for disable networking

- integration/kubernetes/k8s-volume.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/untrusted_workloads/pv-pod.yaml
- integration/kubernetes/untrusted_workloads/pv-volume.yaml
- integration/kubernetes/untrusted_workloads/volume-claim.yaml
This test will create a persistent volume that is backed
by physical storage and then we will create a persistent
volume claim which will automatically bound to the persistent
volume and finally we will create a pod that uses a persistent
volume claim as a storage.
Fixes #921
> tests: Add K8s tests for persistent volumes

- .ci/install_crio.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
- versions.yaml
the centos image that is used in the vexxhost cloud was updated to 7.6, which is good, but the go-md2man package is no longer available, this is why the cri-o tests started to fail. 
Instead of getting the `go-md2man` from the centos repositories, build and install it from sources.
Also, add yum configuration to fail when a package is not available. 
Fixes: #963.
> centos: fix cri-o issues

- Makefile
- integration/oci_calls/oci_call_test.sh
Check OCI calls while running a docker run, docker stop and
docker run ..true in order to compare the arguments that we get
while running the containers with the OCI calls.
Fixes #941
> test: Check OCI calls

- .ci/lib.sh
When trying to kill off stale processes with a combination of
pgrep and kill, a mix of line separator and quotations meant the
kill only worked if we found a single process.
Fix by using a separator of ' '(space) for the pgrep and
don't quote the pid expansion - a pid list is just a plain
list of numbers with spaces between them.
Fixes: #974
> ci: cleanup: fix process kill for multiple processes

- integration/cri-o/crio_skip_tests.sh
unskip crio ulimits test now that kata support rlimits
Depends-on: github.com/kata-containers/agent#431
fixes #907
> integration/cri-o: unskip ulimits test

- .ci/jenkins_job_build.sh
- lib/common.bash
We should probably never fail on bare metal cleanup, as it is trying to potentially
clean up a corrupt system, and may hit things it does not expect.
Instead, try our hardest, and use some defaults if we cannot find the actual
runtime defaults.
> CI: bare metal: do not fail on bare metal cleanup

- integration/vm_factory/vm_templating_test.sh
Make sure it is not affected by being created from vm template.
Depends-on: github.com/kata-containers/agent#425
Depends-on: github.com/kata-containers/runtime#976
Fixes: #968
> vm_factory: add tests to check new vm time

- .ci/teardown.sh
Rather than dump the error line found and all its 'freinds',
which can result in massive log dumps, let's just dump the log
line we found.
If somebody does need to look at the complete log, the CI keeps
them as artifact attachments to the build run anyway.
Fixes: #1000
> CI: logs: reduce the log output upon error

- .ci/static-checks.sh
Fixed a typo in `check_files()` that was stopping the static analysis
script from working correctly when run with `--all`.
Fixes #998.
> CI: Fix static checker test with '--all'

- integration/docker/ulimit_test.go
Ulimit tests are to check resource limits in the container
fixes #986
> integration/docker: Add ulimit tests

- integration/kubernetes/k8s-security-context.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-security-context.yaml
- integration/kubernetes/untrusted_workloads/pod-security-context.yaml
This test sets a security context for a pod.
Fixes #1008
> test: Add K8s test using a security context

- Makefile
- integration/containerd/cri/integration-tests.sh
- integration/containerd/shimv2/shimv2-factory-tests.sh
- integration/containerd/shimv2/shimv2-tests.sh
Add the containerd-shim-kata-v2 testing cases
based on cri+containerd. 
Fixes: #616
Signed-off-by: Fupan Li <lifupan@gmail.com>
> CI: Add the shimv2 testing cases

- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/setup.sh
- .ci/setup_env_debian.sh
- cmd/container-manager/manage_ctr_mgr.sh
These set os scripts will installed system dependencies
as well all the components to run Kata Containers.
Fixes #964
> ci: Add installation scripts for debian.

- .ci/static-checks.sh
> static-checks.sh: skip svg figures

- .ci/resolve-kata-dependencies.sh
We need to add the packaging repo as a repository needed
for building the kata containers project.
Fixes #1024
Depends-on:github.com/kata-containers/packaging#295
> ci: Add packaging repo for kata dependencies

- metrics/lib/common.bash
Die function performs an exit 1 already so with this PR we will remove
the duplicated exits.
Fixes #1027
> metrics: Remove exit after using die function

- .ci/resolve-kata-dependencies.sh
Packaging repo only has the master branch, so we cannot
checkout to a different branch when running tests for
stable branches.
Fixes: #1034.
> ci: don't checkout to different branch on packaging repo

- metrics/time/launch_times.sh
The kernel dmesg output has changed around the 'Freeing kernel memory',
which we search for to try and identify the 'end of kernel' boot time.
Update the search expression we use to find the last instance of these
lines - which was as easy as trimming the 'memory' word from the end
of the expression, which now works for both older and newer kernel
demsg outputs.
As an example of how the outputs changed, here is a grep of two logs
(taken from bare metal hosts btw, not Kata Container boots):
$ grep "Freeing unused kernel" *log
newlog:[    2.243048] Freeing unused kernel image memory: 2180K
newlog:[    2.248191] Freeing unused kernel image memory: 2012K
newlog:[    2.248337] Freeing unused kernel image memory: 120K
oldlog:[    2.462519] Freeing unused kernel memory: 1528K
oldlog:[ …
> metrics: launch times: update end check for new kernel dmesg

- .travis.yml
For an unknown reason travis started failing when
installing bash on osx, but this is fixed when a
second attempt is run.
Fixes: #1041.
> travis: add retry for bash install on osx

- integration/kubernetes/k8s-memory.bats
- integration/kubernetes/k8s-qos-pods.bats
- integration/kubernetes/k8s-volume.bats
Some K8s tests are failing with initrd (issue: kata-containers/runtime#1127)
so we want to skip them in order to unblock the CI.
Fixes #1057
> tests: Skip failing K8s tests on initrd

- integration/stability/soak_parallel_rm.sh
Currently the soak test is looking for processes like qemu, kata-runtime,
kata-shim, pod information, and kata-netmon which are not available in
firecracker.
Fixes #1051
> test: Skip soak test for firecracker

- integration/containerd/shimv2/shimv2-tests.sh
shimv2 on centos have been randomly failing.
See: https://github.com/kata-containers/tests/issues/1047
Skip the test until issue gets solved.
Fixes: #1061.
> shimv2: skip test on centos

- integration/stability/soak_parallel_rm.sh
- metrics/lib/common.bash
In order to enable a Jenkins job, we need to install kata-ksm-throttler
and start it on Debian. We also need to disable the soak test for Debian,
as presently it detects some incomplete containers with incorrect status
(see: https://github.com/kata-containers/runtime/issues/1132).
Fixes #1054
> test: Modify soak test for Debian

- integration/oci_calls/oci_call_test.sh
We need to skip the oci_call_test for Debian as it is randomly
failing.
Fixes #1066
> test: Skip oci_call_test for Debian

- metrics/lib/common.bash
We need to check kata-ksm-throttler process only in Debian.
Fixes #1072
> test: Fix check kata-ksm-throttler process only in Debian

- .ci/install_qemu.sh
- .ci/ppc64le/lib_install_qemu_ppc64le.sh
Add scripts to install qemu as part of the CI.
Fixes: #1068
> CI: install qemu as part of CI scripts on ppc64le

- integration/kubernetes/k8s-memory.bats
- integration/kubernetes/run_kubernetes_tests.sh
Revert the memory value to the original value (https://github.com/kata-containers/tests/pull/534).
The main purpose of this is to fixed the bug (https://github.com/kata-containers/tests/issues/903)
where we could not allocated a memory size more than 100M.
Fixes #953
> test: Update allocated memory size value for K8s test

- .ci/install_firecracker.sh
All our tests are looking for the kata-runtime name so we need to modify
the name of the runtime for Firecracker in order that the tests run correctly.
Fixes #1078
> test: Change runtime name for Firecracker

- integration/docker/cp_test.go
Unskip docker cp test to check mount points are not left
after running docker cp.
Depends-on: github.com/kata-containers/runtime#980
fixes #970
> integration/docker: unskip docer cp test

- .ci/install_firecracker.sh
- .ci/install_kata.sh
- .ci/install_runtime.sh
- .ci/setup.sh
As we are installing from the tar, we are getting the static binaries for
runtime, shim, proxy, etc. With this change, we will avoid the duplication
of installing twice the kata elements.
Fixes #1075
> ci: Modify Firecracker installation

- .ci/static-checks.sh
Fix a big in the static check script `check_docs()` function where regex
anchoring was being used with `grep`. That command doesn't understand
anchors so it needs to be `egrep` instead.
Fixes #1085.
> CI: Fix new URL check logic in static check script

- cmd/kata-manager/kata-manager.sh
Remove directory if git clone fails, otherwise the following installation
fails.
> kata-manager: Remove directory if git clone fails.

- .ci/install_firecracker.sh
- .ci/run.sh
This will modify the run.sh in order to run the soak and the oci call
test for Firecracker.
Fixes #1087
> test: Modify run.sh for Firecracker tests

- .ci/ppc64le/lib_install_qemu_ppc64le.sh
Fix qemu installation which is part
of the CI irrespective of the installation
being from source or package.
Fixes: #1093
> CI: fix qemu install from build/package

- .ci/install_firecracker.sh
- .ci/install_kata.sh
- .ci/install_runtime.sh
- .ci/setup.sh
Instead of installing firecracker, runtime, and all the other Kata
components from the tar, this will change to install from the sources.
Fixes #1091
> ci: Modify Firecracker to install from repository

- .ci/hypervisors/firecracker/configuration_firecracker.yaml
- .ci/hypervisors/firecracker/filter_docker_firecracker.sh
- .ci/run.sh
- Makefile
Currently not all the docker integration tests are running
with Firecracker so with this change we filter the tests.
Fixes #1104
> test: Filter docker integration tests for Firecracker

- .ci/run.sh
- integration/network/disable_net/net_none.bats
Add networking tests (ipvlan and macvlan) and skip the disable
network test for Firecracker.
Fixes #1108
> test: Add and skip networking tests for Firecracker

- integration/docker/main_test.go
Since vish/stress is a single-arch image for amd64, we need
to build it for other architectures like arm64/ppc64le.
Fixes: #1113
> ci: Build memory-tested vish/stress image if arch arm64/ppc64le

- integration/popular_docker_hub_images/popular_docker_images.bats
The timeout -t flag is not longer supported while we are running
a container with crate.
Fixes #1116
> test: Remove -t flag from timeout as it is not longer supported

- .ci/install_qemu.sh
Use `git` instead of `go get` to clone qemu and its repositories since `go get`
downloads the repo and its modules hence it's too slow, this behaviour can fail
in systems that run behind a proxy.
fixes #1119
> ci: build and install qemu behind a proxy

- .ci/hypervisors/firecracker/filter_docker_firecracker.sh
- .ci/lib.sh
- .ci/run.sh
- .ci/setup.sh
The `.ci/lib.sh` script was setting `GOPATH` *three times*. Set it once in
the correct manner so that all scripts which source `.ci/lib.sh` will
have `GOPATH` set.
By setting `GOPATH` at the top of the script, this also resolves the
current CI error we're seeing where `GOPATH` is being referenced before
it's being set:
```sh
/home/centos/tests/.ci/lib.sh: line 19: GOPATH: unbound variable
```
Fixes #1133.
> CI: Set GOPATH once

- integration/docker/run_test.go
Enable docker integration test that verifies than when a host networking
is requested the runtime fails.
Fixes #833
> tests: Enable docker run integration test.

- .ci/ppc64le/clean_up_ppc64le.sh
Run clean-up script as we should provide clean environment
for each CI build.
Fixes: #1138
Signed-off-by: niteshkonkar@in.ibm.com
> CI: Run clean-up script for bare metal ppc64le environment

- cmd/kata-manager/kata-manager.sh
Add a `-f` option to forcibly remove packages that may be "held", "pinned" or locked.
Fixes #1143.
Support Debian, OpenSuSE, SLES and RHEL.
Fixes #1142.
> Kata manager improvements

- data/config.json
add cgroupsPath to test cgroup path creation in functional tests
fixes #1140
> functional: add cgroup path

- integration/docker/cpu_test.go
cpu cgroups in the host is about to be supported and currently the values to
test quota and period are too small to run a hypervisor.
fixes #1152
> integration/docker: increase quota and period

- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/init.sh
- integration/kubernetes/k8s-attach-handlers.bats
- integration/kubernetes/k8s-configmap.bats
- integration/kubernetes/k8s-cpu-ns.bats
- integration/kubernetes/k8s-credentials-secrets.bats
- integration/kubernetes/k8s-env.bats
- integration/kubernetes/k8s-liveness-probes.bats
- integration/kubernetes/k8s-memory.bats
- integration/kubernetes/k8s-parallel.bats
- integration/kubernetes/k8s-pid-ns.bats
- integration/kubernetes/k8s-pod-quota.bats
- integration/kubernetes/k8s-projected-volume.bats
- integration/kubernetes/k8s-qos-pods.bats
- integration/kubernetes/k8s-security-context.bats
- integration/kubernetes/k8s-uts+ipc-ns.bats
- integration/kubernetes/k8s-volume.bats
- integration/kubernetes/nginx.bats
Instead of using `/etc/kubernetes/admin.conf`, copy it to the
`$HOME/.kube/` of the non-root user to be able to make calls
to the kubernetes cluster without being root.
Also remove sudo from `kubectl` calls.
Fixes: #1154.
> k8s: do not use sudo when making calls to kubectl 

- cmd/kata-manager/kata-manager.sh
OpenSuSE Leap 15 set `ID=opensuse-leap` in `/etc/os-release`, whereas
the older Leap 42.3 sets `ID=opensuse`. Update the `kata-manager` script
to handle both values.
Fixes #1150.
> kata-manager: Handle OpenSuSE Leap 15

- .ci/lib.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_debian.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
- integration/stability/soak_parallel_rm.sh
- metrics/lib/common.bash
With this we will install kata-ksm-throttler and when it is installed
we will verify that this process is running. The main purpose is to
enable a Jenkins job for kata-ksm-throttler.
Fixes #1121
> ci: Kata-ksm-throttler for all the distros

- integration/kubernetes/e2e_conformance/run.sh
Add script that runs the heptio/sonobuoy e2e conformance
tests.
Fixes: #1081
Related: https://github.com/kata-containers/runtime/issues/1108
> tests: Add kubernetes e2e conformance test script

- metrics/density/docker_memory_usage.sh
It looks like our use of 'smem | grep' would fail if one of the PIDs
in the list was a subset of another PID - as the grep would extract
both PIDs, which we did not want (the script would fail on the later
shell math).
Fix this by using the awk itself to do the PID line extraction from
the smem with an exact PID match, which also has the nice benefit of
dropping the grep.
Fixes: #1147
> metrics: docker memory: runc: Handle multiple sub-set PIDs

- integration/oci_calls/oci_call_test.sh
Enable this test as it is not failing on the current Jenkins systems
(4 vcpus).
Fixes #1065
> test: Enable oci_call test for Debian

- Makefile
- integration/stability/bind_mount_linux.sh
Test if a container stops properly:
start a container with a bind mount and set bind propagation to a sub-directory of the mount point.
Fixes: #1016
Depends-on:github.com/kata-containers/runtime#963
Signed-off-by: <crossrunning@outlook.com>
> integration/stability: test for bind-mounted volumes

- Makefile
Check the KATA_HYPERVISOR variable to avoid the message of
`ci/hypervisors//filter_docker.sh: No such file`.
Fixes #1158
> test: Check KATA_HYPERVISOR variable at the Makefile

- integration/kubernetes/init.sh
- integration/kubernetes/kubeadm/config.yaml
Instead of hardcoding the k8s version that we are going to
use in the kubeadm config file, lets get it from the
`versions.yaml` file.
Fixes: #1171.
> kubeadm: don't hardcode k8s version on config file

- .ci/aarch64/configuration_aarch64.yaml
"remove bind-mount source before container exit" test suit has passed on aarch64, so delete it in
"configuration_aarch64.yaml"
Fixes: #1182
Signed-off-by: Jianyong Wu  <jianyong.wu@arm.com>
@grahamwhaley @jodh-intel @devimc @Pennyzct
> Integration: reopen a test suit under docker for arm64

- metrics/report/report_dockerfile/fio-reads.R
- metrics/report/report_dockerfile/fio-writes.R
The report is printing 98 for percentiles but it should be 99 for the fio
write and fio reads operations.
Fixes #1089
> metrics: Fix tittle for percentiles

- .ci/lib.sh
when umounting directory ../rootfs/ which has a few sub-directories mounted, we will face 'target busy' error. So we need to add '-R' flag to umount recursively.
I grab a snippet from ARM CI debug info and you can see the error `target is busy`:
` 23:30:15 umount: /run/kata-containers/shared/sandboxes/f302e1e4d4a1391bf43450e0c6abcc3178049328823659fb656b431e3b914fd8/f302e1e4d4a1391bf43450e0c6abcc3178049328823659fb656b431e3b914fd8/rootfs: target is busy.`
Logging into ARM CI and see the mount info:
```
root@testing-1:~# mount | grep "/run/kata-containers/shared/sandboxes/f302e1e4d4a1391bf43450e0c6abcc3178049328823659fb656b431e3b914fd8/f302e1e4d4a1391bf43450e0c6abcc3178049328823659fb656b431e3b914fd8" | awk '{print $3}' | sort -r
/run/kata-containers/shared/sandboxes/f302e1e4d4a1391bf43450e0c6 …
```
> clean-up: fix 'target busy' error when umounting on aarch64

- integration/kubernetes/k8s-liveness-probes.bats
- integration/kubernetes/runtimeclass_workloads/pod-http-liveness.yaml
- integration/kubernetes/runtimeclass_workloads/pod-tcp-liveness.yaml
- integration/kubernetes/untrusted_workloads/pod-http-liveness.yaml
- integration/kubernetes/untrusted_workloads/pod-tcp-liveness.yaml
Add K8s test for http and tcp liveness probes.
Fixes #1178
> test: Add K8s test for http and tcp liveness probes

- integration/kubernetes/k8s-attach-handlers.bats
- integration/kubernetes/k8s-configmap.bats
- integration/kubernetes/k8s-cpu-ns.bats
- integration/kubernetes/k8s-credentials-secrets.bats
- integration/kubernetes/k8s-env.bats
- integration/kubernetes/k8s-liveness-probes.bats
- integration/kubernetes/k8s-memory.bats
- integration/kubernetes/k8s-parallel.bats
- integration/kubernetes/k8s-pid-ns.bats
- integration/kubernetes/k8s-pod-quota.bats
- integration/kubernetes/k8s-projected-volume.bats
- integration/kubernetes/k8s-qos-pods.bats
- integration/kubernetes/k8s-security-context.bats
- integration/kubernetes/k8s-uts+ipc-ns.bats
- integration/kubernetes/k8s-volume.bats
- integration/kubernetes/nginx.bats
- lib/common.bash
k8s: mute message when runtimeclass is not configured
When runtimeclass is not configured on a test environment,
it is normal that we get this message:
```
error: the server doesn't have a resource type "runtimeclass"
```
This message is not the cause of a test failure, since we
use old trusted and untrusted tags when runtimeclass is not
configured.
To avoid confusion, lets send the message to /dev/null.
Also,  add information so that we know if we are running the
tests using runtimeclass or trusted/untrusted annotations.
Fixes: #1196.
> k8s: mute message when runtimeclass is not configured

- integration/ramdisk/ramdisk.sh
- lib/common.bash
- metrics/density/docker_memory_usage.sh
- metrics/lib/common.bash
- metrics/lib/json.bash
- metrics/time/launch_times.sh
Some of our metrics tests code presumed that kata was called `kata-runtime`, and that `kata-runtime` was always installed. That is not now the case with the advent of the static builds and `kata-fc`.
Update the scripts to handle the new runtimes and build types.
> metrics: fix tests to work with static kata (including fc)

- .ci/s390x/configuration_s390x.yaml
The correct name should be 'memory constraints'.
Fixes #1205
Signed-off-by: Tuan Hoang <tmhoang@linux.vnet.ibm.com>
> CI: correct memory test suite name on s390x

- integration/docker/cpu_test.go
Update cpu tests are failing because of a race condition between the test
and the kata agent. When a new CPU is hot plugged it's not connected
automatically, kata agent must receive the order to connect it, therefore
the existence of the directory /sys/devices/system/cpu/cpuX (where X is the
number of a CPU) is not a guarantee that the cpu is online, hence the tests
shouldn't check that directory, instead the online file of the last CPU should
be inspected.
fixes #1209
> integration/docker: fix update cpu tests

- .ci/aarch64/configuration_aarch64.yaml
- integration/docker/cgroups_test.go
Add test to check that cgroups are deleted properly even when
they contain running processes.
fixes #1177
> integration/docker: add test to check that cgroups are deleted

- integration/kubernetes/k8s-parallel.bats
- integration/kubernetes/k8s-volume.bats
Do not overwrite on pod template. Instead create a
temporary file from the template with the needed changes.
This will let us run the tests several times without messing
up with the template files.
Also, remove `declare -a` from `name` array declaration on `k8s-parallel.bats`
For some reason, when using `declare -a` on the `name` array,
the values of the array cannot be retrieved on the `teardown()`
function. This was preventing the `teardown()` to correctly delete
some auto generated pod config files.
So lets remove the `declare -a` and move the declaration
of it to the `setup()`.
> k8s: fix tests to be able to run them several times

- integration/ramdisk/ramdisk.sh
Ensure that dockerd is already running before trying to
run a container.
Fixes: #1222.
> ramdisk: verify docker is up before running a container

- integration/docker/cgroups_test.go
On Power arch, if --cpuset-cpus are set to
offline host cpus, the test shall fail. Fix
it by testing execution on an online host
cpu.
Fixes: #1241
> docker: Test to check cpu cgroups update fails on Power arch

- integration/kubernetes/k8s-qos-pods.bats
These tests have been failing because a cgroup gets out of
memory.
For details, see:
https://github.com/kata-containers/runtime/issues/1249
Skip them until we figure out what to do with this issue.
Fixes: #1239.
> k8s: skip Quality of Service tests

- integration/kubernetes/k8s-memory.bats
Currently the issue https://github.com/kata-containers/runtime/issues/1249
is blocking to run properly the memory constraints test.
Fixes #1244
> test: Skip memory constraints K8s test

- .ci/aarch64/clean_up_aarch64.sh
- .ci/lib.sh
- .ci/ppc64le/clean_up_ppc64le.sh
- .ci/s390x/clean_up_s390x.sh
- .ci/x86_64/clean_up_x86_64.sh
When cleaning up our servers, we should also try to remove the kata
repo links and keys. In the past we have seen issues when keys/repos
change and the old ones already exist, and it has prevented the new
ones being injected/updated. It's also just good practice to try and
remove all the things we installed...
Fixes: #1225
> ci: baremetal cleanup: remove repo links and keys

- integration/stability/soak_parallel_rm.sh
When using vsocks, the `kata-env` command does not provide
a kata-proxy path, so it is useless to run `pgrep` with an
empty path. Lets just don't check for the proxy process if
vsock is enabled.
Fixes: #1246.
> soak_test: don't check for proxy process if using vsocks

- cmd/checkversions/checkversions.sh
Add a script that pulls version/url information from our versions.yaml
files and checks the upstream for newer versions.
It makes use of the Debian 'uscan' tool.
WIP: still need to:
- filter out alpha versions upstream etc.
- add support for git SHA based 'versions'
> cmd: checkversions: A tool to check for upstream component updates

- integration/containerd/shimv2/shimv2-factory-tests.sh
- integration/containerd/shimv2/shimv2-tests.sh
Currently shimv2 tests are not working on openSUSE Leap
(https://github.com/kata-containers/tests/issues/1251).
Fixes #1252
> test: Skip shimv2 on openSUSE Leap

- integration/docker/cpu_test.go
change the bash code used to check the number of vcpus, the actual number of
vcpus is printed until it's equal to the expected number of vcpus,
otherwise the test fails.
fixes #1209
> integration/docker: fix cpu hotplug tests

- .ci/s390x/configuration_s390x.yaml
packaging/pull/340 allows these tests to work.
"CPUs and CPU set" test suite still does not work yet because it
requires CPU hot-unplug feature.
Fixes #1203
Signed-off-by: Tuan Hoang <tmhoang@linux.vnet.ibm.com>
> CI: allow CPU hotplug tests on s390x

- Makefile
- integration/docker/cp_test.go
- integration/docker/volume_test.go
Most of our docker tests can be executed in parallel.
Use the `ginkgo -p` option to achieve this.
The ones that cannot be run in parallel are now tagged in
the test name as [Serial Test] to run them after we run
the tests that can be run in parallel.
This should reduce at least 10 minutes of CI time.
Fixes: #1256.
> docker: Run tests in parallel

- .ci/ci_cache_image.sh
- .ci/install_kata_image.sh
Today we do not generate the rootfs in the CI
if the image is not up-to-date only the agent
is open and installed. While this gives speed
to the CI it can cause issues at release where
assets are created form scrash.
Fixes: #1213
> ci: build the complete image

- .ci/install_runtime.sh
- .ci/lib.sh
Add a test to install kata-runtime in "No GO command or GOPATH not set" mode.
Fixes: #1233
> ci: Test install kata-runtime in "No GO command or GOPATH not set" mode

- integration/docker/package_manager_test.go
The package manager tests should run serialized as they
have a timeout of 900s configured, meaning that in some
cases, they may take more than the configured timeout on
Jenkins and might lead to CI failures.
Fixes: #1268.
> tests: make package-manager tests serial

- .ci/install_bats.sh
Update bats repository.
Old bats repository is no longer active and moved to
new https://github.com/bats-core/bats-core which has an
active community.
Stability fixes and new features like running tests in parallel
have been added to bats in this new repo.
Fixes: #1276.
> tests: update bats repository

- integration/docker/run_test.go
This will check that we do not have dmesg erros while running
a container.
Fixes #1274
> test: Check dmesg errors while running a container

- .ci/static-checks.sh
Sometimes we need to include C files distributed under the GPL license, to
avoid issues with the tool that checks file headers, files with the suffix
`.gpl.c` are skipped.
fixes #1279
> ci: don't check license of C files distributed under the GPL license

- .ci/configure_tracing_for_kata.sh
- Makefile
- lib/common.bash
- tracing/tracing-test.sh
This tracing test runs as follows:
1. Enables tracing on runtime and shim components.
2. Runs a Jaeger container that will receive the trace spans.
3. A kata-container is executed.
4. Verifies that Jaeger has collected a number of spans.
5. Disables tracing.
Fixes: #1255.
> tracing: Add test to verify tracing works correctly

- metrics/network/network-metrics-nginx-ab-benchmark.sh
Ensure we specify which RUNTIME to use for the test, so we do not
just fall to using the default.
Especially relevant as we may switch the default from being Kata.
Fixes: #1287
> metrics: network: ab: specify RUNTIME for test

- .ci/setup_env_sles.sh
This will add CRI-O dependencies for SLES installation setup.
Fixes #1264
> test: Add CRI-O dependencies for SLES setup

- kata-webhook/README.md
- kata-webhook/deploy/webhook-registration.yaml.tpl
- kata-webhook/deploy/webhook.yaml
- kata-webhook/main.go
Not all information about the admission request is available in
the object. Some properties like Namespace is only available in
the request context.
Modify the webhook to allow accessing the full context. This will
allow for richer processing and policies.
This also eliminates removes the need for explict namespace filters
in the webhook configuration. This means user yaml files can now
remain unmodified.
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> kata-webhook: Support fetching request context

- .ci/run_metrics_PR_ci.sh
- cmd/checkmetrics/ci_slaves/README.md
- cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric2.toml
To allow easier management and quicker updates, make the metrics CI check the bounds against config files stored in the source tree.
> ci: metrics: pull checkmetrics configs from source tree

- .ci/resolve-kata-dependencies.sh
To aid in debugging failed CI runs, output the git log after we
have done a rebase to show what we rebased on top of.
Fixes: #1294
> ci: show merge log after rebase

- integration/docker/logs_test.go
The '-d' option could lead to a race condition.
The option sh -c 'echo hello' cause an issue on s390x.
Fixes: #1293
> docker: logs test fix

- .ci/install_kata.sh
- .ci/install_nemu.sh
- .ci/install_runtime.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
- integration/netmon/netmon_test.bats
Add script to install nemu.
Modify setup.sh to install nemu instead of
qemu when the USE_NEMU=true envar is found.
Also update runtime's configuration with correct
nemu path, machine type and firmware when running
with nemu.
Fixes #807.
> CI: Add nemu 

- integration/cri-o/crio_skip_tests.sh
Based on recent fix of the CRI-O bats 'ctr stats' from this following
PR https://github.com/kubernetes-sigs/cri-o/pull/2054, this test is
failing for Kata since Kata v1 does not support proper stats.
This is something that needs to be fixed once the CI for Kata v2 will
be in place.
For now, let's simply skip this test.
Fixes #1311
> integration: cri-o: Skip 'ctr stats'

- integration/cri-o/crio_skip_tests.sh
The name of the test is 'ctr stats output'.
Add the complete name of the test in the list instead
of only part of it.
Fixes: #1311.
> cri-o: fix name of skipped test

- Makefile
- integration/docker/docker.go
- integration/docker/main_test.go
- rand.go
SynchronizedBeforeSuite is used to synchronize parallel test.
Use SynchronizedBeforeSuite to pull all docker images before running any test.
When a test fails, the CI fails. To improve CI time and allow other jobs
run, integration and functional test should fail and stop running the tests
after a failure occurs.
To avoid generating the same container ID or name for two
different tests, the random seed should be generated when
the random string is required.
Run sequentially only the tests that match with FOCUS.
The FOCUS environment variable is used to debug and put attention on
certain tests.
fixes #1306
fixes #1304 
fixes #1302
fixes #1308
> integration/docker: fix tests

- integration/docker/cgroups_test.go
This will run a container with --cgroup-parent for a specific path
in order to verify that we are able to run the container without issues.
Fixes #1299
> test: Add test for --cgroup-parent for specific paths

- integration/docker/sysctls_test.go
This will add a docker integration test for sysctls.
Fixes #1312
> test: Add docker integration test for sysctls

- integration/docker/main_test.go
Each parallel test has its own node number, to avoid two or more test using
the same container name at the same time, parallel node should be included in
the container's name.
fixes #1304
> integration/docker: include number of parallel node in the container's name

- .ci/lib.sh
`.ci/lib.sh` was using `go env` to get GOPATH value,
but this library is also used by the `install_go.sh`
script, which shouldn't require `go` to be installed.
Fix this issue, by adding a default value to GOPATH
if no `go` command is available.
Fixes: #1324.
> ci: fix `.ci/lib.sh` to not require go installed

- integration/kubernetes/k8s-empty-dirs.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-empty-dir.yaml
- integration/kubernetes/untrusted_workloads/pod-empty-dir.yaml
This will add a K8s test to verify empty dir volumes are handled correctly.
Fixes #1310
> test: Add K8s test for empty dir

- Makefile
Ginkgo doesn't skip the tests in `SKIP` when they're run in parallel.
Fixes: #1330
> s390x: run docker test in serial

- integration/docker/commit_test.go
- integration/docker/docker.go
- integration/docker/load_test.go
Use random repositories names to avoid collisions between
parallel tests.
fixes #1332
> integration/docker: use random repo names

- integration/docker/cpu_test.go
- integration/docker/docker.go
- integration/docker/main_test.go
- integration/docker/run_test.go
Use randomDockerName to generate random names since this function
is designed to always generate unique random names.
fixes #1334
> integration/docker: Don't use RandID directly

- .ci/.golangci.yml
- .ci/static-checks.sh
- .travis.yml
- cmd/checkmetrics/main.go
- cmd/log-parser/display.go
- cmd/log-parser/main.go
- integration/docker/cgroups_test.go
- integration/docker/docker.go
- integration/docker/run_test.go
- versions.yaml
gometalinter is deprecated and will be archived April '19. The
suggestion is to switch to golangci-lint which is apparently 5x faster
than gometalinter.
Partially fixes: github.com/kata-containers/runtime#1377
> lint: Switch golang linter to golangci-lint

- lib/common.bash
Cannot pass vm_templating_test.sh if kata-runtime is not pathname
in docker config because extract_kata_env determines $rpath
cannot execute.
Convert $rpath to pathname to handle the issue.
Fixes: #1347
> lib/common: extract_kata_env: Convert $rpath to pathname

- .ci/install_kubernetes.sh
Install cni 0.6.0 to be able to install
kuberentes 1.13.
This is a workaround needed until
https://github.com/kubernetes/kubernetes/issues/75683
gets fixed.
Fixes: #1352.
> ci: k8s: install cni 0.6.0

- lib/common.bash
We are getting the runtime path (rpath) from docker info, but
it may be the case where we try to run `extract_kata_env` and
not running docker, so we shouldn't fail to get the kata
runtime path if docker service is down or not healthy.
Fixes: #1356.
> lib: extract_kata_env: don't rely on docker output

- .ci/setup.sh
This will fix that sometimes the docker installation fails in opensuse.
This restarts docker so we can retrieve properly docker information.
Fixes #1326
> ci: Fix that the docker installation sometimes fails in opensuse

- integration/docker/sysctls_test.go
This adds a docker integration sysctl test to modify the kernel subsystem.
Fixes #1337
> test: Add docker integration test for sysctl kernel

- integration/kubernetes/k8s-sysctls.bats
- integration/kubernetes/kubeadm/config.yaml
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-sysctl.yaml
- integration/kubernetes/untrusted_workloads/pod-sysctl.yaml
This sets sysctls for a kubernetes pod.
Fixes #1339
> test: Add K8s tests for sysctl

- integration/cri-o/crio_skip_tests.sh
skip two new tests that are failing with the kata CI
related: https://github.com/kubernetes-sigs/cri-o/pull/2173
Fixes: #1367.
> cri-o: skip new tests introduced in cri-o repo

- .ci/lib.sh
Go command caches build outputs under `$GOCACHE`, The default location for cache data is a subdirectory named `go-build/` in the standard user cache directory, like `$XDG_CACHE_HOME` in linux.
Since some CI, including ARM CI, is running on bare metal. We need to clean` GOCACHE` before each run.
Fixes: #1365
> gocache: clean GOCACHE on AArch64

- .ci/lib.sh
Logging into ARM CI, Found out quite a big surprise there.
```
root@testing-1:/usr/share# du -sh -- *
142G    kata-containers
```
I suppose, it won't cost them too much time to eat up my whole `/`
Directories `/usr/share/kata-containers` and `/usr/share/defaults/kata-containers` must be cleaned up before each run.
Fixes: #1373
> clean-up: clean stale kata resource on ARM CI

- integration/kubernetes/k8s-block-volume.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-block-pv.yaml
- integration/kubernetes/untrusted_workloads/pod-block-pv.yaml
- integration/kubernetes/volume/block-loop-pv.yaml
- integration/kubernetes/volume/block-loop-pvc.yaml
- integration/kubernetes/volume/local-storage.yaml
This test creates a block loop device and passes it
to a pod as a persistent volume. Then we create a
file system on the device inside the container and
write to it.
Fixes: #1358.
> k8s: add test to verify block volume support

- .ci/configure_containerd_for_kata.sh
Add containerd configuration to support kata runtimeclass.
Fixes: #1369.
> ci: containerd: add config for runtimeclass

- cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric2.toml
Based on the results of the last 24h of jenkins builds for
the tests and runtime repos:
tests: #723-731
runtime: #758-772
Set new bounds values:
what   value
boot   0.85s
ksm    55879.5m
noksm  132458m
Fixes: #1375
> metrics: ci: update slave bounds check values

- .ci/setup_env_rhel.sh
We need sudo to enable epel repository in RHEL.
Fixes #1377
> ci: Add sudo while adding the repository

- integration/kubernetes/runtimeclass_workloads/pod-block-pv.yaml
Remove untrusted annotations for pod definition
`runtimeclass_workloads/pod-block-pv.yaml`. When using containerd,
we will receive an error when we have added runtimeclass and old
untrusted annotations to the pod definition.
Fixes: #1384.
> k8s: Remove untrusted annotations when using runtimeclass

- metrics/storage/README.md
blogbench URL https://www.pureftpd.org/project/blogbench
doesn't exist anymore. Seems that our CI has been failing
when testing master branch since March 19th. Lets remove this
unexistent URL.
Fixes: #1386.
> ci: remove unexistent blogbench URL

- integration/docker/sysctls_test.go
This adds a docker integration test for sysctl for networking.
Fixes #1388
> test: Add sysctl test for networking

- integration/containerd/shimv2/shimv2-factory-tests.sh
- integration/containerd/shimv2/shimv2-tests.sh
shim2 tests are not working on SLES https://github.com/kata-containers/tests/issues/1251.
Fixes #1391
> tests: Skip shimv2 tests on SLES

- integration/popular_docker_hub_images/popular_docker_images.bats
Aerospike server needs at least 6G of memory to run.
Fixes #1394
> test: Fix aerospike test

- cmd/container-manager/manage_ctr_mgr.sh
Use runtime variable if the test run for swarm. Otherwise, set runc as
default runtime to avoid building issue.
Fixes: #1266
> docker: set default runtime

- integration/network/macvlan/macvlan_driver.bats
It is not possible to run macvlan tests on RHEL
https://github.com/kata-containers/runtime/issues/905.
Fixes #1397
> test: Skip macvlan tests for RHEL

- .ci/install_kubernetes.sh
- .ci/lib.sh
- .ci/setup.sh
- Makefile
- integration/cri-o/crio_skip_tests.sh
- integration/docker/commit_test.go
- integration/docker/cpu_test.go
- integration/docker/docker.go
- integration/docker/load_test.go
- integration/docker/main_test.go
- integration/docker/run_test.go
- integration/popular_docker_hub_images/popular_docker_images.bats
- lib/common.bash
- metrics/storage/README.md
- rand.go
56144e6 test: Fix aerospike test
4ac87b1 ci: remove unexistent blogbench URL
c49cb1a clean-up: clean stale kata resource on ARM CI
76ced81 gocache: clean GOCACHE on AArch64
beed7b4 ci: Fix that the docker installation sometimes fails in opensuse
260eae7 lib: extract_kata_env: don't rely on docker output
3f7b06e ci: k8s: install cni 0.6.0
1d80ad3 lib/common: extract_kata_env: Convert $rpath to pathname
98a0b26 integration/docker: Don't use RandID directly
a6a3e5c integration/docker: make API consistent
111ede9 integration/docker: use random repo names
edd730c s390x: run docker test in serial
6c74b58 integration/docker: include number of parallel node in the container's name
b08fa57 ci: fix `.ci/lib.sh` to not require go installed
b513620 makefile: run docker tests faster
4b69b6e makefile: …
> test: backport fixes to stable-1.6 branch

- .ci/.golangci.yml
- .ci/static-checks.sh
- .travis.yml
- cmd/checkmetrics/main.go
- cmd/log-parser/display.go
- cmd/log-parser/main.go
- integration/docker/cgroups_test.go
- integration/docker/docker.go
- integration/docker/run_test.go
- versions.yaml
gometalinter is deprecated and will be archived April '19. The
suggestion is to switch to golangci-lint which is apparently 5x faster
than gometalinter.
Fixes #1323
> backport: lint: Switch golang linter to golangci-lint

- integration/network/disable_net/net_none.bats
- integration/network/ipvlan/ipvlan_driver.bats
ipvlan tests can not be run on RHEL mainly because ipvlan needs a
kernel version greater than 4.2
Fixes #1406
> test: Skip ipvlan test for RHEL

- integration/containerd/shimv2/shimv2-factory-tests.sh
- integration/containerd/shimv2/shimv2-tests.sh
As well as SLES, openSUSE the shimv2 tests are not working on
RHEL.
Fixes #1422
> test: shimv2 test not working on RHEL

- integration/docker/volume_test.go
Don't look for qemu using `ps aux`, since `ExistDockerContainer` already
checks if kata components are still running.
fixes #1415
> integration/docker: don't look for qemu using `ps aux`

- integration/docker/cpu_test.go
Update CPU tests are not stable, mark them as 'Serial Test' to try
to mitigate this issue.
fixes #1418
> integration/docker: mark update cpu test as 'Serial Test'

- integration/netmon/netmon_test.bats
Netmon is not working properly on machine type q35
https://github.com/kata-containers/runtime/issues/1486.
Fixes #1424
> test: Skip netmon test on q35.

- versions.yaml
I would like to handle issue #1381 in 3 steps:
1 step is change golangci-lint.version to introduce v1.16.0 to introduce 8319caf63f0f5fd38b2439c7379823d656fb404e(Makefile: Add target build).
2 step is wait 1 or 2 weeks to make sure golangci-lint v1.16.0 is work OK for each project in multi-arch.
3 step add a patch to change golangci-lint build command from "make" to "make build".
> lint: set golangci-lint.version to v1.16.0

- cmd/log-parser/README.md
The URL https://www.ietf.org/rfc/rfc3339.txt does not exist and that
is making the ci at master to fail. With this we update the timestamp URL
to an existing one.
Fixes #1428
> ci: Update timestamp URL

- .ci/resolve-kata-dependencies.sh
Insted of getting the log with the subject + body of the
commit, only use the body to process the depends-on tag.
Fixes: #1436.
> depends-on: search for the tag only on the commit body

- .ci/lib.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_debian.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/setup_env_ubuntu.sh
- versions.yaml
cri-o is parallelizing its tests and needs gnu/parallel.
Fixes: #1438.
> ci: Install gnu/parallel

- integration/kubernetes/k8s-volume.bats
Instead of checking that the physical volume is available right
after the `kubectl create pv` command is run, check if it becomes
available every 2s for a maximum of 10s.
Fixes: #1440.
> k8s: volume test: wait for physical volume to be available

- .ci/setup_env_sles.sh
Yum command does not exist on SLES. This will fix the GNU
parallel installation.
Fixes #1445
> ci: Fix GNU parallel installation on SLES

- integration/vm_factory/vm_templating_test.sh
Clean the vm_template dir before test executes.
Fixes: #1363
> [stable][1.5.x] vm_factory: Add clean_vm_template in setup

- integration/docker/cgroups_test.go
Issue https://github.com/kata-containers/runtime/issues/1365 was fixed
fixes #1430
> integration/docker: enable Check cgroup paths test

- metrics/report/README.md
`grabdata.sh` takes a number of commandline arguments, that can be
very useful when you are only interested in a subset of tests and want
to save a bunch of time not running tests you are not interested in.
Add details of those to the documentation.
Fixes: #1162
> metrics: report: document grabdata commandline

- integration/kubernetes/e2e_conformance/run.sh
- integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml
There are some tests that have been faling when
running with kata, lets add a list of these tests
and skip them when running the conformance suite.
`skipped_tests_e2e.yaml` has a list of the tests that
currently fail with containerd and cri-o.
We are still investigating the root cause of the failures
on: #1396
Fixes: #1401.
> k8s: e2e: skip failing conformance tests

- integration/containerd/cri/integration-tests.sh
The default configuration file of kata snap can't be modified, since it's in
a read-only filesystem, instead the tests can modify file in
/etc/kata-containers/ hence it shouldn't be deleted.
fixes #1453
> integration/containerd: don't delete kata config in the snap CI

- cmd/container-manager/manage_ctr_mgr.sh
We have random failures while trying to remove docker packages on SLES and it
is related with the lock of the package. This will removelock and then remove
all the packages.
Fixes #1457
> ci: Remove lock before removing docker SLES

- integration/docker/cgroups_test.go
Kata prepended a kata specific string to cgroup path name
to prevend vAdvisor from picking stats data, otherwise, kubelet
will use those "zero" data to override the stats data got from cri
provider.
Fixes:#1461
Depends-on:github.com/kata-containers/runtime#1518
Signed-off-by: lifupan <lifupan@gmail.com>
> cgroup_test: prepend a kata specific string to host cgroup path

- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/setup.sh
- .ci/setup_env_rhel.sh
- .ci/teardown.sh
- cmd/container-manager/manage_ctr_mgr.sh
- integration/containerd/shimv2/shimv2-factory-tests.sh
- integration/containerd/shimv2/shimv2-tests.sh
- integration/netmon/netmon_test.bats
- integration/network/disable_net/net_none.bats
- integration/network/ipvlan/ipvlan_driver.bats
- integration/network/macvlan/macvlan_driver.bats
- integration/swarm/swarm.bats
fa27828 test: Skip netmon test on q35.
0d226d8 test: shimv2 test not working on RHEL
f0b24a6 ci: Fix RHEL script
7ab51a3 test: Fix swarm test instability on RHEL
d743a23 test: Skip ipvlan test for RHEL
937c74e test: Skip macvlan tests for RHEL
7a72480 ci: Add q35 setup
46ef346 tests: Skip shimv2 tests on SLES
3cee799 ci: Add sudo while adding the repository
56ef4e1 ci: Add installation RHEL scripts.
1d49910 ci: Remove lock before removing docker SLES
> backport tests for stable branch 1.6

- integration/vm_factory/vm_templating_test.sh
- lib/common.bash
According to the issue in
https://github.com/kata-containers/runtime/issues/1452,
There is storage related vm template leak in /var/lib/vc/sbs and
/run/vc/sbs that is fixed in
https://github.com/kata-containers/runtime/pull/1491.
Add check for this issue.
Fixes: #1426
> vm_factory: Add check for storage related vm template leak

- .ci/jenkins_job_build.sh
Unit tests on RHEL are failing https://github.com/kata-containers/runtime/issues/1517.
In order to enable a CI, we will skip them until the issue is fixed.
Fixes #1455
> tests: Skip unit tests on RHEL

- .ci/jenkins_job_build.sh
Fix the way we are skipping the unit tests on RHEL.
Fixes #1470
> tests: Fix ci for RHEL

- .ci/setup.sh
Always try to install/update the version of golang.sh we have when
running setup.sh. For Jenkins, this is done already by the jenkins
specific script, but for other CIs and for hand-running the setup
it would be nice to always try to do it before we do anything else.
Fixes: #1464
> ci: setup: always install/update golang on setup

- .ci/configure_containerd_for_kata.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/jenkins_job_build.sh
- .ci/setup.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/teardown.sh
- cmd/container-manager/manage_ctr_mgr.sh
- integration/containerd/shimv2/shimv2-factory-tests.sh
- integration/containerd/shimv2/shimv2-tests.sh
- integration/cri-o/crio_skip_tests.sh
- integration/netmon/netmon_test.bats
- integration/network/disable_net/net_none.bats
- integration/network/ipvlan/ipvlan_driver.bats
- integration/network/macvlan/macvlan_driver.bats
- integration/swarm/swarm.bats
0956d03 test: Skip netmon test on q35.
1d124d2 tests: skip netmon test when running with nemu
35ce055 test: Fix ci for RHEL
8bc1c60 tests: Skip unit tests on RHEL
18be952 test: shimv2 test not working on RHEL
0420d91 ci: Fix RHEL script
180c357 test: Fix swarm test instability on RHEL
a5b8311 test: Skip ipvlan test for RHEL
e1e6dbe test: Skip macvlan tests for RHEL
fbfc5fc ci: Add q35 setup
b87b817 tests: Skip shimv2 tests on SLES
265ef78 test: Skip shimv2 on openSUSE Leap
353d93c ci: Add sudo while adding the repository
93c7a03 ci: containerd: add config for runtimeclass
241df3f cri-o: skip new tests introduced in cri-o repo
d63b1a4 ci: Add installation RHEL scripts.
3b07c55 ci: Fix that the docker installation sometimes fails in opensuse
d587064 cri-o: fix name of skipped test
81fc47d …
> backport tests for stable 1.5

- .ci/jenkins_job_build.sh
- integration/docker/cgroups_test.go
- integration/kubernetes/k8s-volume.bats
Backport includes below changes.
https://github.com/kata-containers/tests/pull/1456
https://github.com/kata-containers/tests/pull/1462
https://github.com/kata-containers/tests/pull/1471
https://github.com/kata-containers/tests/pull/1444
> backport: 1.6.2 patches

- .ci/static-checks.sh
Fixes: #1483
Use git ls-remote instead of curl for git URL check
Signed-off-by: Xu Wang <xu@hyper.sh>
> CI: static check for openstack git URL

- integration/vm_factory/vm_templating_test.sh
According to the issue in
https://github.com/kata-containers/runtime/issues/1514,
runtime add vm template init check in
https://github.com/kata-containers/runtime/pull/1547.
Add test for this check.
Fixes: #1480
> vm_factory: Add test for vm template init check

- integration/netmon/netmon_test.bats
- integration/network/macvlan/macvlan_driver.bats
Before deleting a docker network, ensure to delete all
containers that use it.
Also enhance the teardown to return an error when the
delete command does not behave as expected as it seems that
command failures inside the teardown don't make the test to
fail.
Fixes: #1476.
> tests:network: enhance docker network deletion

- integration/docker/sysctls_test.go
This adds a docker integration test for setting namespaced kernel
parameters to turn on IP forwarding in the containers network
namespace.
Fixes #1491
> test: Add docker integration for --sysctl ip forward

- .ci/lib.sh
If the scripts failed to find go or a GOPATH they would follow a different
path and invoke `sudo -E`, but not with the PATH=$PATH argument. This
normally works on oru CIs, but on Zuul, where the old distro go version
will be in the sudo path first, it fails with a 'go too old' error.
Pass the CI env/user PATH into the `sudo` to ensure we pick up
the correct golang.
Fixes: #1479
> ci: lib.sh: set PATH for sudo even in no-go case

- integration/kubernetes/e2e_conformance/run.sh
- integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml
Use `die` to fail the e2e `run.sh` script when a `grep`
finds a failure in the e2e log.
In addition, remove dash from cri-o in skipped_tests_e2e.yaml
We use `CRI_RUNTIME` to specify which runtime interface we are
using to launch k8s and to know which tests we need to skip for e2e
testing.
Specifically for cri-o, we use `CRI_RUNTIME=crio`, so we
need to remove the dash (-) from cri-o in the skipped_tests_e2e.yaml
file, so that the tests listed there are properly skipped.
> k8s: fix e2e script and yaml file

- integration/cri-o/cri-o.sh
Do not restrict ubuntu version to run with devicemapper.
We have now moved most of our jobs to ubuntu 18.04
and we were not testing with devicemapper.
With this change, we will test cri-o with devicemapper
on all ubuntu versions.
Fixes: #1493.
> cri-o: tests: use devicemapper on all ubuntu versions

- .ci/install_runtime.sh
Add an option in the `.ci/install_runtime.sh` to enable `newstore`
experimental feature in the runtime config file when
`KATA_EXPERIMENTAL_FEATURES` is set to `true`.
Fixes: #1500.
> CI: add condition to be able to test experimental feature

- integration/docker/mem_test.go
Consume twice the memory hot added to the container to guarantee
the `out of memory` error.
fixes #1504
> integration/docker: improve memory test

- .ci/static-checks.sh
Update the `check_vendor()` function in the static check script to run our current vendoring tool (`dep`) in check mode. This will ensure our vendoring does not get silently broken [1].
Fixes #1506.
[1] - See for example https://github.com/kata-containers/runtime/pull/1442.
> CI: Add explicit static check script vendor test

- cmd/kata-manager/kata-manager.sh
The `kata-manager` script needs to download `git` repos. But if `git` isn't available, it can fall back to using `curl` or `wget`. However, if none of these tools are available, it should exit before any changes are
made to the system.
Note: The script _could_ install one of the tools of course. However, all known Linux distro "default installs" provide at least one of these tools, so this scenario should only be hit on very minimal systems. In that case, install one of the tools the error mentions and re-run `kata-manager`.
Fixes #1502.
> kata-manager: Check for dependencies earlier

- cmd/checkcommits/checkcommits.go
- cmd/checkcommits/checkcommits_test.go
Add jenkins github pull request builder env variables
to set commitID, source and dest branches.
Always check against the remote branch instead of the local copy of it.
Fixes: #1516
> Checkcommits 1.6

- cmd/checkcommits/checkcommits.go
- cmd/checkcommits/checkcommits_test.go
Add jenkins github pull request builder env variables
to set commitID, source and dest branches.
Fixes: #1516
> checkcommits: recognize jenkins CI environment

- .ci/static-checks.sh
- cmd/kata-manager/kata-manager.sh
- integration/cri-o/cri-o.sh
- integration/docker/mem_test.go
Backporting below patches for 1.6.3 release.
https://github.com/kata-containers/tests/pull/1484
https://github.com/kata-containers/tests/pull/1494
https://github.com/kata-containers/tests/pull/1503
https://github.com/kata-containers/tests/pull/1505
https://github.com/kata-containers/tests/pull/1508
> backport: 1.6.3 rel

- integration/docker/attach_test.go
Increase the `destroyTime` and run the `attach` command as soon as
possible to avoid random failures in the CI.
fixes #1511
> integration/docker: improve attach test

- .ci/install_crio.sh
Openshift v3.10 uses cri-o v1.10, which still makes reference
to the kubernetes/pause image and this image at docker.io
registry is being removed, so we need to use the pause image
from gcr.
Fixes: #1522.
> tests:openshift: use k8s.gcr.io/pause image

- .ci/static-checks.sh
- cmd/kata-manager/kata-manager.sh
- integration/cri-o/cri-o.sh
- integration/docker/mem_test.go
Changes:
2a3cbb9 (James O. D. Hunt, 4 days ago)
CI: Add explicit static check script vendor test
Update the `check_vendor()` function in the static check script to run our
current vendoring tool (`dep`) in check mode. This will ensure our 
vendoring does not get silently broken [1].
Fixes #1506.
[1] - See for example https://github.com/kata-containers/runtime/pull/1442.
(cherry picked from commit 830983f62b49703e4c052b38ab59947e98722a6f) 
23d8194 (James O. D. Hunt, 4 days ago)
CI: Refactor static check vendor test
Modify the `check_vendor()` function in the static check script. Rather 
than exiting the function as early as possible, change the logic to allow …
> release: 1.5.5 backport fixes

- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/k8s-pod-quota.bats
- integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml
- integration/kubernetes/untrusted_workloads/pod-quota-deployment.yaml
Fix pod quota test to avoid leaving pod information at /var/lib/vc/sbs (issue: https://github.com/kata-containers/runtime/issues/1611) and verify after running the tests that not pod information is left.
Fixes #1513
> test: Fix pod quota test for kubernetes

- integration/kubernetes/k8s-shared-volume.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-shared-volume.yaml
- integration/kubernetes/untrusted_workloads/pod-shared-volume.yaml
This adds a kubernetes test where we have a pod that runs
two containers with a shared volume.
Fixes #1519
> test: Add K8s test for containers with shared volume

- .ci/setup_env_ubuntu.sh
Do not add ppa:alexlarsson/flatpak repo for ppc64le
arch as it fails to add key resulting in CI failure.
Fixes: #1533
> ci: Do not add ppa:alexlarsson/flatpak repo for ppc64le

- tracing/tracing-test.sh
We use an `$attempt` variable to have a maximum
of 3 attempts to validate tracing spans, but
the variable increment was not correct, leading
to having the script getting hanged.
Fixes: #1552.
> tracing: Fix tracing test script.

- Makefile
Ginkgo doesn't skip the tests when they're run in parallel.
Fixes: #1572
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
> ppc64le: run docker test serially

- tracing/tracing-test.sh
increase the `attempt` value before running `continue` command
to prevent the script from getting hanged in a loop forever.
Fixes #1552.
> tracing: Increase `attempt` before exiting current iteration

- .ci/setup_env_rhel.sh
dnf does not exist on RHEL so the installation of libsystemd is
failing on RHEL. This needs to be replaced by yum.
Fixes #1562
> ci: Fix libsystemd installation on RHEL

- cmd/history/README.md
- cmd/history/history.sh
When comparing versions with metrics, it is very handy
to be able to see what changed between versions. Let's
add a script to help us get that data.
Fixes: #1289
> metrics: cmd: history: add a repo history script

- integration/kubernetes/k8s-footloose.bats
- integration/kubernetes/runtimeclass_workloads/footloose-configmap.yaml
- integration/kubernetes/runtimeclass_workloads/pod-footloose.yaml
This adds kata+footloose kubernetes test where
using footloose we are able to connect to pod.
Fixes #1535
> test: Add kata+footloose kubernetes test

- lib/common.bash
- tracing/tracing-test.sh
Defined `KATA_TESTS_LOGDIR` in the common bash library so that tests can write log information to a known location.
Save the trace spans logged with Jaeger to a directory below KATA_TESTS_LOGDIR` so that if the test fails, the spans can be analysed. This will allow the saved trace spans to be attached to a failing PR as artifacts. If the test passes, the cached spans are deleted.
Fixes: #1593.
> Log Jaeger traces

- Makefile
- README.md
Adding generic install- targets has the benefit of having a standardized way
of installing tools from the tests repository, hiding installation details
such as the paths to the actual install scripts.
Fixes: #1599
> make: add install- targets to run CI install scripts

- .ci/jenkins_job_build.sh
The `static-checks.sh` script should run before the
`.ci/setup.sh`, which may take a lot of time. This should
save us some CI resources if the static checks fail.
Fixes: #1598.
> ci: jenkins: run static checks script before setup.

- integration/docker/run_test.go
Now that https://github.com/kata-containers/runtime/issues/366 has
been fixed, we can enable the docker run nonexistent command test.
Fixes #1606
> test: Enable docker integration test for nonexistent command

- .ci/filter/filter_docker_test.sh
- .ci/filter/filter_test_union.sh
- .ci/install_yq.sh
- .ci/kata-arch.sh
- .ci/lib.sh
- .travis.yml
- cmd/github-labels/github-labels.sh
- lib/common.bash
Moving install_yq in a dedicated script allows other repositories to reuse it.
Also, this complements the set of scripts in .ci/ used to install software.
Fixes: #1604
> ci: move install_yq function in lib.sh a dedicate script

- .ci/static-checks.sh
- cmd/check-markdown/README.md
- cmd/check-markdown/add.go
- cmd/check-markdown/add_test.go
- cmd/check-markdown/check.go
- cmd/check-markdown/display.go
- cmd/check-markdown/display_text.go
- cmd/check-markdown/display_tsv.go
- cmd/check-markdown/doc.go
- cmd/check-markdown/extract.go
- cmd/check-markdown/heading.go
- cmd/check-markdown/link.go
- cmd/check-markdown/link_test.go
- cmd/check-markdown/main.go
- cmd/check-markdown/node.go
- cmd/check-markdown/parse.go
- cmd/check-markdown/record.go
- cmd/check-markdown/stats.go
- cmd/check-markdown/toc.go
- cmd/check-markdown/types.go
Add a new test to the CI static check script to look for markdown documents that are not referenced by any other. With a small number of exceptions, most markdown files should be linked to from other markdown documents in the same repository to allow all in-repository documentation to be discovered by link navigation.
This check necessitated updating the markdown check tool to dump all links - see the updated `README` for details.
Fixes: #1588.
> CI: Add unreferenced doc check

- .ci/go-test.sh
We were running `go test` with `-outputdir=` causing the coverage data to be written to a temporary directory, and then discarded. Remove the option to force the coverage data to be written to `coverage.txt` in the top-level repo directory.
Fixes: #1616.
> coverage: Fix unit test coverage collection

- integration/oci_calls/oci_call_test.sh
Fix the comparison that is used to know which docker
version we are using.
Fixes: #1608.
In addition, fixes issues reported by shellcheck.
>  tests: fix oci_call test for docker 18.09 or later

- integration/cri-o/crio_skip_tests.sh
Skip test as we do not have support for device cgroups.
Fixes: #1627.
> cri-o: Skip "aditional devices permissions" test

- integration/kubernetes/k8s-replication.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
This tests uses a kubernetes replicationcontroller that ensures
that a specified number of pod replicas are launched.
Fixes #1618
> tests: Add k8s test for a replicationcontroller

- cmd/container-manager/manage_ctr_mgr.sh
Fix `manage-ctr-mgr.sh` to be able to correctly parse
the full version of docker 18.09.
Fixes: #1622.
> ci: fix manage-ctr-mgr.sh to handle docker 18.09

- .ci/install_nemu.sh
- .ci/install_runtime.sh
- .ci/lib.sh
Build NEMU statically for every CI run to make sure we test a setup
similar to the one we are shipping with Kata.
Fixes: #1536
> nemu: Enable static nemu for ci

- .ci/static-checks.sh
Files passed to `comm(1)` must be sorted.
Fixes: #1614.
> CI: Sort files for comm(1)

- .ci/setup_env_centos.sh
- .ci/setup_env_debian.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/setup_env_ubuntu.sh
- integration/kubernetes/k8s-port-forward.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/redis-master-deployment.yaml
- integration/kubernetes/runtimeclass_workloads/redis-master-service.yaml
This test kubectl port-forward to connect to a Redis server
running in a Kubernetes cluster.
Fixes #1625
> tests: Add k8s test for port forwarding to access redis application

- cmd/kata-manager/kata-manager.sh
Improve kata-manager support for openSUSE, so that installation of Kata
& Docker packages can be done on different openSUSE versions.
Fixes: #1630
> kata-manager: improve openSUSE install support

- .ci/resolve-kata-dependencies.sh
Use the correct branch to search for the `depends-on` tag,
instead of using master branch always.
Fixes: #1636.
> stable-1.7: ci: depends-on: search commits using correct branch

- .ci/resolve-kata-dependencies.sh
Use the correct branch to search for the `depends-on` tag,
instead of using master branch always.
Fixes: #1636.
> ci: depends-on: search commits using correct branch

- .ci/install_qemu.sh
- .ci/lib.sh
This PR is following #1555, we hit a [issue](https://github.com/kata-containers/tests/pull/1555#issuecomment-492595005) there, git v2.7.4 is the latest on Ubuntu 16.04, and option `--shallow-submodules` was introduced in git v2.9.0, which means that for now, shallow clone will not be working well on Ubuntu 16.04.
So we need to check git version firstly before using the shallow clone.
Fixes: #1638
> git: check if git is capable of shallow cloning

- cmd/check-markdown/heading.go
- cmd/check-markdown/heading_test.go
- cmd/check-markdown/main.go
- cmd/check-markdown/node.go
- cmd/check-markdown/parse.go
Don't rely on the blackfriday package for generating heading IDs (used by the `toc` command) as although they are correct for generic markdown, they are not always correct when dealing with GFM [1].
Instead, use our own function which understands GitHub better.
Also added new tests.
[1] - https://github.github.com/gfm
Fixes: #1640.
> check-markdown: Fix heading links

- cmd/github-labels/labels.yaml.in
Added a new `needs-triage` label. The idea is that the new GitHub issue templates can all add this label when issues are created. The Triage Team will then review the new issues, add any missing labels and
*remove* the `needs-triage` label. The `needs-triage` label thus provides a simple way to identify issues
that have not been looked at yet.
Also changed the `bug` label to red.
> GitHub label changes

- .ci/static-checks.sh
Some of the temporary files are directories, so we need
to use `rm -r` to delete them.
Fixes: #1652.
> static-checks: recursively remove tmp files

- cmd/github-labels/labels.yaml.in
Add the missing labels `wip` and `do-not-merge` which got dropped from the new set of GitHub labels.
Also removed the old `from:` entries which no longer apply since we've now moved to the new set of labels.
Fixes: #1669.
> Update GitHub labels

- integration/docker/vsock_test.go
`journalctl -g` does not work properly on some linux distributions,
like ubuntu or centos.
Modify the test to search for `source=agent` using gomega matcher.
Fixes: #1671.
> tests: Modify vsock test to not use `journalctl -g`

- cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric2.toml
Once that https://github.com/kata-containers/tests/pull/1646 lands, we
need to update the current values for the memory footprint ksm to work
with QEMU 4.
Based on the results of jenkins builds for QEMU 4 the test
repo: https://github.com/kata-containers/tests/issues/1646
Set new bound values:
ksm 56088.5m
Fixes #1676
> metrics: update slave bounds check values for memory footprint ksm

- .ci/setup_env_rhel.sh
Now that is not possible to have OBS packages for RHEL https://github.com/kata-containers/packaging/pull/555,
we need to modify the script to install OBS packages for CentOS.
Fixes #1687
> ci: Modify RHEL to install OBS packages

- .ci/static-checks.sh
The static check script runs a number of checks, but some (one) are architecture-specific. Add in three new options to allow the behaviour of the script to be modified:
- `--list`: List all available check functions.
- `--no-arch`: List or run only architecture-agnostic check functions.
- `--only-arch`: List or run only architecture-specific check functions.
Note that now the script searches itself for the list of functions to run rather than hard-coding the list of functions to run. This necessitated changing the name of each check function to `static_check_*()` to ensure only functions in this file are considered.
Fixes: #1673.
> CI: Add arch options to static check script

- .ci/static-checks.sh
A default 'make' of golangci will run all its own testsuite after
it has done a build. That takes minutes, and we probably don't
need to test that the tester itself is OK. Skip the tests and
go directly to a 'build' build.
Fixes: #1683
> ci: static tests: golangci: do not run golangci self tests

- integration/docker/docker.go
- integration/docker/user_test.go
The postgres image was only used to do user/group id checks. It is a big image, and we can do the same checks using a much smaller image such as busybox.
This will reduce our download and storage time.
Drop postgres, move the user tests to busybox.
> integration/docker: drop postgres image

- cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric2.toml
We need to increase the check values for memory footprint ksm as
we have recent failures in the metrics CI. With the data
gathered at http://jenkins.katacontainers.io/job/kata-metrics-tests-ubuntu-16-04-PR/,
we can see that we need to set the bound values to:
ksm 56366.5m
Fixes #1704
> metrics: Adjust check values for memory footprint ksm

- Makefile
- integration/cri-o/cri-o.sh
do not run `cri-o` tests if `TEST_CRIO` is not true
do not run `docker` tests if `TEST_DOCKER` is not true
This behavior will only be valid when running under CI.
When running `make test` without `CI=true`, docker and
cri-o will always run.
Fixes: #1686.
> ci: do not run docker/cri-o tests if TEST_DOCKER/TEST_CRIO are not true 

- Makefile
- README.md
Add a `make help` to the tests Makefile to list all the test targets that are run by default, and thus are also available as direct test target rules.
Enhance the ginkgo SKIP/FOCUS in the Makefile a touch by adding those to the functional target rule.
Document how to use the `make help`, bats files and ginkgo skip/focus for directed test running.
> tests: Improve and document ability to filter/select tests to run

- integration/kubernetes/k8s-block-volume.bats
- integration/kubernetes/k8s-expose-ip.bats
- integration/kubernetes/runtimeclass_workloads/deployment-expose-ip.yaml
- integration/kubernetes/runtimeclass_workloads/pod-block-pv.yaml
Some of our k8s test container images were using some heavyweight items, that can be replaced by lighter ones. This saves us both time and space/cost in the CI.
- swap out debian for alpine
- swap out node-hello for hello-world
On my local tests this:
- trimmed the total image download size for the integration/k8s tests from 1.8g to 1.0g
- took the total time (including bringup and teardown lf the cluster) from 11m25s to 9m43s
> optimise k8s images

- .ci/setup_env_rhel.sh
Now that is not possible to have OBS packages for RHEL https://github.com/kata-containers/packaging/pull/555,
we need to modify the script to install OBS packages for CentOS.
Fixes #1687
> backport1.7: Modify RHEL to install OBS packages

- .ci/setup_env_rhel.sh
Now that is not possible to have OBS packages for RHEL https://github.com/kata-containers/packaging/pull/555,
we need to modify the script to install OBS packages for CentOS.
Fixes #1687
> backport1.6: Modify RHEL to install OBS packages

- integration/kubernetes/k8s-attach-handlers.bats
- integration/kubernetes/k8s-replication.bats
- integration/kubernetes/nginx.bats
- integration/kubernetes/runtimeclass_workloads/lifecycle-events.yaml
- integration/kubernetes/runtimeclass_workloads/nginx-deployment.yaml
- integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
- versions.yaml
This will update to unify all kubernetes tests to use the same nginx
image instead of different versions. This also updates to use
nginx:alpine-1.17.0 image which has a size of 23.6MB and will reduce the
current image download size.
Fixes #1693
> tests: Update nginx image for kubernetes test

- integration/containerd/shimv2/shimv2-tests.sh
Seems the shimv2 test can work well on centos recently,
so reback the shimv2 test on centos.
Fixes:#1047
Signed-off-by: lifupan <lifupan@gmail.com>
> test: reback the shimv2 test on centos

- .ci/install_runtime.sh
This will enable virtio-blk as a block storage driver in
ubuntu 18.04 with INITRD.
Fixes #1603
> ci: Use virtio-block as block storage driver

- .ci/lib.sh
- .ci/static-checks.sh
Add a timeout in the static checks script for `git ls-remote`. This hits the network and can cause a hang (and subsequent job timeout).
Fixes: #1711.
> CI: Add network timeout

- cmd/checkcommits/README.md
- cmd/checkmetrics/README.md
- cmd/kata-manager/README.md
All command names need to be in backticks.
Fixes: #1717.
> docs: Put command names in backticks

- cmd/check-markdown/main.go
Remove the original stub code and actually return the result of `handleDoc()` to unbreak the `check` command. Previously, `check` would display any error and then return successfully! However, the `list` command would (and still does) successfully detect invalid markdown.
Fixes: #1721.
> check-markdown: Fix bug that made checker impotent

- integration/kubernetes/init.sh
When setting up kubernetes on bare metal, it may occur `swap=on` error during preflight checks. 
```
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
[ERROR Swap]: running with swap on is not supported. Please disable swa                            p
[preflight] If you know what you are doing, you can make a check non-fatal with                               `--ignore-preflight-errors=...`
Failed at 54: sudo -E kubeadm init --config "${kubeadm_config_file}"
```
Since running kubernetes with `swap=on` is not supported. we need to assure swap file/partition turned off before kubeinit preflight checks.
> kubernetes: assure swap=off when running kubernetes integration tests

- .ci/jenkins_job_build.sh
```
17:41:04 .ci/jenkins_job_build.sh: line 48: /home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/tests/.ci/kata-arch.sh: No such file or directory
```
Let's install `tests/` repo brfore using script `kata-arch.sh`, which lives in `tests/` repo.
I'm confused why it only occurred in ARM CI node???? ☹
@chavafg @grahamwhaley
> arch: install tests repo brfore using script kata-arch.sh

- .ci/setup.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_debian.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/setup_env_ubuntu.sh
- .travis.yml
Refactored the setup scripts to allow them to be called from the `.travis.yml` configuration file.
Now, the main setup script detects when it is running under Travis and passes a `minimal` flag to the distro-specific setup script. The latter script will then perform the minimal setup and exit.
Also:
- Simplified the existing setup scripts a little.
- Updated the Travis distro to Xenial to install `yamllint` without having to use `pip`.
Fixes: #1724.
> Allow Travis to call CI setup

- integration/kubernetes/k8s-job.bats
Currently this test is leaving pod information https://github.com/kata-containers/tests/issues/1746.
Fixes #1745
> tests: Skip kubernetes job test

- .ci/aarch64/kubernetes/init.sh
- integration/kubernetes/init.sh
flannel pod always got OOM killed on AArch64.
flannel pod has set memory limitation:
```
containers:
- name: kube-flannel
image: quay.io/coreos/flannel:v0.10.0-arm64
command:
- /opt/bin/flanneld
args:
- --ip-masq
- --kube-subnet-mgr
resources:
requests:
cpu: "100m"
memory: "50Mi"
limits:
cpu: "100m"
memory: "50Mi"
```
oom-killer logs in dmesg:
```
kernel: [429178.253663] conmon invoked oom-killer: gfp_mask=0x6000c0(GFP_KERNEL), order=0, oom_score_adj=-999
700]  oom_kill_process+0x330/0x370
kernel: [429178.253701]  out_of_memory+0x1b4/0x510
kernel: [429178.253708]  mem_cgroup_out_of_memory+0xc4/0xe0
kernel: [429178.253736] memory: uIsage 51200kB, limit 51200kB, failcnt 100154
kernel: [429178.264979] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=crio-conmon-095c9da0df6d2e4d867f3 …
```
> k8s: use Wave Net on AArch64 instead of flannel

- lib/common.bash
When extracting the `kata env`, do not fail/abort if a runtime
cannot be found - fall through to take the defaults.
Fixes: #1751
> lib: common: do not bork if no runtime found for env

- .ci/static-checks.sh
If a URL check fails, retry 3 times (by default) in case of transitory network errors.
Fixes: #1734.
> CI: Retry URL checks

- .ci/static-checks.sh
Exclude firecracker swagger generated files from static checks.
Fixes: #1754
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> static-checks: Exclude generated files

- .ci/install_firecracker.sh
Upgrade firecracker to 0.17.0. The binary locations have changed.
Depends-on: github.com/kata-containers/runtime#1813
Fixes #1756
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> Firecracker: Upgrade firecracker to 0.17.0

- .ci/install_kubernetes.sh
- .ci/setup_env_centos.sh
- integration/kubernetes/k8s-port-forward.bats
- integration/kubernetes/run_kubernetes_tests.sh
This will install and run kubernetes tests on CentOS with machinetype q35.
Fixes #1699
> ci: Add CentOS to run kubernetes

- README.md
- Unit-Test-Advice.md
Add a new document that offers advice for writing new unit tests.
Fixes: #1758.
> docs: Add unit test advice doc

- .ci/install_crio.sh
- .ci/install_kubernetes.sh
- .ci/setup.sh
- .ci/setup_env_fedora.sh
- Makefile
- integration/kubernetes/init.sh
- integration/kubernetes/k8s-port-forward.bats
- integration/kubernetes/run_kubernetes_tests.sh
This will enable and run kubernetes on Fedora in order to increase
the number of distros where k8s tests are being run.
Fixes #1761
> ci: Add kubernetes in Fedora

- .ci/install_runtime.sh
- .ci/lib.sh
- .ci/run.sh
- config.go
- integration/docker/mem_test.go
Add configuration option to use virtio-fs.
We will currently use nemu for testing the
virtio-fs support.
Depends-on: github.com/kata-containers/runtime#1639
Fixes: #1536.
> ci: Add virtio-fs support

- .ci/setup_env_debian.sh
We can remove the addition of the librbd1 repository for Debian as
this step is not necessary.
Fixes #1740
> ci: Remove librbd1 repository on Debian

- cmd/check-spelling/data/main.txt
Add the common contraction "crypto" for cryptography to the custom dictionary.
Fixes: #1769.
> dictionary: Add "crypto"

- cmd/check-spelling/data/main.txt
Add the word "chipset" to the custom dictionary.
Fixes: #1773.
> dictionary: Add "chipset" word

- .ci/ci_cache_qemu.sh
- .ci/install_qemu.sh
- .ci/lib.sh
We now can download qemu artifacts from our jenkins
server instead of building it on every job. This speeds up
the CI and save us some resource utilization.
Fixes: #1748.
> CI: Use cached qemu if up to date

- .ci/static-checks.sh
- CI: Add shell script static analysis check
Add a basic CI shell checker test to catch basic syntax errors.
Fixes: #1787.
- Add a CI check on JSON files.
Fixes: #1788.
- Correct the handling of an incorrect CLI option in the static checks script. This is a nasty issue where the `local` keyword means that the return value of `getopt(1)` is *always* zero, even when an incorrect
option is specified.
See: https://github.com/koalaman/shellcheck/wiki/SC2155
> CI: Add shell script and JSON checks to static analysis script

- .ci/setup_env_centos.sh
- .ci/setup_env_debian.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/setup_env_ubuntu.sh
We are not longer using the installation from the OBS repository,
this will remove the unnecesary steps.
Fixes #1790
> ci: Remove installation from OBS

- .ci/static-checks.sh
Update static check script to ignore XML files when considering whether files need a license header.
Fixes: #1800.
> CI: Ignore XML (and *.yml) files in license check

- .ci/install_runtime.sh
Once kata-containers/runtime#1779 is merged, we will be able
to run CI using `acrn` hypervisor. Add support for running kata
with acrn using its dedicated configuration file.
In addition, `kata-runtime kata-check` will fail if the hypervisor
in the kata runtime config file is not found, so run kata-check 
after correct config file is in place.
> ci: fix `install_runtime.sh` and add support for using acrn config file

- .ci/run.sh
- integration/stability/soak_parallel_rm.sh
Currently we have issues while trying to run the soak test on
firecracker (see https://github.com/kata-containers/tests/pull/1803).
We need to remove it so the change https://github.com/kata-containers/runtime/pull/1649
can be merged.
Fixes #1805
> tests: Skip soak test in firecracker

- .ci/run.sh
- integration/stability/soak_parallel_rm.sh
- metrics/lib/common.bash
Instead of taking the full path name of the hypervisors, we need to change
to use only the name of the process as this will change once that we enable
jailer on firecracker.
Fixes #1804
> tests: Fix soak tests

- .ci/install_crio.sh
- versions.yaml
> ci: make crictl install faster and independent of CRI-O

- .ci/ci-fast-return.sh
- .ci/ci-fast-return.yaml
- .ci/ci-fast-return/test.yaml
- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/static-checks.sh
If a PR has only modified docs et. al., and no code files, then do not run the full test suite.
Do still run the static checks if required.
> ci: enable fastpath CI skip/return for non-code-ish PRs

- .ci/aarch64/kubernetes/init.sh
- integration/kubernetes/init.sh
Sorry for the trouble, I have decided to switch back to use flannel. It is small work load. And It is easy to be cleaned up on bare-metal. ;)
I know, A few days ago, I just replaced it with `weave`. But in recent days, I found that it costs too much work to clean up on bare-metal, and it requires more useless extra work load than flannel,
e.g.
```
root@entos-thunderx2-desktop:~/go/src/github.com/kata-containers/tests/integration/kubernetes# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp9s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
link/ether 68:05:ca:83:6f:34 brd ff:ff:ff:ff:ff:ff
3: docker0: …
```
> network_plugin: delete memory limitation of flannel on AArch64

- .ci/install_crio.sh
The latest merge of the cri tools PR seems to beak upstream tests with the error:
```
.ci/install_crio.sh: line 65: crictl_version: unbound variable
```
I'm unsure why we did not cover this failure on the CI, but that the variable is unbound would mean that this statement is false, right:
```
if [ "$ghprbGhRepository" != "${crio_repo/github.com\/}" ]
```
Reference: http://jenkins.katacontainers.io/job/kata-containers-crio-PR/3883/console
Closes #1815
> ci: fix possible unbound variable in install_crio.sh

- .ci/static-checks.sh
`check_commits` was renamed to `static_check_commits`.
Fixes #1820.
> ci: static-checks: fix check_commits comparison

- .ci/jenkins_job_build.sh
Currently we call the jenkins script to set up the system, and then call
the run_metrics_PR_ci.sh script from the metrics jenkins job files to
run the actul metrics.
This flow does not 'understand' the new ci fast path, and then fails.
The best fix is to move the call to the metrics script into the main
jenkins file, and remove it from the jenkins job files.
Fixes: #1835
> ci: jenkins: metrics: add metrics call direct to jenkins script

- .ci/ci-fast-return.sh
We need `yq` installed to parse our yaml config file. Use our
`install_yq` script to ensure it is present or installed.
Fixes: #1833
> ci: fast-path: install yq before use

- cmd/check-spelling/data/distros.txt
We refer to macOS in some docs - either that things are or are not
supported on that platform for instance.
`macOS` is not in the standard base hunspell dict, so add it to our
local distro dict.
Fixes: #1825
> spellcheck: add macOS

- cmd/check-spelling/data/distros.txt
Add minikube to dictionary.
Fixes: #1842
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
> spellcheck: add minikube

- .ci/jenkins_job_build.sh
As we `pushd` into the kata repositories paths (other than
tests) we need to specify the `tests_repo_dir` to call
the metrics script
Fixes: #1840.
> ci: metrics: run metrics script using full tests repo path

- .ci/jenkins_job_build.sh
It seems that we need to add the complete path in order that the jenkins_job
finds the script to perform the ci-fast-return.sh
Fixes #1829
> ci: Set the complete path for the ci-fast-return.sh

- Makefile
- integration/stability/hypervisor_stability_kill_test.sh
Kill hypervisor and then force remove the container.
We should be able to handle the exceptional case properly.
Fixes: #1838
Depends-on: github.com/kata-containers/runtime#1897
> integration: add hypervisor kill test

- .ci/ci-fast-return.sh
- .ci/install_go.sh
- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .travis.yml
- cmd/check-spelling/data/distros.txt
efe44db spellcheck: add minikube
a38e336 ci: metrics: run metrics script using full tests repo path
ccef774 ci: jenkins: metrics: add metrics call direct to jenkins script
ef5b03b ci: Allow travis to use go install script
87caf2a ci: fast-path: install yq before use
f9ca367 ci: Set the complete path for the ci-fast-return.sh
7c39ca0 spellcheck: add macOS
c6a4c1b ci: move pr file list funcs out to library file
> backport 1.8 tests improvements

- integration/stability/hypervisor_stability_kill_test.sh
We need to disable this test on FC as it is failing
(see https://github.com/kata-containers/tests/issues/1848) in order
to not affect the firecracker CI.
Fixes #1849
> test: Skip hypervisor stability test on FC

- Unit-Test-Advice.md
The expectError should be replace by d.expectError at the Unit Test
Advice document.
Fixes #1837
> docs: Fix Unit Test Advice document
