.ci/install_firecracker.sh

While running multiple times the fc installation script fails to
detect the variables of driver and path at the configuration file. This
ensures that we can detect those variables.
Fixes #1854

ci: Fix FC installation script

---

integration/containerd/cri/integration-tests.sh

Fix continerd to containerd
Fixes: #1857
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

cri-containerd: Fix spelling mistake in function name

---

.ci/static-checks.sh

go.mod and go.sum are generated by go modules tooling.
Ignore license checks for these files.
Fixes #1859

static-checks: Ignore go modules metadata files.

---

.ci/lib.sh
integration/kubernetes/cleanup_bare_metal_env.sh
integration/kubernetes/cleanup_env.sh
integration/kubernetes/init.sh
lib/common.bash

When running `kubeadm reset` to delete stale resource derived from k8s integration tests, we often get following suggestion:
```
The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually.
For example:
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.
The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
```
Especially for cleaning up iptables, if you don't clean it up, it may lead to `cni0` interface not being set up in master node next time.
They all exist in bare-metal environment. ;)

clean-up: do extra clean up for k8s integration on bare-metal CI

---

cmd/check-spelling/data/distros.txt
cmd/check-spelling/kata-spell-check.sh

Add "MacOS" and "OpenSUSE" to the distros fragment for the custom dictionary.
Both these terms already existed in distros fragments file, but with different capitalisation, correct for each term.
Although `hunspell(1)` will automatically accept the capitalised versions of custom words specified in the dictionary in all lower-case, it will *not* accept capitalised custom words starting with a lower-case letter but containing an upper-case one, like both of the previously specified terms.
Also fix an unbound variable error if no spell checker CLI command is specified and improve the error message in that scenario.
Fixes: #1866.

Add distro words and minor spell checker fixes

---

.ci/static-checks.sh

Only run static checks on the files in the Git index, to avoid any side
effects of checks failing because of untracked files, such as build
artifacts.
Fixes: #1867

static-checks: only check files in Git index

---

integration/kubernetes/runtimeclass_workloads/pod-http-liveness.yaml
integration/kubernetes/runtimeclass_workloads/pod-tcp-liveness.yaml

original image `liveness` and `goproxy:0.1` have all been discarded by kubernetes community. And they are also single-arch images only for amd64.
kubernetes community has centralized quite a few images into the unified `agnhost`, including `liveness`, detailed info seen here [kubernetes/kubernetes#78389](https://github.com/kubernetes/kubernetes/pull/78389).
The `agnhost` binary has several sub-commands which are can be used to test different Kubernetes features. And `agnhost` image is multi-arch image for several platforms, including amd64, arm64, ppc64le, etc.
```
$ docker manifest inspect gcr.io/kubernetes-e2e-test-images/agnhost:2.2
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": …
```

liveness: replace test image liveness and goproxy with unified agnhost

---

integration/cri-o/cri-o.sh

cri-o implemented parallel tests for 1.15, but this doesn't
work when running the tests with `devicemapper` driver as
each thread will launch different cri-o processes in parallel
and will try to use the same block device.
For this case use `JOBS=1` to run the tests sequentially.

cri-o: Run tests sequentially when using devicemapper

---

cmd/kata-manager/kata-manager.sh

Fail in case that OBS packages are not found for a specific VERSION ID
while executing the installation guide from the documentation.
Fixes #1691

ci: Fail if OBS packages are not found on kata manager

---

cmd/kata-manager/kata-manager.sh

This reverts commit 2aa6cf2401ea0505aebbf395bcfade0d0edeaad3.
Undo change that breaks OBS installs; the check introduced by [1] always fails since the release number is not encoded in the installation document - it's defined as a variable.
[1] - https://github.com/kata-containers/tests/pull/1875
Fixes: #1881.

revert: "ci: Fail if OBS packages are not found on kata manager"

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric2.toml

Our metrics shifted (in the good direction), probably due to
changes in the kernel configs and qemu updates.
Reset the values to a new baseline. Data gathered using
the new metrics history script. Base ouput data was:
allvalues are [0.8041 0.8085000000000001 0.7976500000000002 0.82155 0.7955 0.80935 0.8016500000000001 0.8127000000000001 ]
boot-times: mean .80, 95% mean .76, 105% mean .84
min 0.7955 (99.00% of mean), max 0.82155 (102.00% of mean)
allvalues are [122674.13 122790.79 123279.39 123288.42 123087.39 122773.55 121926.11 123410.47 ]
memory-footprint: mean 122903.78, 95% mean 116758.59, 105% mean 129048.96
min 121926.11 (99.00% of mean), max 123410.47 (100.00% of mean)
allvalues are [49832.46 49696.02 49865.95 49930 49941.06 49783.15 49618.4 49900.52 ]
memory-footprint-ksm: mean …

metrics: update baseline to account for recent changes

---

Makefile
integration/ksm/ksm_test.sh
metrics/lib/common.bash

This will run two containers and will wait to the KSM to settle down
and then it will check that the merged pages count is increasing.
Fixes #1827

test: Add KSM test

---

.ci/static-checks.sh

We recently switched from using `find(1)` to `git-ls-files(1)` to determine which files run static checks for [1]. Unfortunately, the formats of these commands are slightly different so update the code to ignore vendor files as previously, vendor files were being checked.
[1] - https://github.com/kata-containers/tests/pull/1868
Fixes: #1892.

CI: Ignore vendor files harder

---

integration/kubernetes/k8s-expose-ip.bats
integration/kubernetes/runtimeclass_workloads/deployment-expose-ip.yaml

The `agnhost` image was created by k8s for testing purposes. one benefit is to be able to aggregate, like 10 images worth of functionality into 1 image.
Sub-command netexec is to start a HTTP server on given TCP / UDP ports with a few endpoints.
The `/echo` endpoint returns the given msg, e.g./echo?msg=echoed_msg. Therefore, we could use above functionality to achieve what hello-app is intended for.
Detailed info about `agnhost` image is [here](https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost).
Otherwise, hello-app is also single-arch image only for amd64, while agnhost is multi-arch image for multiple archs, including x86_64, arm64, s390x, etc.

expose-ip: replace hello-app with agnostic image agnhost:2.2

---

integration/popular_docker_hub_images/popular_docker_images.bats

The opensuse docker hub image has been deprecated, so we are replacing
it to use opensuse/leap.
Fixes #1895

tests: Update opensuse popular images test

---

cmd/README.md
cmd/checkmetrics/history/README.md
cmd/checkmetrics/history/history.sh

Add a tool that gathers recent metrics build results from
the Jenkins server fragments directly, and performs some
statistics on them.
This is very useful when trying to re-set the baseline
data for the metrics CI system.
Fixes: #1878

checkmetrics: add a tool to gather recent metrics history

---

.ci/aarch64/configuration_aarch64.yaml
.ci/filter/filter_k8s_test.sh
integration/kubernetes/run_kubernetes_tests.sh

Hi guys.
Recent days, I have been focusing on including k8s integration tests on ARM CI.
The last majority work may be building up k8s filter frame, just like what I did for docker integration tests.
Since for now, a few advanced feature hasn't been fully supported on aarch64, like cpu hotplug, we need to skip a few k8s intergration tests involving these features.

filter: build filter frame for k8s intergration tests on aarch64

---

integration/popular_docker_hub_images/popular_docker_images.bats

The -t option for the timeout has been deprecated, this will fix to run the
vault image for the docker popular image test.
Fixes #1898

test: Update vault test

---

integration/kubernetes/k8s-replication.bats

It seems that there is an issue while running the replication test
https://github.com/kata-containers/runtime/issues/1931 so we need to
skip the test.
Fixes #1900

test: Skip k8s replication test

---

integration/kubernetes/cleanup_bare_metal_env.sh

This is one bug report for my one previous PR #1812.
I have tried to clean up stale files under `/var/lib/cni/networks/*` and `/opt/cni/bin/*`, which need `sudo` rights to do cleaning up.
Actually, original plan didn't really fulfill the task, and all stale file still remained left. But since we add `-f` flag, error has been hidden away. when we turn off this flag, it will output:
`rm: cannot remove '/opt/cni/bin/*': No such file or directory`
All is due to that in original plan, `sudo rm -rf /opt/cni/bin/*`, `sudo` right is granted to `rm` command, not the shell `cleanup_bare_metal_env.sh`. 
So when the shell do wildcard expansion with `/opt/cni/bin/*`, it does not have permission to expand. 
Nevertheless, to get around this, we need a shell with `sudo` rights executing `rm`.

clean_baremetal: granting a shell `sudo` rights, not `rm`

---

integration/popular_docker_hub_images/popular_docker_images.bats

Currently, the zookeeper docker integration test is failing this will
fix the issue.
Fixes #1905

test: Fix zookeeper docker integration test

---

.ci/static-checks.sh

While we move to go modules, perform the dep check for repos
that still use dep.
Run `go mod verify` instead for go modules.
Note, this just verifies the integrity of modules in the local
cache. We would have instead wanted to verify the vendored code
here, but that is still not supported.
https://github.com/golang/go/issues/27348
Fixes #1879

modules: Verification for go modules

---

integration/popular_docker_hub_images/popular_docker_images.bats

Today the image of ubuntu-upstart has been deprecated at docker hub so
it is not possible to retrieve the image. This removes the test.
Fixes #1910

test: Remove ubuntu-upstart docker integration test

---

integration/containerd/cri/integration-tests.sh

Remove the artifacts leftover from installation from source before
execution.
This ensures that make test-integration builds the CI-Version
of cri-containerd.
Fixes: #1851
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

cri-containerd: Remove wrong artifacts before test-integration

---

.ci/ci_cache_components.sh

The help function does not exists, this will modify it to use the
usage function as well we modify the opts for the menu.
Fixes #1917

ci: Fix ci_cache script

---

.ci/install_nemu.sh

While trying to build nemu, we need to pass the arch as a parameter to
execute the packaging script. See
https://github.com/kata-containers/packaging/blob/master/static-build/nemu/build-static-nemu.sh#L18
Depends-on: github.com/kata-containers/packaging#672
Fixes #1915

ci: Fix nemu installation

---

.ci/install_cri_containerd.sh

To acquire version of `cri_containerd`, you only need the file `vendor.conf` under `containerd/containerd` repo. 
You don't need to download the whole repo, that's time-consuming.

cri-containerd: acquire cri_containerd version in faster way

---

integration/kubernetes/cleanup_bare_metal_env.sh
integration/kubernetes/cleanup_env.sh
integration/kubernetes/run_kubernetes_tests.sh

there are several scenarios where `cleanup_env.sh` wouldn't be invoked or be interrupted in the middle.
a) for now, `cleanup_env.sh` is only invoked on successful completion of the script.
Hence, we use `trap` to ensure the cleanup happens on any exit.
b) Sometimes, we failed on `kubeadm init`. on such point, the cluster network may not be initialized, which means no `cni0` interface, regardless of `flannel` interface. Hence, cleanup will exit in the middle.
```
Cannot find device "cni0"
```
So adding `|| true` ensures that the resulting compound command
always exits with status zero.
c) When `runc list` returned no stale container resource like the following:
```
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```
the compound `&&` command would exit with `1`, leading …

cleanup_k8s: ensure execution of cleanup no matter what

---

.ci/lib.sh

Hi guys
@grahamwhaley has commented in my another PR about cleaning up the cri-o install at the end of or before each PR.
So I read through the log generated during one cri-o installation, in order to catch up all ephemeral files for later clean-up.
cri-o related binary:
```
install  -D -m 755 bin/crio /usr/local/bin/crio
install  -D -m 755 bin/conmon /usr/local/libexec/crio/conmon
install  -D -m 755 bin/pause /usr/local/libexec/crio/pause
```
cri-o related config:
```
install  -D -m 644 crio.conf /etc/crio/crio.conf
install  -D -m 644 crio-umount.conf /usr/local/share/oci-umount/oci-umount.d/crio-umount.conf
install  -D -m 644 crictl.yaml /etc
```
cri-o systemd service file:
```
/etc/systemd/system/crio.service
```

crio: delete stale cri-o related resource

---

.ci/install_nemu.sh
.ci/install_qemu.sh

This will fix the install prebuilt nemu and qemu and avoid the
source installation of these kata components.
Fixes #1923

ci: Fix install prebuilt nemu and qemu

---

.ci/install_agent.sh
.ci/install_kata.sh
.ci/install_proxy.sh
.ci/install_runtime.sh
.ci/install_shim.sh
.ci/lib.sh

Some new features maybe not supported in some hosts
with old kernel, so let older version of kata installed
easier by adding a version argument.
fixed: #1908
@jodh-intel  @grahamwhaley  @Pennyzct

tests: install kata with specific version

---

integration/popular_docker_hub_images/popular_docker_images.bats

This adds the gradle and nextcloud docker hub images tests to the
popular docker images.
Fixes #1921

tests: Add gradle and nextcloud tests

---

integration/kubernetes/e2e_conformance/run.sh

instead of specifying the location where we think the
`e2e.log` file is, use `find` to search for it under
`plugins/e2e` directory.
In addition, remove `SONOBUOY_KATA_YAML` variable 
which is no longer used in the script.

k8s: e2e: fix how we get e2e log location

---

cmd/check-spelling/data/acronyms.txt

Add the "IoT" (Internet of Things) acronym to the spell checker dictionary.
Fixes: #1932.

spelling: Add IoT to spell check dictionary

---

.ci/install_runtime.sh

This will disable virtio-blk as a block storage driver in
ubuntu 18.04 with INITRD on ppc64le.
Fixes: #1930
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

ci: Don't use virtio-block as block storage driver for ppc64le

---

.ci/install_firecracker.sh
.ci/static-checks.sh
Unit-Test-Advice.md
cmd/check-spelling/kata-spell-check.sh
integration/containerd/cri/integration-tests.sh

b5aa2bb check-spelling: Fix unbound variable
d2a7537 cri-containerd: Fix spelling mistake in function name
023697e ci: Fix FC installation script
19f37ac CI: Fix getopt return check in static check script
da14284 docs: Fix Unit Test Advice document

backport fixes to stable-1.8

---

integration/kubernetes/init.sh
lib/common.bash

`cniVersion` is needed inside the flannel config file. If it
is not provided, cni has issues releasing ip adresses after
pods are deleted.
Fixes: #1936.
In addition:
- add `RUNTIME` and `RUNTIME_PATH` default values 
to the kubernetes `init.sh` script.
- use sudo for docker calls as some environments may not be 
able to call docker without using sudo.

k8s: Add cniVersion to flannel config file

---

integration/kubernetes/cleanup_bare_metal_env.sh

Everytime, when creating a new container, a veth pair including one `eth0` in container namespace, and one `vethXXX` in pod namespace has been created.
Then, the `vethXXX` has been plugged into the bridge `cni0` for intra-node communication.
In cleaning process, we only deleted `cni0` interface for now. 
See one quick kubernetes integration tests on AArch64.
**Before, we have only five interfaces:**
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp9s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
link/ether 68:05:ca:83:6f:34 brd ff:ff:ff:ff:ff:ff
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 …
```

bare-metal: delete stale veth interfaces on bare-metal machine

---

integration/popular_docker_hub_images/popular_docker_images.bats

This adds the eclipse-mosquitto and amazonlinux docker hub images to the most
popular docker hub images testing. This is part of the effort to increase the
number of images that we are testing.
Fixes #1944

tests: Add eclipse-mosquitto and amazonlinux images

---

cmd/check-spelling/data/main.txt
cmd/check-spelling/data/projects.txt

Allow the word "Podman" to be accepted by the spell checker.
Also, allow the word "uncomment" to be specified in the plural, past tense or present continuous tense.
Fixes: #1948.

Spell checker update dictionary

---

integration/popular_docker_hub_images/popular_docker_images.bats

This adds groovy and matomo images to the popular docker hub test
images.
Fixes #1946

tests: Add groovy and matomo images

---

.ci/setup_env_sles.sh

Currently the CI fails to retry the moreutils repository and the main reason
is that this repository does not longer exists for SLES 12 SP4 so we need to
retry the repository for SLES 12 SP3.
Fixes #1929

ci: Fix moreutils repository for SLES

---

cmd/container-manager/manage_ctr_mgr.sh

Currently Fedora 30 does not support docker-ce 18.06 so we need to modify
the cmd/manage_ctr_mgr.sh to support this docker version.
Fixes #1951

ci: Add support for docker 18.06 to fedora 30

---

.ci/install_firecracker.sh
integration/stability/hypervisor_stability_kill_test.sh

Don't use --features flags since vsocks support is enabled by default
Update firecracker and jailer path
Depends-on: github.com/kata-containers/runtime#2050
fixes #1959

ci: fix firecracker 0.18 installation

---

.ci/setup_env_sles.sh

This adds the repository to retry these packages for SLES 12 SP4.
Fixes #1957

ci: Add repo for pandoc and hunspell packages

---

.ci/setup_env_sles.sh

In order to retry packages of myspell we need to add the leap oss repository
for SLES 12 SP4.
Fixes #1969

ci: Add leap oss repository for SLES 12 SP4

---

.ci/jenkins_job_build.sh
.ci/lib.sh
.ci/rollback_enable_sandbox_cgroup_only.sh
.ci/run.sh
.ci/toggle_sandbox_cgroup_only.sh
integration/docker/cgroups_test.go
integration/kubernetes/init.sh

- Add scripts to enable it if needed.
- Add script to rolback config to enable it.
- Check in docker test if option is enabled to not check cgroups in the
host.
Depends-on: github.com/kata-containers/runtime#1880
Fixes: #1810
Signed-off-by: Jose Carlos Venegas Munoz <jcvenega@jcvenega-nuc.zpn.intel.com>

test: Make aware test pod cgroup option.

---

.ci/install_kata_kernel.sh

- ci: fix `get_current_kernel_version` for experimental kernel.
echo the value of `kernel_version` on `get_current_kernel_version`
function.
- ci: use experimental_latest_build_url to verify the checksum.
Instead of using the `latest_build_url` for experimental kernel,
use the correct url which is `experimental_latest_build_url`.
This will verify the integrity of the kernel with the correct
checksum.
Fixes: #1977.

ci: fix retrieval of cached experimental kernel 

---

.ci/install_kata_kernel.sh

This will rename the kernel experimental with the appropiate sufix
`virtiofs.container`
Fixes #1979

ci: Fix kernel symlink for experimental kernel

---

integration/docker/docker_arch_base.go
integration/docker/docker_arm64.go
integration/docker/docker_ppc64le.go

Lately, ARM CI and Power are all failing in trying to pull docker centos image.
See issue here: [kata-containers/ci#222](https://github.com/kata-containers/ci/issues/222).
That's because that the latest `centos:latest` is updated to `centos:8`, but it has only one entry for `amd64`.
```
$ export DOCKER_CLI_EXPERIMENTAL=enabled
$ docker manifest inspect centos:latest
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 529,
"digest": "sha256:6ab380c5a5acf71c1b6660d645d2cd79cc8ce91b38e0352cbf9561e050427baf",
"platform": {
"architecture": "amd64",
"os": "linux"
}
}
]
}
```
I have already informed the upstream about this missing issue, and will keep track of …

centos: fix the missing entry in centos:latest on non-amd64 platform

---

.ci/resolve-kata-dependencies.sh

osbuilder and packaging are branched now.
Fixes: #1990

ci: Use stable branch for packaging and osbuilder

---

.ci/setup_env_sles.sh

Missing arch on sles setup while trying to retry a repository.
Fixes #1992

ci: Missing arch on sles setup

---

.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/install_nemu.sh
.ci/install_qemu.sh
.ci/install_qemu_experimental.sh
.ci/lib.sh

- fix the URL to get cached version of experimental qemu.
- remove unused code.
- use `ln -sf` to remove previous versions of qemu binaries
- print versions of current and cached qemu
- use variables for jenkins URL and artifacts paths.

ci: Fixes for `.ci/install_qemu_experimental.sh`

---

.ci/install_rust.sh
.ci/kata-arch.sh
.ci/setup_env_ubuntu.sh
.ci/static-checks.sh

This patch adds preliminary support to rust agent.
Fixes: #1965

Add rust support to CI

---

integration/kubernetes/e2e_conformance/run.sh
versions.yaml

instead of running `go get`, we need to download the
sonobuoy binary from the release assets.
Add a sonoboy entry in our local versions.yaml file to use
version 0.16.1 which is the latest currently.
Fixes: #2000.

e2e: fix sonobuoy retrieval

---

integration/kubernetes/init.sh

While running manually the ./init.sh, this gets stuck while doing
the systemctl status ${crio_service} and this avoids to run the script
completely. This PR fixes that option.
Fixes #2004

tests: Fix checking status for crio service

---

.ci/static-checks.sh

Fix the regex handling to really exclude vendored files when performing static analysis checks.
Fixes: #2017.

CI: Really ignore vendored files in static checks

---

.ci/aarch64/configuration_aarch64.yaml
.ci/ppc64le/configuration_ppc64le.yaml
integration/docker/package_manager_test.go

dnf and yum update tests are failing when running with
virtiofs. More info can be found on #2008.
While this is being fixed, lets skip it to have a green CI.
In addition, unskip the yum test running with 9p, which was
not working in the past but now behaves correctly.
Fixes: #2013.
Fixes: #1270.

virtiofs: Skip package manager test for dnf and yum

---

tracing/tracing-test.sh

While running the tracing test locally and on the tracing directory, it fails
to locate the configure_tracing_for_kata.sh. This improves and fixes that issue
so no matter if you are running it using the Makefile or on the tracing directory
that will not fail.
Fixes #2025

test: Fix script location for the tracing test

---

.ci/s390x/configuration_s390x.yaml

The cri-containerd testsuite keeps failing for s390x. Disable it to have a
working CI for s390x.
Fixes: #2021
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

s390x: Disable cri-containerd testsuite

---

integration/kubernetes/init.sh
versions.yaml

Update flannel version used in our K8s tests.
This version (commit) contains a fix that adds
the cniVersion to the kube-flannel.yml which is
needed by cri-o.
Fixes: #1938.

ci: Update flannel version

---

cmd/check-spelling/data/main.txt

Add udev related words to the spell checking dictionary.
Fixes: #2036.

dictionary: Add udev + uevent

---

.ci/teardown.sh

collect containerd logs in the `teardown.sh` script.
Fixes: #2034.

ci: Collect containerd logs

---

.ci/static-checks.sh

`xurls` search rather aggressively for URLs. Stop it from failing due to false positives by excluding code blocks before passing the remainder of the doc to `xurls`.
Fixes: #2040.

CI: Stop xurls checking code blocks

---

integration/containerd/cri/integration-tests.sh

Since the containerd cri testing cases would setup it's own containerd
daemon, which would conflict with the systemd containerd service, thus
it's better to stop it before running cri testcases.
Fixes: #2042
Signed-off-by: lifupan <lifupan@gmail.com>

cri: disable containerd service

---

integration/popular_docker_hub_images/popular_docker_images.bats

There is an extra character in the popular docker hub images test, this
will remove it.
Fixes #2046

test: Remove extra character in popular test

---

.ci/teardown.sh

Tracing is not running in all the jenkins jobs which generates that
the tracing.log is not being generated. This will avoid the issue of
failing while trying to cp this log.
Fixes #2048

ci: Do not fail the teardown script if traces log is not found

---

.ci/teardown.sh

Split the tracing log and read it only when the file exists as some
jenkins jobs do not run tracing.
Fixes #2052

ci: Split and read tracing log when exists

---

.ci/install_runtime.sh
.ci/run.sh
integration/cri-o/crio_skip_tests.sh

kata + crio + firecracker are more stable. Run cri-o tests in firecracker CI
fixes #2060

integration/cri-o: run cri-o tests in firecracker CI

---

.ci/configure_crio_for_kata.sh
.ci/install_crio.sh
integration/cri-o/cri-o.sh
versions.yaml

cri-o config file changed a little bit in v1.16.0, so we need
to adjust our configuration script to work with this new version.
Fixes: #2056.

ci: fix `configure_crio_for_kata.sh` script for cri-o 1.16

---

.ci/configure_cni.sh
.ci/configure_containerd_for_kata.sh
.ci/install_cni_plugins.sh
integration/containerd/cri/integration-tests.sh

The cni config used for tests from the cri repo has ipv6 routes.
Skip this and use a cni config used for crio as well.
Depends-on: github.com/kata-containers/runtime#2100
Fixes #2002

containerd: Skip using the config provided by cri

---

integration/containerd/shimv2/shimv2-tests.sh

CNI binaries should have already been installed by the setup.sh script.
So just check here if the "bridge" cni plugin that we use in the CI
already exists. If so just configure cni. Only install if this binary
does not exist.
Fixes #2067

ci: Do not install CNI binaries a second time in the CI.

---

integration/kubernetes/k8s-hugepages.bats
integration/kubernetes/run_kubernetes_tests.sh

This adds a kubernetes test by enabling hugepages and sandbox_cgroups
at the configuration.toml
Fixes #2064

k8s: Add hugepages test

---

kata-webhook/deploy/webhook.yaml

`extensions/v1beta1` is deprecated on k8s 1.16. The recommendation
is to migrate to use the `apps/v1` API.
See:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Fixes: #2073.

k8s: kata-webhook: use apps/v1 API for Deployment

---

lib/common.bash

This adds qemu-virtiofs-system to common so we can extract the
path.
Fixes #2066

ci: Add qemu-virtiofs to common

---

.ci/install_qemu_experimental.sh

This will avoid that the cache experimental qemu jenkins job failed because
the kata-qemu-static.tar.gz is not being found.
Fixes #2075

ci: Fix cache experimental qemu jenkins job

---

.ci/static-checks.sh

This will enable to install yamllint in different linux distributions in
order to run static-checks.
Fixes #1659

static-checks: Install yamllint as a pre-requisite

---

.ci/install_firecracker.sh

when testing changes on firecracker repo, we don't want to
install the version of firecracker that we have in versions.yaml.
So skip the installation as it is already done in the Jenkins
job.
Fixes: #2082.

ci: skip Firecracker install when testing changes on fc repo

---

integration/kubernetes/k8s-number-cpus.bats
integration/kubernetes/run_kubernetes_tests.sh
integration/kubernetes/runtimeclass_workloads/pod-number-cpu.yaml

This will check the number of cpus, this is related to issue
https://github.com/kata-containers/runtime/issues/2186. This
verifies that we have the correct number of cpus after ending a
container.
Fixes #2080

test: Add k8s test to check number of cpus

---

integration/docker/run_test.go

This will test the kata-runtime list functionality by first running a
container and then running the kata-runtime list command in order to
verify that we get the container information.
Fixes #1507

tests: Check kata-runtime list functionality

---

integration/docker/run_test.go

kata-runtime list needs sudo to run correctly, this will fix the issue, this will ensure that only sudo can run kata-runtime list.
Fixes #2088

test: Check sudo before running kata-runtime list

---

metrics/network/network-metrics-iperf3.sh

there must be sure about the existence of iperf3 command before
do the server check.
if iperf3 not present in host, test_cmd will fail without warning.
Fixes: #2091
@amshinde  @jcvenegas

tests: check iperf3 before do check iperf3 server.

---

metrics/network/network-metrics-iperf3.sh

Currently, count value in network-metrics-iperf3.sh freezed as
count value is assigned its original value round after round.
remove the "count=" to let it go.
Fixes: #2090
@jodh-intel @grahamwhaley

tests: let iperf server check work by let counter go

---

integration/kubernetes/init.sh

File crio.sock is not a regular file, we should use `-e` to check
its existence. not `-f`.
Fixes: #2094

k8s: use `-e` to check the existence of crio.sock

---

.ci/static-checks.sh

The previous check was causing the function to return false
even though yamllint is installed successfully.
Fixes #2098

static-check: Fix bug in yamllint installation check

---

integration/docker/mem_test.go

This enables the docker memory integration tests for virtiofs as
this issue https://github.com/kata-containers/runtime/issues/1745 is
closed.
Fixes #2104

test: Enable docker memory tests for virtiofs

---

integration/stability/soak_parallel_rm.sh

The issue of have hanging processes on debian while we run the soak
test is not being seen at debian 10. This PR enables the test.
Fixes #2106

test: Enable soak test on Debian 10

---

.ci/install_qemu_experimental.sh

Now the tarball provides a different name
On untar be more verbose to see what got installed

ci: fix install qemu-virtiofs

---

integration/stability/soak_parallel_rm.sh
lib/common.bash

Fixes #2112
Checking "/run/vc" can also get active pods so we don't have to use
"/var/lib/vc", also I'm working on removing "/var/lib/vc" dir from
persistent data, we should remove "/var/lib/vc" from tests repo first.
Signed-off-by: Wei Zhang <weizhang555.zw@gmail.com>

tests: replace "/var/lib/vc" with "/run/vc"

---

.ci/ci_cache_components.sh

The tarball name for qemu experimental has been changed, this PR updates the
tarball name to kata-static-qemu-virtiofsd.tar.gz.
Fixes #2121

ci: Fix qemu virtiofs cache components script

---

integration/kubernetes/cleanup_bare_metal_env.sh

If we have enabled pipefail option, `set -o pipefail`, the pipeline will fail when any sub-command exits with a non-zero status. 
But when pipeline consist of `grep`, it may fail unnecessarily.
For `grep` command, the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.
In most scenario, we allow no lines being selected. just like the one in `integration/kubernetes/cleanup_bare_metal_env.sh`
```
veth_interfaces_union=$(sudo ip link | grep "veth" | awk '{print $2}' | cut -d '@' -f1)
```

pipe: pipeline failed when no line selected in `grep`

---

.ci/aarch64/configuration_aarch64.yaml
.ci/aarch64/lib_setup_aarch64.sh

Let's turn on k8s integration tests on aarch64.
For now, we only support k8s running with CRI-O.
Fixes: #2114

k8s: turn on k8s integration tests on aarch64

---

.ci/ci_cache_components.sh
.ci/install_qemu.sh

The qemu tarball has been renamed to kata-static-qemu.tar.gz, this PR
fixes the cache and static installation script for qemu.
Fixes #2123

ci: Fix qemu tarball name

---

.ci/install_kata.sh
.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/lib.sh

allow users and CI scripts install a specific version of kata using
`.ci/install_kata.sh` script, for example to build and install the versions
1.9.1, just run the following command:
`.ci/install_kata.sh 1.9.1`
fixes #2132

ci: add support for installing specific version of kata

---

.ci/ci_cache_components.sh
.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/install_nemu.sh
.ci/install_qemu.sh
.ci/install_qemu_experimental.sh
.ci/lib.sh

9e739cf  ci: Fix qemu tarball name
3134b33 ci: use variables for jenkins url and artifacts paths
af3e5a5  ci: fix install qemu-virtiofs
b24eb57 ci: Fix qemu virtiofs cache components script

tests: Backport qemu fixes for 1.9

---

.ci/aarch64/configuration_aarch64.yaml
integration/kubernetes/k8s-number-cpus.bats

Since AArch64 doesn't support cpu hotplug on kata containers, we need to skip related k8s tests for now.
Fixes: #2126
Depends-on: github.com/kata-containers/tests/#2117

k8s: skip cpu hotplug related test

---

.ci/static-checks.sh

clh client code is generated, ignore static check for it, fix missing
case.
Fixes: #2142

ci: static: ignore spell for clh client code

---

metrics/time/launch_times.sh

In case the guest kernel is compiled with SECURITY_DMESG_RESTRICT=y
the test container needs to have the CAP_SYSLOG capability in order
to run dmesg.
Signed-off-by: Ralf Haferkamp <rhafer@suse.com>

metrics: launch_times: Set capabilities for dmesg

---

.ci/install_cloud_hypervisor.sh

Currently the jenkins url variable seems empty as we need to first make
the source of that variable from lib.sh.
Fixes #2161

ci: Fix cloud hypervisor script

---

.ci/ci_cache_components.sh

In the case of qemu and qemu experimental we have the tar file in a
specific location and we need to check it. This PR fixes the regression
that was introduced by the commit 06da90d9a26a366d75b0dc56565a3d8ed2098752.
Fixes #2152

ci: Fix ci_cache_components.sh script to locate qemu

---

integration/cri-o/crio_skip_tests.sh

While we are investigating the reason for this failure, skip this
test. None of the recent commits on the runtime seem to be an obvious
cacndidate for failure.
Fixes #2166

cri-o: Skip cri-o "ctr execsync" test.

---

.ci/aarch64/configuration_aarch64.yaml
integration/kubernetes/k8s-expose-ip.bats

The failure on k8s `expose IP address` test on ARM CI is quite strange and confused.
```
10:49:45 not ok 1 Expose IP Address
10:49:45 # (in test file k8s-expose-ip.bats, line 48)
10:49:45 #   `curl http://$svcip:$svcport/echo?msg=${echo_msg} | grep "$echo_msg"' failed
curl: (7) Failed to connect to 10.111.96.90 port 8080: Connection refused
```
I couldn't reproduce the error on local machine, or even offline ARM CI machine, no matter how many times I tried.
I'm wondering if it's that when we used jenkins to trigger test job, some sub-process occupied the service `8080` port, which leads to the error: `connection refused`.
And that's Maybe why we only got this error on ARM CI job??????😥
This commit now is only to verify my guess. If it still fails, I may should skip this test... …

k8s: failure on k8s "expose IP address" test on ARM CI

---

Gopkg.lock
Gopkg.toml
vendor/github.com/onsi/ginkgo/config/config.go
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
vendor/github.com/onsi/ginkgo/ginkgo/bootstrap_command.go
vendor/github.com/onsi/ginkgo/ginkgo/convert/import.go
vendor/github.com/onsi/ginkgo/ginkgo/convert/package_rewriter.go
vendor/github.com/onsi/ginkgo/ginkgo/convert/testfile_rewriter.go
vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/interrupt_handler.go
vendor/github.com/onsi/ginkgo/ginkgo/main.go
vendor/github.com/onsi/ginkgo/ginkgo/run_command.go
vendor/github.com/onsi/ginkgo/ginkgo/suite_runner.go
vendor/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hash.go
vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
vendor/github.com/onsi/ginkgo/internal/codelocation/code_location.go
vendor/github.com/onsi/ginkgo/internal/leafnodes/benchmarker.go
vendor/github.com/onsi/ginkgo/internal/remote/aggregator.go
vendor/github.com/onsi/ginkgo/internal/remote/server.go
vendor/github.com/onsi/ginkgo/internal/spec/spec.go
vendor/github.com/onsi/ginkgo/internal/spec/specs.go
vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go
vendor/github.com/onsi/ginkgo/reporters/default_reporter.go
vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go
vendor/github.com/onsi/ginkgo/types/types.go

After update golang version to 1.13.5 in runtime, got following fails
with test:
GOPATH=/home/jenkins/workspace/kata-containers-runtime-Power8-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/vendor go build ./vendor/github.com/onsi/ginkgo/ginkgo
unlink vendor/src
./ginkgo -failFast -v -focus "" -skip "Update CPU set|CPUs and CPU set|Update CPU constraints|Hotplug memory when create containers|run container and update its memory constraints|check dmesg logs errors|memory constraints|check yum update|run container exceeding memory constraints" \
functional/ -- -runtime=kata-runtime -timeout=120
flag provided but not defined: -test.timeout
Usage of /tmp/ginkgo426003962/functional.test:
Update github.com/onsi/ginkgo version to v1.10.3 to handle this issue.
Fixes: #2174 …

vendor: Update github.com/onsi/ginkgo version to v1.10.3

---

integration/kubernetes/k8s-number-cpus.bats

Run the test that checks the number of cpus after killing a
container
Depends-on: github.com/kata-containers/runtime#2251
fixes #2116

integration/kubernetes: unskip k8s-number-cpus test

---

.ci/install_crio.sh
integration/cri-o/crio_skip_tests.sh

CI today does not use conmon version specified in
version.yaml, instead builds from master.
The latest version of conmon seemed to have changed certain
exit codes for exec and introduced errors described in
kata-containers/runtime#2352
Have the CI checkout version from versions.yaml and build conmon.
Fixes #2170

Fix crio execsync issue

---

.ci/ci_cache_components.sh

While creating the cache asset we need to pass the component name, this PR
fixes this by passing as a component name only cloud-hypervisor instead of
passing the full name and the full path.
Fixes #2177

ci: Fix cache for cloud hypervisor

---

integration/containerd/cri/container_restart_test.go.patch
integration/containerd/cri/integration-tests.sh

This PR mainly adds a ~~crictl~~ cri integration test patch based container restart case as well as fix two cases that doesn't exist in the cri integration test.
I think it's better to add such case to https://github.com/containerd/cri/tree/master/integration and I'll try to raise a PR there about this later. If that case is merged then we can use it in future after vendor update :)
Fixes: #2138, #2139
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>

Add container restart case

---

.ci/resolve-kata-dependencies.sh

In order to enable a CI for the kata-containers repository we need to add
it as a kata dependency.
Fixes #2179

ci: Add kata-containers repository to kata dependencies

---

.ci/jenkins_job_build.sh

The setup.sh is located at a different location for the kata-containers
repository so we need to introduce the correct location.
Fixes #2181

ci: Add kata-containers repository for the jenkins job build script

---

.ci/install_rust.sh

As we need to install rust on CI systems, we need to make
the installation non-interactive.
Fixes: #2187.

rust: run installation non-interactive

---

.ci/ci_cache_components.sh

This PR fixes the cloud hypervisor binary path in order to perform the
cache of cloud hypervisor.
Fixes #2185

ci: Fix cloud hypervisor binary path for cache components

---

.ci/install_kata_image_rust.sh

We need to create the image path in order to place there the rust agent image
as currently it does not exists.
Fixes #2191

ci: Create image path for rust agent image

---

.ci/install_runtime.sh

Currently the CI fails when cloud-hypervisor (CLH) is being used. This is
because kata-runtime is only set as default/new Docker runtime when QEMU is
being used. 
Fixes: #2189

ci: Set kata-runtime as Docker runtime when using cloud-hypervisor

---

.ci/install_kata_image_rust.sh

Currently we are getting the error that the kata-containers directory is not
found while we are trying to install the rust image. This PR fixes that issue.
Fixes #2193

ci: Add installation path for rust image

---

.ci/go-test.sh

Currently anything under virtcontainers are skipped for non-root users.
We should just treat them the same as others instead.
Depends-on: Depends-on: github.com/kata-containers/runtime#2371
Fixes: #2197

ci: do not skip virtcontainers directories with non-root users

---

.ci/lib.sh

While trying to call the function get_dep_from_yaml_db from lib.sh, this
is failing while trying to run the install_yq.sh script as sometimes it does
not find the script in the current path. This PR fixes that issue by
improving the path.
Fixes #2203

ci: Improve path for calling install_yq.sh script

---

.ci/install_crio.sh

CI today does not use conmon version specified in
version.yaml, instead builds from master.
The latest version of conmon seemed to have changed certain
exit codes for exec and introduced errors described in
https://github.com/kata-containers/runtime/issues/2352
Have the CI checkout version from versions.yaml and build conmon.
backport of b145f4ca07e4acdaa8d6d308a942ed05f9181f2e
Fixes #2170

[1.10 backport]: cri-o: Check out specific version of conmon in CI

---

.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/install_qemu.sh
.ci/install_runtime.sh
Makefile
integration/compatibility/run.sh

Backward compatibility test checks if docker exec (create and start) and
rm (stop and delete) work in a kata container started with the current
installed version (PR) and modified with the master version of kata.
Forward compatibility test does the same but starting a container with the
master version of kata and modifying it with the current installed version (PR)
fixes #2134

ci: add backward and forward compatibility tests

---

.ci/run.sh
Makefile
integration/sandbox_cgroup/sandbox_cgroup_test.sh

This enables the sandbox cgroup feature at the configuration.toml and then
it runs the docker integration tests in order to ensure that this functionality
is working.
Fixes #2208

test: Sandbox cgroup test

---

.ci/setup_env_centos.sh

We need to enable PowerTools repository for CentOS 8 in order to be
able to install packages like moreutils, libseccomp-devel, pandoc, etc.
Fixes #2214

ci: Enable PowerTools repository for CentOS 8

---

.ci/setup_env_centos.sh

We need to enable the priority for CentOS Base repository if we want to update
CentOS 8 without issues. This PR enables the priority and with that solves the
issues that some perl packages can not be installed.
Fixes #2223

ci: Enable priority for CentOS base repository

---

integration/vcpus/default_vcpus_test.sh

Now that the issue has been solved, this PR will enable this test
on Firecracker.
Fixes #2225

test: Enable vcpu test for Firecracker

---

.ci/static-checks.sh

Rather than fail the spell check on the first failure, continue to
check all the changed documents, and report the global fail at the
end. This may help reduce CI/review cycle time if/when multiple docs
are submitted in a single PR.
Also spit out a URL link to the documentation repo docs in the case
of failure, to help direct authors to guidance docs.
Fixes: #2227

ci: static check: spellcheck: check all docs

---

.ci/install_kubernetes.sh

We need to import the gpg keys and disable the gpgcheck from the
/yum/repos.d/kubernetes repository as it is not possible to perform
the installation of the kubernetes components, this issue is related
with https://github.com/kubernetes/kubernetes/issues/60134.
Fixes #2233

ci: Fix kubernetes installation for Fedora 31

---

cmd/check-spelling/data/acronyms.txt

Add the lowercase vhost to the spell checker dictionary.
Fixes: #2245.
Signed-off-by: Liu Xiaodong <xiaodong.liu@intel.com>

spelling: Add vhost to spell check dictionary

---

.ci/static-checks.sh

During the merge of #2228 the final check in the spell check got
inverted - fix with a `|| true`.
Fixes: #2239

ci: spell check: fix inverted test

---

.ci/install_kata_image.sh
.ci/install_runtime.sh
.ci/setup.sh
.ci/setup_env_fedora.sh

This PR avoids the installation of docker and the configuration of
the runtime with docker as also uses podman to build the image.
Fixes #2250

ci: Setup podman for the cgroupsv2+podman ci

---

.ci/install_kata_image.sh

We need to set the variable TEST_CGROUPSV2 as not all the jobs will have it.
Fixes #2252

ci: Fix TEST_CGROUPSV2 unbound variable

---

.ci/configure_crio_for_kata.sh
.ci/install_crio.sh
.ci/setup_env_centos.sh
integration/containerd/shimv2/shimv2-tests.sh
integration/kubernetes/run_kubernetes_tests.sh

This PR removes non-existing packages for CentOS 8 as also skips the
CRI-O, kubernetes, and shimv2 installation mainly because of missing packages as dependencies.
Fixes #2247

ci: Enable ci for CentOS8

---

integration/docker/mem_test.go

When `sandbox_cgroup_only` is `true`, all cgroups are honoured and all kata
components (including hypervisor) are placed in the same cgroup.
Hypervisor + kata components may consume more than 100MB of RAM, hence memory
cgroup must be big enough to contain them.
fixes #2254

integration/docker: increment amount of memory in docker mem tests

---

integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml
integration/kubernetes/kubeadm/config.yaml
integration/kubernetes/runtimeclass_workloads/kata-runtimeclass.yaml
integration/kubernetes/runtimeclass_workloads/pod-number-cpu.yaml

We are using k8s 1.16, so we can enable PodOverhead alpha
feature for our testing.
In addition, modify skipped tests:
- Remove `Downward API` tests from the list of skipped tests.
These tests pass when enabling the `PodOverhead` feature on
kubernetes.
- Add a `Daemon set` test which requires to have a cluster
with at least two nodes.
Fixes: #2242.

k8s: e2e: Enable podOverhead feature and modify skipped tests

---

integration/docker/kill_test.go

Before try to kill container check if run exit code
returned 0.
Fixes: #2260

test: docker: check docker run exitcode

---

.ci/aarch64/clean_up_aarch64.sh
.ci/jenkins_job_build.sh
integration/kubernetes/init.sh
integration/kubernetes/k8s-uts+ipc-ns.bats
integration/stability/bind_mount_linux.sh

I've found some stale files under `/tmp` on ARM CI:
```
-rw-------   1 root    root       384 Jan 14 02:49 kubeadm_config.0rtpew.yaml
.............
-rw-------   1 root    root       290 Jan 14 23:08 pod_config.1fs8Z1.yaml
..............
```
`mktemp` creates a temporary file or directory under `/tmp`.
It's caller's responsibility to delete them when it is in no use.

cleanup: delete what mktemp creates

---

.ci/install_cloud_hypervisor.sh

packaging installer script will clone the hypervisor repository,
if is not found, because test setup goes to the repository and
not the parent directory, it clones the hypervisor two times.
Fixes: #2258

setup: clh: do not clone more than one time.

---

lib/common.bash

This PR fixes the issue of unbound variable on common.bash for experimental qemu.
Fixes #2244

ci: Fix unbound variable on common.bash

---

.ci/install_yq.sh

latest version of `yq` is not expanding anchors correctly and
we are having failures when building the initrd.
Let's stick to version 2.3.0 which is also used in runtime
and osbuilder repos.
Fixes: #2274

CI: do not use latest version of yq

---

.ci/install_yq.sh

This is backport of #2275 
latest version of `yq` is not expanding anchors correctly and
we are having failures when building the initrd.
Let's stick to version 2.3.0 which is also used in runtime
and osbuilder repos.

backport-1.10: CI: do not use latest version of yq

---

.ci/install_yq.sh

latest version of `yq` is not expanding anchors correctly and
we are having failures when building the initrd.
Let's stick to version 2.3.0 which is also used in runtime
and osbuilder repos.
Fixes: #2274
(cherry picked from commit 94c25fc0274f62630eb63ed2b3c2e0a64c6473b7)

backport-1.9: CI: do not use latest version of yq

---

.ci/install_kata_image_rust.sh

This reverts commit 16682ae20bdb828451b1d6b9c093b9877e39c50a.
Static link still does not work, revert this patch
Fixes: #2276

Revert: "rust-agent: use --release build for rust agent"

---

.ci/jenkins_job_build.sh
.ci/run.sh
Makefile
integration/podman/main_test.go
integration/podman/podman.go
integration/podman/run_test.go

This PR enables to have rootless podman integration tests.
Fixes #2280

tests: Add podman integration tests

---

Makefile

This PR fixes the comment about the Cloud hypervisor configuration file.
Fixes #2295

makefile: Fix configuration file name

---

.ci/install_cloud_hypervisor.sh

Currently, we have a failure at the nightly jenkins job, the main issue
is that the ci_cache_components.sh script is looking the cached cloud
hypervisor inside the cloud hypervisor repository. This PR fixes that
issue.
Fixes #2291

ci: Fix cloud hypervisor jenkins job

---

.ci/static-checks.sh

When the shell cmd return non-zero, the script
would return directly and there is no chance
to do the return code check in the following
cmd.
Fixes: #2205
Signed-off-by: fupan.lfp <fupan.lfp@antfin.com>

ci: fix the issue of missing show error info

---

.ci/install_yq.sh
.ci/lib.sh

v3.1.0 fixes reading anchors and also fixes an issue reading the
yaml file on ARM systems.
`yq` 3.1.0 now requires to pass `-X` when reading Anchors, so adding
it to our `get_dep_from_yaml_db` function.
Fixes: #2290.

ci: update yq to v3.1.0

---

.ci/jenkins_job_build.sh

As we are not doing the setup and installation of virtcontainers, we need
to skip running the unit tests for podman CI.
Depends-on: github.com/kata-containers/runtime#2452
Fixes #2298 

ci: Skip running unit tests with podman

---

.ci/aarch64/configuration_aarch64.yaml
.ci/aarch64/kubernetes/init.sh

Hi~ guys
I'm so sorry that, lately, ARM CI is quite unstable. 
I've already debugged a few issues. I'll elaborate and fix them here.
On PR #1809, we edited config file for pod flannel `kube-flannel.yml`, in order to delete the default 50M memory limitation for flannel pod on AArch64.
Recently, this config file has been updated on upstream, which leads to above modification ineffective. 
We have elaborated this issue in [kata-containers/ci#245](https://github.com/kata-containers/ci/issues/245).
Lately, this failure on `check dnf update` docker test occurred frequently, almost six, or seven times of ten trials.

AArch64: fix unstable ARM CI

---

Makefile
integration/ipv6/ipv6.sh

This adds a docker test for ipv6. This enables docker with ipv6 and then
we perform a ping in one of the containers.
Fixes #2270

test: Add docker test for ipv6

---

.ci/jenkins_job_build.sh

In some of the kata repositories is possible to run the unit tests,
this PR allows to run them.
Fixes #2306

ci: Allow to run unit tests

---

.ci/install_kubernetes.sh
integration/kubernetes/run_kubernetes_tests.sh

We have seen random failures when we are trying to enable kubernetes repository
in Fedora 31. There are some times that the Fedora CI is failing when we
try to import the gpgkey from the kubernetes repository
(https://packages.cloud.google.com/yum/doc/yum-key.gpg). This PR removes
that we install and run kubernetes on Fedora.
Fixes #2302

ci: Do not install and run kubernetes on Fedora

---

cmd/check-spelling/data/projects.txt

Add the relevant project names so we can type about EFK and ELK
stacks etc.
Fixes: #2333

spellcheck: add project works for EFK stack etc.

---

.ci/podman/configuration_podman.yaml
versions.yaml

We need to update podman version to 1.8.0 as currently with version 1.6.2
we have issues trying to download the images. We also need to remove port nginx
test as has random failures with this new podman version.
Fixes #2336

versions: Update podman version to 1.8.0 and remove port nginx test

---

lib/common.bash
metrics/density/docker_memory_usage.sh
metrics/density/fast_footprint.sh
metrics/density/footprint_data.sh

As virtiofs enabled in kata, virtiofsd will run as a standalone binary.
it will contribute to memory footprint of kata so we should add
virtiofsd into metrics memory measure list.
This commit depends on if virtiofsd can be added into kata-env, whose PR is  https://github.com/kata-containers/runtime/pull/2492.
Fixes: #2321
@jodh-intel  @devimc  @grahamwhaley  @Pennyzct

test: metrics: add virtiofsd to memory measure list

---

.ci/install_crio.sh
integration/kubernetes/init.sh
integration/kubernetes/kubeadm/config.yaml

Hi~ guys
I've found tons of leaking network namespace mount point on ARM CI, which comes from cri-o.
```
root@arm-testing-2:~# mount | grep "/run/netns/cni-" | wc -l
3084
```
`cri-o v1.16.x` forgets to un-mount them when they're in no use. But it got fixed in `cri-o v1.17.0`,
see [related code here](https://github.com/cri-o/cri-o/blob/release-1.17/internal/lib/sandbox/namespaces_linux.go#L183) for confirmation. ;)
So we need to do the version update for cri-o. And Since CRI-O and Kubernetes follow the same release cycle and deprecation policy, I will also update k8s as well. ;).
This PR has been split into three commits.
- **k8s: update kubeadm config to version v1beta2**
In k8s new release v1.17.x, `kubeadm.k8s.io/v1beta1` has been deprecated, so we should update our kubeadm config to …

cri-o: fix netns mount point leaking from cri-o

---

cmd/container-manager/manage_ctr_mgr.sh

openSUSE Leap and SLES does not longer support docker 18.06, they required
as a minimum docker 18.09. This PR updates that version without affecting anything,
as docker 18.09 in openSUSE and SLES supports devicemapper.
Fixes #2342

ci: Update docker version for openSUSE and SLES

---

.ci/static-checks.sh

The `list` var in the skip_paths function was not local, thus
afiact, rendering it global. Thus, when skip_paths was called
more than once, the list grew and grew, and included the unfiltered
files, including vendor files.
Fix by making it local, so it is built afresh on each function
invocation.
Fixes: #2338

ci: static: markdown: make list var func local

---

functional/state_test.go

Currently, we have seen random failures on state functional test. We
will investigate the root cause of this failure but in order to have
a more stable CI we need to skip it.
Fixes #2348

test: Skip state functional test for Debian 10

---

.ci/static-checks.sh

`skip_paths()` output was being contaminated with the
`grep` output inside the function. Use `grep -q` to silence
the output of `grep`.
Fixes: #2338.

static_checks: fix `skip_paths` function

---

integration/docker/package_manager_test.go

Performing a dnf -y update on a fedora container 31 is failing as
it is complaining about a missing rpm package. This PR removes the option
to use latest Fedora and use Fedora 30 which shows a stable behaviour.
Fixes #2359

test: Update package manager test for Fedora

---

cmd/check-spelling/README.md

Note that if you have made local dictionary edits and wish to use them,
then you may need to `make-dict` to have them take effect.
Fixes: #2332

spellcheck: Add master dict rebuild note

---

versions.yaml

Now that we have updated our supported k8s version to 1.17,
use Sonobuoy 0.17.2 to run e2e k8s tests.
Fixes: #2361.

tests: e2e: Update Sonobuoy to 0.17.2

---

.ci/hypervisors/clh/configuration_clh.yaml

This patch brings back the docker integration tests on CPU hot-plug for our
cloud-hypervisor CI.
Fixes: #2363
Depends-on: kata-containers/runtime#2509
Depends-on: kata-containers/packaging#968

ci: Enable CPU hot-plug tests for cloud-hypervisor

---

integration/docker/docker.go
integration/docker/package_manager_test.go

In order to avoid random timeouts, docker images must be pulled before
running `docker run`
fixes #2366

integration/docker: pull fedora 30 image before using it

---

.ci/jenkins_job_build.sh

This will set the noninteractive mode for Ubuntu and Debian.
Fixes #2371

ci: Set noninteractive on Ubuntu and Debian

---

.ci/filter/filter_docker_test.sh
.ci/jenkins_job_build.sh

All docker integration tests have not been running since yq was updated
to v3.1 (for at least 12 days). The root cause is that yq v3.1 is no
longer returning 'null' as empty strings. To be safe, we keep checks on
both 'null' and '""' (empty string). Also, we observed some regression
test failures with this patch (at least for CIs on ubuntu-initrd, clh,
and Fedoba31).
Fixes: #2368

ci: Bring back docker integration tests since yq v3.1

---

.ci/setup_env_opensuse.sh
integration/entropy/entropy_time.bats

In order to enable the openSUSE Leap 15.1 CI, we need to remove the
openSUSE cloud repo as this is related with https://bugzilla.suse.com/show_bug.cgi?id=1165519
as well to skip the entropy test.
Fixes #2352

ci: Enable openSUSE Leap 15.1 CI

---

.ci/hypervisors/clh/configuration_clh.yaml

Skip test that got a regression while docker tests were skipped.
Fixes: #2376

clh: docker: Skip CPU hotplug test

---

.ci/install_kata_image.sh

While trying to build the image for podman with osbuilder, we got an error
saying that the ROOTFS_DIR does not exist. The main issue is that we are
trying to find the ROOTFS_DIR at the top of osbuilder directory, but for podman
the ROOTFS_DIR is created inside the rootfs-builder directory. This PR fixes that
issue by passing the correct location of the ROOTFS_DIR that is being generated by osbuilder
with podman.
Fixes #2370

ci: Fix ROOTFS_DIR for podman CI

---

metrics/report/report_dockerfile/Dockerfile

the rocker/tidyverse:latest have no latex-xcolor package, so specify an
older tag to let docker build work.
also, specifying a stable tag cancel the potential risk of the update of the latest image.
Fixes: #2393
@jodh-intel  @grahamwhaley  @devimc

metrics: specify a tag for rocker/tidyverse

---

.ci/hypervisors/firecracker/configuration_firecracker.yaml
Makefile
command.go
config.go
integration/docker/cpu_test.go
integration/docker/mem_test.go
integration/docker/package_manager_test.go
integration/docker/vsock_test.go

All docker tests are using the 'DefaultHypervisor' (a.k.a 'qemu') as the
key when reading from KataConfig. This will cause test failures for the
tests requires information from the configuration file (e.g. cpu_test,
mem_test and vsock_test) when kata is not using qemu as its
hypervisor. This patch introduced a new global variable 'KataHypervisor'
which is initialized based on the environment variable 'KATA_HYPERVISOR'
that should be set by the CI script.
Fixes: #2383

test:docker: Use the right hypervisor when reading from KataConfig

---

.ci/install_firecracker.sh
.ci/install_kata.sh
.ci/install_runtime.sh
cmd/container-manager/manage_ctr_mgr.sh

Hi~ guys
I've been trying to enable FC tests on ARM CI lately.
All tests work well in my local machine and I may need to do the following twist on upstream existing configuration.
- **configure_docker: add -s option for configuring storage driver**
When running with firecracker, docker is configured by `/etc/docker/daemon.json`, which is inconsistent with the original installation in [install_docker()](https://github.com/kata-containers/tests/blob/master/.ci/setup.sh#L49). They are using systemd service file to configure.
Let's stick with one method, and add new `-s` option to configure storage driver.
- **FC: speed up installing firecracker/jailer**
Since we only use `firecracker/jailer` in stable version, we could just download binary from their release page.Therefore we could save the …

AArch64: enable fc tests on ARM CI

---

.ci/hypervisors/clh/configuration_clh.yaml

The regression we had on CPU releated tests was caused by the bug
reported in issue #2383. With that bug being fixed, we are bring back
CPU related tests back to the CI.
Depends-on: kata-containers/runtime/pull/2552
Fixes: #2363

clh:docker: Enable CPU tests

---

.ci/ci-fast-return.sh

We should run the whole CI when there are only changes in the vendor
directory. To accomplish this, use `get_pr_changed_file_details_full`.
Fixes: #2241.

ci: ci-fast-return.sh should consider vendor changes

---

.ci/install_cri_containerd.sh

Enhances the `install_cri_containerd.sh` script to be able to build and
install containerd using a commit SHA as the version.
The script should now work when containerd versions are:
- a release number, e.g. `v1.3.3`
- a commit SHA, e.g. `3a4acfbc99aa976849f51a8edd4af20ead51d8d7`
Fixes: #2414.

containerd: be able to build from source when version is a commit

---

integration/vcpus/default_vcpus_test.sh

We need to enable debug for the vcpu test in order to see why this tests
is randomly failing.
Fixes #2407

tests: Enable debug for vcpu test

---

.ci/hypervisors/clh/configuration_clh.yaml

There are many docker integration tests that are currently being skipped
for CI on clh (as tracked in #2399). With recent developments of
cloud-hypervisor driver in Kata and various fixes in the kata/tests
repo, we are expecting to have many more integration tests on docker to
be supported.
Depends-on: github.com/kata-containers/runtime#2552
Fixes: #2411

clh:docker: Enable multiple integration tests being skipped

---

.ci/podman/configuration_podman.yaml
versions.yaml

This PR updates the podman version to 1.8.2 as well as updates the tests
for the podman CI.
Fixes #2422

ci: Update podman to 1.8.2

---

integration/kubernetes/run_kubernetes_tests.sh

With support of CPU hotplug introduced to kata with clh, we now can run
CPU-related k8s integration tests.
Fixes: #2325

clh: k8s: Enable CPU related tests

---

.ci/hypervisors/clh/configuration_clh.yaml

Enable all package manager test but skip yum. `yum test is doing some file operations that break virtio-fs.
For more information see:
https://github.com/kata-containers/tests/issues/2008
Fixes: #2418

docker: clh: Skip check yum update

---

.ci/hypervisors/clh/configuration_clh.yaml

Memory hotplug now is enabled in clh, enable test for docker.
Fixes: #2424

clh: Enable memory hotplug test for clh

---

.ci/jenkins_job_build.sh
.ci/run.sh

Make docker test run in its own job for clh.
Fixes: #2428

ci: split docker test for clh

---

.ci/install_cloud_hypervisor.sh

Script installer always install cloud-hypervisor from source.
When it tries install from binary this fails when it does curl.
curl fails because it downloads the binary called cloud-hypervisor
in a path with a directory with the same name. Fix by moving
to the rigth path. Aditonally remove silent download to
allow see errors from curl and progress-bar.
Fixes: #2432

setup: Fix clh cache installer

---

.ci/s390x/configuration_s390x.yaml

The package manager dnf tries to update shadow-utils that needs to set
xattr. The option is not supported by 9p. The test is successfull using
another storage driver like devicemapper. As overlay is the default for
the CI and we don't support virtiofs on s390x yet, we can simply skip
this test.
Fixes: #2358

s390x : skip dnf update

---

.ci/setup_env_rhel.sh

This PR enables the repository that is needed for perl-IPC-Run for RHEL.
We need to enable this repository as perl-IPC-Run is a dependency for
moreutils package and we need moreutils because we are using chronic.
Fixes #2438

ci: Enable repo for perl-IPC-Run

---

.travis.yml
versions.yaml

With golang updated to v1.13, we found golangci-lint build error on ARM CI.
```
08:55:44 go build -o golangci-lint ./cmd/golangci-lint
08:55:49 go: github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)
```
Taking advices here(https://github.com/filecoin-project/go-filecoin/issues/3486#issuecomment-534858459), we need to update `golangci-lint` to `v1.18.0` to get Go `1.13` support.
Fixes: #2434

golangci-lint: fix `invalid pseudo-version` error on ARM CI

---

.ci/hypervisors/clh/configuration_clh.yaml

apt-get upgrade is not working until no_posix_lock is enabled.
Skip test to make work the CI.
Fixes: #2444

docker: clh: Skip apt-get upgrade

---

.ci/install_kata_kernel.sh

Add prefix to experimental kernel to match with current cached version.
Fixes: #2442

ci: kernel: install experimental kernel using cache

---

integration/stability/hypervisor_stability_kill_test.sh

While running the hypervisor stability kill test on SLES and openSUSE Leap,
we can see that pod information is left kata-containers/runtime#2611,
we need to skip this until this is solved.
Fixes #2454

tests: Skip hypervisor stability kill test on SLES and openSUSE

---

Makefile

This PR sort the contests of the tests in alphabetical order.
Fixes #581

makefile: Sort the tests in alphabetical order

---

.ci/hypervisors/clh/configuration_clh.yaml
Makefile

Running test in serial takes a long time, just qemu uses today
parallel, refactor makefile to run all as parallel.
Fixes: #2426

make: docker: Run docker test in parallel for all jobs

---

cmd/container-manager/manage_ctr_mgr.sh

This PR fixes the issue that the metadata file does not match checksum,
as it is performing a clean all of the repository which helps to avoid
this issue.
Fixes #2468

ci: Fix centos repositories issues

---

.ci/teardown.sh

Filter out libcontainer log messages (which get logged by the agent) as they trigger errors from the the log-parser that runs in the CI. The reason for the errors is that the log-parser expects all log entries to provide a standard set of fields, but libcontainer does not provide a way to pass a logger object into it, so it logs in its own format, which does not include mandatory fields like "pid".
See: https://github.com/kata-containers/tests/tree/master/cmd/log-parser#logfile-requirements
Fixes: #2470.

CI: Hide libcontainer logs from log-parser

---

.ci/teardown.sh

The shimv2 runtime logs to 'kata' in the journal, not 'kata-runtime'.
Add that to the CI teardown script log collection methods so we
capture them if available.
Fixes: #2466
(Also Fixes the original/duplicate https://github.com/kata-containers/ci/issues/270)

ci: teardown: save shimv2 logs

---

.ci/install_bats.sh
integration/cri-o/cri-o.sh
versions.yaml

We should not install the latest bats version as it has issues
when we skip tests https://github.com/bats-core/bats-core/issues/292
and when we are running in parallel https://github.com/bats-core/bats-core/issues/290.
Fixes #2483

ci: Do not install latest bats version

---

.gitignore
kata-webhook/README.md

The whole vendor directory has to be copied under the kata-webhook
directoy, otherwise we'll face failures such as:
```
fidencio@laerte ~/go/src/github.com/kata-containers/tests/kata-webhook $ docker build -t katadocker/kata-webhook-example:latest .
Sending build context to Docker daemon  13.82kB
Step 1/7 : FROM golang:latest AS builder
---> 2421885b04da
Step 2/7 : WORKDIR /go/src/kata-pod-annotate
---> Using cache
---> 2fbde962f238
Step 3/7 : COPY . ./
---> Using cache
---> 20cf32a11a54
Step 4/7 : RUN CGO_ENABLED=0 go build -o /go/bin/kata-pod-annotate
---> Running in a90ab84e36bc
main.go:18:2: cannot find package "github.com/slok/kubewebhook/pkg/http" in any of:
/usr/local/go/src/github.com/slok/kubewebhook/pkg/http (from $GOROOT)
/go/src/github.com/slok/kubewebhook/pkg/http (from …
```

kata-webhook: Update README.md

---

.ci/install_bats.sh
integration/cri-o/cri-o.sh
versions.yaml

8612081 ci: Do not install latest bats version

backport fix for stable 1.10

---

.ci/setup_env_centos.sh
.ci/setup_env_debian.sh
.ci/setup_env_fedora.sh
.ci/setup_env_opensuse.sh
.ci/setup_env_rhel.sh
.ci/setup_env_sles.sh
.ci/setup_env_ubuntu.sh

This PR orders the package dependencies for the different distros in alphabetical order
in order to make easier to add or remove packages.
Fixes #2477

ci: Get package dependencies in alphabetical order

---

.ci/install_crio.sh
lib/common.bash

Update network_ns_flag to reflect changes in CRI-O v1.17 where
manage_network_ns_lifecycle was deprecated and replaced with
manage_ns_lifecycle.
Fixes #2448

ci: Update network namespace flag for CRIO install

---

.ci/setup_env_fedora.sh
integration/podman/run_podman_tests.sh

This PR will build and install podman from source in order to avoid
future issues where a certain version of podman in Fedora 31 is not present.
This issue is related with https://github.com/kata-containers/ci/issues/271.
Fixes #2480

ci: Build podman from source

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml

Increase memory-footprint `midval` to consider the memory overhead added by
`CONFIG_RANDOMIZE_BASE` in the guest kernel.
fixes #2500
fixes kata-containers/ci#273

ci: fix metrics CI

---

functional/vfio/config.json.in

vfio test should not have access to all host devices, instead the runtime
should be able to identify what devices are needed and update the device
cgroup when `sandbox_cgroup_only` is true.
fixes #2486

functional: apply device constraints to vfio test

---

.ci/configure_crio_for_kata.sh
.ci/install_crio.sh

We need to update how we get the value of the crio version
as the output of `crio --version` has changed since
crio 1.18.0.
This change now works with new and old versions of crio.
Fixes: #2506.

ci: update the way we get crio version

---

.ci/setup_env_rhel.sh
cmd/container-manager/manage_ctr_mgr.sh

This PR modifies the setup scripts to support rhel 8 by modifying
the docker installation as well as the packages.
Fixes #2510

ci: Update setup script to support rhel 8

---

.ci/aarch64/lib_install_qemu_aarch64.sh

This remains the original aarch64-softmmu *explicit* default config. And
borrows the tuned configuration from i386-softmmu except the board specific
ones.
Fixes: #2521
Signed-off-by: Jia He <justin.he@arm.com>

qemu-aarch64: Use tuned aarch64-softmmu.mak

---

metrics/lib/json.bash

This PR does not hard code runc names for the metrics code, this will get
the runtime form the docker in order to avoid failures related that runc
is not found.
Fixes #1796

metrics: Get runc name

---

Makefile
functional/vfio/run.sh

Add kata-runtime hypervisor and machine type options to VFIO test which
change default configuration file and modify machine_type variable when
using qemu.
Fixes #2462

functional/vfio: Add hypervisor option to VFIO test

---

integration/entropy/entropy_time.bats

We have seen random failures on SLES CI for the entropy time test, currently
we are trying to debug this issue and reproduce it locally. This PR skips
meanwhile this test in order to have a more stable CI.
Fixes #2538

test: Skip entropy time test on SLES

---

.ci/static-checks.sh

Add a new regex to ignore more auto-generated code.
Fixes: #2542.

CI: Make static checker ignore more auto-generated code

---

metrics/README.md
metrics/report/README.md

Note in the documentation that you can set `RUNTIME` in the environment to determine which container runtime the tests are run against.

metrics: Note use of RUNTIME in documentation

---

cmd/check-spelling/data/projects.txt

Add more tracing project names to the spell checker.
Fixes: #2560.

spellcheck: Add tracing project names

---

metrics/report/report_dockerfile/dut-details.R
metrics/report/report_dockerfile/fio-reads.R
metrics/report/report_dockerfile/fio-writes.R
metrics/report/report_dockerfile/footprint-density.R
metrics/report/report_dockerfile/lifecycle-time.R
metrics/report/report_dockerfile/mem-in-cont.R
metrics/report/report_dockerfile/memory-footprint.R
metrics/report/report_dockerfile/metrics_report.Rmd
metrics/report/report_dockerfile/network-cpu.R

Fix up two issues with the report generator:
- it was not very 'pleasant' at handling missing data, giving out errors and warnings. Make it smarter, and have it report 'no data found' for such cases.
- It looks like over at https://github.com/kata-containers/runtime/commit/a4b3c65c16f63f1690966f68426a703cd3af7ab5 the kata-env info changed 'shape', which gets output in the JSON data that the report generator parses. It was broken. Fix it up to handle the new Semver fields. (/cc @Pennyzct just fyi, as I think you added that Semver change - sorry if I didn't spot and make the link...)

metrics: report: clean up report generation

---

metrics/report/report_dockerfile/fio-reads.R
metrics/report/report_dockerfile/fio-writes.R

The x-axis on the fio latency percentile graphs was using the default
divisons, which was 'divide into 8', which placed each division tickmark
at 12.5% intervals. That's not useful for visually assessing the data.
Fix the intervals at 10%, which although a touch dense and noisy, does
make it much easier to assess the graph, particularly at the 'knee'
point, which tends to be crammed into the top 10% of the data.
Fixes: #2558

metrics: report: make fio percentile x-axis readable

---

metrics/report/grabdata.sh

Evaluate the version of Elastic we use for the density tests later.
Do it in the function that uses it, not at initialisation, as we do
not always perform the density tests, and we'd rather only fail
when necessary.
Fixes: #2549

metrics: report: evaluate elastic version later

---

metrics/time/launch_times.sh

The `date` command `-N` format changed in version 8.32, and now
pre-pends 0's to pad the field. Explicitly strip those 0's, otherwise
it causes the later json prints to barf, as it sees them as octal.
This is also backwards compat with older date versions (if the 0's
are not there, the strip is benign).
Fixes: #2562

metrics: time: explicitly strip leading 0's from date

---

lib/common.bash

We have a generic 'is_a_kata_runtime' function that was a bit
hard wired to specific names. We have a growing collection of kata
runtime names now, so let's get a little more flexible in our spotting
by just going for any runtime named 'kata*'.
Specifically, this now matches kata-qemu-virtiofs for instance.
Fixes: #2564

common: match more kata runtimes in generic check func

---

metrics/density/footprint_data.sh

The results that we are getting from the footprint_data.sh were we are using
smem tool should be in B instead of KB.
Fixes #2169

metrics: Fix footprint data results

---

.ci/setup.sh
functional/state_test.go
integration/docker/package_manager_test.go
tracing/tracing-test.sh

This PR enables rhel 8 CI. In this PR, we skipped the tests that are not running
on RHEL 8 as well as a modification in the setup.sh
Fixes #2540

ci: Enable RHEL 8 CI

---

.ci/jenkins_job_build.sh
.ci/run.sh

This PR enables the posiblity to run a podman cloud hypervisor CI.
Fixes #2547

ci: Enable podman cloud hypervisor CI

---

.ci/install_agent.sh
.ci/install_cloud_hypervisor.sh
.ci/install_kata_image.sh
.ci/install_kata_image_rust.sh
.ci/install_proxy.sh
.ci/install_qemu.sh
.ci/install_qemu_experimental.sh
.ci/install_runtime.sh
.ci/install_shim.sh
.ci/lib.sh
.ci/resolve-kata-dependencies.sh
.ci/static-checks.sh
.ci/vfio_jenkins_job_build.sh

The resolve-kata-dependencies.sh allows to overwrite
the kata-containers repositories, this results in
cloning them from arbitrary locations (usually a fork). Other
scripts,however, does not allow that because they have
hard-coded in values. One example is install_proxy.sh
which always clone and build from
github.com/kata-containers/proxy
So this change adapt those scripts to allow cloning and
building from arbitrary locations too.
Fixes #2535

ci: Allow to overwrite the repositories

---

.ci/teardown.sh

Arm CI and ppc64 travis ci logs were all flooded with `find: /tmp/...: Permission denied` error.
And that's due to not giving find command root permission, based on most of files/dirs under ``/tmp were owned by root.

test: fix "find: /tmp/...: Permission denied" error

---

.ci/aarch64/lib_install_qemu_aarch64.sh

Mostly, we use virt machine in qemu to start kata on arm64. so it's
meaningful to customize virt-board specific qemu. in this patch,
we add "VIRT" interface to let the user choose if they want to get
this customized qemu.
Fixes: #2578
@jodh-intel  @liwei

ci: add virt board specific optimization of qemu support for arm

---

lib/common.bash

This PR adds support for cloud hypervisor, this will help to retrieve
the correct hypervisor path while running metrics.
Fixes #2589

common: Add support for cloud hypervisor

---

.ci/vfio_jenkins_job_build.sh

Pull request's environment variables MUST BE honoured as they were declared,
nothing else. For example `ghprbPullLongDescription` contains PR's
description, so if it contains bash variables, like $foo and $bar, those
variable MUST NOT be expanded, otherwise the VFIO CI may fail due to unbound
variables.
fixes #2592

vfio: do not expand variables declared in PR's environment variables

---

metrics/density/footprint_data.sh

This PR retrieves the correct hypervisor name instead of having qemu name
in all the cases. This will fix that if we are running with cloud hypervisor
or firecracker, we will see that in the results json and not qemu.
Fixes #2597

metrics: Support different hypervisors for footprint test

---

.ci/static-checks.sh

Add a new regex to ignore more auto-generated code.
Fixes: #2542.
(cherry picked from commit 83f712ef4729863d843adb25a3faf71d71ed509e)

Backport: CI: Make static checker ignore more auto-generated code

---

integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
integration/kubernetes/e2e_conformance/run.sh
integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml

For PRs the CI runs a subset of test to make sure e2e setup works.
Then it has a job that run once a day with full list of e2e tests.
Add list to a yaml like other test that are skipped.
Fixes: #2582

 k8s: e2e: Move focus list to yaml

---

.ci/jenkins_job_build.sh

On cloud-hypervisor jobs when the image is not cached, the CI scripts try to
build the image from a source, but when it does uses PODMAN, the logic of the
script installation is that if TEST_CGROUPSV2 is false, it will use docker else
podman, the clh jobs export TEST_CGROUPSV2 as no. And fallback to use
podman.On clh jobs when the image is not cached, the CI scripts try to build
the image from a source, but when it does uses PODMAN, the logic of the script
installation is that if TEST_CGROUPSV2 is false, it will use docker else
podman, the clh jobs export TEST_CGROUPSV2 as no.
Use `false` to avoid the script use podaman.
Fixes: #2604

clh: ci: Do not build image using podman

---

.ci/vfio_jenkins_job_build.sh

the sed expression used to replace the first `=` with `='` is incorrect,
look for the variable name using [[:alnum:]_]+ not .*
fixes #2606

ci/vfio: fix not a valid identifier

---

metrics/density/fast_footprint.sh

This PR modifies the fast footprint density script to handle multiple
hypervisors names.
Fixes #2608

metrics: Handle multiple hypervisors

---

cmd/pmemctl/pmemctl.sh
integration/pmem/pmem_test.sh

Add script to create raw files that can be used as pmem volumes in kata
containers, such files contains metadata to indentify them as files that can
be used as pmem devices that support DAX.
pmemctl script will be mentioned in the documment that explains how to use
pmem volumes in Kata Containers.
fixes #2612

cmd: add pmemctl script

---

integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
integration/kubernetes/e2e_conformance/run.sh
integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml

Enable virtiofs CACHE=auto for k8s end-to-end this feature is required by some tests in k8s but is always by default.

clh: enable missing end-to-end tests

---

.ci/install_runtime.sh
.ci/jenkins_job_build.sh
Makefile
functional/vfio/run.sh

Copy config file instead of moving so that the original is still
available.
Fixes #2551

ci: Copy config file instead of moving

---

.ci/hypervisors/clh/configuration_clh.yaml
integration/kubernetes/run_kubernetes_tests.sh

With the support of disk block device hotplug added to clh, those tests
now should pass.
Fixes: #2318

clh: Enable block device hotplug related tests

---

.ci/static-checks.sh

This PR will ignore of chcking of drawio files.
Fixes: #2637

ci: ignore license header check for drawio files

---

cmd/check-spelling/data/projects.txt

This PR will add Grafana to projects.txt in spelling check to avoid ci failings.
Fixes: #2639

ci: Add Grafana to spelling check word list

---

.ci/run.sh

This PR fixes the runtime variable for the run script which is being
used to run the tests for rust agent 2.0
Fixes #2641

ci: Fix runtime variable for run script for rust 2.0

---

integration/containerd/cri/integration-tests.sh

This PR updates the runtime name for the cri integration tests used
by rust 2.0
Fixes #2633

test: Update runtime for cri integration test for rust 2.0

---

.ci/install_kata.sh
.ci/jenkins_job_build.sh

This change belongs to the context of issue #2527 , which in order to work needs to have kata-containers binaries (+ QEMU) installed in a well-known path (e.g. /opt/kata) inside a container image. I'm using this `.ci/install_kata.sh` script so that binaries are built and installed, and cached-on-jenkins artifacts (e.g. QEMU) are pulled in together. That script runs `kata-check` in the end, but I would like to not run it (makes no sense for my use case).
Since I'm sending it as an RFC I didn't create an related issue and the static checks of for this patch are expected to fail. 
----
The .ci/install_kata.sh script runs the kata-check by the end of the
installation process.
This change makes the script look at the RUN_KATA_CHECK environment variable
which can be set to "false" and then the …

ci/install_kata: Allow to not run kata-check

---

.ci/configure_crio_for_kata.sh
.ci/install_kubernetes.sh
.ci/jenkins_job_build.sh
.ci/run.sh
.ci/setup_env_debian.sh
integration/kubernetes/init.sh
integration/kubernetes/k8s-block-volume.bats
integration/kubernetes/k8s-expose-ip.bats
integration/kubernetes/k8s-liveness-probes.bats
integration/kubernetes/k8s-shared-volume.bats
integration/kubernetes/nginx.bats
integration/kubernetes/run_kubernetes_tests.sh

This PR enables and sets kubernetes tests with kata rust agent 2.0
on debian.
Fixes #2643

tests: Enable kubernetes tests with kata rust 2.0

---

.ci/install_kubernetes.sh

This PR enables the k8s installation for fedora as this will be used
for testing rust agent 2.0
Fixes #2647

ci: Enable k8s installation for fedora rust agent 2.0

---

.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/install_qemu.sh
.ci/install_qemu_experimental.sh
.ci/install_runtime.sh
.ci/lib.sh

This patch series tries to fix the issue #2537
I tested those modification in the script...
https://github.com/wainersm/kc-tests/blob/master/.ci/openshift-ci/buildall_install.sh
... which will install kata and dependencies in the directory passed as argument.

ci: adapt scripts to consider DESTDIR when installing kata

---

metrics/density/docker_memory_usage.sh

Now that we have several hypervisors we should not hardcore qemu as the
only one. This PR fixes the name for the json results.
Fixes #2657

metrics: Fix docker memory metric json

---

.ci/jenkins_job_build.sh
.ci/run.sh
.ci/vfio_jenkins_job_build.sh
functional/vfio/run.sh

Run teardown.sh to generate the build artifacts, making vfio CI logs
accessible from http://jenkins.katacontainers.io
fixes #2645

ci/vfio: run teadown.sh on exit

---

.ci/ci_cache_components.sh

The tests_repo variable no longer need to be defined in the script
since it is now exported by lib.sh
Fixes #2535

ci/ci_cache_components: Remove the tests_repo variable

---

.ci/lib.sh

For some dependencies we want to build a specific version, which is handled
by the build_version function in .ci/lib.sh.  It does this by creating a
new branch at the specific revision we want, then building.  However, this
new branch is left over, which means the check out will fail if we attempt
it again without manually removing the branch.
In fact, there's no real point to creating a branch: git allows us to just
checkout the commit we want directly.  That will leave the tree in
"detached HEAD" mode, which is awkward if you're developing in the tree,
but is just fine for building a dependency as we are here.
Fixes: #2650

Don't create branches when building dependencies at specific versions

---

.ci/ci_entry_point.sh

While running the ci entry point script, we have the following error that is
not possible to perform the git rebase as that should be a git checkout of
the target branch.
Fixes #2663

ci: Fix checkout for ci entry point

---

cmd/checkmetrics/history/history.sh

Recently metrics artifacts started to be collected
with teardown script, urls to  download now are
pointing to a new path.
This patch updates the paths to query if
find a valid json file will download it.
Fixes: #2666

metrics: history update query paths

---

.ci/resolve-kata-dependencies.sh

If we do rebase, it is required that every commit cannot conflict but a
merge only requires that the final code do not conflict.
Fixes: #2673

ci: resolve resulting code base by merging

---

.ci/install_runtime.sh

Trying to disable vmx-rdseed-exit on other system than x86_64 will fail
fixes #2678

ci: disable vmx-rdseed-exit only on x86_64

---

integration/popular_docker_hub_images/popular_docker_images.bats
versions.yaml

When we try to use the image oraclelinux:latest we are getting an error
saying that the manifest does not exist. This PR specifies a version of
this image which is working.
Fixes #2670

test: Use a specific oraclelinux image for popular docker images test

---

.ci/install_runtime.sh

experimental QEMU doesn't support vmx-rdseed-exit, if we try to disable it
we'll get the following error:
`qemu-virtiofs-system-x86_64: Property '.vmx-rdseed-exit' not found`
fixes #2686

ci: don't disable vmx-rdseed-exit on experimental QEMU

---

Makefile
integration/change_configuration_toml/change_configuration_toml.bats

This PR is a test where we change the machine type at the configuration toml
for an invalid one and we verify that is not possible to run a container.
Fixes #2675

test: Change the configuration toml

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml

QEMU 5 KSM memory footprint is a little bit bigger than QEMU 4,
change midval from 61380.0 to 66170.0.
fixes #2690

metrics: adjust memory KSM midval to support QEMU 5

---

integration/popular_docker_hub_images/popular_docker_images.bats
versions.yaml

The manifest of the latest image is not found, this pr fixes the mariadb
popular docker images test.
Fixes #2692

test: Fix mariadb popular docker images test

---

.ci/install_runtime.sh

Due to a bug in KVM, QEMU cpu feature vmx-rdseed-exit must be disabled
in the CI (hyperV). For more information about this issue, see
kata-containers/runtime#2355 (comment)
fixes #2553

[2.0-dev - fwport] ci: support QEMU 5.0.0

---

.ci/run.sh
integration/containerd/cri/integration-tests.sh

Reduce snap-ci build time by running only the following tests:
* docker
* crio
* shimv2
* kubernetes
fixes #2706

ci: add SNAP to the list of CI jobs

---

.ci/aarch64/lib_install_qemu_aarch64.sh
.ci/install_cloud_hypervisor.sh
.ci/install_kata_kernel.sh
.ci/install_qemu.sh
.ci/install_qemu_experimental.sh
.ci/lib.sh
.ci/ppc64le/lib_install_qemu_ppc64le.sh
.ci/resolve-kata-dependencies.sh
.ci/s390x/lib_install_qemu_s390x.sh

Now that `packaging` repo was merged into `kata-containers`,
use the new location to build kernel and qemu.
Fixes: #2700.

CI: use packaging location inside kata-containers repo

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml
metrics/storage/blogbench.sh

Enable blogbench as part of the metrics CI to measure read-write IO
performance on every pull request
fixes #2716

metrics: enable blogbench to check IO performance

---

Makefile
integration/sandbox_cgroup/check_cgroups_sandbox.sh

This test will check that certain cgroups are not present while running
a container when we have sandbox enabled.
Fixes #2695

test: Check cgroups with sandbox

---

Makefile

This PR enables conformance tests in order to run in the virtiofs CI.
Fixes #2713

tests: Enable conformance tests on virtiofs

---

metrics/storage/blogbench.sh

This PR disables dax for blogbench in order to avoid gets stuck while running virtiofs+qemu. This issue is related
with https://github.com/kata-containers/tests/issues/2717.
Fixes #2724

metrics: Disable dax for blogbench for virtiofs+qemu

---

integration/kubernetes/k8s-pid-ns.bats

This PR imporves the k8s pid test by also verifying that the first pid
container and the second pid container are not empty. This is related with
the comment that was made in https://github.com/kata-containers/runtime/issues/2788#issuecomment-657895989.
Fixes #2722

test: Improve k8s pid test

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml

This adds the limits for blogbench for read and write for the
clh+virtiofs.
Fixes #2720

metrics: Add blogbench limits for clh+virtiofs

---

integration/kubernetes/k8s-pid-ns.bats

This PR improves the k8s pid test by verifying that the pid containers
are not empty.
Fixes #2730

test: Improve k8s pid test for kata 2.0

---

.ci/static-checks.sh

For kata 2.0, checkcommits should check against 2.0-dev branch.
Fixes: #2732

test: check against 2.0-dev branch instead of master

---

README.md

This PR updates the breaking compatibility section to replace the
kata-containers/runtime repository for the kata-containers/kata-containers
repository.
Fixes #2751

docs: Update breaking compatibility sectionf in README for kata 2.0

---

.ci/teardown.sh

This PR removes getting the logs for kata-proxy and kata-shim
processes for kata 2.0 as they do not exist.
Fixes #2738

ci: Remove getting logs for kata-proxy and kata-shim for 2.0

---

.ci/install_qemu.sh
.ci/s390x/lib_install_qemu_s390x.sh

Since kata now needs support for multidevs, this PR switches from packaged qemu to custom build qemu.
Fixes #2756
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

s390x: Switch to newer qemu version

---

integration/kubernetes/k8s-expose-ip.bats
integration/kubernetes/k8s-pid-ns.bats
integration/kubernetes/k8s-pod-quota.bats
integration/kubernetes/k8s-shared-volume.bats

This PR removes the skipping of the kubernetes tests for kata 2.0
Fixes #2753

tests: Unskip k8s tests for kata 2.0

---

.ci/lib.sh

Some stale files and directorys of containerd and cni have not cleaned
up after last ci which lead to ci crash for next time on arm
as all ARM ci runs on baremental.
Fixes: #2758
@jodh-intel @devimc @GabyCT @Pennyzct

ci: clean up stale files for containerd and cni

---

.ci/teardown.sh

Gzip virtiofs log at teardown stage.
Fixes: #2763

ci: gzip virtiofs log

---

cmd/check-spelling/data/main.txt

Fixes: #2772
reason: for https://github.com/kata-containers/agent/pull/814
Signed-off-by: jiangpengfei <jiangpengfei9@huawei.com>

spellcheck: add netlink term to spellchecker

---

integration/kubernetes/k8s-custom-dns.bats
integration/kubernetes/k8s-number-cpus.bats

There is no need to use the -i option if there is no stdio.
Depends-on:github.com/kata-containers/kata-containers#440
Fixes: #2770

ci: delete -i option of kubectl exec

---

.ci/jenkins_job_build.sh

Add line for codecov execution script back for coverage reporting.
Fixes #2779

ci: Add codecov execution script back

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml

This PR enables the limits for blogbench operations like read and write for
virtiofs+qemu.
Fixes #2726

metrics: Enable blogbench limits for virtiofs+qemu

---

integration/kubernetes/runtimeclass_workloads/initContainer-shared-volume.yaml

In some case the `date +%s` may get the same value
in initContainer and normal container, use $EPOCHREALTIME
can ensure that the values are different.
Fixes: #2783

ci: add sleep in init container

---

.ci/install_runtime.sh
metrics/density/docker_memory_usage.sh

- disable vmx-rdseed-exit:  Needed to use qemu 5.0+ in azure VMs.
- Install docker all the time, needed to build cached components in podman tests
Depends-on: github.com/kata-containers/packaging#1097
Depends-on: github.com/kata-containers/runtime#2840
Fixes: #2736

ci: Fixes to build experimental QEMU with virtiofs

---

.ci/ci_entry_point.sh
.ci/install_cloud_hypervisor.sh
.ci/jenkins_job_build.sh

This PR will allow us to enable a jenkins job for the clh+virtiofs CI.
Depends-on: github.com/kata-containers/kata-containers#533
Fixes #2788

ci: Enable clh+virtiofs CI

---

metrics/storage/webtool.sh

This PR sets a different timeout to launch and verify that the webtool
container is up. This saves us some time as we previously had.
Fixes #2792

metrics: Set a timeout to launch webtool containers

---

integration/popular_docker_hub_images/popular_docker_images.bats

This PR updates the consul docker hub popular image test as the -t flag has
been removed it from the command timeout.
Fixes #2786

tests: Update consul docker integration test

---

.ci/install_runtime.sh
.ci/jenkins_job_build.sh
.ci/run.sh
integration/kubernetes/run_kubernetes_tests.sh
metrics/density/docker_memory_usage.sh

We now have a running CI for clh w/ kata 2.0, but it is failing at a very early 
stage (before starts to run tests). 
First, we are falling into the default code path in run.sh for the CLH CI,
where we are running all tests w/ 'make test'. This patch added the code
path for clh in run.sh to run k8s tests w/ containerd only.
Second, to have a functioning CI, this PR also back-ported patches from 
tests/master branch to tests/dev-2.0 branches.
Third, this PR works along with PR https://github.com/kata-containers/kata-containers/pull/543,
which back-ported related patches from kata-runtime to kata 2.0. 
Depends-on: github.com/kata-containers/kata-containers#543
Fixes: #2788

ci: Enable and fix clh CI for kata 2.0 for k8s+containerd tests

---

integration/kubernetes/k8s-exec.bats
integration/kubernetes/run_kubernetes_tests.sh
integration/kubernetes/runtimeclass_workloads/busybox-pod.yaml

Add cases for test `kubectl exec`'s options, input, and return values.
Fixes: #2765

ci: add test cases for kubectl exec command

---

.ci/lib.sh
integration/kubernetes/cleanup_bare_metal_env.sh
integration/kubernetes/init.sh

Clean stale files and directories under /run, /var/lib/ at the end
of ci build.
Cleanup iptables before "iptables-save" as stale iptables may
accumulated across ci build round after round as for the cases
where the ci run in bare metal.
Fixes: #542
@jodh-intel @devimc

ci: deep clean stale files and cleanup iptables before save

---

.ci/jenkins_job_build.sh
.ci/run.sh
Makefile
integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
integration/kubernetes/e2e_conformance/run.sh
integration/kubernetes/e2e_conformance/setup.sh
kata-webhook/deploy/webhook.yaml
kata-webhook/main.go

This PR adds a minimal set for e2e k8s tests for containerd with
shimv2 for the new rust agent 2.0
Fixes #2660

tests: Enable a minimal set for e2e k8s tests

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml

We observed the CLH metrics CI can fail with decreased memory
footprint (compared with the reference value). As we are more concerned
about the increased memory footprint, this patch loosed the checks on
the minVal by increasing the `minpercent` from `5.0` to `25.0`.
Fixes: #2808

metrics: clh: Loose the check on the minVal of memory footprint

---

.ci/install_rust.sh

There is no aarch64 musl toolchain.
Fixes: #2811

ci: fix rust install

---

.ci/hypervisors/firecracker/configuration_firecracker.yaml

Along with the development of kata in general, The vsock test is now
passing w/ firecracker.
Fixes: #2398

ci: Enable vsock_test for firecracker

---

.ci/vfio_jenkins_job_build.sh

Due to a known bug in kata-log-parser[1], the teardown process is
failing in the VFIO CI.
Add `|| true` after running teardown, this way the VFIO CI won't fail
if kata-log-parse fails.
fixes #2827
[1] - https://github.com/kata-containers/tests/issues/2570

ci/vfio: don't fail if teardown fails

---

.ci/install_rust.sh

ppc64le uses glibc implemtation of the
toolchain to install rust agent
Fixes: #2829

ppc64le: fixing rust install

---

metrics/machine_learning/tensorflow.sh

This PR adds the tensorflow benchmark for FP32 inference.
Fixes #2832

metrics: Add tensorflow benchmark for fp32

---

.ci/configure_crio_for_kata.sh

This is partially motivated by failures in https://github.com/cri-o/cri-o/pull/4165 where we expect to be able to see if we're running kata if the runtime chosen has "kata" in the runtime name.
This is also more idiomatic for how cri-o works now
Signed-off-by: Peter Hunt <pehunt@redhat.com>

crio: use drop-in file to configure kata runtime

---

.ci/configure_crio_for_kata.sh

Using cat with sudo presents problems, so use `sudo tee` instead
Fixes #2837
Signed-off-by: Peter Hunt <pehunt@redhat.com>

crio: write to config dir with sudo

---

.ci/configure_crio_for_kata.sh

when setting up crio >= 1.18.0, use drop-in configs (more idiomatic and simpler), rather
than replacing in line
Fixes #2835
Signed-off-by: Peter Hunt <pehunt@redhat.com>

[2.0] crio: use drop-in file to configure kata runtime

---

.ci/README.md
.ci/install_runtime.sh
.ci/openshift-ci/README.md
.ci/openshift-ci/buildall_install.sh
.ci/openshift-ci/cluster/configs/crio_kata.conf
.ci/openshift-ci/cluster/configs/selinux.conf
.ci/openshift-ci/cluster/deployments/daemonset_kata-installer.yaml.in
.ci/openshift-ci/cluster/deployments/machineconfig_kata_runtime.yaml.in
.ci/openshift-ci/cluster/deployments/machineconfig_selinux.yaml.in
.ci/openshift-ci/cluster/deployments/runtimeclass_kata.yaml
.ci/openshift-ci/cluster/install_kata.sh
.ci/openshift-ci/run_smoke_test.sh
.ci/openshift-ci/smoke/http-server.yaml
.ci/openshift-ci/smoke/route.yaml
.ci/openshift-ci/smoke/service.yaml
.ci/openshift-ci/test.sh

This is an initial implementation on kata-containers's side of the requirements to get it on-boarded into the OpenShift CI. On the README file added on this PR there are more detailed technical information about the openshift-ci and how the scripts/files proposed on this PR are used. On openshift-ci's side there will be needed to have https://github.com/openshift/release/pull/9009 merged too. Please, refer to that README (and the openshift-ci documentation pointers it provides) for further information.
In the issue #2527 I describe the ultimate goal with these changes which is to run e2e openshift 4 tests with latest kata-containers code. However this initial implementation provides only a smoke test suite that I used for the purpose of testing the CI code itself. So once this initial …

On-boarding Kata Containers into OpenShift CI

---

integration/docker/cpu_test.go

Remove cpuset test
This test will fail until we have appropriate CPUSet support inside the
guest. Today CPUSets are only supported on the host, and are done by
placing the entire guest into a CPUset that matches the sum of container
cpusets. This isn't reflected via nproc in the guest.

integration: update cpuset tests

---

cmd/checkcommits/checkcommits.go
cmd/checkcommits/checkcommits_test.go

strings.TrimSpace only trims leading and trailing spaces. As a result,
singleWordLine is almost always true. Change to use strings.Fields to
determine singleWordLine.
In the meantime, change defaultMaxBodyLineLength to 150. 72 is way too
small and no one is using such small terminals. Linux kernel already
extends its 80-character limit to 100 and it is just a warning not
a real limit. Since we use it as a hard limit to filter out overly large
lines, let's use a really overly large number.
Fixes: #2847

checkcommits: fix singleWordLine

---

metrics/machine_learning/Dockerfile_fp32_inference/Dockerfile
metrics/machine_learning/tensorflow_fp32_inference.sh

This PR adds the tensorflow fp32 inference benchmark, now we will be
able to launch a container with this benchmark.
Fixes #2849

metrics: Add tensorflow fp32 inference container benchmark

---

.ci/jenkins_job_build.sh
integration/kubernetes/run_kubernetes_tests.sh

This PR fixes the regression on the CLH CI in the test repo for kata 2.0 ( http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/). There are three issues being fixed: 
1. In many of our CI scripts, we assume the 'KATA_DEV_MODE' environment variable to be not set at all when we are not in the 'kata dev mode'. Setting its value explicitly to 'false' would fail the check '[-n $KATA_DEV_MODE]' and make the script believe we ARE in the 'kata dev mode', which would skip some installation. For example, 'install_rust.sh'  is totally skipped in CLH's CI, which caused rust-agent compiling failure and the CI failure. (commit https://github.com/kata-containers/tests/pull/2862/commits/26e49adb7847620224702dc730a0829c45ae0e52).
2. Failure on the new k8s test `pod OOM`. …

ci: Fix the CLH CI regression in the test repo for kata 2.0

---

.ci/static-checks.sh

Improve the license checker function to also check for a copyright
header.
Fixes: #2323.

CI: Check for copyright header

---

versions.yaml

Bump the version of `golangci-lint` to `v1.18.0` for parity with the
vesrion in `master`. The newer version is more strict.
Fixes: #2870.

versions: Update golangci-lint version to 1.19.0.

---

.ci/teardown.sh

Compress virtiofsd  logs to save space in CI.
Fixes: #2874

ci: compress virtiofsd logs

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml

We have an increment in the memory footprint maximum value as it seems that
a PR was merged where this changed was introduced. This PR fixes the metrics
CI as right now it is broken, we are incrementing the tolerance to 7%.
Fixes #2839

metrics: Increase maxpercent for memory footprint limits

---

cmd/container-manager/manage_ctr_mgr.sh

This PR enables the docker repo for centos 7 in centos 8 mainly to the lack
of the current docker version supported by kata. In the centos 8 docker
repository the only docker version that is supported is 19. With this we will have
the possibility to install docker 18.06.
Fixes #2880

ci: Fix docker installation centos 8 kata 2.0

---

.ci/install_rust.sh

Specify default toolchain version during rustup init,
so avoid to download toolchain twice.
Fixes: #2883
Signed-off-by: zhanghj <zhanghj.lc@inspur.com>

ci: specify default toolchain version during rustup init

---

cmd/container-manager/manage_ctr_mgr.sh

This PR enables docker repo for centos 7 in centos 8 mainly to the lack
of the current docker version supported by kata. In the centos 8 the
only docker version available is 19, however kata needs 18.06.
Fixes #2890

ci: Fix docker installation centos 8

---

.ci/jenkins_job_build.sh
.ci/run.sh

This PR enables the possiblity to run e2e k8s tests for clh and
containerd.
Fixes #2878

ci: Enable minimal e2e k8s tests with clh and containerd

---

.ci/install_kata_image.sh
.ci/install_qemu.sh
.ci/install_runtime.sh

Add initrd support to enable a CI job that will run the tests with initrd.

CI: Add initrd support to CI scripts

---

cmd/container-manager/manage_ctr_mgr.sh

This PR enables the possiblity to install docker 18.06 by using
the CentOS 7 repository as the latest CentOS repository has docker
19.
Fixes #2892

ci: Fix docker installation for rhel 8

---

integration/kubernetes/k8s-block-volume.bats
integration/kubernetes/runtimeclass_workloads/pod-block-pv.yaml

It is much more stable and includes e2fsprogs by default, thus
we do not have to install e2fsprogs on the fly which is not the purpose
of the test and might hit network issues.
Fixes: #2865

k8s: use ubuntu instead of alpine

---

cmd/container-manager/manage_ctr_mgr.sh

This PR enables the possiblity to install the supported docker version
in CentOS and RHEL for kata 2.0
Fixes #2898

ci: Fix docker installation for RHEL and CentOS kata 2.0

---

.ci/static-checks.sh

Patch files from other projects are not created by Kata
containers, and should not check license header in CI.
Fixes: #2904

ci: skip checking license header for patch files

---

cmd/check-spelling/data/main.txt

The spell check was missing ttRPC even though the architecture document
mentions it; add it.
Fixes #2897

spellcheck: Add ttRPC to spellcheck

---

.ci/ci-fast-return.sh

Use the special file descriptor created for messages when installing `jq(1)` and `yq(1)` to avoid polluting the standard streams and causing the fast return script to fail.
Also drops the `-E` from the `sudo(8)` call for SUSE for consistency with the other distro logic.
Fixes: #2365.

Fix fast return

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml

We observed reduced boot-time for cloud-hypervisor w/ kata from one
recent PR kata-containers/runtime#2996. It is expected as we removed
some unnecessary VMMping in the clh driver. Expecting to land the
changes in kata-runtime, we need to adjust the mival of boot time for
clh metrics.
Depends-on: github.com/kata-containers/runtime#2996
Fixes: #2911

metrics: clh: Update the 'midval' for boot time

---

.ci/aarch64/configuration_aarch64.yaml

skip k8s-oom test on ARM as it can't pass on ARM for now,
even the root cause is unknown.
Fixes: #2887
@devimc @jodh-intel

ci: skip k8s-oom test on ARM.

---

.ci/aarch64/lib_install_qemu_aarch64.sh

As obs-packaging has been removed, new patch path should be set.
Fixes: #2906
Signed-off-by: Edmond AK Dantes <edmond.dantes.ak47@outlook.com>
@jodh-intel  @jongwu  @devimc

ci: change qemu patch path for qemu build on arm64

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml
cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml

Disabling the DAX option of `virtio-fsd` has direct impact to the memory
foot-print and I/O performance. We need to adjust the expected `midval`
for our metrics CI jobs on `cloud-hypervisor` and `qemu with virtiofs`.
Depends-on: github.com/kata-containers/runtime#2997
Fixes: #2923

metrics: Update the expected midval for CI jobs using virtio-fs

---

versions.yaml

Recently we've seen CI issues on both Debian and CentOS because of
iptables > 1.8 has been causing a different set of connectivity issues.
The one CI is facing is due to a known issue with flannel*, which was
pointed out by Archana Shinde and updating flannel does solve the issue
without causing any other regression.
A huge thanks to Archana for nailing down the issue.
*: https://github.com/coreos/flannel/issues/1306
Fixes: #2910

versions: Update flannel version to v0.13.0-rc2

---

.ci/ci-fast-return.sh

Allow the CI to be skipped if the magic `force-skip-ci` label is set for a PR.
Added test for new function.
Fixes: #2914.

CI: Add ability to skip CI run in fast-return script

---

cmd/check-spelling/data/projects.txt

The [`musl`](https://musl.libc.org/) library is used for building the
rust agent for 2.0 but we don't have "musl" in the spell check dictionary.
Fixes: #2936.

spellcheck: Add "musl" to dictionary

---

.ci/configure_containerd_for_kata.sh
.ci/configure_crio_for_kata.sh

This flag should be used while running privileged containers
with Kata. Lets add this flag as certain tests are run in privileged
containers.
Fixes #2929

ci: Add flag "privileged_without_host_devices"

---

.ci/ci_entry_point.sh
.ci/jenkins_job_build.sh
.ci/run.sh
.ci/vfio_jenkins_job_build.sh
Makefile
integration/kubernetes/runtimeclass_workloads/vfio.yaml
integration/kubernetes/vfio.sh

Use kubernetes + containerd + intel/sriov-network-device-plugin to
run a kata container, hot attach a VFIO network device to check
whether it was added correctly or not.
fixes #2917

ci: add VFIO CI for kata 2.0

---

.ci/aarch64/configuration_aarch64.yaml
integration/kubernetes/run_kubernetes_tests.sh

It seems that filter_k8s_test.sh is failing to filter the last
component.
E.g., adding an extra component can make it work.
```
[witch-1@kubernetes]$../../.ci/filter/filter_k8s_test.sh
../../.ci/aarch64/configuration_aarch64.yaml "k8s-oom.bats"
k8s-oom.bats
[witch-1@kubernetes]$../../.ci/filter/filter_k8s_test.sh
../../.ci/aarch64/configuration_aarch64.yaml "k8s-oom.bats foo"
foo
```
Also mark k8s-block-volume as skipped since it is failing randomly.
Fixes: #2944

k8s: skip oom and k8s-block-volume test for aarch64

---

.ci/aarch64/configuration_aarch64.yaml
integration/kubernetes/k8s-memory.bats
integration/kubernetes/runtimeclass_workloads/pod-memory-limit.yaml

Increase the memory size to allow testing.
Depends-on: github.com/kata-containers/kata-containers#910
Fixes: #2942

k8s: enable memroy tests

---

.ci/jenkins_job_build.sh

Uncomment the crucial line to allow fast return to work on the `2.0-dev` branch as it currently does for `master`.
Also includes cherry pick of 77a968e89b535ae1b8acca19d622d36d97df942a (PR https://github.com/kata-containers/tests/pull/2653) to ensure fast return only works on PR branches. 
Fixes: #2948.

2.0 dev actually enable fast return

---

integration/netmon/netmon_test.bats

We have random failures on the netmon test on CentOS 8, this is an
issue https://github.com/kata-containers/tests/issues/2933.
Fixes #2938

tests: Skip netmon test on CentOS 8

---

integration/kubernetes/run_kubernetes_tests.sh

This patch enables the last skipping k8s integration tests for clh.
Fixes: #2324

k8s: Enable the 'sysctls' test for clh

---

.ci/static-checks.sh

Stop the license checker from looking for license headers in kernel config files.
Also ignore license header check for drawio files (effectively a cherry pick of 11ea324de4144c5dc67e9e6fe9cb5514231089c9 (which fixed #2637).
Fixes: #2960.

CI: Don't license check kernel config files

---

.ci/jenkins_job_build.sh
.ci/vfio_jenkins_job_build.sh
integration/kubernetes/vfio.sh

escape ID variable since it shouldn't be expanded in the host
fixes #2940

ci: vfio: fix VFIO CI

---

integration/kubernetes/init.sh

Kubernetes is being installed at the setup.sh script, we do not need
to installed it twice in init.sh. This PR removes the duplication
of the kubernetes installation.
Fixes #2886

ci: Remove duplication of kubernetes installation

---

.ci/configure_crio_for_kata.sh
.ci/install_crio.sh
versions.yaml

- We need to update Sonobuoy to 0.18.5 to test k8s to 1.18.9
Related: github.com/kata-containers/kata-containers#961
- Update network_ns_flag to reflect change in CRI-O v1.17. Configure flag
based on installed CRI-O version.
- We need to update how we get the value of the crio version
as the output of `crio --version` has changed since crio 1.18.0.
This change now works with new and old versions of crio.
- ci: do not use drop-in file
Found an issue when the default runtime (runc) is configured in
the main config file.
Fixes: #2957.

ci: scripts modifications to support cri-o and kubernetes 1.18

---

.ci/install_crio.sh

This PR fixes removes the git merge-base call as this is not longer needed.
Fixes #2959

ci: Fix git error in crio installation

---

integration/docker/package_manager_test.go

This PR enables the package manager test for virtiofs CI.
Fixes #2008

test: Enable package manager test for virtiofs

---

.ci/static-checks.sh

It is just a plain list.
Fixes: #2972

static-check: do not check ignore list license header

---

.ci/install_kata.sh
.ci/install_qemu.sh

So that we can use it to test virtio-fs.
Depends-on: github.com/kata-containers/kata-containers#936
Fixes: #2950

ci: install virtiofsd when installing qemu

---

.ci/aarch64/configuration_aarch64.yaml
.ci/aarch64/lib_install_qemu_aarch64.sh
.ci/ci_entry_point.sh
.ci/configure_crio_for_kata.sh
.ci/install_crio.sh
.ci/install_kata.sh
.ci/install_qemu.sh
.ci/jenkins_job_build.sh
.ci/run.sh
.ci/static-checks.sh
.ci/vfio_jenkins_job_build.sh
Makefile
cmd/check-spelling/data/projects.txt
integration/kubernetes/init.sh
integration/kubernetes/k8s-memory.bats
integration/kubernetes/run_kubernetes_tests.sh
integration/kubernetes/runtimeclass_workloads/pod-memory-limit.yaml
integration/kubernetes/runtimeclass_workloads/vfio.yaml
integration/kubernetes/vfio.sh
versions.yaml

The PR backports following commits from `2.0-dev` to `stable-2.0.0`, up to commit 5fe07fa2d9e363521ac36fa44574a23f595cab76("Merge pull request #2951 from bergwolf/install-virtiofsd"):
3328658 static-check: do not check ignore list license header
e5568ec ci: Fix git error in crio installation
0247155 ci: install virtiofsd when installing qemu
758059a ci: vfio: unskip cloud-hypervisor tests
0881d68 ci: vfio: workaround virtiofs bug
3690aa1 ci: Fix cri-o drop-in configuration file
4a7f771 ci: Remove duplication of kubernetes installation
7a4c068 ci: ignore files within kernel/configs directory
4acf8bf vfio: skip cloud-hypervisor
1ff48cc ci: vfio: fix VFIO CI
c5dd6b3 CI: ignore license header check for drawio files
4d9218f CI: Don't license check kernel config files
8372e64 ci: update the way …

Backport 2.0-dev commits to stable-2.0.0

---

.ci/openshift-ci/run_e2e_test.sh
.ci/openshift-ci/test.sh

Enable the execution of Openshift e2e tests in the OpenShift CI
Kata Containers job.
The smoke tests continue to execute. Run them first, and proceed to
the e2e tests only if passed.

ci/openshift-ci: Run the OpenShift e2e tests

---

.ci/aarch64/configuration_aarch64.yaml

tests skip info included in arch specific configuration
file doesn't pass to Makefile, which lead to ci failure.
this patch pass these info to Makefile.
Fixes: #2977
@devimc @bergwolf @dgibson

docker: cpuset case test on arm64 should be skipped

---

lib/common.bash

To overwrite the KATA_TESTS_BASEDIR variable it should be defined
another of same name, not KATA_TESTS_LOGDIR.
Fixes #2999
Backport of https://github.com/kata-containers/tests/pull/3000

lib/common.bash: Fix overwrite of KATA_TESTS_BASEDIR

---

integration/docker/docker.go

rw check on block device is enhanced in qemu 5.1. So block device should be
set to rw using blockdev before hotplug test in docker.
If not, block device hotplug test will fail.
test case:
docker run --rm --runtime kata-runtime --device /dev/loop0 ubuntu ls
more info see https://patchew.org/QEMU/20200717105426.51134-1-kwolf@redhat.com/20200717105426.51134-3-kwolf@redhat.com/
Fixes: #3002
@jodh-intel @fidencio @devimc

docker: set rw on block device before hotplug test.

---

.ci/static-checks.sh

These are pulled from other repositories.
Fixes: #3005

static-checks: ignore gogo and google proto files

---

.ci/jenkins_job_build.sh
.ci/run.sh
integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
integration/kubernetes/e2e_conformance/setup.sh
integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml

This PR enables the clh+containerd full k8s e2e testing.
Fixes #2989

ci: Enable clh+containerd k8s e2e testing

---

.ci/run_metrics_PR_ci.sh

After running the metrics tests we need to remove docker configuration file
so we have a clean environment.
Fixes #3010

ci: Remove docker file after running baremetal tests

---

integration/kubernetes/vfio.sh

Delete vfio POD after checking the net interfaces otherwise the following PODs
won't be created since there is already a POD with the same name and yaml.
Due to bug #3013 I was unable to detect that VFIO hotplug is not working with
QEMU+initrd. Let's skip these tests until we get a fix.
fixes #3013

ci: fix VFIO CI

---

.ci/vfio_jenkins_job_build.sh
integration/kubernetes/runtimeclass_workloads/vfio.yaml
integration/kubernetes/vfio.sh

set terminationGracePeriodSeconds to 0 to reduce pod deletion time
Fix warning: Error loading config file: /root/.docker/config.json.Use an empty json object `{}`.
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
fixes #3025 #3027 #3028

Fix VFIO CI

---

Makefile
functional/vfio/run.sh

This patch enables the VFIO test with qemu-virtiofs.
Fixes: #2677

ci: vfio: Enable vfio test with qemu-virtiofs

---

integration/kubernetes/k8s-copy-file.bats

k8s-copy-file.bats tests regressed after bumping CRI-O version to
v1.18.4.
This has been tracked on CRI-O side`[0]`, we already have a patch waiting
for reviews, and we should enouble this test back as soon as a new
release contains the fix.
`[0]:` https://github.com/cri-o/cri-o/issues/4353
Fixes: #3033 

k8s: Skip "k8s-copy-file" tests with CRI-O

---

integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml

Added to the list a test that requires a two node cluster.
Additionally, fixed a letter in another entry which requires
to be Uppercase.
Fixes: #3034.

k8s: Fix e2e conformance skip list for containerd

---

integration/kubernetes/init.sh

Default log level for kubelet is 2, changes it to 4 will get more detail logs.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
Fixes: #3039

ci: enable debug log for kubelet

---

Makefile
functional/vfio/run.sh

This reverts commit 5f411ed3386ee06043e929988aeedc3ea7f32b5b.
qemu + virtiofs + vfio test is failing randomly with the
following error:
```
Failed to remove paths:
map[blkio:/sys/fs/cgroup/blkio/vc/kata/kata_vfiotest ...[snip]...]
```
fixes #3043

ci: revert: vfio: Enable vfio test with qemu-virtiofs

---

.ci/teardown.sh

To save space in CI.
Fixes: #2874

backport: stable-1.11 ci: compress kata-hypervisor logs

---

.ci/teardown.sh

To save space in CI.
Fixes: #2874

backport stable-1.12: ci: compress kata-hypervisor logs

---

integration/kubernetes/vfio.sh

Don't clone k8snetworkplumbingwg/sriov-network-device-plugin using
--depth=1, otherwise `git clone` will fail if the commit version
tagged in the versions.yaml is not the latest commit in that repo.
fixes #3052

vfio: ci: don't clone with --depth=1

---

.ci/teardown.sh

To save space in CI.
Fixes: #2874

ci: compress kata-hypervisor logs

---

integration/kubernetes/k8s-copy-file.bats

This basically reverts commit ef5cda7463416997bc051b83fc87ac3100be93ae,
as the fix for this already reached CRI-O, and CRI-I version will be
bumped on the kata-containers side.
Fixes: #3041

k8s: Re-enable "k8s-copy-file" tests for CRI-O

---

integration/kubernetes/k8s-oom.bats

k8s-oom.bats has been introduced and enabled only for containerd as the
patch for CRI-O had to be backported to the correct branch.  As the
backport was done and we are bumping CRI-O dependency version for
kata-containers, we can finally enable this test also for CRI-O.
Depends-on: github.com/kata-containers/kata-containers#1117
Fixes: #2859

k8s: Enable "k8s-oom" tests for CRI-O

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml

As a result of disabling the virtio-fs DAX when using cloud-hypervisor,
the expected memory footprint of kata+clh is reduced substantially. This
PR updates the reference value of memory footprint used by our metrics
CI.
Depends-on: github.com/kata-containers/runtime#3073
Fixes: #3057

metrics: clh: Update midval for memory footprint

---

.ci/run_metrics_PR_ci.sh

Use `trap` to make sure the `teardown` function runs even
if something in the script fails earlier.
Fixes: #3036.

ci: metrics: always run teardown in run_metrics_PR_ci.sh

---

integration/kubernetes/k8s-init.bats
integration/kubernetes/runtimeclass_workloads/pod-init.yaml

This adds a k8s test to verify that init containers are not broken with k8s.
Fixes #2825

test: Add k8s test to verify init containers work

---

.ci/openshift-ci/buildall_install.sh
.ci/openshift-ci/cluster/install_kata.sh

Currently Kata Containers is built with feature selinux disabled
and the OpenShift workers are configured with SELinux on permissive
mode. This will change the build and installation so that SELinux
is on.
Fixes #3086

.ci/openshift-ci: Turn SELinux on

---

integration/kubernetes/vfio.sh

Don't clone k8snetworkplumbingwg/sriov-network-device-plugin using
--depth=1, otherwise `git clone` will fail if the commit version
tagged in the versions.yaml is not the latest commit in that repo.
fixes #3052

[backport] vfio: ci: don't clone with --depth=1

---

.ci/ci_cache_components.sh
.ci/install_kata_image.sh
.ci/openshift-ci/buildall_install.sh

Root filesystems built by the "dracut" method haven't been tested so far the way "distro"-built ones are, and corresponding build artifacts haven't been cached either.
This PR adds the required mechanism to enable this.  Starting the actual testing and caching will require a subsequent change in Jenkins CI configuration. 
Fixes  #2855
Signed-off-by: Pavel Mores <pmores@redhat.com>

ci: dracut-built rootfs testing

---

cmd/check-spelling/data/acronyms.txt
cmd/check-spelling/data/main.txt

New words we need to include: pmem, seccomp, vmm, OpenAPI.
Fixes: #3105

spellcheck: Add more words to dictionary

---

.ci/setup_env_centos.sh

CentOS decided to rename all its repos names in a minor release,
resulting in breakage in several CIs, including Kata Container's
one.
Just renaming the repo from PowerTools to powertools solves the
issue.
Reference: https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes
Fixes: #3116
Signed-off-by: Fabiano Fidêncio <fabiano@fidencio.org>

1.x | centos: PowerTools repo got renamed to powertools

---

cmd/container-manager/manage_ctr_mgr.sh

If system has docker already installed, then remove it
by also making sure docker.socket is stopped as well.
Fixes: #3103

ci: stopping docker.socket before remove package docker-ce

---

.ci/static-checks.sh

static_check_license_headers() correctly excludes *.pb.go files, which are
generated from .proto files.  However, it doesn't exclude *pb_test.go
which are also generated (from oci.proto and health.proto).  This can cause
bogus CI failures.

tests: Exclude *pb_test.go from SPDX header checks

---

.ci/setup_env_centos.sh

CentOS decided to rename all its repos names in a minor release,
resulting in breakage in several CIs, including Kata Container's
one.
Just renaming the repo from PowerTools to powertools solves the
issue.
Reference: https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes
Fixes: #3116
Signed-off-by: Fabiano Fidêncio <fabiano@fidencio.org>

2.x | centos: PowerTools repo got renamed to powertools

---

integration/containerd/cri/integration-tests.sh

On commit fa5b6af50e8382f TestContainerListStatsWithSandboxIdFilter
is skipped from cri-containerd test suite for the Cloud Hypervisor.
This test is also failing with QEMU, so skip it as well.
Fixes #2329

tests/cri-containerd: Skip TestContainerListStatsWithSandboxIdFilter with QEMU

---

integration/kubernetes/e2e_conformance/run.sh

Sonobuoy may crash on start up, then cleanup() is called and
it will try to access resources that doesn't exist. So this fixes
some failures on that function:
- e2e_result_dir "unbound variable"
- Cannot print the log file if it wasn't created
- sonobuoy status/delete can fail
This isn't going to fix #3101 , actually it is just an improvement for when the sonobuoy fail.

k8s/e2e: Make cleanup() fault tolerant

---

.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/install_runtime.sh

This pull request is meant to prepare the ci scripts for build and install Kata Containers (plus kernel, qemu, and image) in a DESTDIR. It will be necessary to on-board 2.x into OpenShift CI (likewise it was done for 1.x).
Except for the last commit (where I enable dracut based build on `install_kata_image.sh`) the others on this PR are forward-ports.

Prepare 2.x for OpenShift CI - part 1

---

integration/kubernetes/k8s-copy-file.bats
integration/kubernetes/k8s-uts+ipc-ns.bats
integration/kubernetes/runtimeclass_workloads/busybox-template.yaml

Found that with this new spec (runtimeclass_workloads/busybox-template.yaml),
the k8s-copy-file.bats is stable. Use this new spec to bring stability to the
CI while we debug the current failure.
Related:
https://github.com/kata-containers/kata-containers/issues/1227
https://github.com/kata-containers/tests/issues/3061
Fixes: #3140.

k8s: Change pod spec used in k8s-copy-file.bats

---

integration/kubernetes/k8s-cpu-ns.bats
integration/kubernetes/k8s-number-cpus.bats
integration/kubernetes/k8s-pid-ns.bats

This PR containers improvements to the kubernetes bats tests.
It is fixed:
* Issue #3134 - On k8s-cpu-ns.bats test there some checks where the variables aren't double-quoted and that can end up on "unary operator expected" like below:
17:21:33 # /tmp/bats-run-123469/bats.123514.src: line 48: [: -eq: unary operator expected
17:21:33 # pod "constraints-cpu-test" deleted
17:21:33 Failed at 86: bats "${K8S_TEST_ENTRY}"
* Issue #3135 - The `kubectl exec POD CMD` is deprecated in favor of `kubectl exec POD -- CMD` but some of our tests still use the former syntax.

integration/kubernetes: tests improvements - part 1

---

.ci/setup_env_centos.sh

In case the environment has already the extra packages repository
set, the script will fail with "too many arguments" message. Fixed
it by double-quoting the command.
Fixes #3137

.ci/setup_env_centos.sh: Fix "too many arguments" error

---

.ci/lib.sh

In .ci/lib.sh, `pgrep -d ' ' -f "${stale_process}"` will output all of the
pids in the system if "stale_process" is NULL. Then the next command -
`kill -9 $pids` will corrupt the system.
Fixes: #3141
@jodh-intel @chavafg @lifupan

ci/lib.sh: fix bug of pid match error.

---

.ci/static-checks.sh

The copyright header check in static_check_license_headers() requires
a "(C)" and a year.  Red Hat, for one, recommends to its employees omitting
both of those from copyright headers because:
* The (C) is legally redundant with the word "Copyright"
* The years are difficult to keep up to date and unnecessary
In order to allow copyright headers as recommended by Red Hat (and maybe
others), make static_check_license_headers() less picky.

tests: Make copyright header check less picky

---

.ci/jenkins_job_build.sh
.ci/run.sh

In the saga to achieve tests-parity between containerd and CRI-O, let's
enable the minimal kubernetes-e2e tests to run also with CRI-O.
The main difference here between the containerd job is that this job is
running on a Fedora system, instead of using an Ubuntu one.
Fixes: #3075
(cherry picked from commit f2de04635fd1d8109dd4f0a824795f847b5e5788)

ci: Enable minimal kubernetes-e2e tests with CRI-O

---

.ci/openshift-ci/build_install.sh
.ci/openshift-ci/cluster/configs/crio_kata.conf
.ci/openshift-ci/cluster/configs/selinux.conf
.ci/openshift-ci/cluster/deployments/daemonset_kata-installer.yaml.in
.ci/openshift-ci/cluster/deployments/machineconfig_kata_runtime.yaml.in
.ci/openshift-ci/cluster/deployments/machineconfig_selinux.yaml.in
.ci/openshift-ci/cluster/deployments/runtimeclass_kata.yaml
.ci/openshift-ci/cluster/install_kata.sh
.ci/openshift-ci/images/Dockerfile.installer
.ci/openshift-ci/images/entrypoint.sh
.ci/openshift-ci/qemu-build-pre.sh
.ci/openshift-ci/run_smoke_test.sh
.ci/openshift-ci/smoke/http-server.yaml
.ci/openshift-ci/smoke/service.yaml
.ci/openshift-ci/test.sh

This is the continuation of part 1 (https://github.com/kata-containers/tests/pull/3102) towards getting Kata Containers 2.x on-board into OpenShift CI.
This PR add scripts and files to build and install Kata in a Openshift cluster as well as run a smoke test. Most of the commits are forward-ports (simple cherry-pick and squash).

Prepare 2.x for OpenShift CI - part 2

---

Makefile
README.md

This PR updates the README file with the current tests that we have for
kata 2.0 as well as it removes the sections that currently are not working
with kata 2.0. This PR also modifies the Makefile to make it more consistent
with the README and the current tests that are working with kata 2.0
Fixes #3156

tests: Update instructions for running tests for kata 2.0

---

.ci/install_runtime.sh

The .ci/install_go.sh script is going to install go into /usr/local/go/bin. If
I have (or some script) exported PATH as PATH=/usr/local/go/bin:$PATH and run
.ci/install_runtime.sh it isn't guaranteed it will pick up that golang version to
build the runtime.  That happen because whether `sudo -E` will preserve PATH or not
depend on how sudoers security policy was configured. Thus, the script was changed
to pass PATH explicitly in the sudo's call.
Fixes #3174 

ci/install_runtime: export PATH on sudo env properly

---

Makefile
integration/stability/hypervisor_stability_kill_test.sh
lib/common.bash

This PR updates the hypervisor stability test to work with ctr.
Fixes #3166

tests: Enable hypervisor stability kill test

---

.ci/openshift-ci/build_install.sh
.ci/openshift-ci/cluster/install_kata.sh
.ci/openshift-ci/qemu-build-pre.sh

This is the continuation of part 1 (https://github.com/kata-containers/tests/pull/3102) and part 2 (https://github.com/kata-containers/tests/pull/3139) towards getting Kata Containers 2.x on-board into OpenShift CI.
Here I fixed some issues found while running the scripts on the CI environment.

Prepare 2.x for OpenShift CI - part 3

---

.ci/ci_entry_point.sh
.ci/lib.sh
.ci/static-checks.sh
README.md
cmd/pmemctl/pmemctl.sh

So that we can rename the default branch to main.
Fixes: #3181
Depends-on: github.com/kata-containers/kata-containers#1311
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
Signed-off-by: Fabiano Fidêncio <fabiano@fidencio.org>

ci: rename 2.0-dev to main

---

.ci/setup_env_ubuntu.sh

Seems that our ubuntu images are broken due to:
```
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
linux-headers-5.10.0-051000-generic : Depends: linux-headers-5.10.0-051000 but it is not installable
linux-headers-5.10.0-051000-generic-64k : Depends: linux-headers-5.10.0-051000 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Failed at 18: sudo -E apt install -y moreutils
```
One possible way to solve this is preemptively doing an:
`apt --fix-broken install`
Fixes: #3177

ubuntu: Preemptively do an 'apt --fix-broken install'

---

.ci/openshift-ci/smoke/http-server.yaml
.ci/openshift-ci/test.sh

This is the continuation of part 1 (https://github.com/kata-containers/tests/pull/3102), part 2 (https://github.com/kata-containers/tests/pull/3139)  and part 3 (https://github.com/kata-containers/tests/pull/3175) towards getting Kata Containers 2.x on-board into OpenShift CI.
The important fix is regarding set SELinux to permissive mode, with this I hope to have the last change in place to allow build, install and run a single smoke test on OpenShift CI. The other change is just a bonus.

Prepare 2.x for OpenShift CI - part 4

---

.ci/run.sh
integration/pmem/pmem_test.sh

This PR adds the pmem integration test to run in the containerd CI. Also, it checks that ctr processes are not
running in order to properly clean the environment.
Fixes #3191

tests: Modify pmem integration test

---

.ci/jenkins_job_build.sh

Some jobs already use vanilla qemu and kernel. Lets
use vanilla in all jobs to make consistent the testing.
Depends-on: github.com/kata-containers/kata-containers#1302
Fixes: #3171

[2.0]ci: Not use experimental kernel and qemu

---

.github/workflows/main.yml

This PR updates the ubuntu version from 18.04 to 20.04 that is being
used in the github actions.
Fixes #3197

github: Update ubuntu version

---

.ci/jenkins_job_build.sh

This variable is used to enable shimv2 for some tests,
shimv2 is default in kata 2.0, lets document it and
make it explicit at init.
Fixes: #3194

ci: Init and document SHIMV2_TEST envvar.

---

.ci/static-checks.sh

License header should not be checked for kernel configs.
The path of checking excluding term "tools/packaging/kernel/configs/*"
is for kata 2.x and is pointless in packaging 1.x. So correct it here.
Fixes: #3189
@jodh-intel @GabyCT

static_check: bypass license check for kernel configs

---

cmd/checkmetrics/history/history.sh

This PR updates the history tool in order to gathered the metrics
results from the kata containers 2.0 jenkins jobs.
Fixes #3213

tests: Update history tool to use the proper jenkins jobs

---

README.md

Now that we have a metrics CI in kata 2.0, we should include that we
are supporting metrics in the README documentation.
Fixes #3219

docs: Include metrics tests in the README

---

.ci/install_kata.sh
.ci/install_kata_kernel.sh
.ci/install_qemu_experimental.sh
.ci/install_runtime.sh
.ci/jenkins_job_build.sh
.ci/run.sh
cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml
config.go

Create a virtiofs job to explicitly export
variables for virtiofs testing, like qemu, kernel,
and test to run.
Add a variable shared_fs to define what shared fs will be used
virtiofs could run even witout qemu_experimental.
Fixes: github.com/kata-containers/runtime#3083
Depends-on: github.com/kata-containers/runtime#3122
Depends-on: github.com/kata-containers/packaging#1190

ci: Move to stable virtiofs

---

cmd/history/history.sh

This PR updates the history script to use kata-containers and tests
repository for kata 2.0 as the others are not longer valid.
Fixes #3227

tests: Update history script to use the proper repos for kata 2.0

---

kata-webhook/Dockerfile

Before one can build the container image the vendor directory from the
parent directory has to be copied to the kata-webhook directory.
Otherwise the build will fail because it can't find all necessary
packages. See issue https://github.com/kata-containers/tests/issues/2479
This is solved on the master branch for Kata 1.x by adding a manual step
to the README.md.
We can avoid this manual step  by copying in the vendor directory during
the docker build.
The vendor directory is ~28 megs and it takes less than a second to copy
it into the build env, so no noticeable slow down.
When this is accepted I can send a similar PR for the master branch.
Fixes: #3230
Signed-off-by: Jens Freimann <jfreimann@redhat.com>

kata-webhook: simplify building kata-webhook container

---

README.md

This PR updates the url for the versions database in order to use
the kata 2.0 url.
Fixes #3233

docs: Update url for the versions database

---

cmd/checkversions/checkversions.sh

This PR updates the checkversions script to use the kata-containers
repository for kata 2.0
Fixes #3231

test: Update checkversions script to use kata-containers repository

---

integration/kubernetes/vfio.sh

Make sure the container in the POD is up and running before
checking its MAC addresses.
fixes #3236

ci: vfio: wait for container to be ready before checking MACs

---

integration/docker/cpu_test.go

As we are fixing the `--cpuset-cpus` support in kata with
docker (kata-containers/runtime#3138), it exposes the `cpuset-cpus test`
is actually not testing the expected behavior of kata. By design, Kata
does not constrain the guest vCPUs at all, because we don't track the
mappings between guest vCPU and host CPUs. As a result, we are always
allowing containers to use all onlined vCPUs in the guest. The current
cpuset-cpus assumes the guest cgroups constrain the vCPU in the exactly
same way as the CPUs are constrained on the host. That is wrong.
This patch adjusts the `cpuset-cpus test` to respect the actual behavior
of kata with `docker --cpuset-cpus`.
Depends-on: github.com/kata-containers/runtime#3138
Fixes: #3241

test: docker: Adjust the `cpuset-cpus test`

---

.ci/jenkins_job_build.sh
.ci/run.sh

This PR enables the clh+crio kata 2.x kubernetes testing.
Fixes #2997

ci: Enable clh+crio kata 2.x testing

---

.ci/hypervisors/firecracker/configuration_firecracker.yaml

As we fixed the CPU constraints docker tests in #3242, the firecracker
CI is now failing on this test as expected as firecracker is missing the
CPU hotplug functionality. Let's skip the `CPU constraints` docker tests
along with all other CPU related tests in firecracker CI.
Fixes: #3250

ci: Disable the `CPU constraints` docker tests for firecracker

---

cmd/github-labels/labels.yaml.in

This PR updates the related label to use the proper repository
for kata 2.0
Fixes #3248

labels: Update related label to use kata 2.0

---

.ci/static-checks.sh

This PR changes the branch from master to main in order to test kata 2.0
Fixes #3258

static-check: Change branch to main for kata 2.0

---

.ci/setup_env_ubuntu.sh

The ninja-build package is needed on Ubuntu for building QEMU 5.2
onward.
Fixes #3263

ci: Install ninja-build package on Ubuntu

---

.ci/static-checks.sh

Added tools/packaging/qemu/default-configs directory to the list
of exclusions for the license header checker.
Fixes #3275

static-checks: Do not inspect default-configs of QEMU

---

versions.yaml

This PR updates the version yaml to use the proper repositories
for kata 2.0
Fixes #3279

versions: Update versions yaml to use kata 2.0

---

.ci/run.sh
integration/vcpus/default_vcpus_test.sh

This PR modifies the vcpu test to use ctr in order to be
supported in kata 2.0
Fixes #3283

test: Modify vcpu test to use ctr

---

.ci/openshift-ci/cluster/deploy_webhook.sh

The deploy_webhook.sh script builds and deploy the kata-webhook in
the OpenShift test cluster.
Fixes #2527

openshift-ci: Add script to build and deploy the webhook

---

.ci/openshift-ci/build_install.sh

Until now the openshift-ci CI job was testing Kata Containers with the
9p shared fs backend because the version 5.0 of QEMU have a bug which
prevents virtiofsd from working properly on OpenShift. With the recent bump
on the version (5.2) of QEMU, it is now possible to test with the virtio-fs
backend instead.
Fixes #3299

openshift-ci: Enable the virtio-fs backend

---

.ci/static-checks.sh

It's better to output the details onto the log about
the rustfmt check, such it's better for developers to know
which files needed to be formated.
Fixes: #3294
Signed-off-by: fupan.lfp <fupan.lfp@antfin.com>

static: rustfmt check output the details on the files

---

.ci/install_firecracker.sh
.ci/setup.sh
cmd/container-manager/manage_ctr_mgr.sh

Kata Containers 2.x doesn't do any tests using Docker itself, as it's
support has been removed.  Knowing this, we still rely on docker, but
only as "users", allowing us to be way less opinionated about the
package version (as, for instance, we don't require devicemapper support
for that).
Fixes: #3271

[2.x] Don't use a specific version of Docker

---

integration/vcpus/default_vcpus_test.sh

This PR skips the vcpu test on intird as we have seen random
instabilties.
Fixes #3303

test: Skip vcpu test for initrd due to instabilities

---

.ci/run.sh
.ci/toggle_sandbox_cgroup_only.sh
integration/sandbox_cgroup/sandbox_cgroup_test.sh

This PR enables the sandbox cgroup test for kata 2.0 in order to use
ctr stability tests instead of docker integration tests.
Fixes #3291

test: Enable sandbox cgroup test for kata 2.0

---

metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-daemonset.yaml
metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-service.yaml

This PR modifies the iperf3 bandwith test to use k8s for kata 2.0,
as we currently we do not support docker.
Fixes #3301

metrics: Modify iperf3 bandwith test to use k8s for kata 2.0

---

.ci/setup_env_centos.sh

Fix various issues to be able to run `jenkins_job_build.sh` on centos 8. Right now, I hardcoded the docker version, until we decide which is the right one to pick. For more details check  #3245
cc @fidencio

ci: fix scripts for centos 8

---

integration/stability/hypervisor_stability_kill_test.sh

To avoid the failure of using docker images due to the pull limits,
this PR updates the image to use for the test.
Fixes #3323

test: Update image for the stability test for kata 2.0

---

.ci/jenkins_job_build.sh
.ci/run_metrics_PR_ci.sh
cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh

This PR enables the iperf3 bandwidth test for the metrics CI.
Fixes #3320

metrics: Enable iperf3 bandwith test

---

.ci/install_crio.sh
integration/cri-o/cri-o.sh

CRI-O tests have been constantly failing on 1.x, and it seems to be due
to using devicemapper as the storage driver.
Fixes: #3330

cri-o: Stop using devicemapper with CRI-O

---

.ci/teardown.sh

- Background
At the teardown phase, the log collection will split log files by size 5M,
this is the original log file size, after gzipped, the file size may be only 300k.
- Problem
In some cases of failings, there will be too many log files.
- How to fix
Increasing log split size from 5M to 50M should decrease the final log file count.
Fixes: #3328
Signed-off-by: bin liub <bin@hyper.sh>

ci: Increasing log file split size to reduce log files count

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-kata-metric3.toml

This PR defines a new memory footprint limit value for kata 1.x
Fixes #3335

metrics: Define new memory footprint value for kata 1.x

---

.ci/lib.sh
integration/kubernetes/k8s-attach-handlers.bats
integration/kubernetes/k8s-copy-file.bats
integration/kubernetes/k8s-custom-dns.bats
integration/kubernetes/k8s-pid-ns.bats
integration/kubernetes/k8s-security-context.bats
integration/kubernetes/k8s-shared-volume.bats
integration/kubernetes/k8s-sysctls.bats

This PR introduces waits for pods to be ready in some k8s integration
tests as they fail randomly.
Fixes #3337

tests: Wait for the pods to be ready

---

.ci/install_kata_kernel.sh
.ci/install_qemu.sh
.ci/install_qemu_experimental.sh
.ci/install_runtime.sh
.ci/jenkins_job_build.sh
.ci/run.sh
Makefile
conformance/posixfs/fstests.sh

Today kata containers uses qemu vanilla, but some new features  for virtiofs maybe helpful for some users or even to identify potencial issues with virtiofs new features.  Enable a job that  runs experimental virtiofs.
- Add new VIRTIOFS-EXPERIMENTAL job
- Enable posix filesystem test
Depends-on: https://github.com/kata-containers/kata-containers/pull/1422

Enable: Experimental virtiofs testing

---

.ci/install_rust.sh

s390x uses a glibc Rust target since musl is not available, therefore, a GNU target should be added on s390x when installing Rust.
Fixes: #3159

ci: Do not install musl Rust target for s390x

---

.ci/.golangci.yml

Per https://github.com/golang/lint/blob/master/README.md
```
The suggestions made by golint are exactly that: suggestions. Golint is
not perfect, and has both false positives and false negatives. Do not
treat its output as a gold standard. We will not be adding pragmas or
other knobs to suppress specific warnings, so do not expect or require
code to be completely "lint-free". In short, this tool is not, and will
never be, trustworthy enough for its suggestions to be enforced
automatically, for example as part of a build process
```
So the official readme is telling us not to include it in a build process. Let's follow its suggestion...

ci: drop golint

---

integration/kubernetes/k8s-oom.bats

This PR skips the k8s oom test in order to get other PRs
to land.
Fixes #3354

tests: Skip k8s oom test to unblock CI

---

Makefile

cloud hypervisor is not stable,
see https://github.com/kata-containers/kata-containers/issues/1488
fixes #3359

ci: vfio: skip cloud hypervisor

---

.ci/openshift-ci/qemu-build-pre.sh

The commit e221c45d7a on kata-containers/kata-containers unified the
qemu's version and tag fields on versions.yaml. Now the version field
should be the only used, and currently it points to v5.2.0. So this
change is to adapt the qemu-build-pre.sh script properly.
Fixes #3357

ci/openshift-ci: Fix qemu_version on qemu-build-pre.sh

---

.ci/install_kata_kernel.sh

Moving to linux 5.10.x breaks ARM CI. Allow
ARM CI keep using 5.4.x based kernel.
Fixes: #3362
Depends-on: github.com/kata-containers/kata-containers#1540

ci: arm: Use 5.4.x kernel tag, until 5.10.x is fixed.

---

cmd/checkmetrics/history/history.sh

This PR updates the history tool for metrics in kata 2.0 to use
the proper json files that are being generated in the metrics CI
at the artifacts.
Fixes #3364

metrics: Update history tool for metrics kata 2.0

---

integration/kubernetes/k8s-oom.bats
integration/kubernetes/runtimeclass_workloads/pod-oom.yaml

Let container run more longer, and if fails, get the pod full YAML spec.
Fixes: #3348
Signed-off-by: bin liub bin@hyper.sh

kubernetes: change OOM test parameter to ensure it will be success

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-clh-baremetal-kata-metric3.toml

The metrics CI on cloud-hypervisor for kata 1.x is now broken because of
increased memory footprint. A similar issue on metrics CI for qemu was
also reported recently in issue #3335. Following the fix/work-around on
the qemu+kata 1.x metrics CI (PR #3336), we will need to update the mid-val
of reference memory footprint for cloud-hypervisor w/ kata 1.x. This
patch increase mid-val for cloud-hypervisor by 22.5% which is the same
increase percentage on qemu's metrics CI.
Fixes: #3379

metrics: clh: Update the midval for memory footprint for kata 1.x

---

.ci/install_yq.sh

Since the resolution of https://github.com/mikefarah/yq/issues/502, the `yq` binary is no longer broken on s390x. This is an upgrade to the latest v3 version of yq (v4 has new syntax).
Fixes: #3157

Upgrade to yq 3.4.1

---

.ci/install_qemu.sh
.ci/s390x/lib_install_qemu_s390x.sh

- Originally, QEMU was preferrably to be installed from a distro package
on s390x because configure-hypervisor.sh was not yet ported (see
#1130). Since https://github.com/kata-containers/packaging/pull/333
fixed this, QEMU should be built from source on s390x as well.
- Remove s390x-specific build_and_install_qemu to ease maintenance
e.g. to enable patches
Fixes: #3381
This aids the enablement of virtio-fs support on s390x (see https://github.com/kata-containers/kata-containers/issues/1469) since the required QEMU 5.2.0 is generally not packaged.
/cc @jschintag 
Backport required.

ci/s390x: Build QEMU from source

---

integration/kubernetes/k8s-liveness-probes.bats
integration/kubernetes/k8s-memory.bats

This PR introduces waits for pods to be ready in some k8s integration
tests in order to be ready in order to avoid random failures.
Fixes #3392

tests: Introduce more time for the pods to be ready in k8s

---

.ci/install_kata_kernel.sh

As the bug in kernel 5.10.x on arm64 is fixed, remove the
special kernel version tag for arm64.
Fixes: #3387
Depends-on: github.com/kata-containers/kata-containers#1597
Change-Id: I2d1e33cb9e77a577a86323dfe814ef829a7b54d5
@jcvenegas @GabyCT

kernel: get kernel version arch-indepently.

---

integration/kubernetes/k8s-cpu-ns.bats
integration/kubernetes/k8s-empty-dirs.bats
integration/kubernetes/k8s-parallel.bats
integration/kubernetes/k8s-projected-volume.bats

This PR introduces waits for pods to be ready in some unstable k8s tests.
Fixes #3398

tests: Introduce more time for the pods to be ready in unstable k8s

---

.ci/openshift-ci/build_install.sh
.ci/setup_env_centos.sh

This contain the changes required to switch the build root on OpenShift CI from CentOS 7 to 8. Thus, it fixes #3389.

openshift-ci: build kata containers on CentOS 8

---

.ci/run.sh
Makefile
integration/ksm/ksm_test.sh

This PR updates the ksm test to use ctr for kata 2.0, this test runs
two containers and waits for the KSM to settle down and then checks
the merged pages count is increasing.
Fixes #3394

test: Update ksm test to use ctr for kata 2.0

---

integration/kubernetes/k8s-empty-dirs.bats
integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml

Added a test case to reproduce the error in k8s e2e test:
[sig-storage] EmptyDir volumes when FSGroup is specified [LinuxOnly] [NodeFeature:FSGroup] new files should be created with FSGroup ownership when container is non-root

k8s: Add empty dir when FSGroup is set test 

---

kata-webhook/README.md
kata-webhook/create-certs.sh
kata-webhook/deploy/webhook.yaml
kata-webhook/main.go

kata-webhook currently works with hardcoded RuntimeClass name kata.
If the k8s cluster is configured with other RuntimeClasses, such as
kata-clh or kata-qemu, the webhook will not work.
With this change, the webhook will be able to get the name of the
RuntimeClass from an environment variable so that you can specify
other values.
Updated documentation for this new change.
Fixes: #3415.

kata-webhook: Use env var to change runtimeclass name

---

.ci/install_crio.sh

Since https://github.com/cri-o/cri-o/issues/4506 got merged, CRI-O
default config file is empty, unless use explicitly generate it with
`crio config --default`.
Fixes: #3423

1.x | ci: Fix broken CRI-O CI due to empty crio.conf

---

cmd/checkmetrics/ci_slaves/checkmetrics-json-virtiofs-baremetal-kata-metric3.toml

This PR updates the memory value for virtiofs metrics CI as currently
is failing. It seems that this update is related with issue
github.com/kata-containers/tests/issues#3404.
Fixes #3429

metrics: Update memory value for virtiofs metrics CI

---

metrics/storage/blogbench.sh

This PR enables DAX while we are running blogbench when we
are using virtiofs.
Fixes #2717

metrics: Enable DAX for blogbench using virtiofs

---

.ci/jenkins_job_build.sh

Codecov is currently not configured for 2.x branches, and we are
currently discussing which tools we want to use fore code coverage.
In the meantime, it doesn't make sense to run this script.
Fixes: #3435.

CI: remove codecov execution

---

.ci/install_kata_image.sh
.ci/install_kata_kernel.sh
.ci/install_runtime.sh

c5c1e957 ci: Add dracut support for install_kata_image.sh
701152e5 ci: Make install scripts to use the DESTDIR variable

backport fixes for stable-2.0

---

.ci/install_yq.sh

In more recent versions of `yq`, the binary is no longer broken on
s390x. This is an upgrade to the latest v3 version of yq (v4 has new
syntax). This is a forward-port of https://github.com/kata-containers/tests/pull/3158.
Fixes: #3418

[forward-port] ci: Upgrade to yq 3.4.1

---

integration/kubernetes/k8s-empty-dirs.bats
integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml

This adds the test case where the emptyDir volume is stored on memory;
likewise the mounted point and any created files should be owned
by the GID specified on the security context fsGroup.
Fixes #3409

k8s: New case for empty dir when FSGroup is set test

---

integration/ksm/ksm_test.sh

This PR skips KSM tests on ARM CI as it seems that is not
working properly.
Fixes #3438

test: Skip KSM tests on ARM CI

---

.ci/aarch64/install_rom_aarch64.sh
.ci/install_runtime.sh

Port [1] here.
run "ENABLE_ARM64_UEFI=true .ci/install_runtime" to install UEFI rom
on arm64, then you can start kata-container with ACPI enabled.
Fixes: #1706
[1] https://github.com/kata-containers/tests/pull/3151
@jodh-intel @GabyCT

.ci/aarch64: Add UEFI rom installation helper for qemu/arm64

---

.ci/install_crio.sh

This PR excludes the  btrfs-tools or btrfs-progs-devel package that
seems to be needed to build CRI-O or containerd in RHEL CI.
Fixes #3445

ci: Fix RHEL CI when building CRI-O

---

.ci/run_metrics_PR_ci.sh
metrics/time/launch_times.sh

ubuntu image was removed from `mirror.gcr.io` registry,
change to fedora image and pull it from its official registry.
fixes #3443

ci: metrics: change image used to test boot time

---

integration/kubernetes/k8s-empty-dirs.bats
integration/kubernetes/k8s-scale-nginx.bats
integration/kubernetes/nginx.bats
integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml
lib/common.bash

The "Empty dir volume when FSGroup is specified with non-root" test
has randomically failed. Let's prefetch the agnhost image to try
to avoid timeout waiting for the pod to come up.
Fixes #3449

k8s: Prefetch image on emptyDir test

---

integration/kubernetes/k8s-pod-quota.bats

This PR allows more time to check the pod-quota k8s deployment
as we have seen random failures in checking if the deployment
is ready.
Fixes #3452

test: Allow more time to check pod-quota deployment

---

.ci/setup_env_ubuntu.sh

To be fair, this is also a CRI-O dependency and later on we should
explore using buildtags based on installed packages (rather than
explicitly defining those).
Fixes: #3456

ubuntu: Install btrfs-progs as containerd dependency

---

integration/kubernetes/k8s-empty-dirs.bats
integration/kubernetes/k8s-expose-ip.bats
integration/kubernetes/k8s-liveness-probes.bats
integration/kubernetes/runtimeclass_workloads/deployment-expose-ip.yaml
integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml
integration/kubernetes/runtimeclass_workloads/pod-http-liveness.yaml
integration/kubernetes/runtimeclass_workloads/pod-tcp-liveness.yaml
versions.yaml

This is a refactor on some kubernetes integration tests to ensure they
rely on the same version of the agnhost image. It was added a new
entry on versions.yaml to record the exact image's name and version.
Fixes #3455

k8s: Use the same agnhost image version

---

cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml

This PR fixes the boot time baseline as it seems that we are getting
less boot time as we changed the test image.
Fixes #3459

metrics: Fix boot times metrics baseline

---

.ci/run_metrics_PR_ci.sh
cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml

This PR removes iperf3 metrics as it seems that kubernetes is not
cleaning properly the environment.
Fixes #3475

metrics: Remove iperf3 due to issues with kubernetes

---

.ci/openshift-ci/images/Dockerfile.installer
.ci/setup_env_centos.sh
Makefile

I don't think it makes sense to maintain the CI scripts for CentOS 7, so I propose its removal on this PR. While ago @fidencio sent a similar PR but at that time I was using CentOS 7 to build kata on openshift-ci; recently I changed it to use CentOS 8 which allow us now to proceed with the removal.

CI: Remove CentOS 7 support

---

.ci/setup_env_ubuntu.sh

This PR adds libbtrfs-dev as a containerd dependency as it is also
needed to build properly containerd in Ubuntu 20.04
Fixes #3461

ci: Add libbtrfs-dev as a containerd dependency in Ubuntu

---

.ci/install_kata_kernel.sh

Today I created two jobs on CI to nightly build either vanilla and experimental kernels:
http://jenkins.katacontainers.io/job/kata-containers-2.0-kernel-experimental-x86_64-nightly
http://jenkins.katacontainers.io/job/kata-containers-2.0-kernel-vanilla-x86_64-nightly
It is using the same mechanism and scripts as used with kata 1.x. So basically on this PR I am only adjusting urls.

ci: Use cached kernels

---

.ci/install_kata_kernel.sh
.ci/run_metrics_PR_ci.sh
cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
integration/kubernetes/k8s-credentials-secrets.bats
integration/kubernetes/k8s-exec.bats
integration/kubernetes/k8s-number-cpus.bats
integration/kubernetes/k8s-volume.bats
metrics/time/launch_times.sh

This PR contains the first round of backports we need for the stable-2.1 branch and that would be really beneficial to have those merged before the 2.1.0 release.
Those are:
https://github.com/kata-containers/tests/pulls?q=is%3Apr+is%3Aclosed+label%3Amissing-backport-to-stable-2.1.0

stable-2.1: First round of backports

---

README.md

As we still didn't get CRI-O unit tests to run against shimv2, we
removed those from our tree as part 816aee4. However, we left some
documentation behind and that will break the static check.
Fixes: #3505

readme: Remove reference to cri-o unit tests

---

.ci/install_kubernetes.sh
integration/containerd/cri/integration-tests.sh
integration/kubernetes/init.sh

Currently, before containerd integration test, containerd service is
stopped., which will disable docker service. Then, the TestImageLoad
will fail for it depends on docker service.
Here, we restart docker before containerd test to avoid that failure.
But these tests have been working well for years. I can't tell why it
is.
Fixes: #3478
Signed-off-by: Jianyong.wu <jianyong.wu@arm.com>

ci: workaround to fix arm ci failure on behalf of containerd and k8s test

---

.ci/lib.sh
.ci/static-checks.sh
README.md
cmd/github-labels/labels.yaml.in
cmd/pmemctl/pmemctl.sh
versions.yaml

This commit forces all the checks and references to point to stable-2.1
branch rather than pointing to `main`.  This will guarantee that changes
done on `main` won't affect the testing of this specific branch.

ci: Refer to stable-2.1 branch on stable-2.1 branch

---

.ci/setup_env_ubuntu.sh

This PR adds libbtrfs-dev as a containerd dependency as it is also
needed to build properly containerd in Ubuntu 20.04
Fixes #3461
(cherry picked from commit 1f3c4cdd29d5eb193dd1c231aacee426dc37ab75)

stable-2.1 | ci: Add libbtrfs-dev as a containerd dependency in Ubuntu

---

integration/kubernetes/init.sh

While using the init.sh script to setup a local dev environment, I've found
that the cri runtime service was not enabled, and I had to re-start it on
reboots.
Enabling it makes sure it is always available.
Fixes #3519

k8s: enable cri runtime service rather than start it

---

.ci/install_kubernetes.sh
.ci/ppc64le/lib_install_qemu_ppc64le.sh
integration/containerd/cri/integration-tests.sh
integration/kubernetes/init.sh

This contains two backports:
**ci: updates to kata setup scripts for ppc64le**
- kubenetes package installation for ppc64le
- virtiofsd installation
Fixes: #3185
Signed-off-by: Jing Wang <jing.wang4@ibm.com>
(cherry picked from commit 0febfe00f8c8bbfc45ce27ec852320a698aef1ad)
**ci: workaround to fix arm ci failure.**
Currently, before containerd integration test, containerd service is
stopped., which will disable docker service. Then, the TestImageLoad
will fail for it depends on docker service.
Here, we restart docker before containerd test to avoid that failure.
But these tests have been working well for years. I can't tell why it
is.
Also do cleanup before k8s initialization to avoid lots of bizarre
issues.
for example:
1. [ERROR Port-10250]: Port 10250 is in use
2. Unfortunately, an …

stable-2.0 | Backport fixes for ARM & PPC

---

.ci/install_kubernetes.sh
integration/containerd/cri/integration-tests.sh
integration/kubernetes/init.sh

Currently, before containerd integration test, containerd service is
stopped., which will disable docker service. Then, the TestImageLoad
will fail for it depends on docker service.
Here, we restart docker before containerd test to avoid that failure.
But these tests have been working well for years. I can't tell why it
is.
Also do cleanup before k8s initialization to avoid lots of bizarre
issues.
for example:
1. [ERROR Port-10250]: Port 10250 is in use
2. Unfortunately, an error has occurred:
timed out waiting for the condition
Fixes: #3478
(cherry picked from commit d7ca6409275b88ef12fad30ec7c8c188e8766f47)

stable-2.1 | ci: workaround to fix arm ci failure.

---

integration/containerd/cri/integration-tests.sh

Add TestContainerMemoryUpdate to test the memory update function with
or without virtio-mem.
Fixes: #3508

containerd/cri/integration-tests.sh: Add TestContainerMemoryUpdate

---

.ci/setup.sh

Removes existing k8s+crio config during setup to ensure k8s will not use crio when running a containerd test.
Fixes #3480
Signed-off-by: MatthieuSarter matthieu.sarter@ibm.com

ci: remove existing k8s+crio config before seting up new config

---

integration/containerd/cri/integration-tests.sh

Add TestContainerMemoryUpdate to test the memory update function with
or without virtio-mem.
Fixes: #3508
Back porting from https://github.com/kata-containers/tests/pull/3509

[2.1] containerd/cri/integration-tests.sh: Add TestContainerMemoryUpdate

---

.ci/ci_cache_components.sh
.ci/install_qemu.sh
.ci/lib.sh

his changed the installer script to fetch and install a built QEMU
if a suitable version is found on the project's Jenkins.
To detect changes that would flag a cache mismatch it is employed
a simple algorithm to generate a SHA-256 from the files and scripts
used to build QEMU. The cached and current sha-256 is compared to
determine whether or not use the cached asset.
Fixes #3119

CI: Use cached QEMU

---

integration/kubernetes/k8s-sysctls.bats

This reverts commit 1e89be5d9f1b25395dd9b4e5c227f8a089abf6d0.
Depends-on: github.com/kata-containers/kata-containers#1844
Fixes: #3523

kubernetes: Reenable "Setting sysctl" test with CRI-O"

---

.ci/ci_cache_components.sh
.ci/install_qemu.sh
.ci/lib.sh
.ci/setup.sh
integration/kubernetes/k8s-sysctls.bats

Folks, this is the last round of backports before getting 2.1.0 out, and it includes:
* One backport related to removing cri-o configuration for kubelet, in case of running a baremetal CI that would have to deal with both cri-o and containerd
d390f57955fc74f74c74e5b8ae5b778f5e1c33a8 ci: Removes existing k8s+crio config during setup
* Start using cached QEMU, which saves a brutal time when running the CI
d5a91e26e1fd13440aa5da4e00a7fa4f1c629147 ci/install_qemu: Always copy the tarball to the cache directory
2e4c14af3f374c0f4331f8ffa9259bd9f815cbd8 ci/install_qemu: Use cached QEMU
* Re-enable a previously disabled Kubernetes test, as the fix is getting in for the agent
3722c8cfad58d42c3b732282eeeb2702f2b26028 kubernetes: Reenable "Setting sysctl" test with CRI-O"
Depends-on: …

stable-2.1 | The last round of backports before releasing 2.1.0

---

.ci/openshift-ci/build_install.sh
.ci/openshift-ci/cluster/install_kata.sh

This PR fixes the issue #3544 related with installation of kata containers now has symlinks to the kernel and image.
I am also sending a improvement that will help on future to spot problems on CI.

openshift-ci: Fix job is broken due symlink on installation and improvements

---

.ci/setup.sh

On Fedora, we get:
```
Install CNI binaries
~/go/src/github.com/kata-containers/tests
Configure CNI
rm: cannot remove '/etc/systemd/system/kubelet.service.d/0-crio.conf':
Permission denied
```
The file cannot be removed by a regular user. Add `sudo` to fix that.
Fixes: #3553
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

tests: Remove 0-crio.conf using sudo.

---

README.md

This PR updates the README document to remove the reference to ginkgo tests
as for kata 2.x they are not longer running.
Fixes #3551

docs: Update README document

---

.ci/configure_crio_for_kata.sh

When using `tee -a ...` we ended up appending content to the
configuration file, while what we wanted was to simply override the
file's content, if the file existed.
Knowing this, let's drop the `-a` from the command line.
Fixes: #3563

ci: Ensure the configuration is not duplicated on a 2nd run

---

README.md

This PR adds vfio tests as part of the current tests that we support
in kata 2.x.
Fixes #3561

docs: Include vfio tests in the documentation

---

integration/containerd/cri/integration-tests.sh

As memory hotplug has enabled for now on arm64, let memory update test run.
Fixes: #3533
Depends-on: github.com/kata-containers/kata-containers#1888

containerd: enable memory update test on arm64

---

README.md
cmd/check-spelling/data/main.txt

This PR updates the README to start including more information about
Jenkins jobs and github actions that are being used in kata repositories.
Fixes #3565

docs: Update README to include Jenkins and github actions documentation

---

README.md

This PR updates the README file to include specific job jenkins triggers.
Fixes #3572

docs: Include specific job triggers at README

---

.ci/configure_crio_for_kata.sh

When using `tee -a ...` we ended up appending content to the
configuration file, while what we wanted was to simply override the
file's content, if the file existed.
Knowing this, let's drop the `-a` from the command line.
Fixes: #3563
(cherry picked from commit e0ddb18e194430e7ec63ca71e277f8814f0cd584)

[stable-2.1] ci: Ensure the configuration is not duplicated on a 2nd run

---

integration/kubernetes/run_kubernetes_tests.sh

[stable-2.1] ci: Reenable OOM and sysctl tests when using clh

---

integration/containerd/cri/integration-tests.sh

As memory hotplug has enabled for now on arm64, let memory update test run.
Fixes: #3533
@GabyCT @fidencio

backport-2.1: containerd: enable memory update test on arm64

---

README.md

This PR includes a missing title in the table of contents of README.
Fixes #3578

docs: Include missing tittle in table of contents README

---

README.md

This PR includes a missing title in the table of contents of README.
Fixes #3578

docs: Include missing title in table of contents README

---

metrics/density/footprint_data.md

This PR fixes the footprint data documentation. This replaces docker
to what we are using which is using ctr as well as it is updating
the changes that we did in the footprint script.
Fixes #3583

docs: Fix footprint data documentation

---

integration/kubernetes/runtimeclass_workloads/pod-block-pv.yaml

In pod-block-pv k8s test, use libpod latest (has no 18.04 tag) instead
of footloose 18.04 for quay.io registry organization, because footloose
has no s390x image.
Fixes: #3606

k8s: Use libpod instead of footloose

---

.ci/ppc64le/configuration_ppc64le.yaml

Currently these tests are failing on ppc64le,
skip them for now.
Fixes: #3608

ci: skips k8s tests on ppc64le

---

.ci/install_kata_image.sh
.ci/setup.sh

Docker is unavailable on Fedora/RHEL for ppc64le & s390x.
- ci: Enable running osbuilder with Podman & without a container engine, neither of which are currently supported
- ci/ppc64le,s390x: Install and use Podman on Fedora
Fixes: #3598
@Amulyam24, @bpradipt, or @clnperez: PTAL

Use Podman on Fedora-likes for ppc64le & s390x

---

.ci/ppc64le/kubernetes/init.sh

The pod gets often OOM killed with default limitation.
Fixes #3590
Signed-off-by: MatthieuSarter <matthieu.sarter@ibm.com>

kubernetes: remove memory limitation for flannel on ppc64le

---

.ci/setup.sh

In the setup phase, if some installations failed,
the CI should break and exit.
Fixes: #3613
Signed-off-by: bin liub <bin@hyper.sh>

tests: exit shell script when something failed

---

metrics/storage/fio-k8s/cmd/fiotest/go.mod
metrics/storage/fio-k8s/pkg/k8s/go.mod

fio-k8s: Lower the go dependency to 1.15

---

.ci/install_kata_image.sh

initrd only works with agent as init, so enable it, unless AGENT_INIT is
already set. Die when someone still tries to use INITRD=yes without
AGENT_INIT=yes.
Fixes: #3604

ci: Enable AGENT_INIT if TEST_INITRD == yes

---

.ci/configure_containerd_for_kubernetes.sh
.ci/install_crio.sh
.ci/setup.sh

An entry for CRI-O is created in /etc/systemd/system/kubelet.service.d
when using CRI-O. Do the same when using Kubernetes and containerd.
Remove the other configuration respectively.
Fixes: #3602

ci: Install k8s containerd config if required

---

Makefile
integration/cri-o/cri-o.sh
integration/cri-o/crio_skip_tests.sh

Add back integration tests with CRI-O but 2.x ready as per issue https://github.com/kata-containers/tests/issues/3592.
Once kata is installed on the system, "make crio" should allow the tests to be run.

integration/cri-o: add integration tests kata 2.x ready

---

.ci/set_kata_config.sh
cmd/checkmetrics/ci_worker/checkmetrics-json-kata-metric3.toml
cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
integration/ksm/ksm_test.sh
integration/sandbox_cgroup/sandbox_cgroup_test.sh
metrics/lib/common.bash

Due to virtio-fs using file-backed memory, KSM (Kernel Samepage Merging) is unstable or, depending on architecture, might not work at all.
- Generalize `.ci/toggle_sandbox_cgroup_only.sh` to `.ci/set_kata_config.sh` so it can be used for other keys.
- Disable virtio-fs for KSM test. Keep virtio-9p if it was enabled.
- Give KSM a little time to kick in (just because there are no shared pages *immediately* after starting container doesn't mean it isn't working).
- Re-enable KSM test on ARM. **I'm assuming this will fix ARM, but I don't have the means to test it. Test before merging.**
Fixes: #3531

 Disable virtio-fs for KSM

---

.ci/static-checks.sh

Display the HTTP error code if the static check script fails to verify a URL.
Fixes: #3624.

CI: Show HTTP error code in static check script

---

cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric4.toml
cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml

Due the change of metrics server, it seems that we need to re-calculate
blogbench baseline. This PR fixes this issue.
Fixes #3637

metrics: Fix blogbench and bootime baseline

---

integration/vcpus/default_vcpus_test.sh

Improved the vcpus integration tests:
* The clean_env_ctr() is going to clean up all tasks and containers
so it doesn't need to try the same on teardown();
* More verbose. Print if the test failed and when entered teardown();
Fixes #3283

tests: Strengthen the vcpus integration tests

---

integration/ksm/ksm_test.sh

Fails when pages merged on second container is equal to first, which
should still be a pass
Fixes: #3631

integration: Fix off-by-one in KSM comparison

---

.ci/install_runtime.sh
Makefile
cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
integration/kubernetes/vfio.sh

Issue: https://github.com/kata-containers/kata-containers/issues/1953
aims to remove the support for the legacy X86 machine (PC), remove
the related tests.
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>

ci: Remove X86 pc machine related tests

---

.ci/install_cri_containerd.sh
.ci/setup_env_centos.sh
.ci/setup_env_fedora.sh
.ci/setup_env_rhel.sh
.ci/setup_env_ubuntu.sh

- CRI-containerd installation needs our $BUILDTAGS for its $BUILD_TAGS
env -- not the other way around...
- Install ninja-build for QEMU on CentOS
- Install openssl non-`-devel` on s390x Fedora-likes for generating
X.509 certificates during kernel build
- Install curl as general dependency on Ubuntu (used for checking
versions)
- Fix non-fatal dependency typos in Ubuntu setup
Fixes: #3633

ci: Minor script fixes

---

.ci/s390x/configuration_s390x.yaml

to pave the way for a basic s390x CI. They depend on
- https://github.com/kata-containers/kata-containers/issues/1412
- Replacing docker.io/containerstack/alpine-stress with an image that is
also built for s390x -- probably need local build, which requires
Podman for CRI-O, which isn't enabled yet.
Also remove obsolete skippings
Fixes: #3626

ci: Skip memory-related tests on s390x

---

integration/cri-o/cri-o.sh

Make a copy of ctr.bats before editing it.
This prevents multiple lines from being added to the file in cri-o sources.
It also makes it possible to change the list of skipped tests and take the
change into account.
Fixes: #3622

integration/cri-o: do not edit ctr.bats

---

Unit-Test-Advice.md

The default branch of kata-containers/tests is main and the
former kata-containers/runtime repo was moved under
kata-containers/kata-containers.
Fix the URLs accordingly.
Fixes #3655
Signed-off-by: Greg Kurz <groug@kaod.org>

docs: Fix URLs in unit test doc

---

.ci/install_cri_containerd.sh
integration/containerd/cri/integration-tests.sh
integration/kubernetes/init.sh

Since 1.5.0, containerd had embedded cri and there's no
need to get the cri version.
Depends-on: github.com/kata-containers/kata-containers#2040
Fixes:#3630
Signed-off-by: fupan.lfp <fupan.lfp@antgroup.com>

containerd: fix the issue of getting cri version

---

.ci/teardown.sh

Add logs for mounts and processes at CI teardown to help with debugging
failures.
Fixes: #3670.

CI: Add mounts and pids to teardown

---

cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml

This PR updates the metrics value for the memory ksm test. It seems
that the change of server modified the value so this PR fixes it.
Fixes #3667

metrics: Update metrics ksm value

---

.ci/install_kata_image.sh
.ci/install_runtime.sh
.ci/lib.sh

Update kata-containers repo constants so they can be set as shell
variables if required.
Fixes #3648

ci: Add support for forked repo in ci scripts

---

integration/containerd/cri/integration-tests.sh

As discussed in
https://github.com/kata-containers/kata-containers/issues/1412, memory
hotplugging is not possible on s390x (until virtio-mem lands).
Therefore, disable the memory update test, as on ppc64le.
Fixes: #3674

containerd: disable memory update test on s390x

---

.ci/.golangci.yml

Let's hammer this issue down by temporarily disabling govet checks, as
it does affect a whole lot of code that's already part of our codebase
and, for some reason, it just started being opinionated now.
The proposal here is, disable it ... and do a somewhat taskforce to
re-enable this, skipping the checks wherever it makes sense to be
skipped (our tests, for instance).
Fixes: https://github.com/kata-containers/tests/issues/3694
Note:
The kind of issues govet will expose are all related to field alignment
in structs, which we could do better indeed.
Here's one example of the exposed issues:
```
INFO: Running golangci-lint on /home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/cli …
```

ci: Temporarily disable govet checks

---

.ci/configure_containerd_for_kata.sh
.ci/lib.sh
integration/stability/agent_stability_test.sh
integration/stability/hypervisor_stability_kill_test.sh
integration/stability/soak_parallel_rm.sh
lib/common.bash
metrics/lib/common.bash

Some code in tests is using kata-runtime as the
runtime (process) name, which leads to some tests
have been skipped.
And netmon test should be deleted too.
Fixes: #3691

tests: fix wrong runtime name

---

integration/kubernetes/nginx.bats

For nginx connectivity test, get deploy/pod
detail info at the end for debugging.
Fixes: #3689

tests: get deploy/pod details for debugging

---

.ci/install_rust.sh

Set `--default-toolchain` option can install the desired version
of rust and avoid installing two versions of rust toolchain.
Fixes: #3672

tests: Set --default-toolchain when installing rustup

---

integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml

It seems that the job of k8s e2e conformance tests with clh+containerd
has been failing. This PR adds to more tests to skip as the issue is
being investigated https://github.com/kata-containers/tests/issues/3665.
Fixes #3665

tests: Add more tests to skip in k8s e2e conformance for clh+containerd

---

integration/kubernetes/k8s-nginx-connectivity.bats
integration/kubernetes/run_kubernetes_tests.sh

Only run wget once may fail without retries.
The wget command in busybox image doesn't support
many options that used to control the retry, so here a
while-loop of shell is used.
And this commit also rename nginx.bats
to k8s-nginx-connectivity.bats to follow the naming rule
with other files under the same directory.
Fixes: #3714

tests: do retry for running wget command in pod

---

metrics/README.md

This PR updates the documentation for metrics with the current
implementation for kata 2.x metrics CI and tests. This PR removes
the master branch trending topics as they are not implemented in
kata 2.x metrics CI and also the master tracking as for kata 2.x
all metrics tests are being run.
Fixes #3710

docs: Update readme for metrics

---

cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml

Seems that using golang 1.16 has some impact in the memory-footprint-ksm
metrics.
Depends-on: github.com/kata-containers/kata-containers#2102

metrics: Update memory-footprint-ksm midval
