kata-containers/tests

- .ci/configure_containerd_for_kata.sh
- .ci/s390x/configuration_s390x.yaml
- Unit-Test-Advice.md
- integration/containerd/cri/integration-tests.sh
- integration/ksm/ksm_test.sh
- integration/kubernetes/e2e_conformance/skipped_tests_e2e.yaml
eef0c6d91fb6cb40e1e29f4a62e2fbb4406af70a containerd: disable memory update test on s390x
2972ff149b55fe334a643030bd73bacb1872e7ed tests: Add more tests to skip in k8s e2e conformance for clh+containerd
231d4632182b67e8073f542d0682ec117ec1ccbb docs: Fix URLs in unit test doc
a2268f44178611059758857d7649f436fc2185ed integration: pmem: fix test
912087fa7e13c3b705ad5250cb10f3407dd16f3a integration: Fix off-by-one in KSM comparison
ebd42776e97a8d2de94bd4474bb38a3ca277c7b3 ci: Skip memory-related tests on s390x
> stable 2.1 | Backports

- .ci/teardown.sh
Support golang 1.16.x. Set GO111MODULE environment variable to "auto"
fixes #2256
> ci: fix teardown.sh

- .github/workflows/main.yml
If a PR has the `force-skip-ci` label set, don't run the static tests.
Fixes: #3703.
> CI: Honour force-skip-ci label

- .ci/lib.sh
Clean up scripts uninstall `containerd.io` on Ubuntu when the package is
called `containerd`. This can lead to Docker failing to start because
containerd was not fully removed and systemd still remembers the
custom-installed unit file which points to `/usr/local`, as seen e.g. in
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/83
(although I can also reproduce this on x86?).
Fixes: #3705
> ci: s/containerd.io/containerd/ in cleanup

- .ci/install_cri_containerd.sh
- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/run.sh
- .ci/setup.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_sles.sh
- cmd/container-manager/manage_ctr_mgr.sh
- integration/containerd/cri/integration-tests.sh
- ci: Apply fixes from CentOS/RHEL to SLE
- no seccomp & btrfs
- CC=gcc on s390x
- ci: Re-apply $BUILD_TAGS fix
- PR #3634 fixed use of the $BUILD_TAGS variable, which was later overwritten in #3629. Re-apply this fix.
- ci: Add a non-k8s CRI_CONTAINERD job
- Kubernetes is really hard to set up on SUSE (I failed to set it up even on x86). The "blessed" way to run k8s on SUSE is Kubic, but that is e.g. not built for s390x. Add a job for cri-containerd without k8s.
- integration: Copy configuration.toml
- Copy `/usr/share/defaults/kata-containers/configuration.toml` to `/etc/kata-containers` (previously only done on Ubuntu). Also fix trailing space.
- ci: Fix SLE package install
- Skip all the individual repositories, just add openSUSE Leap OSS. On s390x, use 15.3 or newer, because that is …
> Update SUSE support, especially for s390x

- .ci/static-checks.sh
- cmd/github-labels/github-labels.sh
The `.ci/static-checks.sh` script relies on external tools provided by the distro (e.g. `chronic` and `pandoc`) as well as on in-house ones which are built and installed under `$GOPATH/bin`. For a first comer to ensure that those tools are installed and searchable may not be obvious. So on this PR I tried to make the script more friendly by pointing out where those tools live (what they eat? :) and how to install some of them.
> static-checks: Friendly messages when required commands aren't found

- .github/workflows/main.yml
go 1.14 already reached its EOL and has already been removed from
kata-containers/kata-containers repo.
See:
https://github.com/kata-containers/kata-containers/commit/e386069158a9da167d9f64efc1e9402e53571f15
https://endoflife.date/go
Fixes: #3733
> github: Don't run static checks for go 1.14

- .ci/.golangci.yml
structures in kata-containers repo have been aligned correctly
let's enable govet again.
Depends-on: github.com/kata-containers/kata-containers#2237
fixes #3726
> ci: enable govet

- cmd/container-manager/manage_ctr_mgr.sh
Install docker via `apt-get` as installing
from `download.docker.com` doesn't work.
Fixes #3739
> ci: fix docker install on ppc64le

- metrics/lib/json.bash
This PR removes proxy component as it is not longer used in kata 2.x
for the json results that we obtain when we run metrics tests.
Fixes #3742
> metrics: Remove proxy from json results

- .ci/lib.sh
Proxy is not longer a component on kata 2.x, this PR removes it
from the list of processes used in the kill stale function.
Fixes #3745
> ci: Remove proxy at the kill stale process function

- cmd/log-parser/README.md
This PR updates the log-parser documentation with the proper urls
for kata 2.x as well as it removes the references of kata components
not longer use in kata 2.x
Fixes #3736
> docs: Update log-parser documentation

- metrics/storage/blogbench_dockerfile/Dockerfile
Specify build type by passing `--build` option
to enable building the image on `ppc64le`.
Additionally, change the base image to
avoid docker pull rate limit.
Fixes: #3699
> metrics: fix blogbench image build on ppc64le

- cmd/check-spelling/data/main.txt
Add word "swappiness" to dictionary in spellcheck.
Fixes: #3730
> spellcheck: Add word "swappiness" to dictionary

- metrics/density/memory_usage.sh
This PR removes the references to proxy component as it is not
longer supported on kata 2.x
Fixes #3755
> metrics: Remove proxy from memory usage script

- integration/containerd/cri/integration-tests.sh
Remove duplicate line
`create_containerd_config "${containerd_runtime_test}"`
in main.
Fixes: #3761
> integration-tests.sh: Remove duplicate line in main

- kata-webhook/README.md
- kata-webhook/deploy/webhook.yaml
Now that the project owns https://quay.io/kata-containers, let's take
advantage of that and host our webhook example image there.  This will
immediately help consumers of the image that are facing pull limitations
due to the current dockerhub policy.
Fixes: #3749
> webhook: point the image to quay.io

- metrics/lib/json.bash
This PR fixes the issue of extracting the proper kata-runtime kata-env
when we are running with the runtime of io.containerd.run.kata.v2.
Fixes #3766
> metrics: Get kata-env when using kata with containerd

- README.md
This PR updates the breaking compatibility section to make reference
to main instead of master.
Fixes #3768
> docs: Update breaking compatibility section

- .ci/run.sh
Kata must be able to run using a read-only rootfs image,
otherwise something is broken and a bug must be opened
fixes #3770
> ci: make rootfs image read-only

- integration/containerd/cri/integration-tests.sh
k8s impact on containerd stop
containerd may fail to stop when k8s is running, as k8s may restart
docker or containerd meanwhile containerd stop. To fix is, k8s should be
killed before containerd stop.
Fixes: #3644
> integration: fix containerd service fail to stop randomly issue

- .github/workflows/main.yml
Looking at the changes that could cause the static-checks not to run
when a PR is updated I think 649a5a38c90a7eee351768d5c99c57a1dad636f4
could be the one that introduced such a regression.
Let's (try to) fix this by enforcing the workflow to run also when the
PR has been "edited" and "synchronized".
Fixes: #3772
> ci: Run static checks when PRs are updated

- .ci/lib.sh
- .ci/setup.sh
Being able to reproduce a CI failure would help developers to
better debug failed tests.
Currently there is no way to run the same CI job(test) on a
local server since the workflow is based on environment variables we don't have access to.
Add the list of the environment variables to the procenv-user-log .
Fixes: #3764
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>
> ci/setup: Print the environment variables

- integration/kubernetes/k8s-memory.bats
Since 591c556 "tests: Add some kubectl describe information to teardown of
many k8s tests", most of the Kubernetes bats tests had a kubectl describe
in the teardown path which helps to debug at least some CI failures when
pods fail to reach Ready state.
Unfortunately the k8s-memory.bats test was missed, probably because it
didn't have any teardown code to begin with.  Correct that oversight.
> tests/integration: Add basic debug information to k8s-memory teardown

- cmd/github-labels/labels.yaml.in
This PR updates the proper url for documentation requirements in the
github labels.
Fixes #3779
> labels: Update github labels for documentation

- metrics/density/memory_usage.sh
This PR removes old and unsupported runtimes for memory usage
metrics script.
Fixes #3785
> metrics: Remove old and unsupported runtimes

- metrics/storage/webtooling.sh
This PR updates and replaces the runtime for a variable that we
have already defined at lib/common.sh of metrics CI
Fixes #3787
> metrics: Replace runtime for a proper variable

- .ci/install_kata_image.sh
In a previous commit the rootfs image was converted to read-only, hence
the installation script on baremetal is failing because it tries to
overwrite it, let's try to umount and delete it before installing the
new image.
fixes #3789
> ci: fix image instalation on baremetal

- metrics/README.md
This PR updates the branch reference in the metrics readme documentation
with the current one that we are using on kata 2.0
Fixes #3798
> docs: Update readme metrics documentation

- integration/containerd/cri/integration-tests.sh
Remove the temporary directory after cleaning the CI
since it holds some configuration files used by
the cleaning code.
fixes #3806
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>
> integration/containerd: Fix cleaning flow

- .ci/install_rust.sh
so that when we build the agent in Docker, we do not need to install
sudo in the container.
Fixes: #3800
> ci: Only use sudo in Rust installation if required

- .ci/lib.sh
- .github/workflows/main.yml
1474f085c7023e1eb77210132dcf24a972880560 ci: Set GO111MODULE="auto" in lib.sh
6780b3626c13b47bac04f2259872783cabb78a10 github: Don't run static checks for go 1.14
> stable-2.1 | ci: Set GO111MODULE="auto" in lib.sh

- .ci/containerd_devmapper_setup.sh
- .ci/lib.sh
- .ci/run_metrics_PR_ci.sh
- .ci/setup.sh
- cmd/container-manager/manage_ctr_mgr.sh
- functional/vfio/run.sh
- integration/containerd/cri/integration-tests.sh
- integration/ksm/ksm_test.sh
- integration/sandbox_cgroup/sandbox_cgroup_test.sh
- integration/stability/agent_stability_test.sh
- integration/stability/hypervisor_stability_kill_test.sh
- integration/stability/soak_parallel_rm.sh
- integration/vcpus/default_vcpus_test.sh
- lib/common.bash
- metrics/density/fast_footprint.sh
- metrics/density/footprint_data.sh
- metrics/lib/common.bash
- metrics/storage/webtooling.sh
- tracing/tracing-test.sh
Too many systemd service restarts in a short period of time may result in systemd disabling the service.
Add a function to the common library that abstracts the service restart.
Use the opportunity to add error messages and return error codes so then later will be possible to stop the test if something goes wrong.
Improve a  little the logs while at it.
> lib: Ensure the StartBurstLimit is disabled when restarting services

- .ci/ci_job_flags.sh
- .ci/run.sh
FIRECRACKER_JAILER is a target introduced and used by the two* CIs,
which have been recently introduced to avoid regressions when running
firecracker with the jailer.
*: The CIs using this CI_JOB target:
- kata-containers-2.0-tests-firecracker-jailer-ubuntu-PR
- kata-containers-2.0-firecracker-jailer-ubuntu-PR
Fixes: #3802
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
> ci: Also test firecracker with jailer

- .ci/install_crio.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_debian.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/setup_env_ubuntu.sh
- Makefile
- tracing/test-agent-shutdown.sh
Run this test before the tracing test since agent tracing requires the agent
be able to shutdown gracefully. As such, ensure the shutdown is working
before moving on to testing tracing.
Fixes: #3494.
> agent: Add agent shutdown test

- README.md
This PR updates the proper url for the documentation install guides
for kata 2.0
Fixes #3810
> docs: Update documentation url for kata 2.0

- metrics/density/fast_footprint.sh
- metrics/density/footprint_data.sh
Currently at metrics common we have defined the CTR_RUNTIME variable
which is currently the runtime that we are using for metrics tests.
This PR updates the density scripts to use that variable instead of
repeating the value with two variables.
Fixes #3814
> metrics: Update runtime variable in density tests

- .ci/lib.sh
- README.md
- cmd/check-markdown/README.md
- cmd/github-labels/labels.yaml.in
- cmd/log-parser/README.md
- metrics/README.md
5423ef46 docs: Update checkcommits README information
444e638d docs: Update readme metrics documentation
c660af67 docs: Update documentation url for kata 2.0
9971d230 labels: Update github labels for documentation
5112449e docs: Update breaking compatibility section
fa650cec ci: Remove proxy at the kill stale process function
accaa483 docs: Update log-parser documentation
> backports for stable-2.1

- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/setup.sh
- .ci/setup_env_centos.sh
- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
- integration/containerd/cri/integration-tests.sh
- integration/kubernetes/run_kubernetes_tests.sh
since it's more aligned with CRI-O, e.g. for importing images.
- A comment in the CRI tests claims that their TestImageLoad test
depends on it, but my experiments don't confirm this.
- Likewise, kubeadm depends on Docker according to a comment, but I
can't reproduce that.
Fixes: #3635
Depended-on: github.com/kata-containers/kata-containers#2068
I-once-thought-it-depended-on: github.com/kata-containers/tests#3658
But-it-really-Depends-on: github.com/kata-containers/kata-containers#2150
Do you think that any of these are a blocker?
- ~Podman is incompatible with osbuilder Ubuntu in that it can't be debootstrapped, apt errors about setting up packages.~ fixed with an Ubuntu 20.04 guest
- The metrics tests use Docker a lot, but those are configured to CRI-containerd and we don't run them on …
> ci: Use Podman on Fedora-likes

- .ci/static-checks.sh
- cmd/check-spelling/data/main.txt
- cmd/check-spelling/data/projects.txt
Fixes: #3819
see also: kata-containers/kata-containers#2425
Before:
```
$ ./kata-spell-check.sh check ~/project/kata/kata-containers/tools/packaging/kernel/README.md 
INFO: Spell checking file '/home/dcmiddle/project/kata/kata-containers/tools/packaging/kernel/README.md'
WARNING: Word 'dev': did you mean one of the following?: deb, derv, div, den, rev, deg, def, dew, Nev, Rev, evade
WARNING: Word 'libelf': did you mean one of the following?: libel, libels, lib elf, lib-elf, libel f, belief
WARNING: Word 'yaml': did you mean one of the following?: yam, yams, yawl, ya ml, ya-ml, yam l
WARNING: Word 'yq': did you mean one of the following?: y, q, ye, sq, ya, yr, yo, yd, Sq
ERROR: Spell check failed for file: '/home/dcmiddle/project/kata/kata-containers/tools/packaging/kernel/README.md'
``` …
> Update static-checks URLs and spelling word lists

- versions.yaml
This fixes setting up flannel on Kubernetes v1.22.0.
Without this fix applying kube-flannel with fail with error:
no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1".
> versions: Update flannel version to v0.14.0

- metrics/lib/json.bash
Currently the RUNTIME that we are using on metrics for kata 2.0
is defined as CTR_RUNTIME, this PR fixes the correspondent name
of the variable.
Fixes #3823
> metrics: Fix RUNTIME at metrics json results

- .ci/lib.sh
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/init.sh
- integration/kubernetes/k8s-memory.bats
- integration/kubernetes/k8s-oom.bats
- integration/kubernetes/runtimeclass_workloads/pod-memory-limit.yaml
- integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
- integration/kubernetes/runtimeclass_workloads/stress/Dockerfile
containerstack/alpine-stress is only built for x86_64 and I cannot find
a substitute. Let's build the image ourselves to have a `stress`
container available on all architectures.
Fixes: #3678
Depends-on: github.com/kata-containers/tests#3636
> integration/k8s: Build custom stress image

- metrics/lib/json.bash
Currently at the metrics tests scripts we are using containerd and when
we are running with RunC this is being called io.containerd.runc.v2, this
PR updates this current runtime to get proper results at metrics.
Fixes #3826
> metrics: Use containerd runc runtime for metrics

- metrics/storage/webtooling.sh
To make easier to identify the correct TPS value, this PR renames
the name of the variables to make it clearer.
Fixes #3834
> metrics: Rename web tooling results variables

- integration/kubernetes/init.sh
While running standalone the kubernetes scripts using `make kubernetes`
without using CI environment we are hitting an error saying that CI
is an unbound variable. This PR is fixing it.
Fixes #3843
> ci: Fix unbound variable for init script for kubernetes

- .ci/s390x/configuration_s390x.yaml
Following the merge of #3679, a stress image is available on s390x,
thus, the memory tests can be re-enabled.
Fixes: #3840
> ci: Enable memory tests on s390x

- .ci/lib.sh
- .ci/static-checks.sh
- README.md
- cmd/github-labels/labels.yaml.in
- cmd/pmemctl/pmemctl.sh
- versions.yaml
This commit forces all the checks and references to point to CCv0 branch
rather than pointing to `main`.  This will guarantee that changes done
on `main` won't affect the testing of this specific branch.
Fixes: #3853
> CCv0 | ci: Refer to CCv0 branch on CCv0 branch

- integration/kubernetes/init.sh
- integration/pmem/pmem_test.sh
* Specify a version for the registry image
* Don't re-run a registry from the pmem test
* Don't delete all docker images to avoid rate limit issue
fixes #3837
> integration/pmem: fix bare metal CI

- .ci/install_bats.sh
Since the bump to Golang 1.16 (commit 188c129f3) scripts which uses `go
get -d` to download code should export GO111MODULE="auto" in case they
don't source lib.sh (commit 1474f085c7). That's the case of
install_bats.sh.
Fixes #3781
> ci: set GO111MODULE="auto" in install_bats.sh

- integration/kubernetes/cleanup_env.sh
Even though it doesn't block the CI, when docker
is used as the container engine, it is better to
remove the resources before containerd is stopped.
Fixes: #3871
> ci: improve cleanup

- .ci/ppc64le/configuration_ppc64le.yaml
For our current CI, skip unstable tests
and enable memory test.
Fixes: #3869
> ci: Skip unstable tests

- integration/kubernetes/init.sh
Wait for registry container before pushing stress-kata image
fixes #3865
> [backport] integration/kubernetes: wait for registry container

- cmd/checkmetrics/compare.go
Comparison operators are inverted.
Fixes #3875
Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
> cmd: checkmetrics: Fix debug log

- .ci/ci_job_flags.sh
- .ci/jenkins_job_build.sh
In .ci/jenkins_job_build.sh it is exported a bunch of variables
as per job-type, they are used to control the setup of the system
and the execution of tests.
This creates the ci_job_flags.sh as the new home for those variables
so that external scripts (not just jenkins_job_build.sh) can source
the variables before running the same setup and run tests scripts.
> backport ci: Introduce the ci_job_flags.sh file

- integration/kubernetes/k8s-block-volume.bats
This will allow to run the kubernetes suite with a non-root user, i.e., all tests should pass with `make kubernetes`.
Fixes #3873
> integration/kubernetes: allow to run block volume test with ordinary users

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
Our current values do not take the cgroup creation and management
overhead into account.
Fixes #3804
Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
> checkmetrics: Bump boot time latency to take cgroup management overhead

- .ci/aarch64/configuration_aarch64.yaml
enable memory hotplug test in k8s integration test
Fixes: #3885
> k8s: enable memory hotplug test for arm64

- kata-webhook/create-certs.sh
- kata-webhook/deploy/webhook.yaml
Primarily this should fix a test case which is failing on OpenShift CI (see #3858). While I am at it, I improved the `create-certs.sh` script a little bit.
> kata-webhook: request cpu/memory to the pod and a few improvements

- .ci/lib.sh
- .ci/setup.sh
so you can choose to use Docker rather than Podman on Fedora-likes.
Fixes: #3901
> ci: Honor USE_DOCKER

- lib/common.bash
- metrics/lib/json.bash
Currently some tests scripts are using io.containerd.kata.v2 as a runtime
so in this PR we are adding this to be recognized as a kata runtime, it
also fixes the unrecognised runtime message.
Fixes #3894
> ci: Add io.containerd.kata.v2 as a runtime

- .ci/lib.sh
- lib/common.bash
For the function clean_env_ctr, adds a loop that waits
until all running processes are stopped before to proceed
to delete all running containers.
Fixes #3896
> ci: Fix ctr cannot delete a non stopped container

- .ci/jenkins_job_build.sh
IIUC this should fix the mess with the dependencies between branches
When PR for kata-containers is send and this PR **Depends-on** some PR in tests, this tests PR is not merged/applied until the resolve-kata-dependencies.sh is called, hence, sourcing lib.sh before resolve-kata-dependencies.sh will result in lib.sh from the plain tests target branch (without merging the tests PR we depends-on). if the tests PR changes touched lib.sh these changes are not used (although we "depends-on" them"), this may cause a mess
Thing is, i think i cannot really test it before it's merged @Jakob-Naucke @marcel-apf  WDYT?
(https://github.com/kata-containers/tests/pull/3890 or similar might still be needed to fix completely the issue on stable)
@fidencio 
Fixes: #3889
Signed-off-by: Snir Sheriber …
> ci: fix deps resolving

- .ci/lib.sh
clean up stale network interfaces, files and process about cni, flannel
and k8s before tests.
Fixes: #3918
> lib: clean up k8s related evironment before real test

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
This PR updates the minpercent for boot time as it has been seen that sometimes
the boot time is less to the current one by decreasing the minpercent we will
avoid random failures when checking the minimum value for boot time, this is
not a performance degradation.
Fixes #3929
> metrics: Update minpercent for boot time

- metrics/density/memory_usage.sh
- metrics/lib/json.bash
Currently for the memory test we are using containerd and a as runtime io.containerd.kata.v2,
however, we can not extract general information like hypervisor path in order to get the pss
memory for the hypervisor. This PR fixes that issue by using kata-runtime when we are using
io.containerd.kata.v2 so we can get the information properly.
Fixes #3935
> metrics: Fix unknown runtime error at memory test

- .ci/lib.sh
- integration/kubernetes/cleanup_env.sh
This created the registry_server_teardown function which should
be used to remove the registry container after its use.
The original code is from integration/kubernetes/cleanup_env.sh but
changed to check before whether the container exists or not.
This is just an improvement to #3871.
Fixes: #3871
> ci/lib: Introduce the registry_server_teardown()

- .ci/vfio_jenkins_job_build.sh
- functional/vfio/run.sh
- lib/common.bash
Allow multiple test runs.
Enable the debug console so the container can be debugged (requires manually disabling the trap).
Add the kata vm dmesg to the output logs.
> Vfio test improvements

- cmd/github-labels/archive/README.md
This PR updates the github labels archive documentation for kata 2.0
Fixes #3944
> docs: Update github labels archive documentation

- metrics/lib/common.bash
This PR fixes the proper CTR RUNTIME to for kata 2.0 in order to
avoid the warning message of unrecognised runtime and get the proper
kata extract environment.
Fixes #3946
> metrics: Get kata extract environment for metrics

- .ci/install_cri_containerd.sh
- .ci/install_kata_image.sh
- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/static-checks.sh
- integration/kubernetes/e2e_conformance/setup.sh
Make the build understand if they are running against a target branch
of CCv0 or main and update branches dynamically based on this
Add code to get containerd from our CCv0 PR rather than a released build
Add new CCv0 condition to the code that created the kata image.
CCv0 requires some extra packages for running and debug. It also needs
umoci, which is not yet availabe as a distro package, so wget it direct
Fixes: #3887
Depends-on: github.com/kata-containers/kata-containers#2577
> CCv0 | ci: Add CCv0 features into CI script

- .ci/setup_env_ubuntu.sh
- Vagrantfile
The aim with this pull request is to fix the `vagrant up fedora` command which is not currently working. I also send a bonus commit that is just an improvement. I tested both `vagrant up fedora` and `vagrant up ubuntu` to ensure no regressions with ubuntu.
@dgibson reported the problem on #3760 but actually I never hit the same issue. Here instead it has crashed because of commit 26cef9d.
@Jakob-Naucke I didn't touch your code which forces the use of Podman on Fedora-likes. Instead I ensure it work with this vagrant file. TBH, I don't know why (and didn't investigate) on the Fedora box with cgroups v2, Podman fails to build the guest image.
Fixes #3760
> vagrantfile: Fix vagrant up fedora

- .ci/vfio_jenkins_job_build.sh
improve VFIO test. Use ci_entry_point.sh to clone the tests repo,
checkout the right branch and run the test
fixes #3954
> ci/vfio: use ci_entry_point.sh

- .ci/install_qemu.sh
The 'build_and_install_qemu' function in .ci/install_qemu.sh has explicit
code for patching the qemu we're going to use for running the guest.  But,
we already have scripts for this in the main kata repo, specifically
in tools/packaging/scripts/patch_qemu.sh.  Confusingly the latter is used
for static qemu builds, but the one in tests is used for other qemu builds.
Move to using patch_qemu.sh consistently.
Fixed #3957
> tests: Use qemu patching scripts from kata-containers repository

- .ci/vfio_jenkins_job_build.sh
improve VFIO test. Use ci_entry_point.sh to clone the tests repo,
checkout the right branch and run the test
fixes #3954
> [backport-2.2] ci/vfio: use ci_entry_point.sh

- cmd/github-labels/README.md
- cmd/github-labels/github-labels.sh
This PR updates github labels document to reflect kata 2.0 repositories
Fixes #3963
> docs: Update github labels documentation with kata 2.0 repository

- lib/common.bash
- grep container for whole word in tasks. Otherwise, e.g. `test1` can be
caught when `test` is to be removed, and `test1` won't find anything.
- cut name out -- no point in killing `[PID] RUNNING`
- Rename this variable from `tasks` to `task` to avoid confusion. There
will be no more than one task associated with the container name.
Fixes: #3961
Btw, I could observe this on x86 too.
> ci: Kill tasks by whole word in clean_env_ctr

- tracing/test-agent-shutdown.sh
The newly introduced agent shutdown test (#3495) needs Rust, but if we
build the agent itself in a container, Rust will not be installed on the
host. Add a Makefile target for this.
Fixes: #3812
> agent: Install Rust for shutdown test

- tracing/test-agent-shutdown.sh
The changes break CI jobs which run test-agent-shutdown.sh.
This reverts commit ca718a600954323cfe95624913e880f2c59543d9.
Fixes #3978
> agent: Revert "agent: Install Rust for shutdown test"

- metrics/density/memory_usage_inside_container.sh
This PR is replacing clean_env for clean_env_ctr which is the correct
function to clean an environment while using containerd for the
memory usage script.
Fixes #3976
> metrics: Replace clean_env for clean_env_ctr

- tracing/test-agent-shutdown.sh
We do not want to run the test shutdown on Metrics CI this PR will skip this test.
Fixes #3980
> tracing: Skip agent test shutdown on Metrics CI

- .ci/ci_job_flags.sh
This PR simplifies and removes the duplicated setting for the CI JOBS
flags for METRICS and METRICS_EXPERIMENTAL.
Fixes #3991
> ci: Remove duplicated settings on CI JOB definition for metrics

- .ci/ci_job_flags.sh
- .ci/run.sh
- Makefile
Add Makefile target for QAT and define QAT value for CI_JOB
environment variable
fixes #4000
> ci: Add Makefile target for QAT

- .ci/jenkins_job_build.sh
It's not easy for arm64 to test snap build in github action like x86 does,
thus, adding snap build test along with integration test.
Fixes: #3966
> snap: add snap build test for non-x86

- integration/qat/qat_test.sh
To avoid the failure of the "input device is not a TTY" this
PR removes t from docker run.
Fixes #4002
> test: Remove terminal for docker run in qat test

- .ci/install_qemu.sh
If the download or installation of the cached Qemu fails, we should try
to build it from sources
Fixes #4006.
> CI: Build Qemu if the cached qemu is not installed correctly

- Makefile
Remove -f from Makefile qat target to honor wild card [asterisk]
for filename expansion in globbing.
fixes #4008
> ci: remove -f from Makefile qat target

- .ci/install_qemu.sh
If the download or installation of the cached Qemu fails, we should try
to build it from sources
Fixes #4006.
(cherry picked from commit 929caef6478da1b0e8ec3321b455a5a59297bff1)
> [Backport 2.2] CI: Build Qemu if the cached qemu is not installed correctly

- .ci/jenkins_job_build.sh
"kata_repo_dir" may not exist. So before go into it, do check
and get it if there is no such dir.
Depends-on: github.com/kata-containers/kata-containers#2706
Fixes: #4004
> snap: check if kata_repo_dir exist before go into

- integration/qat/qat_test.sh
This PR fixes the issue of provided file is not a console when running
the run_test for the qat test.
Fixes #4016
> tests: Fix terminal issue for the qat test

- .ci/ci_entry_point.sh
- Dont fail if test repository is already cloned
- Checkout to target branch only if provided
e.g. 
```sh
#!/bin/bash
set -e
set -x
curl -OL https://raw.githubusercontent.com/kata-containers/tests/main/.ci/ci_entry_point.sh
export CI_JOB="CLOUD-HYPERVISOR-K8S-CONTAINERD"
export DEBUG=true
bash -x ci_entry_point.sh "https://github.com/kata-containers/kata-containers"
```
Signed-off-by: Carlos Venegas <jose.carlos.venegas.munoz@intel.com>
> ci: Allow use entry point for new VM.

- integration/kubernetes/k8s-optional-empty-configmap.bats
- integration/kubernetes/k8s-optional-empty-secret.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-optional-empty-configmap.yaml
- integration/kubernetes/runtimeclass_workloads/pod-optional-empty-secret.yaml
These tests makes sure that if a configmap/secret is present but empty, or if the volume is declared `optional: true` that the agent will still create the volumeMount folder.
Signed-off-by: Simon Kaegi <simon_kaegi@ca.ibm.com>
> integration/kubernetes: volume tests for empty/missing configmap/secret

- .ci/jenkins_job_build.sh
Fixes: #4021
This also fixes the issue of checking out `kata-containers:main` when `stable` should be used.
/cc @snir911 @GabyCT
> Backport ci: fix deps resolving

- .ci/aarch64/lib_install_qemu_aarch64.sh
It's easy to maintain to keep qemu version of arm in consistent with
other arches.
Depends-on: github.com/kata-containers/kata-containers#2732
Fixes: #4019
> qemu: get qemu version of arm from arch independent label

- integration/kubernetes/init.sh
- versions.yaml
Move the operation of starting the container registry
and pushing the custom stress image before containerd
service is stopped when crio is used as the runtime
for k8s tests. Also, consolidated the steps into
a single function.
Fixes: #3899
> ci: fix custom stress image building

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric4.toml
It seems that the change to qemu 6.1 introduced higher ksm memory values
which makes the metrics CI unstable. This PR is recalculating the value
for the metrics limits.
Fixes #4023
> metrics: Recalculate KSM memory values for metrics

- .ci/resolve-kata-dependencies.sh
When we have a PR on branch `X`, the kata-containers/kata-containers
repo should use branch `X` too. Add (re-enable?) this functionality in
`.ci/resolve-kata-dependencies.sh`.
Fixes: #4030
@chavafg were you going anywhere else with that TODO?
> ci: Checkout reference branch in Kata repo

- .ci/resolve-kata-dependencies.sh
When we have a PR on branch `X`, the kata-containers/kata-containers
repo should use branch `X` too. Add (re-enable?) this functionality in
`.ci/resolve-kata-dependencies.sh`.
Fixes: #4039
Backport of #4031
> Backport ci: Checkout reference branch in Kata repo

- .ci/jenkins_job_build.sh
Earlier, as mentioned in the script, the
static checks for ppc64le were being run on
Travis. Now, since Travis is no longer used,
run it on Jenkins for non-x86.
Fixes: #4026
> ci: fix running static checks on non-x86

- metrics/lib/common.bash
- metrics/storage/blogbench_dockerfile/Dockerfile.in
- metrics/storage/fio_dockerfile/Dockerfile.in
- metrics/storage/web-tooling-dockerfile/Dockerfile.in
Mitigate image registries rate limit issue.
Define a list of public container registries and use it to build
the images used to run metrics.
fixes #3968
> metrics: support pulling container images from different registries

- kata-webhook/Dockerfile
- kata-webhook/README.md
- kata-webhook/deploy/webhook-registration.yaml.tpl
- kata-webhook/go.mod
Update the webhook reference to stop using the deprecated reference.
Fixes: #3996
> ci: fix install failure for the webhook

- integration/rootless/rootless_test.sh
rootless pod must be ready before stopping it
fixes #4032
> integration/rootless: check pod status before stopping it

- integration/kubernetes/k8s-optional-empty-configmap.bats
- integration/kubernetes/k8s-optional-empty-secret.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-optional-empty-configmap.yaml
- integration/kubernetes/runtimeclass_workloads/pod-optional-empty-secret.yaml
These tests makes sure that if a configmap/secret is present but empty, or optional but not present that the volumeMount folder is created.
Backports: #4011
Fixes: #4012
Signed-off-by: Simon Kaegi <simon.kaegi@gmail.com>
> stable-2.2 | integration/kubernetes: volume tests for empty/missing configmap/secret

- .ci/jenkins_job_build.sh
Static checks need this file so that modules like kata-runtime can be
built and tested.
Fixes: #4044
/cc @Amulyam24 @jongwu
> ci: Create config-settings.go pre-static checks

- metrics/time/launch_times.sh
This PR replaces the clean_env for the proper clean_env_ctr function which
is the correct one to clean an environment that is using containerd.
Fixes #4053
> metrics: Replace clean_env for clean_env_ctr for launch times script

- .ci/run_metrics_PR_ci.sh
- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric4.toml
This PR enables the memory inside container for the clh metrics baseline.
Fixes #4063
> metrics: Enable memory inside container for clh metrics

- integration/cri-o/cri-o.sh
- integration/cri-o/crio_skip_tests.sh
- Add some code to the test script to selectively enable tests based on the version of cri-o being tested
- Enable several tests that we were skipping, for specific versions of cri-o
- Also enable a test fixed in kata - as we are testing against "main", there is no need to check the version here
> Selective enablement of tests

- cmd/checkcommits/checkcommits.go
- cmd/checkcommits/checkcommits_test.go
PR #3938 added support for handling revert commits. However it
incorrectly failed to check the commit body of such commits. This meant
that revert commits were considered invalid due to a missing "Fixes"
comment, even if the range of commits on a PR contained such a comment.
Revert commits now have their bodies checked and new tests have been
added to assert the expected behaviour.
Fixes: #4143.
> checkcommits: Fix revert commit handling

- kata-webhook/deploy/webhook.yaml
This reverts commit 43b47ecefea5c6e2c3ac81fe41ca782680dbfa58.
Fixes #4080
> Revert "kata-webhook: Use temporary webhook image"

- integration/cri-o/cri-o.sh
Use the PULL_BASE_REF variable exported by the jenkins job to get the version of cri-o we're testing against.
> ci: cri-o integration tests - get cri-o version from jenkins' environment

- .ci/go-test.sh
Run `go test` with `-race` on architectures that support this by now.
This might also help uncover the root cause of #4131, even though that
has only been observed on s390x thus far.
Fixes: #4141
/cc @jodh-intel
> ci: Enable data race detection on ARM and Power

- metrics/report/report_dockerfile/dut-details.R
This PR removes unsupported results json files for metrics CI in order
to get a proper metrics report.
Fixes #4150
> metrics: Remove unsupported metrics results for report generation

- metrics/report/report_dockerfile/metrics_report.Rmd
This PR removes the footprint density metrics that were used on kata 1.x
and that is not supported on kata 2.0
Fixes #4153
> metrics: Remove unsupported footprint density report

- metrics/report/report_dockerfile/metrics_report.Rmd
This PR removes fio information from metrics report generation as this
is not longer being used on kata 2.0 metrics
Fixes #4159
> metrics: Remove fio information from metrics report

- .ci/install_crio.sh
This was mistakenly added as part of
66eea16d6301d7a9710e236bfa7834792c5f9de0.
Fixes: #4165
> crio: Remove internal Red Hat registry

- .ci/setup.sh
Fix the logical operator after a failed containerd Kubernetes
configuration. Previously, it would display a success even on failure.
Fixes: #4167
> ci: Fix logical operator in k8s installation

- .ci/setup.sh
We use `errexit` at this point, so huge chains of logical operators are
no longer required. Also use `if` rather than `&&` for containerd
Kubernetes configuration (was `||`, would display success even on
failure).
Fixes: #4167
Backport of #4169
> stable-2.3 | ci: Fix logical operators in setups

- .ci/lib.sh
This PR removes a unsupported variable that is not longer being used in
kata 2.0 as we are not using nemu anymore.
Fixes #4186
> ci: Remove unsupported variable

- metrics/lib/common.bash
This PR removes unsupported runtime as it is not longer being used in the
metrics CI for kata 2.0
Fixes #4184
> metrics: Remove unsupported runtime

- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
- .ci/vagrant-cleaner.sh
- README.md
- Vagrantfile
I started this string of commits by changing the Vagrantfile so that the VM boots with q35 machine type (fix #3752). As q35 is required to run the vfio tests (because it needs iommu and one extra virtio-net device) and the Vagrantfile had no support for such as test, I also changed it so that if the user exports `CI_JOB=VFIO` then extra arguments are passed to QEMU to allow testing Kata + VFIO.
Other changes came after to address the issues #3757 and #3942.
I tested those changes on my laptop x86_64 (Intel) with Fedora 33. I booted the fedora and ubuntu guests for VFIO and non-VFIO tests (`CI_JOB=CRIO_K8S`) normally (although sometimes the SSH connection fails after reboot; usually I destroy/up an 2nd time and it works). I don't have a ubuntu bare-metal to test the VFIO job but I will …
> Vagrant: boot q35 machine and other improvements

- .ci/install_rust.sh
For the reasons described in #4188 this makes more sense.
> Install the oldest, rather than newest supported Rust by default

- .ci/static-checks.sh
Skip SPX check on .tar and .gpg
Fixes: #4190
> CCv0 | static-checks: skip license checks

- .ci/configure_cni.sh
- .ci/install_cri_containerd.sh
- .ci/install_kata_image.sh
- integration/containerd/cri/integration-tests.sh
- fix: Shell syntax error. 
- fix: support containerd 1.6.x
Depends-on: https://github.com/kata-containers/kata-containers/pull/2733
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
> work with containerd 1.6.x

- .ci/aarch64/configuration_aarch64.yaml
- .ci/s390x/configuration_s390x.yaml
- integration/kubernetes/k8s-inotify.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml
- integration/kubernetes/runtimeclass_workloads/inotify-configmap.yaml
- integration/kubernetes/runtimeclass_workloads/inotify-updated-configmap.yaml
Add test to ensure fsnotify works and that symlinks are preserved.
Fixes: #4180
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
> kubernetes: add integration test for inotify workaround support

- .ci/ppc64le/configuration_ppc64le.yaml
There is no multiarch image supported,
skip the test for now.
Fixes: #4202
> ci: skip k8s-inotify on ppc64le

- .ci/install_cri_containerd.sh
- .ci/lib.sh
- integration/containerd/cri/integration-tests.sh
Since the containerd/cri repo had been deprecated, thus we should
switch to integration tests from containerd repo instead of
containerd/cri.
Fixes: #4198
Signed-off-by: Fupan Li <fupan.lfp@antgroup.com>
> integration: containerd cri integration tests using containerd repo

- Makefile
The docker stability tests are not longer supported on kata 2.0 as they
were updated and replaced by stability tests. This PR removes them.
Fixes #4207
> ci: Remove docker stability from Makefile

- integration/kubernetes/k8s-replication.bats
- integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
This contain a couple of improvements:
- in case of test failure let's print the description of the replication
controller deployment, so to help debug;
- use array to hold the list of pods as the current code only works if
replicas is equal to one;
- if we are unfortunate to have leftovers pods from previous tests which
application is tagged as 'nginx' then it will mess with the replication test. So
let's tag our app as 'nginx-rc-test' to avoid that.
Fixes #4214
> k8s: improve the replication test

- .ci/aarch64/configuration_aarch64.yaml
- .ci/install_cri_containerd.sh
- .ci/lib.sh
- .ci/ppc64le/configuration_ppc64le.yaml
- .ci/s390x/configuration_s390x.yaml
- integration/containerd/cri/integration-tests.sh
- integration/kubernetes/k8s-inotify.bats
- integration/kubernetes/k8s-replication.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml
- integration/kubernetes/runtimeclass_workloads/inotify-configmap.yaml
- integration/kubernetes/runtimeclass_workloads/inotify-updated-configmap.yaml
- integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
This PR backports:
* kubernetes: add integration test for inotify workaround support (#4180)
* ci: skip k8s-inotify on ppc64le (#4202)
* integration: containerd cri integration tests using containerd repo (#4198)
* k8s: improve the replication test (#4214)
> stable-2.3 | Some backports before the 2.3.0 release

- .ci/openshift-ci/build_install.sh
- .ci/openshift-ci/cluster/configs/crio_kata.conf
- .ci/openshift-ci/cluster/deploy_webhook.sh
- .ci/openshift-ci/cluster/deployments/configmap_installer_kernel.yaml
- .ci/openshift-ci/cluster/deployments/configmap_installer_qemu.yaml
- .ci/openshift-ci/cluster/deployments/configmap_kata-webhook.yaml.in
- .ci/openshift-ci/cluster/deployments/daemonset_kata-installer.yaml.in
- .ci/openshift-ci/cluster/deployments/machineconfig_kata_runtime.yaml.in
- .ci/openshift-ci/cluster/deployments/machineconfig_sandboxedcontainers_extension.yaml
- .ci/openshift-ci/cluster/deployments/runtimeclass_kata.yaml
- .ci/openshift-ci/cluster/install_kata.sh
- .ci/openshift-ci/images/entrypoint.sh
- .ci/openshift-ci/smoke/http-server.yaml
- .ci/openshift-ci/smoke/service.yaml
- kata-webhook/deploy/webhook.yaml
- versions.yaml
This is the needed changes on Kata Containers side to allow:
1) build with same configuration as OpenShift Sandboxed Containers
2) configure the runtime to use the host kernel
3) configure the runtime to use the system QEMU
Fixes #4163
> openshift-ci: adapt scripts to test like OpenShift Sandboxed Containers

- cmd/check-spelling/data/acronyms.txt
- cmd/check-spelling/data/main.txt
Let's add a few new words to our dictionary so the DinD documentation
can be merged on the kata-containers side.
The words needed are:
- AUFS
- DinD
- dind
- emptydir
- loopback
- memdisk
- OverlayFS
Fixes: #4229
> spell-checker: Add new words for DinD docs

- integration/kubernetes/runtimeclass_workloads/kata-runtimeclass.yaml
RuntimeClass' API version of node.k8s.io/v1beta1 is deprecated,
should be updated to node.k8s.io/v1.
Fixes: #4243
Now in CI logs:
> 14:30:53 Create kata RuntimeClass resource
14:30:53 Warning: node.k8s.io/v1beta1 RuntimeClass is deprecated in v1.22+, unavailable in v1.25+
14:30:53 runtimeclass.node.k8s.io/kata created
> tests: update API version of RuntimeClass resource

- .ci/install_kata_image.sh
Change the default CCv0 install image to build and add just umoci
Fixes: #4245
Depends-on: github.com/kata-containers/kata-containers#3171
> ci: Make building skopeo not default

- integration/kubernetes/k8s-nested-configmap-secret.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-nested-configmap-secret.yaml
This test makes sure that pods that mount a secret volumes inside of configmap volume will work correctly.
Fixes: #4239
Signed-off-by: Simon Kaegi <simon.kaegi@gmail.com>
> integration/kubernetes: volume tests for nested configmap and secret

- integration/kubernetes/k8s-nested-configmap-secret.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-nested-configmap-secret.yaml
This test makes sure that pods that mount a secret volumes inside of configmap volume will work correctly.
Fixes: #4239
Signed-off-by: Simon Kaegi <simon.kaegi@gmail.com>
(cherry picked from commit 5b573173c6bb127fdc8b3b2cac45d552deebe0d5)
> stable-2.3 | integration/kubernetes: volume tests for nested configmap and secret

- metrics/density/memory_usage.sh
This PR removes the kata-fc runtime as currently for metrics CI, we are
not using firecracker.
Fixes #4257
> metrics: Remove kata-fc from memory usage script

- .github/workflows/main.yml
This is not the most beautiful solution, but that's what I've already
been doing as part of the `kata-containers` repo since
kata-containers/kata-containers#2361.
We do that othewise some of the checks won't even start, making any PR
using the `force-skip-ci` label not mergeable.
Fixes: #4253
> static-checks: Check for the `force-skip-ci` label on each step

- .ci/ci_job_flags.sh
A flag was missing, making the script try to test with containerd
rather than cri-o.
Fixes: #4103
> ci: fix CI entry point for cri-o PRs

- .github/workflows/main.yml
According to https://endoflife.date/go golang 1.15 is not supported
anymore.  Let's remove it from out tests, add 1.17.x, and bump the
newest version known to work when building kata to 1.17.3.
This is the tests counterpart of kata-containers/kata-containers#3017,
which I simply forgot to open when dealing with the `kata-containers
repo.
Fixes: #4250 
> workflows: Bump golang to 1.17

- .ci/ci_job_flags.sh
A flag was missing, making the script try to test with containerd
rather than cri-o.
Fixes: #4264
> stable-2.3 | ci: fix CI entry point for cri-o PRs

- README.md
Unit-Test-Advice.md was moved to kata-containers repo but URLs pointing
to that document were not updated. This patch updates these URLs.
fixes #4272
> docs: fix check-markdown test

- .ci/openshift-ci/images/Dockerfile.installer
- .ci/openshift-ci/images/entrypoint.sh
- .ci/openshift-ci/test.sh
- versions.yaml
This is a respin of [openshift-ci: adapt scripts to test like OpenShift Sandboxed Containers](https://github.com/kata-containers/tests/pull/4164).
When I started working on the new job on OpenShift CI for OCP 4.10 I realized that the `centos:8` image had been updated to ship the EL 8.5 kernel, consequently kata's initrd now includes `4.18.0-348.2.1.el8_5.x86_64` modules. The OCP 4.10 worker nodes will be running with an EL 8.4 kernel, and that mismatch drives the Kata's VM to crash on boot. To solve that problem I added a code on the installer script to simply copy the host's kernel modules over the initrd in case of mismatch. This worked out on my test environment.
An alternative approach would be to use a buildroot which provides the EL 8.4 kernel but I couldn't find a suitable image, …
>  openshift-ci: adapt scripts to test like OpenShift Sandboxed Containers - respin

- .ci/jenkins_job_build.sh
Multiple unit tests fail on ppc64le blocking the CI.
Skip tests and enable later when stable.
Fixes:#4286
> ci: skip unit tests on ppc64le

- .ci/setup.sh
so that podman will use runc and not crun, as it seems we
mess some crun configuration earlier
Fixes: #4283
> env: install runc before podman

- .ci/aarch64/kubernetes/init.sh
- .ci/ppc64le/kubernetes/init.sh
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/init.sh
- integration/kubernetes/run_kubernetes_tests.sh
- versions.yaml
The main goal of this PR is to address the improvements listed in #4247 for the initialization script of the kubernetes integration tests.
The highlights are:
* now the initialization is retried in case of fail
* added debug information to `wait_for_pods()` as in my experience that method drive to many CI jobs to fail and we don't know what happened
* More `info()` calls to help debugability
Along the way I refactored some scripts to improve maintainability and ease reviews.
> kubernetes: strengthen the init.sh and misc refactors

- .ci/jenkins_job_build.sh
- tracing/test-agent-shutdown.sh
In the unit tests and the agent shutdown test, we install Rust iff it
isn't installed. On CI instances that are not reinstated for every job
(e.g. ARM & s390x), this leads to Rust never getting updated (1.47 at
the moment). The Rust installation script already does what we should
do: It installs the required version of Rust unless it is already
installed. Use that without checks.
Fixes: #4179
/cc @dgibson @stevenhorsman
> ci: Always install newest Rust version

- .ci/jenkins_job_build.sh
- tracing/test-agent-shutdown.sh
In the unit tests and the agent shutdown test, we install Rust iff it
isn't installed. On CI instances that are not reinstated for every job
(e.g. ARM & s390x), this leads to Rust never getting updated (1.47 at
the moment). The Rust installation script already does what we should
do: It installs the required version of Rust unless it is already
installed. Use that without checks.
Fixes: #4179
Backport of #4288
> Backport ci: Always install newest Rust version

- integration/kubernetes/k8s-seccomp.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/pod-seccomp.yaml
Added a test case which reproduces the k8s e2e test:
[k8s.io] [sig-node] Security Context should support seccomp runtime/default [LinuxOnly]
The test creates a container configured to use the "runtime/default" seccomp profile, then
it checks the container process is subject to seccomp mode "2" (filtering).
Fixes #1476
> k8s: Add seccomp support test

- .ci/openshift-ci/images/Dockerfile.installer
- .ci/static-checks.sh
- conformance/posixfs/Dockerfile
- integration/kubernetes/runtimeclass_workloads/stress/Dockerfile
- kata-webhook/Dockerfile
- metrics/network/iperf3_dockerfile/Dockerfile
- metrics/network/iperf_dockerfile/Dockerfile
- metrics/network/nuttcp_dockerfile/Dockerfile
- metrics/report/report_dockerfile/Dockerfile
- metrics/storage/blogbench_dockerfile/Dockerfile.in
- metrics/storage/fio_dockerfile/Dockerfile.in
- metrics/storage/web-tooling-dockerfile/Dockerfile.in
- versions.yaml
This will introduce a new checker to inspect the dockerfiles of the project with use of the [hadolint](https://github.com/hadolint/hadolint) tool.
Before turn on that check, it will be needed to delint all the dockerfiles. I already did it for the tests repository, remaining to change the files in the kata-containers repository.
Fixes #4149
Depends-on: github.com/kata-containers/kata-containers#3109
> Static checks: adds a checker for dockerfiles

- .ci/static-checks.sh
Since we'd plan to move the protocols crate to upper libs
directory, thus rename the excluded spdx license checking
files.
Fixes: [#3348](https://github.com/kata-containers/kata-containers/issues/3348)
Signed-off-by: Fupan Li <fupan.lfp@antgroup.com>
> ci: exclude the SPDX-License check for some proto files

- integration/kubernetes/k8s-caps.bats
I noticed infrequent failures of the capability check test where the
resulting logs observed during teardown match our expected value.
Let's add a 1 second delay between pod readiness and our check of the running
container logs to ensure  the logs are available.
Fixes: #4318
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
> k8s: ensure capability test container logs are available before checking

- .ci/static-checks.sh
Some test material has specific format and SPDX claims cannot be added
to those files.
Fixes: #4321
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
> ci: exclude the SPDX-License check for some test materials

- .ci/ci_entry_point.sh
As "by default, a rebase will simply drop merge commits from the todo
list, and put the rebased commits into a single, linear branch", let's
ensure we pass --rebase-merges to git rebase.
Reference: https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt--r
Fixes: #4329
Backports: #4330 
Signed-off-by: Fabiano Fidêncio fabiano.fidencio@intel.com
> CCv0 | ci: do not drop merge commits when rebasing

- .ci/ci_entry_point.sh
As "by default, a rebase will simply drop merge commits from the todo
list, and put the rebased commits into a single, linear branch", let's
ensure we pass `--rebase-merges` to `git rebase`.
Reference: https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt--r
Fixes: #4329
> ci: do not drop merge commits when rebasing

- .ci/ci_entry_point.sh
- Ubuntu 18.04 uses an old version of git (2.17)
- That doesn't support `--rebase-merges`
- Instead we use `--preserve-merges`
Fixes: #4334
> ci: Use different rebase flag for ubuntu 18.04

- .ci/ci_entry_point.sh
Sorry for the breakage, again, but it seems I've overlooked and used
"local" outside of a function, causing a breakage while trying to fix a
breakage. /o\
```
++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-PR-x86_64-clh-crio-tests-repo/ci_entry_point.sh +79: local rebase_merge_flag="--rebase-merges"'
Failed at /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-PR-x86_64-clh-crio-tests-repo/ci_entry_point.sh +79: local rebase_merge_flag="--rebase-merges"
++ exit 1
```
3rd time's the charm!
Fixes: #4334
> ci: "local" can only be used in functions

- Makefile
This PR removes part of how we were running podman integration tests
for kata 1.x, currently for kata 2.0 we do not have podman integration
tests running or even existing in our test repository, this PR makes
cleaner the Makefile.
Fixes #4352
> Makefile: Remove unused podman tests

- .github/workflows/main.yml
- Makefile
Added the "static-checks" target which will run the static checks.
Accordingly updated the github workflow.
Fixes #4337
> Makefile: add static-checks target

- integration/kubernetes/k8s-env.bats
- integration/kubernetes/runtimeclass_workloads/pod-env.yaml
This increased the coverage of k8s-env.bats by adding cases where
different sources have their values loaded and exported in the container
environment.
Fixes #4323
> k8s: add more test cases in k8s-env.bats

- integration/kubernetes/k8s-cpu-ns.bats
- integration/kubernetes/k8s-credentials-secrets.bats
- integration/kubernetes/k8s-projected-volume.bats
- integration/kubernetes/k8s-ro-volume.bats
- integration/kubernetes/k8s-volume.bats
- integration/kubernetes/tests_common.sh
In k8s-inotify.bats and k8s-nested-configmap-secret.bats,
the `fc_limitations` is used but not defined.
Fixes: #4361
> k8s: add firecracker limitation issue link

- .ci/ci_crio_entry_point.sh
The entry point script for cri-o testing should not fail when no PR number is
given. This allow local testing of the script, and make it possible to use
the same script on daily runs (from main/HEAD) and on PR-triggered jobs.
Fixes: #4346
> ci: do not fail if no PR number is given

- Vagrantfile
Instead of using the same distro as the host, let's just use the default
one.
The reasoning behind this change is because support for some of the
distros used as rootfs has been removed.
Fixes: #4356
Depends-on: github.com/kata-containers/kata-containers#3420
> vagrant: Use the default distro with osbuilder

- .ci/ci_entry_point.sh
- Improve the logic to support distros other than Ubuntu 18.04
Fixes: #4344
> ci: Improve `--rebase-merges` compatibility

- .ci/aarch64/install_rom_aarch64.sh
modify prepare_default_uefi() to download fd file to the correct dir
Fixes: #4348
Signed-off-by: Binbin Zhang <binbin36520@gmail.com>
> ci: fix install_rom_aarch64.sh on non-ubuntu/debian os

- .ci/install_kata.sh
This PR removes a variable that is not longer being used for
the install kata script for kata 2.0
Fixes #4371
> ci: Remove unused variable at install kata script

- .ci/jenkins_job_build.sh
avoid rate limiting, other checks still run on GHA
Fixes: #4369
Creating PR on stable first because stable is affected right now AFAICT.
> stable-2.3 | ci: Run static checks --only-arch

- versions.yaml
This PR removes kibana from versions.yaml as this was used for
docker integration tests that we do not longer have in kata 2.0
Fixes #4377
> versions: Remove kibana information

- integration/kubernetes/init.sh
- integration/kubernetes/kubeadm/config.yaml
- integration/kubernetes/run_kubernetes_tests.sh
The primary goal of this pull request is to fix #4290 which has hurt badly our baseline jobs. My previous attempt to solve that problem (076f6273573c45b9af046a309b877e4467441ec9) didn't work out. With the approach I am proposing here I ran 50x in my local machine without a single failure (at least not related with that problem); but let's see how it behaves on Jenkins.
While here I am sending a change that allow the developer to keep kubernetes running after the tests execution. I need this for debugging and developing tests and I believe others will be benefited too.
> kubernetes: bring up kubelet with '--v 4' by default and misc improvement

- Makefile
- integration/agent/agent_test.sh
Since the kata agent would change some of its threads
namespaces during creating the container's process,
thus this test would to check whether those changes
were recovered.
Fixes: #4340
Depeneds-on: https://github.com/kata-containers/kata-containers/pull/3370
Signed-off-by: Fupan Li <fupan.lfp@antgroup.com>
> integration: add the agent namespace test cases

- README.md
- Vagrantfile
As some CI jobs will run on Fedora 35, it was added its support on
Vagrant so jobs can be ran locally.
Fixes #4373
> Vagrantfile: Add support to Fedora 35

- .ci/ci_job_flags.sh
This PR removes some ci job flags that are not longer being used in
our kata 2.0 CI and baseline jobs.
Fixes #4389
> ci: Remove unused ci job flags

- .ci/jenkins_job_build.sh
no point in forcing skip if we're still running those
Fixes: #4384
Backport of #4385
> stable-2.3 | ci: force-skip-ci check before static checks

- .ci/ci_crio_entry_point.sh
CRI-O latest release is now 1.23, and we should be testing against the
same version of Kubernetes.
Fixes: #4382
> ci: crio: Bump CRI-O latest release

- versions.yaml
This PR removes elasticsearch from versions.yaml as this was used
for the docker integration tests that are not longer being part
of kata 2.0
Fixes #4398
> versions: Remove elasticsearch

- integration/kubernetes/init.sh
Tentative to fix a problem with CRI-O. Apparently it can sometimes not realize a new CNI configuration was installed as a result the deployed flannel pods fail to start up. 
Fixes #4381
> k8s: fix a problem on flannel installation

- .ci/ci_job_flags.sh
- .ci/run.sh
This PR removes unused ci job flags at the run.sh and ci_job_flags.sh
scripts as they are not being part of the baseline or PR CI jobs that
we have for kata 2.0
Fixes #4402
> ci: Remove unused ci job flags for kata 2.0

- integration/kubernetes/e2e_conformance/e2e_k8s_jobs.yaml
This PR removes unused e2e k8s tests filter flags as they are not part
of the current baseline and PR CIs for kata 2.0
Fixes #4410
> tests: Removed unused e2e k8s tests flags

- .ci/jenkins_job_build.sh
`.ci/` will only be a valid path when we're running on `tests`. Specify
explicitly so that it also works in the main repository.
Fixes: #4416
> ci: Use tests directory for setting 9p

- .ci/jenkins_job_build.sh
avoid rate limiting, other checks still run on GHA
Fixes: #4369
/cc @Amulyam24
Forward port of #4370
> ci: Run static checks --only-arch

- versions.yaml
This PR removes the alpine reference from the versions.yaml file
as this was used by docker integration tests which we do not longer
support in kata 2.0
Fixes #4418
> versions: Remove alpine reference

- .ci/jenkins_job_build.sh
until leftover shims under virtio-fs (#3998) are resolved.
Fixes: #4406
Backport of #4407 (e: including #4417). Sad but better than making failures the norm.
> ci: Switch to virtio-9p on s390x

- .ci/aarch64/install_rom_aarch64.sh
- integration/kubernetes/k8s-caps.bats
07a46826 ci: fix install_rom_aarch64.sh on non-ubuntu/debian os
209def11 k8s: ensure capability test container logs are available before checking
> stable-2.3: backports

- integration/agent/agent_test.sh
This PR removes the ctr runtime variable as it is already defined
at the metrics/lib/common.sh which this script is making reference
in order to avoid a double definition.
Fixes #4426
> tests: Remove ctr runtime duplicate definition

- .ci/aarch64/lib_install_qemu_aarch64.sh
- .ci/ci-fast-return.sh
- .ci/ci_crio_entry_point.sh
- .ci/install_cloud_hypervisor.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/install_qemu_experimental.sh
- .ci/install_runtime.sh
- .ci/jenkins_job_build.sh
- .ci/lib.sh
- .ci/openshift-ci/build_install.sh
- .ci/openshift-ci/qemu-build-pre.sh
- .ci/ppc64le/lib_install_qemu_ppc64le.sh
- .ci/resolve-kata-dependencies.sh
- tracing/test-agent-shutdown.sh
- Add logic to resolve-kata-dependencies.sh to skip
depends-on processing if ignore_depends_on label
is present
- Refactor common code and tests from ci-fast-return.sh
into lib.sh
Fixes: #4360
> ci: Add ignore_depends_on label

- .ci/install_kata_image.sh
- .ci/static-checks.sh
From 2.0 there will only one Rust agent,
so the RUST_AGENT is not needed anymore.
Fixes: #4447
> tests: remove RUST_AGENTs variable

- .ci/setup.sh
When using podman we need to also install `podman-docker`, as that
provides a compatibility layer which is very much needed as outside
scripts (as in, scripts from our dependencies) may not be aware of
`podman`.
Fixes: #4552
Depends-on: github.com/kata-containers/kata-containers#3664
> ci: install podman-docker when using podman

- integration/cri-o/cri-o.sh
- integration/cri-o/crio_skip_tests.sh
The cri-o integration test script is focusing on ctr.bats only.
This commit makes it possible to define a list of validated test files
that we want to use during testing.
Fixes: #4433
> ci: make it possible to use multiple test files

- integration/containerd/cri/integration-tests.sh
Debug logs are not enable when cri containerd tests are running.
Enable them for better CI debug.
Fixes: #4393
Signed-off-by: Carlos Venegas <jose.carlos.venegas.munoz@intel.com>
> test: cri: enable containerd debug logs

- integration/stability/soak_parallel_rm.sh
In `soak_parallel_rm.sh`'s `kill_all_containers`, we run e.g. `ctr tasks
kill $(ctr tasks ls -q)`, wrongly assuming that `ctr tasks kill` can
kill multiple tasks in one go. Let's just kill and delete all tasks and
containers respectively.
Fixes: #4430
> stability: Kill _all_ containers

- integration/kubernetes/k8s-hugepages.bats
There are too many errors with this case, temporarily disable
it and enable again after the issue fixed.
Fixes: #4474
> tests: temporarily disable hugepage sandbox cgroup only case

- integration/stability/soak_parallel_rm.sh
In `soak_parallel_rm.sh`'s `kill_all_containers`, we run e.g. `ctr tasks
kill $(ctr tasks ls -q)`, wrongly assuming that `ctr tasks kill` can
kill multiple tasks in one go. Let's just kill and delete all tasks and
containers respectively.
Backport of #4431
> stable-2.3 | stability: Kill _all_ containers

- .ci/lib.sh
- .ci/run.sh
- .ci/run_metrics_PR_ci.sh
- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
IPerf bench runs on top of a K8s setup, for instance ci metrics
needs to clean the k8s setup, before start the test.
Fixes: #4205
> ci: add k8s uninstallation to metrics tests

- functional/kata-monitor/run.sh
This commit is meant to address #3983: add a new script to allow basic testing of kata-monitor
> ci: add basic tests for kata-monitor

- .ci/install_cloud_hypervisor.sh
- .ci/install_runtime.sh
- .ci/vfio_jenkins_job_build.sh
Let's avoid code duplication and re-use here the very same script that's
used to build the kata-deploy binaries.
By doing this we:
* Reduce code duplication / complexity;
* Test the same build scripts used for kata-deploy on every single CI
job;
Fixes: #4462
> clh: Use kata-containers' static build script

- integration/containerd/cri/integration-tests.sh
Instead of blindly copying the default Kata config, use the existing if
it is available, and restore it afterwards; as there might be important
changes, e.g. #4407.
Also, do not change the default config.
Fixes: #4435
Backport of #4436.
> stable-2.3 | integration/containerd: Do not override config

- .ci/README.md
- .ci/setup_env_centos.sh
backport of https://github.com/kata-containers/tests/pull/4300 so that centos stream jobs will work also on stable
> stable-2.3: backport adapt to centos stream

- .ci/run_metrics_PR_ci.sh
This PR removes unused code that belonged to kata 1.x metrics CI and
it is not longer being used for kata 2.x metrics CI for PR or
baseline.
Fixes #4492
> metrics: Remove unused code for run metrics script

- .ci/install_qemu.sh
For non-cached builds, a `git clone` into QEMU_REPO is attempted, but
QEMU_REPO_URL is no longer set before it. Set it before use.
Fixes: #4484
/cc @devimc
> ci: Set qemu_repo after QEMU_REPO_URL

- integration/kubernetes/k8s-number-cpus.bats
In integration/kubernetes/k8s-number-cpus.bats the number of cpus in
the pod is stored in $number_cpus which is afterwards used to compare
with the maximum allowed. But $number_cpus can be empty sometimes, so
here is added a checking before using it.
Fixes #4328
> k8s: check $number_cpus before using it

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
This PR updates the blogbench limits for qemu in order to avoid
random failures related with them for the metrics CI. This seems
to be related that we changed the baremetal for the metrics CI.
Fixes #4498
> metrics: Update blogbench limits for qemu

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
This PR updates the boot time for qemu for the metrics CI, this
is related with the issue that we recently changed the baremetal
where metrics is running.
Fixes #4500
> metrics: Update boot time for qemu

- metrics/storage/blogbench.sh
This PR updates the blogbench clean environment to use the
clean_env_ctr which is used to remove containerd containers.
Fixes #4510
> metrics: Use clean env for ctr for blogbench metrics

- .ci/static-checks.sh
contains too many assumptions about substitutions
Fixes: #4504
> static-checks: Exclude Dockerfile.template

- .ci/static-checks.sh
contains too many assumptions about substitutions
Fixes: #4504
Backport of #4505
> stable-2.3 | static-checks: Exclude Dockerfile.template

- integration/containerd/cri/integration-tests.sh
if not present previously (otherwise, a backup would have existed).
Fixes: #4435
This is a forward-port of a comment made in #4469, a backport of #4436.
> integration/containerd: Remove Kata config

- .ci/ci_job_flags.sh
- .ci/run.sh
This PR removes the metrics experimental flag from the definition as well
as the run script as this is not being used in any CI for kata 2.0
Fixes #4527
> ci: Remove unused metrics experimental flag

- integration/containerd/cri/integration-tests.sh
Test TestContainerMemoryUpdate is deisabled by #4394,
re-enable it.
Fixes: #4525
> tess: enable TestContainerMemoryUpdate test

- .ci/ci_job_flags.sh
- .ci/run.sh
- functional/vfio/run.sh
- integration/qat/qat_test.sh
- metrics/density/memory_usage.sh
- metrics/lib/common.bash
- metrics/lib/json.bash
Generally speaking, the runtime type consists of 4 parts,
such as `io.containerd.runc.v1`, but `io.containerd.run.kata.v2`
may mislead users about how to name runtime type.
Fixes: #4531
> tests: unify runtime type to io.containerd.kata.v2

- .ci/run.sh
- Makefile
- functional/kata-monitor/run.sh
Include kata-monitor testing in our CI jobs.
Namely: add to CI_JOBs "CRIO_K8S" and  "CRI_CONTAINERD|CRI_CONTAINERD_K8S".
Since the current kata-monitor tests are quite basic and quick (less than one minute) shouldn't affect the CI pipeline that much.
Fixes #4506
> Add kata-monitor tests in CI jobs

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
This PR updates the lower limit for boot time for qemu in order to avoid
random failures related with showing less boot time in the metrics CI.
This is related with the change of the baremetal for the metrics CI.
Fixes #4538
> metrics: Update lower limit for boot time

- .ci/jenkins_job_build.sh
- Remove error message about missing spec of the Kata containers
repository. nounset takes care of this.
- Remove comment about running fast return check before static checks.
We have stopped doing this and there is no need to because we run the
static checks `--only-arch` and other checks are run in GHA.
Fixes: #4471
> ci: Remove some jenkins_job_build.sh cruft

- integration/kubernetes/init.sh
- integration/kubernetes/k8s-block-volume.bats
- integration/kubernetes/vfio.sh
`kubectl get nodes` returns all node names in lower case.
`hostname` returns the true host name, with capitalization honored.
This converts the hostname to lower case so that the master node
is successfully untainated for scheduling. Without this, the node
name is not recognized and the test fails with the error:
```
0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```
Fixes: #4502
Signed-off-by: Agam Dua <agam_dua@apple.com>
> ci: Fixed: convert nodename to lower case to match kubectl

- metrics/network/README.md
This PR updates the network documentation for kata 2.0 metrics.
Fixes #4555
> metrics: Update network documentation

- .github/workflows/add-pr-sizing-label.yaml
Created a new GitHub Action workflow file that adds a sizing label to
each PR.
Fixes: #4550.
> CI: Create GHA to add PR sizing label

- .github/workflows/add-pr-sizing-label.yaml
Change the secret used by the GitHub Action  that adds the PR size
label to one with the correct set of privileges.
Fixes: #4562.
> CI: Update GHA secret name

- .ci/configure_tracing_for_kata.sh
Change configuration section for agent tracing. Remove setting for
netmon since it is no longer a configuration option and for
internetworking model and network namespace since they are not relevant
for tracing in 2.x.
Fixes #4543
> tracing: Update tracing configuration script

- .ci/openshift-ci/build_install.sh
Dracut is used to build the image rootfs. Ensure the tool is installed
on the build environment.
Fixes #4564
> openshift-ci: Install dracut on build environment

- integration/cri-o/crio_skip_tests.sh
The cri-o integration test scrip skip failure test cases.
Ensure CI run BATS files 100% pass.
Fixes: #4489
Signed-off-by: Xiangchun Fu <xfu@redhat.com>
> ci: enable CI to run BATS files with 100% pass rate

- .ci/setup_env_centos.sh
setup_env_centos.sh appends some lines to package manager
config files, it makes too many duplicated lines in the
config files.
Since these config files are not edited manually too often,
so check the last line and append new lines only when needed.
Fixes: #4535
> setup: avoid appending duplicated lines to config files

- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/static-checks.sh
- functional/kata-monitor/run.sh
Fix the shell here document static check added on #3937 which detects
problems perfectly, but doesn't actually exit on error.
Fixes: #4568.
> CI: Make here document checker die on error

- .ci/ci_job_flags.sh
- .ci/run.sh
Currently the kata-agent integrates with skopeo to pull and verify
container images inside the guest. On the absence of skopeo, the agent
falls back to a (still) limited implementation. For example, without skopeo
the container policy file is not ignored, so images cannot be verified.
This adds the CC_SKOPEO_CRI_CONTAINERD job type which extends the
CC_CRI_CONTAINERD (added in commit 0678babef540884) configuration
so that skopeo is installed in the guest image. We will use that configuration
to test features which relies on skopeo.
Fixes #4572
> ci: add CC_SKOPEO_CRI_CONTAINERD CI job type

- integration/kubernetes/k8s-hugepages.bats
Sync and free pagecache, dentries and inodes before enabling hugepages.
Ensures enough hugepages can be allocated.
Fixes: #4575
/cc @liubin
> integration/k8s: Drop caches before hugepages

- .ci/run.sh
- tracing/test-agent-shutdown.sh
- tracing/tracing-test.sh
Since the current job that ran the tracing test is disabled, move it to
an existing job.
Fixes #4195
> tracing: Move tracing test to different job

- .ci/ci_job_flags.sh
- .ci/run.sh
As we're running those with QEMU only, let's improve the coverage and
add cloud-hypervisor to the possible tests.
Note: This is only addin the possibility to run the jobs, but the jobs
are not yet created.
Fixes: #4580
> CCv1 | ci: Add cloud-hypervisor to the CC specific jobs

- integration/cri-o/crio_skip_tests.sh
Seccomp tests seems to fail with kata for now.
We should skip them until we can investigate and fix.
Fixes: #4587
> ci: skip seccomp tests

- metrics/storage/README.md
This PR updates the storage README by removing the old references
for the fio benchmark that uses docker and is not part of the kata 2.x CI.
Fixes #4594
> docs: Update storage README

- cmd/checkcommits/README.md
- cmd/checkcommits/checkcommits.go
- cmd/checkcommits/checkcommits_test.go
This PR removes semaphore CI from checkcommits documentation and scripts as we
are not longer using this CI for kata 2.0
Fixes #4592
> checkcommits: Remove semaphore from documentation and scripts

- tracing/test-agent-shutdown.sh
- tracing/tracing-test.sh
tracing: Remove Jaeger container before starting
can be left over on permanent instances
---
tracing: Skip agent shutdown test on s390x
is unstable, see https://github.com/kata-containers/tests/issues/4597
Fixes: #4598
> tracing: Fix or skip on s390x

- .ci/aarch64/install_rom_aarch64.sh
It's better clone source code, including acpica and edk2, from a stable tag.
As there maybe some unkonw issue about qemu efi from linaro, which doesn't
work well with ata. So, only create qemu efi from souce code, until the issue is fixed.
Fixes: #4603
> uefi/arm64: optimize UEFI installation

- .ci/aarch64/install_rom_aarch64.sh
It's better clone source code, including acpica and edk2, from a stable
tag.
As there maybe some unknown issue about qemu efi from linaro, which doesn't
work well with kata. So, only create qemu efi from souce code, until the
issue is fixed.
Fixes: #4603
> backport: uefi/arm64: optimize uefi installation

- .ci/ci_clh_entry_point.sh
- .ci/ci_job_flags.sh
- .ci/install_cloud_hypervisor.sh
- .ci/install_runtime.sh
- .ci/run.sh
This will allow to test each cloud-hypervisor PR, and give us a head's
up on changes that will break Kata Containers, as we've faced in the
past.
Fixes: #4600
> ci: Add an external job for testing cloud-hypervisor

- .ci/setup_env_ubuntu.sh
- integration/containerd/confidential/agent_image.bats
- integration/containerd/confidential/lib.sh
- Update the enable full debug method to toggle all the debug flags on
kata's configuration.toml to ensure that hypervisor debug is enabled
- This seems to mean that logs are not streamed to the console socket
so we need to get them from the journal instead
Fixes: #4609
> ci: Enable full debug

- integration/kubernetes/cleanup_bare_metal_env.sh
in baremetal cleanup. Prior to saving iptables, all rules are removed,
but this is still required for the tracing test.
Fixes #4617
/cc @GabyCT @cmaf -- this is required because of https://github.com/kata-containers/tests/blob/08a08131669057c7c2de8c2428d38691979ec2ca/integration/kubernetes/init.sh#L178-L179 Please tell me if you think we should instead remove rules less aggressively in the first place there.
> integration/k8s: Re-add DOCKER iptables chain

- integration/qat/qat_test.sh
Share GOPATH with the QAT container, this container will use
the source code in GOPATH to try to build the image, this change
is needed to test if a pull request doesn't break QAT CI
Depends-on: github.com/kata-containers/kata-containers#3966
fixes #4624
> qat: share GOPATH with QAT container

- integration/containerd/confidential/fixtures/container-config.yaml
- integration/containerd/confidential/fixtures/container-config_signed-protected-other.yaml
- integration/containerd/confidential/fixtures/container-config_unsigned-protected.yaml
- integration/containerd/confidential/fixtures/container-config_unsigned-unprotected.yaml
- Update the names of the four cc test container config to be unique
- This allows them to run in the same pod
Fixes: #4637
> ci: Update test container config names

- cmd/checkmetrics/json_test.go
This PR updates the checkmetrics json_test.go to remove older components
that belonged to kata 1.x and update some componets for kata 2.0
Fixes #4639
> checkmetrics: Update json_test.go script

- integration/containerd/confidential/lib.sh
- Let the crictl_delete_cc_pod logic to work for pods with multiple
containers
Fixes: #4641
> ci: crictl _delete_cc_pod fix

- .ci/install_firecracker.sh
Starting with v0.23.2, firecracker binaries are relased in a tarball.
Prepare CI for that in order to bump the firecracker version from
v0.23.1 to v0.23.4 in the kata repo.
Fixes #4647
Depends-on: github.com/kata-containers/kata-containers#4011
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
Signed-off-by: Greg Kurz <groug@kaod.org>
> ci: Get firecracker binaries from the released tarball

- cmd/check-spelling/data/files.txt
This PR updates the correct link for documentation reference in
the files document.
Fixes #4663
> checkspelling: Update link in files document

- .ci/ci_clh_entry_point.sh
`make install` will overwrite the previous configuration and, if we
don't set DEFAULT_HYPERVISOR=cloud-hypervisor, the kata-containers'
makefile assumes DEFAULT_HYPEVISOR=qemu, which results in the CI running
with QEMU instead of Cloud Hypervisor.
Fixes: #4669
> ci,clh: Set DEFAULT_HYPERVISOR on kata reinstall

- cmd/log-parser/agent.go
- cmd/log-parser/agent_test.go
- cmd/log-parser/logentry.go
- cmd/log-parser/logentry_test.go
- cmd/log-parser/main.go
- cmd/log-parser/parse.go
- cmd/log-parser/parse_test.go
Adding a parameter to kata-log-parser to make it accept lines with
missing fields (name, source, level or pid).
Other checks are kept untouched.
Some tests have been added to verify this new behavior.
Fixes: #4632
> tests: kata-log-parser should not make an error for missing fields

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
This PR adjusts the blogbench value for cloud hypervisor for the
write operations in order to avoid random failures, the change
is related with the new release.
Fixes #4665
> metrics: Adjust blogbench value for cloud hypervisor

- cmd/github-labels/archive/labeler-original-labels-kata-containers-tests.yaml
This PR removes an unused github label as the User Guide does not exist
in kata 2.0 and this is referring to kata 1.x
Fixes #4671
> labels: Remove unused github label

- integration/kubernetes/k8s-replication.bats
This avoids intermittent failures in the CI
Fixes: #4653
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
Suggested-by: Greg Kurz <groug@kaod.org>
> k8s: Wait for k8s replication controller to show up

- functional/tdx/run.sh
tdx: Fix TDX availability message
If /sys/firmwware/tdx_seam is not present in the system, then Intel TDX
is **not** available there.
Fixes: #4673
---
tdx: Make it clear the tests is QEMU specific
Right now the tests is totally tied to QEMU, and we better make it
clear, failing in case someone tries to run it with a different
hypervisor.
---
@devimc, please, take a look.
> tdx: Fix TDX availability message and make it clear the test is QEMU specific

- cmd/github-labels/labels.yaml.in
This PR updates the url links for several github labels.
Fixes #4690
> labels: Update url links for github labels

- .ci/install_cri_containerd.sh
- Try and add the recommended safe diretory fix to resolve the
`unsafe repository <repo> is owned by someone else` error
Fixes: #4698
> ci: Attempt to fix git error

- .ci/aarch64/lib_install_qemu_aarch64.sh
- .ci/install_cri_containerd.sh
- .ci/install_qemu.sh
- .ci/lib.sh
- .ci/ppc64le/lib_install_qemu_ppc64le.sh
New git will check git repo's mode/permission, and will return error:
fatal: unsafe repository ('/some/path' is owned by someone else)
See:
https://github.blog/2022-04-12-git-security-vulnerability-announced/
for more information.
We have 3 repos run into this issue: kata-containers, containerd and
QEMU(only build from source for aarch64/ppc64le).
For the first two repos,
we can just use `git config --global --add safe.directory`.
But QEMU have
some submodules, we need to add all submodules to the safe
directory, so unlike kata-containers and containerd repos,
for QEMU we add `sudo -E` before commands run in the repo.
Fixes: https://github.com/kata-containers/tests/issues/4692
> qemu: use sudo to clone and make QEMU

- .ci/ci_job_flags.sh
- .ci/containerd_devmapper_setup.sh
- .ci/run.sh
- .ci/setup.sh
- integration/containerd/cri/integration-tests.sh
ci: Add USE_DEVMAPPER flag
Currently selecting whether devmapper should (or should not) be used as
the containerd snapshotter is done based on the HYPERVISOR used with
Kata Containers, leading the only testing it when using Firecracker.
In order to prepare the ground for adding new jobs, let's ensure we
un-tie its configuration from the hypervisor being used.
---
ci: Add cloud-hypervisor + devmapper CI
In order to ensure situations like the ones reported on the following
issues* won't happen again, let's add a new CI job covering Cloud
Hypervisor, running with containerd as the CRI Engine, having devmapper
as its snapshotter.
---
ci: Add QEMU + devmapper CI
In order to ensure situations like the ones reported on the following
issues* won't happen again, let's add a new CI job covering …
> ci: Add Cloud Hypervisor / QEMU jobs to test with the "devmapper" snapshotter

- integration/kubernetes/k8s-qos-pods.bats
This PR fix the syntaxis for qos tests by correcting the
position of the double quotation marks.
Fixes #4705
> kubernetes: Fix syntaxis for qos tests

- .ci/ci_job_flags.sh
It is not needed to export SECCOMP=yes for the Confidential Containers
jobs because the osbuilder's rootfs.sh script sets that variable by
default.
Fixes #4626
> ci/ci_job_flags.sh: Do not set SECCOMP=yes on CC jobs

- tracing/test-agent-shutdown.sh
- tracing/tracing-test.sh
Use trace forwarder in tracing test to forward agent spans in order to
include agent tracing in test.
Fixes #4634
> tracing: Enable agent tracing in test

- integration/containerd/confidential/agent_api.bats
- integration/containerd/confidential/agent_image.bats
- integration/containerd/confidential/asserts.sh
- integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml
- integration/containerd/confidential/run_tests.sh
- lib/common.bash
Added a e2e test to check that when a pod is created with an agent API
config that blocked certain endpoints that requests to these are rejected.
Fixes #4676
> tests: add test case for kata agent API configuration

- integration/containerd/confidential/agent_image.bats
- integration/containerd/confidential/lib.sh
ci: Enable ci build behind firewall    
For CI jobs behind firewall, we need pass the https_proxy to guest.
Current confidential CI did not utilize kubernetes coredns service, we
also need extract the dns from host. For the dns service provided by
systemd-resolved, we need get from file /run/systemd/resolve/resolv.conf
ci: Add TEE_TYPE flag for TEE enabled kernel/hypervisor
> CCv0: Enable TEE related CI behind firewall

- .ci/aarch64/lib_install_qemu_aarch64.sh
- .ci/install_cri_containerd.sh
- .ci/install_qemu.sh
- .ci/lib.sh
- .ci/ppc64le/lib_install_qemu_ppc64le.sh
New git will check git repo's mode/permission, and will return error:
fatal: unsafe repository ('/some/path' is owned by someone else)
See:
https://github.blog/2022-04-12-git-security-vulnerability-announced/
for more information.
We have 3 repos run into this issue: kata-containers, containerd and
QEMU(only build from source for aarch64/ppc64le).
For the first two repos,
we can just use `git config --global --add safe.directory`.
But QEMU have
some submodules, we need to add all submodules to the safe
directory, so unlike kata-containers and containerd repos,
for QEMU we add `sudo -E` before commands run in the repo.
Fixes: #4692
> backport-2.4: tests: fix unsafe repository for new versions of git

- tracing/test-agent-shutdown.sh
Trace mode was previously removed to simplify tracing; remove associated
configuration step from agent shutdown test.
Fixes #4720
> agent-shutdown: remove trace mode configuration

- cmd/log-parser/agent.go
The agent logging carte "slog" is using short naming for its log leveling,
this is causing the parser to log redundant/duplicated log levels such as
"erro"/"error", "warn"/"warning"... this patch groups the common log levels
See: https://docs.rs/slog/2.0.6/slog/static.LOG_LEVEL_SHORT_NAMES.html
Fixes: #4700
> log-parser: match agent log levels

- integration/rootless/rootless_test.sh
This added two more asserts to the rootless test:
- that the QEMU process is owned by the temporary non-root user
- that the QEMU files are owned by that user too.
Fixes #4654
> integration/rootless: add more asserts

- .ci/ci_job_flags.sh
- .ci/run.sh
- Makefile
In order to merge the Confidential Containers (CC) CCv0 branch into main (https://github.com/kata-containers/tests/issues/4441), there will be needed to differentiate the "vanilla" and "CC" builds of Kata Containers because the later depends on a [fork of containerd](https://github.com/confidential-containers/containerd). In other words, in some situations the scripts will need to tweak the code for CC. Thus, this pull requests introduces the `KATA_BUILD_CC` variable, which should be use exported in the environment (`export KATA_BUILD_CC=yes`) to indicate the build target is for CC.
Apart from this new variable, there are created:
1. the `CC_CRI_CONTAINERD` and `CC_CRI_CONTAINERD_CLOUD_HYPERVISOR`  CI job configurations. They will be used on near future to test more merges, being #4627 …
> Prepare to merge CCv0 into main: introduce the KATA_BUILD_CC variable

- .ci/aarch64/install_rom_aarch64.sh
- .ci/install_go.sh
- .ci/kata-simplify-log.sh
- .ci/vagrant-cleaner.sh
- cmd/check-spelling/kata-spell-check.sh
- cmd/container-manager/manage_ctr_mgr.sh
- cmd/pmemctl/pmemctl.sh
- metrics/lib/common.bash
Rework the scripts that used to define their own `die()`, `info()`
and/or `warn()` functions to use the standard versions defined in
`lib/common.bash`.
Fixes: #4702.
> scripts: Remove duplicated die/info/warn functions

- metrics/disk/cassandra_kubernetes/cassandra-tdx.sh
This PR adds the cassandra benchmark with tdx configuration.
Fixes #4730
> metrics: Add cassandra k8s + tdx

- README.md
- lib/common.bash
- lib/error.sh
Enhance the standard `die()` function to dump lots of information (in
YAML format) after displaying the error message when running under the
CI. The dump includes a full stacktrace and lots of environment details
to help with debugging.
> **Note:**
>
> The conventional way of displaying this additional information is by
> defining a `trap` handler. However, that technique cannot be used here
> as this is effectively a library and the callers of this library can
> (and do) define their own `traps` (and only one `trap` can be defined
> per signal).
Fixes: #4732.
> scripts: Make die show stacktrace and other info under CI

- cmd/check-spelling/data/projects.txt
- cmd/log-parser/README.md
- remove outdated kata v1 info (although it may still be valid)
- mention the cmdline options
- present jq processing examples
Fixes: #4712
> log-parser: update documentation with recent changes

- integration/containerd/confidential/agent_api.bats
- integration/containerd/confidential/agent_image.bats
- integration/containerd/confidential/asserts.sh
- integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml
- integration/containerd/confidential/tests_common.sh
This is a follow up of https://github.com/kata-containers/tests/pull/4677 where @stevenhorsman suggested to put common test code into a library. While here I changed the name of the `$start_date` variable to a more meaningful one.
> CCv0: refactoring common code into tests_common.sh

- .ci/openshift-ci/cluster/deployments/configmap_installer_qemu_4_10.yaml
- .ci/openshift-ci/cluster/install_kata.sh
- .ci/openshift-ci/images/Dockerfile.installer
- .ci/openshift-ci/images/entrypoint.sh
In order to update the job on OpenShift CI to test on 4.11 there is needed to adapt the installer script (among a few changes).
Fixes #4707
> ci: update scripts to support OpenShift 4.11

- .ci/ci_crio_entry_point.sh
CRI-O has moved to using golang 1.18+, for some time now.
Peter Hunt has approached us to do the bump as part of our CI as well.
Fixes: #4767
> crio: Update golang to 1.18+ in this specific CI

- README.md
This PR adds the missing commands that needs to be add when somebody
wants to run the .ci/setup.sh script in order to install the components
like the CI.
Fixes #4769
> docs: Add missing commands for the setup.sh documentation

- Makefile
- functional/tracing/test-agent-shutdown.sh
- functional/tracing/tracing-test.sh
Continuing part 1 (#4751)  and 2 (#4752)...
The tracing tests are conceptually functional testing, so moving them to the
right directory.
Fixes #4645
> Reorganize the tests - part 3 (move tracing to functional)

- Makefile
- README.md
- stability/agent_stability_test.sh
- stability/hypervisor_stability_kill_test.sh
- stability/soak_parallel_rm.sh
Continuing the part 1 (https://github.com/kata-containers/tests/pull/4751), this is going to create a `stability` directory out of `integration` to host any test related with stability/load testing.
Fixes #4645
> Reorganize the tests - part 2 (new stability directory)

- .ci/install_cloud_hypervisor.sh
- .ci/install_kata.sh
- .ci/install_virtiofsd.sh
- .ci/setup_env_alinux.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_opensuse.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_sles.sh
- .ci/setup_env_ubuntu.sh
As the very basic steps on the tests repo, we need to:
* Create a script to install virtiofsd;
* Ensure it gets installed for the supported architectures;
For this we can rely on the work that's been proposed on the kata-containers repo (see: https://github.com/kata-containers/kata-containers/pull/4233) and take advantage of the installation script already provided there (as already done for Cloud Hypervisor).
Fixes: #4784
> Add the needed support to start using the rust version of the virtiofsd

- .ci/configure_containerd_for_kata.sh
- integration/nydus/nydus_tests.sh
This PR updates the runc containerd runtime to use io.container.runc.v2
as we are using a containerd version > 1.4 and following the
https://github.com/containerd/containerd/blob/6b35307594841829c398ee8cf1100538867fcb82/docs/cri/config.md.
Fixes #4786
> ci: Update runc containerd runtime

- .ci/install_kata.sh
For x86_64, instead of installing both the C and the rust versions of
the daemon, let's just install the rust one as we have the tests passing
with it.
Fixes: #4788
Depends-on: github.com/kata-containers/kata-containers#4253
> virtiofsd: Do not install the C version of the daemon (x86_64)

- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_ubuntu.sh
The kata-webhook deployment script uses the openssl(1) command to create
SSL certificates. This changed the setup scripts of CentOS, Ubuntu, and
Fedora to ensure that tool is installed in the CI environment.
Fixes #4775
> setup: install openssl(1)

- .ci/install_cri_containerd.sh
This PR fix the misspelling for the CONTAINERD_ARCH variable
at the install script for containerd.
Fixes #4781
> ci: Fix misspelling for CONTAINERD_ARCH variable

- functional/tracing/test-agent-shutdown.sh
Modify agent shutdown test to detect hypervisor and run test with either QEMU or cloud hypervisor. The main changes are modifying the socket paths for the agent-ctl tool and socat and additional arguments since CLH uses hybrid VSOCK unlike QEMU.
> agent-shutdown: add CLH to agent shutdown test

- .ci/install_qemu.sh
For some reason it was not caught by the CI before, but the install_qemu
script looks for the virtiofsd in the location where it should be if
built and installed via QEMU.
This is not needed anymore, at least for x86_64, as we're using the rust
version of virtiofsd.
Fixes: #4791
> ci: Don't look for the C version of virtiofsd (x86_64)

- .ci/install_kata.sh
- .ci/install_qemu.sh
- .ci/install_virtiofsd.sh
- .ci/ppc64le/lib_install_qemu_ppc64le.sh
As rust based virtiofsd is supported to build on non-x86_64, use it
as the default virtiofsd.
Fixes: #4795
Depends-on: github.com/kata-containers/kata-containers#4276
> virtiofsd: install standalone virtiofsd for non-x86_64

- .ci/lib.sh
- README.md
Fix the problem of getting the QEMU from cache (main branch)
* ci/lib.sh: fix sha256sum_from_files() not picking all files
* README: fix broken urls
> stable 2.4 | Fix QEMU cache resolution

- .ci/install_virtiofsd.sh
- .ci/openshift-ci/build_install.sh
This fixes the scripts so that virtiofsd (rust) is proper installed in the OpenShift CI environment.
Fixes #4798
> Adapt Openshift CI for the virtiofsd-rs

- .ci/install_kata.sh
- .ci/install_qemu.sh
- .ci/install_virtiofsd.sh
- .ci/ppc64le/lib_install_qemu_ppc64le.sh
Merge remote-tracking branch 'upstream/main' into CCv0
Fixes: #4808
Depends-on: github.com/kata-containers/kata-containers#4314
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>
> CCv0: Merge main into CCv0 branch

- .ci/ci_crio_entry_point.sh
CRI-O v1.24.0 has been released on May 10, and we should ensure we're
using it together with an equivalent version of cri-tools and k8s.
While here, let's follow a recommendation from Sascha Grunert, and bump critools to
v1.24.2 when testing the 1.24.x release of CRI-O.
Fixes: #4813
> crio: Update `latest_release` to v1.24.x

- integration/kubernetes/init.sh
kubeadm adds this new taint on kubernetes 1.24+.
Fixes: #4815
> k8s: Untaint control-plane nodes

- .ci/static-checks.sh
Third-party files may include a file named THIRD-PARTY,
this file should not be checked for license header anymore.
Fixes: #4833
> ci: ignore license header check for THIRD-PARTY file

- metrics/disk/cassandra_kubernetes/cassandra.sh
This PR expands the cassandra stress write results so we can gathered
latency, latency mean, latency 95th percentile and latency 99th percentile.
Fixes #4831
> metrics: Expand cassandra stress write results

- metrics/disk/cassandra_kubernetes/cassandra.sh
This PR adds the read operation for cassandra benchmark.
Fixes #4835
> metrics: Add read operation for cassandra benchmark

- integration/containerd/shimv2/shimv2-tests.sh
This PR removes the skip for some integration containerd shimv2 tests
as this is not longer a problem.
Fixes #4839
> tests: Remove skip for integration containerd shimv2 tests

- .ci/run.sh
Disable agent shutdown test and tracing test due to the socat repo being
down, which is affecting the CI. An attempt at using a mirror repo
failed because the version did not support VSOCK, which is required for
the agent shutdown test.
Fixes #4847
I commented the relevant lines out following the format for the disable PMEM test.
> tracing: Temporarily disable tests

- functional/tracing/test-agent-shutdown.sh
- functional/tracing/tracing-test.sh
We do not need to run the tracing test on more than one CI job
(jenkins-ci-ubuntu-20-04), disable for additional job.
Fixes #4845
> tracing: Disable test qemu-devmapper job

- .ci/jenkins_job_build.sh
Change the snap command to use `--debug`
after the version change.
Fixes: #4851
> ci: fix snap cli option

- .ci/install_qemu.sh
As we're currently installing the standalone rust version of virtiofsd
for all the architectures, we can stop looking for the virtiofsd that
comes with QEMU, as we also stopped building it for all the
architectures.
Fixes: #4811
Depends-on: github.com/kata-containers/kata-containers#4308
> ci: Stop looking for virtiofsd files when installing QEMU

- .ci/run.sh
The socat repo is accessible again; re-enable agent shutdown and tracing
tests.
Fixes #4859
> agent shutdown: tracing: Re-enable tests

- .ci/install_kata_kernel.sh
Adding another case to the CI's kernel builder for sev.
Depends on https://github.com/kata-containers/kata-containers/pull/4180 this PR in kata for additions to the kernel builder for efi_secret which is needed for SEV.
Fixes #4837
Signed-off-by: Alex Carter [alex.carter@ibm.com](mailto:alex.carter@ibm.com)
@fitzthum @larrydewey @ryansavino
> ci: add sev build option for kernel

- .ci/lib.sh
This PR removes an unused variable for KATA_OBS_REPO which belonged
to a reference that we used in kata 1.x but not longer at kata 2.x
Fixes #4869
> ci: Remove unused variable for KATA_OBS_REPO

- functional/kata-monitor/run.sh
- integration/containerd/confidential/fixtures/pod-config.yaml.in
- integration/containerd/confidential/lib.sh
- integration/containerd/confidential/tests_common.sh
- integration/containerd/cri/integration-tests.sh
- integration/nydus/nydus-sandbox.yaml
- integration/nydus/nydus_tests.sh
CCv0: Add uid to the crictl pod-config yaml to fix the crictl 1.24.1 compatibility problems
Fixes: #4875 
> CCv0: Add uid to the crictl pod-config yaml

- metrics/storage/fio-k8s/cmd/fiotest/main.go
This PR enables the support of the --numjobs flag to the FIO kubernetes
storage test.
Fixes #4879
> metrics: Add --numjobs flag support for FIO test

- .ci/ci_job_flags.sh
- .ci/install_kata_image.sh
- Makefile
- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/agent_image_encrypted.bats
- integration/kubernetes/confidential/lib.sh
Add tests to pull an encrypted image and create a CC pod with Kubernetes
Fixes: #4685
Signed-off-by: Megan Wright <megan.wright@ibm.com>
Co-authored-by: Georgina Kinge <georgina.kinge@ibm.com>
> CCv0: Kubernetes CC pod creation with encrypted image

- metrics/storage/fio-k8s/cmd/fiotest/main.go
This PR redirects the FIO output to /home directory instead of /tmp directory
to make sure we are not excercising memory.
Fixes #4886
> metrics: Redirect output for FIO benchmark

- integration/confidential/lib.sh
Due to the changes introduced as part of
https://github.com/kata-containers/kata-containers/pull/4565, we should
adjust the regular expression used for switching the configuration on.
Fixes: #4894
> CC | confidential: Adjust switch_image_service_offload()

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR adds iperf3 parallel measurements which measures the
bandwidth of simultaneos connections make to the server.
Fixes #4899
> metrics: Add iperf3 parallel measurements

- .ci/run_metrics_PR_ci.sh
- metrics/lib/common.bash
- metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR adds the start and end kubernetes functions to the common script
for metrics as these functions will be used in other metrics benchmarks
that will use kubernetes.
Fixes #4904
> metrics: Create a common for kubernetes

- .github/workflows/commit-message-check.yaml
When this github action was ported over from kata-containers, I changed
the body length limit to 72 to match the community contribution
documentation. However, in the kata-containers repo it was changed back
to 150 after 72 was decided to be too short.
The community contribution documentation is being changed to 150, so
this should be changed to be consistent.
Fixes #4913
Signed-of-by: Derek Lee <derlee@redhat.com>
> ci: change commit body line limit from 72 to 150

- cmd/check-spelling/data/projects.txt
Noticed CONTRIBUTING.md in the community repo was not passing spell
check due to "rustlang". "golang" is already in the dict, so added
"rustlang" to projects.txt dictionary.
Fixes #4917
Signed-off-by: Derek Lee <derlee@redhat.com>
> spell-check: Add 'rustlang' to spell check dictionary

- .ci/install_qemu.sh
As per the confirmation that `build-static-qemu.sh` from `kata-container`
works for s390x, it makes sense to turn on caching for the architecture.
The corresponding Jenkins job has been created and tested:
http://jenkins.katacontainers.io/job/kata-containers-2.0-qemu-s390x/
Fixes: #4920 
> build: Enable QEMU cache for s390x

- .ci/run.sh
- .ci/setup_env_ubuntu.sh
- functional/kata-monitor/run.sh
- functional/tracing/test-agent-shutdown.sh
- functional/tracing/tracing-test.sh
- functional/vcpus/default_vcpus_test.sh
- integration/ksm/ksm_test.sh
- integration/kubernetes/k8s-hugepages.bats
- integration/nydus/nydus_tests.sh
This PR adds the suppor for ubuntu 22.04 in order to have it
in our kata CI.
Fixes #4901
Depends-on: github.com/https://github.com/kata-containers/kata-containers/pull/4397
> ci: Add support for ubuntu 22.04

- .github/workflows/commit-message-check.yaml
Allows merges not down via PRs not to be flagged by the commit checker.
Lines that start with 'Merge ' will be accepted alongside commits with a
subsystem of the form 'subsystem: '.
Fixes #4929
Signed-off-by: Derek Lee <derlee@redhat.com>
> ci: Allow commits to start with 'Merge' instead of subsystem

- metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-sync.job
This PR adds the support for sync engine configuration to gathered synchronous
FIO test results.
Fixes #4930
> metrics: Support sync engine configuration for FIO tests

- .ci/run.sh
This PR skips the nydus integration test to allow unblock the kata CI
until the issue is resolved.
Fixes #4948
> tests: Skip nydus integration test

- metrics/storage/fio-k8s/Makefile
- metrics/storage/fio-k8s/cmd/fiotest/Makefile
This PR will add a new rule that will help us to run the FIO test
in the metrics kata CI.
Fixes #4950
> makefile: Add rule for fio test for kata CI

- metrics/storage/fio-k8s/configs/example-config/fio-jobs/randrw-async.job
This PR adds the asynchronous job FIO configuration using as
an engine io_uring.
Fixes #4945
> metrics: Add asynchronous job FIO configuration

- integration/kubernetes/confidential/agent_image_encrypted.bats
remove skopeo since it's not longer needed.
Fixes #4903
Signed-off-by: Tong Luo <tong.luo1@ibm.com>
> CC | test: no longer skip two tests

- versions.yaml
This PR updates the xurls version that is being used in kata containers.
Fixes #4958
> versions: Update xurls version

- .ci/install_runtime.sh
When hypervisor is dragonball, it will compile runtime-rs with cargo.
So need to install rust environment first.
> ci: install rust for runtime-rs

- .ci/install_runtime.sh
- integration/kubernetes/run_kubernetes_tests.sh
add sudo when compile runtime-rs and enable the case: k8s-seccomp.bats
because it's already fixed: https://github.com/kata-containers/kata-containers/pull/4692
> ci: add sudo when compile runtime-rs and enable k8s-seccomp.bats

- stability/soak_parallel_rm.sh
The case 'soak_parallel_rm.sh' will check the files in VC_POD_DIR.
However, for a brand new test machine, the path VC_POD_DIR doesn't
exist.
> ci: check if VC_POD_DIR exists before checking the files in VC_POD_DIR

- .ci/ci_job_flags.sh
This PR removes a duplicated kubernetes flag as by default
kubernetes is being set to no.
Fixes #4974
> ci: Remove duplicated kubernetes flag

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
This PR increases the boot time value for qemu as it seems that
adding liburing to build qemu does that.
Fixes #4963
Depends-on: github.com/kata-containers/kata-containers#4646
> metrics: Increase boot time value for qemu

- integration/kubernetes/k8s-kill-all-process-in-container.bats
- integration/kubernetes/run_kubernetes_tests.sh
- integration/kubernetes/runtimeclass_workloads/initcontainer-shareprocesspid.yaml
When a container terminated in shared process pidns pod,
we should check whether all of the processes especially the
daemon process created in a container had terminated.
Fixes: #4936
Signed-off-by: Fupan Li <fupan.lfp@antgroup.com>
> k8s: Add an integration test for checking process leak

- .ci/install_firecracker.sh
In the latest FC releases, the asset we download and decompress has the following syntax:
release-vX.X.X-ARCH/firecracker-vX.X.X-ARCH
until v0.25 there was no ARCH in the folder name. Since we are updating the supported FC version, this patch fixes the script that installs the firecracker binary and the jailer.
Depends-on: github.com/kata-containers/kata-containers#4735
Fixes: #4967
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
> fc: fix uncompressed dir path

- metrics/storage/fio-k8s/fio-test-ci.sh
This PR adds a script that will be used in our kata metrics CI
so we can collect FIO measurements.
Fixes #4965
> metrics: Add script to run FIO in metrics CI

- .ci/run_metrics_PR_ci.sh
- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/storage/fio-k8s/Makefile
- metrics/storage/fio-k8s/fio-test-ci.sh
This PR enables FIO read tests to be measured at our kata metrics CI.
Fixes #4981
> metrics: Enable FIO read tests

- .ci/install_kata.sh
SEV tests need kata to be configured based on the selected TEE TYPE. This change ensures that the correct kernel build is made based on previous functionality from #4838
Fixes: #4896
Signed-off-by: Alex Carter <alex.carter@ibm.com>
> ci: set SEV TEE_TYPE

- .ci/static-checks.sh
~~Adds a user agent of '/' to the check_url curl.~~
https://amd.com has a denylist for certain user-agents including the
lack of a user-agent
'/' is the shortest string that gets past the denylist
~~To avoid being non-generic, I opted not to use any real user-agent.
In other projects, 'curl' is used as the user-agent, however, this is
denylisted by amd.com.~~
The denylist also seems to keep a running list of browser versions it
finds acceptable if the browser is mentioned (i.e.the string
Firefox/71.0 works if it is in the user-agent, but not Firefox/ or
Firefox/70.0. ~~Because of this, I opted not to include any real browsers.~~
~~As far as I can tell from the issue the only site that the project had
problems with was https://amd.com, which does not currently denylist
just '/'. I did not …
> ci: Add generic user agent to check_url

- .ci/run.sh
- Makefile
- integration/containerd/runk/runk-tests.sh
Use runk as the default OCI runtime of containerd to validate runk's
commands. Tests includes creating containers, exec a process, kill and
delete containers.
Fixes #4882
Signed-off-by: Chen Yiyang <cyyzero@qq.com>
> runk: add tests for runk

- .ci/run_metrics_PR_ci.sh
- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/network/latency_kubernetes/latency-network.sh
This PR enables the latency network measurements in our kata metrics
CI.
Fixes #4993
> metrics: Enable latency network measurement

- lib/common.bash
This PR improves the ctr cleanup function as it was seen than when we
are using RunC the current cleanup is not able to delete properly
the containers as we got an error saying that we can't delet
non stopped containers. This PR fixes that issue as it was tested
both on RunC and Kata and is working properly.
Fixes #4995
> common: Improve ctr cleanup

- metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR deletes the iperf3 server and client pods in
order to leave properly clean the environment after
running the network iperf3 tests.
Fixes #5000
> metrics: Delete iperf3 server and client pods

- metrics/storage/fio-k8s/pkg/k8s/k8s.go
Delete the prefix space when calling external command.
Fixes: #4998
> metrics: delete space in command string

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/storage/fio-k8s/fio-test-ci.sh
This PR enables the 90, 95 and 99 read percentile FIO metrics in
our kata metrics CI.
Fixes #4989
> metrics: Enable read percentile fio metrics

- metrics/density/memory_usage.sh
This PR uses the clean_env_ctr function that is being implemented
in the common.sh script to make uniform its used across the scripts.
Fixes #5003
> metrics: Use clean_env_ctr function in memory script

- .ci/setup_env_ubuntu.sh
Install the extra protoc packages required to build ocicrypt-rs
Fixes: #5013
> CC | ci: Add protoc to dependencies

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/storage/fio-k8s/fio-test-ci.sh
This PR enables the write io and bw using FIO to collect this
data in our kata CI.
Fixes #5005
> metrics: Enable write io and bw for FIO metrics

- metrics/density/memory_usage.sh
This PR removes the docker path that was used in kata 1.x for RunC
in the memory usage script. This PR updates the ctr shim path for
RunC in the memory usage script as now we are using ctr instead of
docker so we can measure correctly the pss memory.
Fixes #5011
> metrics: Update ctr shim path for RunC

- .ci/lib.sh
For the stale files under .cargo/ may block the cargo build.
It's better to clean up the whole rust environment before move
into test.
Fixes: #5020
> ci/lib: clean up rust environment before test

- .ci/run.sh
Nydus test is more complext and relies on third party components.
Let's move it to after simpler stability checks so that it makes life
easier to diagnose failures.
Fixes: #5034
> ci: move nydus test to after stability

- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
metrics: Increase midval of memory-footprint and memory-footprint-ksm
Increase midval of memory-footprint and memory-footprint-ksm to handle the memory-footprint issue when add wasm function to kata-agent.
Depends-on: github.com/https://github.com/kata-containers/kata-containers/pull/4032
Fixes: #4696
Signed-off-by: Hui Zhu <teawater@antgroup.com>
> metrics: Increase midval of memory-footprint and memory-footprint-ksm

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- metrics/storage/fio-k8s/fio-test-ci.sh
This PR enables write FIO percentiles in our kata metrics CI.
Fixes #5018
> metrics: Enable write FIO percentiles

- integration/containerd/runk/runk-tests.sh
This PR corrects a misspelled work in the runk tests that are running
in the kata CI.
Fixes #5044
> tests: Correct misspelled word in runk tests

- .ci/install_runtime.sh
The variable $USER is used on some chown operations in
.ci/install_runtime.sh. But that variable can be unset, for example, in
a container. The script was changed to fallback to `id -u` in case $USER
is not set. Also it is now passing group id to chown, as '<id number>:'
raises an error.
Fixes #5049
> ci/install_runtime: fix unbound variable

- metrics/density/footprint_data.sh
This PR updates the footprint data script for kata metrics CI.
It removes flags that are not longer supported by ctr.
Fixes #5055
> metrics: Update footprint data script

- metrics/disk/cassandra_kubernetes/cassandra.sh
This PR removes the StatefulSet in the Cassandra k8s test for
the metrics tests.
Fixes #5051
> metrics: Delete statefulset in Cassandra test

- cmd/container-manager/manage_ctr_mgr.sh
This PR updates the help message to reference Kata Containers
instead of Clear Containers when the mange ctr mgr script
is being used.
Fixes #5066
> ci: Update help message in manage ctr mgr script

- .ci/install_runtime.sh
Let's ensure we use functions provided in the CI for setting up the
proper runtime configuration.
This is a regression introduced by the following commit:
https://github.com/kata-containers/tests/commit/87dd763ab43516268b69b847c25fc20d7c8e8b3f
Fixes: #5069
> install_runtime: Cleanup TDX configuration

- integration/containerd/runk/runk-tests.sh
Add test cases for `pause`/`resume` commands. It should work well on
both cgroup v1 and v2 environment. Exec a process which produces
massages into a file, pause it and check messages are not produced
anymore. Then resume it, and check whether messages are produced again.
Depends-on: github.com/kata-containers/kata-containers#4870
Fixes: #5014
Signed-off-by: Chen Yiyang <cyyzero@qq.com>
> runk: add tests for `pause`/`resume` commands

- .github/workflows/add-pr-sizing-label.yaml
Removes man-db from add-pr-sizing-label action because it sometimes
errors and fails. This does not always occur, but as man-db shouldn't be
needed for any reason, it's probably useful just to remove it.
Same as #4864 in kata-containers/kata-containers
Fixes #5057
Signed-off-by: Derek Lee <derlee@redhat.com>
> github-actions: Remove man-db from add-pr-sizing-label

- metrics/disk/cassandra_kubernetes/cassandra.sh
This PR adds the removal for PVC in the Cassandra metrics test, this
will avoid the issue that when we are removing the PVC it gets stuck
in "terminating" status for a while and will allow the final
unmount from the node so that PVC can be properly delete it.
FIxes #5075
> metrics: Remove pvc in cassandra metrics test

- integration/cri-o/crio_skip_tests.sh
This test was passing, but the test actually checks for failure,
and we were failing for the wrong reasons.
Also adding links to all tests related to the same root cause.
Fixes: #5071
> Skip additional test from shm_size.bats

- lib/common.bash
kata-runtime for CC might be installed in /opt/confidential-containers/bin so not in
PATH. Even if the caller of `cp_to_guest_img()` re-export `PATH=$PATH:/opt/confidential-containers/bin`
the `kata-runtime` won't be found because `sudo` doesn't export the current `PATH` into
the sub-process.
We don't need to run `kata-runtime kata-env` as privileged user. So let's avoid that mess
by simply not using `sudo`.
Fixes #5077
> CCv0 | ci/lib: run kata-runtime as non-sudo in cp_to_guest_img()

- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/agent_image_encrypted.bats
- integration/kubernetes/confidential/lib.sh
This patch set is needed in order to get the current `cc-kubernetes` jobs passing in the TDX capable CI.
---
k8s: Make confidential tests aware of the proxy
Right now the confidential tests are not aware of the proxy, which leads
to failures on the TDX CI, as this CI runs inside Intel network.
Fixes: #5082
---
k8s: confidential: Use `kubernetes_create_cc_pod`
Instead of duplicating the code for creating and checking whether a
pod's been created, let's take advantage of the already present
`kubernetes_create_cc_pod` function.
---
k8s: confidential: Fix identation in `kubernetes_create_cc_pod`
We're using tabs instead of spaces in this file.
---
k8s: confidential: Increase the wait timeout to 60s
Let's double the wait timeout as I've noticed, in the internal TDX CI,
that pulling the image …
> confidential: Adjust Kubernetes confidential jobs for TDX capable CIs

- .ci/lib.sh
- integration/kubernetes/confidential/lib.sh
This is a couple of fixes to allow us to run the cc-kubernetes tests (integration/kubernetes/confidential/agent_image_encrypted.bats) from the CI for the operator.
Fixes #5077
> CCv0 | Allow to run cc-kubernetes tests from operator CI

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
This PR updates the write percentiles in FIO test, we have seen a
reduction in the mean number.
Fixes #5084
> metrics: Fix write percentiles in FIO test

- .ci/install_cloud_hypervisor.sh
- .ci/install_kata.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/install_td_shim.sh
- .ci/install_tdvf.sh
- .ci/install_virtiofsd.sh
- .ci/lib.sh
Adapted the CI build and installation scripts to use kata-deploy. As a rule, they will run `make cc-<artifact>-tarball` then uncompress the resulting tarball on '/'. The variable `KATA_BUILD_CC=yes` should be exported (it is on the CC jobs) and the installation will live under `/opt/confidential-containers`.
Important: the cache for QEMU and Kernel are ignored as for making it work properly it would need a major refactoring on the code and the creation on new cache jobs.
Fixes #4893
> CCv0 | CI: build and install artifacts with kata-deploy

- .github/workflows/commit-message-check.yaml
Some generated merge commit messages are >75 chars
Allow these to not trigger the subject line length failure
Fixes: #5096
Signed-off-by: Megan-Wright <megan.wright@ibm.com>
>     CCv0 | static-checks: Allow Merge commit to be >75 chars

- .ci/install_cni_plugins.sh
- integration/kubernetes/init.sh
This PR updates the cni plugins version that is being used in the
kata CI.
Fixes #5087
Depends-on: https://github.com/kata-containers/kata-containers/pull/5040
> versions: Update cni plugins version

- metrics/disk/cassandra_kubernetes/cassandra.sh
This PR removes the persistent volume that we have in our
Cassandra metrics test.
Fixes #5098
> metrics: Remove persistent volume in Cassandra

- integration/kubernetes/confidential/lib.sh
In retrieve_sandbox_id() the output of `ps -ef` is parsed, the regex looks for
occurencies of "id". Currently the regex expect an extra space after the
id number which can lead to not getting the id.
This commit changed the regex used to a more accurate one.
Fixes https://github.com/kata-containers/tests/issues/5077
> CCv0 | kubernetes/lib: fix regex in retrieve_sandbox_id()

- .ci/install_cloud_hypervisor.sh
- .ci/install_kata.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/install_td_shim.sh
- .ci/install_tdvf.sh
- .ci/install_virtiofsd.sh
- .ci/lib.sh
This is, unfortunately, needed as `make kata-tarball` (and similars) are
not currently working as expected behind a proxy.
See: https://github.com/kata-containers/kata-containers/issues/5077
Once that one is fixed, we can revert this commit.
> CC | Revert #5048 as it exposed proxy issues with the kata-deploy builds

- lib/common.bash
In order to allow the CC how-to dev instructions to run as a non-root user
we need to run kata-runtime as sudo, but we should pass through the
PATH to ensure sudo can access it.
Fixes: #5107
> ci: Add sudo's to kata-runtime commands in CC code

- .ci/static-checks.sh
- .github/workflows/main.yml
Add github user authentication to check_url to increase rate limit from
60 to 5000.
Only if GITHUB_USER is defined and GITHUB_TOKEN is defined.
Changed main.yaml to export secrets.GITHUB_USER and secrets.GITHUB_TOKEN into environment variables.
Fixes #4304
Signed-off-by: Derek Lee derlee@redhat.com
> ci: Add authentication for github domains in check_url

- metrics/README.md
This PR includes the read and write percentile measurments that we
currently have when we run FIO in our metrics Kata CI.
Fixes #5109
> docs: Include read and write percentile measurements

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
This PR updates the jitter value that we have when we ran this
network metric on the kata metrics CI.
Fixes #5111
> metrics: Fix the jitter value

- metrics/network/latency_kubernetes/latency-network.sh
This PR adds the init_env function to latency test to verify that some dependencies are installed as well to get the test banner.
Fixes #5117
> metrics: Add init_env to latency test

- cmd/check-spelling/data/projects.txt
- Add crictl to the dictionary to avoid spell check and work around the link checker failing to parse the heading with backticks
Fixes: #5124
> spell-check: Add crictl to dictionary

- .ci/ci-fast-return.sh
- .ci/lib.sh
- .ci/static-checks.sh
- README.md
- cmd/github-labels/labels.yaml.in
- cmd/history/history.sh
- versions.yaml
So that we run tests with the correct stable branch.
> stable-3.0: update links to stable-3.0

- integration/containerd/confidential/agent_image.bats
- integration/kubernetes/confidential/agent_image.bats
- To try and minimise the kernel_params changes that we do, only add the `agent.container_policy_file` if we need it for skopeo. This means it shouldn't trigger in the operator CI
Fixes: #5137
> ci: Add skopeo guard to config change

- metrics/time/launch_times.sh
This PR updates the boot time test that we are using for the kata metrics CI.
Fixes #5142
> metrics: Update boot time test

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
This PR adjust minimum value limits for FIO tests to avoid random failures in the metrics CI.
Fixes #5149
> metrics: Adjust limits for FIO tests

- integration/kubernetes/confidential/agent_image_encrypted.bats
- integration/kubernetes/confidential/lib.sh
For CC test cases, image will be pulled inside guest and the test cases may run behind firewall, launch time may not stable, increase the wait timeout to avoid random failure due to timeout.
Fixes: #5144
Signed-off-by: Wang, Arron <arron.wang@intel.com>
> k8s: Increase default timeout for CC tests

- integration/cri-o/crio_skip_tests.sh
One of those tests is already skipped, but was renamed. The other is similar. In both cases, the integration test is checking the behaviour of cri-o with default runtimes, which is irrelevant for kata, where the runtime is different anyway.
Those tests need to be skipped.
Fixes: #5156
> Skip additional tests on cri-o CI

- lib/common.bash
- stability/soak_parallel_rm.sh
This PR removes the kill container functions which is a duplicated
of the clean_env_ctr function that we have in the common.sh script.
It also makes general improvements to the clean_env_ctr function.
Fixes #5164
Co-authored-by: David Esparza <david.esparza.borquez@intel.com>
> tests: Improve the clean_env_ctr function for the soak parallel test

- .ci/static-checks.sh
Add user agent back into curl request after it was removed in #4883
Fixes: #5185
> ci: Add user agent back into curl request

- .ci/openshift-ci/qemu-build-pre.sh
On OpenShift CI the tools/packaging/static-build/qemu/Dockerfile have some arguments (ARG) replaced. It is missing the replacement of HYPERVISOR_NAME, that has drive to the qemu build to fail.
Fixes #5173
> openshift-ci: fix build of QEMU

- metrics/storage/blogbench_dockerfile/Dockerfile.in
This PR removes a comment referring a command which is not longer used in the blogbench Dockerfile.
Fixes #5193
> metrics: Remove comment in Dockerfile for blogbench

- integration/kubernetes/run_kubernetes_tests.sh
Enable k8s-empty-dirs.bats for runtime-rs.
Fixes: #5160
Depends-on:github.com/kata-containers/kata-containers#5282
> runtime-rs: enable k8s-empty-dirs.bats test

- .ci/install_virtiofsd.sh
As the build of the virtiofsd was changed to be done inside a container as part of https://github.com/kata-containers/kata-containers/pull/5426, there's no need to install rust on the host.
Fixes: #5200
Depends-on: github.com/kata-containers/kata-containers#5426
> virtiofsd: Do not install rust

- integration/kubernetes/confidential/agent_image_encrypted.bats
We only want to run kubernetes_delete_ssh_demo_pod_if_exists if the
ssh-demo pod exists, so lets select for this pod using the label to try
and ensure we don't pick up other pods.
Fixes: #5100
> ci: Add label selector to pod listing

- cmd/history/history.sh
This PR removes extra blank spaces at the history script.
Fixes #5203
> cmd: Remove blank spaces at history script

- .ci/install_cloud_hypervisor.sh
- .ci/install_kata.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/install_td_shim.sh
- .ci/install_tdvf.sh
- .ci/install_virtiofsd.sh
- .ci/lib.sh
- .ci/setup.sh
Those commits were reverted because we faced an issue running docker inside docker behind proxy.  This issue is now addressed by https://github.com/kata-containers/kata-containers/pull/5323 and https://github.com/kata-containers/kata-containers/pull/5324, which allows us to re-revert the work.
> CC | Re-revert build ci artefacts using kata deploy scripts

- integration/confidential/lib.sh
- integration/containerd/confidential/agent_image.bats
- integration/containerd/confidential/asserts.sh
- integration/containerd/confidential/tests_common.sh
- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/agent_image_encrypted.bats
Measured Boot Image/Rootfs feature will broken current test cases since these test cases will modify the rootfs.
Add two new test cases for measured boot.
Fixes: #5214
Depends-on: github.com/kata-containers/kata-containers#5136
Signed-off-by: Wang, Arron <arron.wang@intel.com>
> ci: Add test cases for measured boot image/rootfs

- .ci/static-checks.sh
`*.bin` files are binary and cannot include a license or copyright header; skip them, similarly to other binary files (`*.jpg`, `*.png`, etc.).
Fixes: #5207
Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>
> CCv0: ci: Ignore license header check for *.bin files

- .ci/jenkins_job_build.sh
This is to revert the change at #4414 because
no error is found on the pod deletion on s390x any more. The error was reported at #3998.
NOTE: This should not be merged before https://github.com/kata-containers/kata-containers/pull/5523.
Fixes: #5221
> ci: Switch back to virtiofsd on s390x

- integration/confidential/lib.sh
- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/agent_image_encrypted.bats
- integration/kubernetes/confidential/lib.sh
Now we can pass in aa_kbc_params via command line, we don't need to mess about with the agent-config.toml file
Depends-on: github.com/kata-containers/kata-containers#5533
Fixes: #5226
> ci: Simplify aa_kbc_params setting

- functional/sev/run.sh
- integration/confidential/lib.sh
- integration/containerd/confidential/agent_image.bats
Update tests that need the signature verification to be enabled, by removing the default kernel_param that disables it
Depends-on: github.com/kata-containers/kata-containers#5552
Fixes: #5228
> ci: Set-up sig verification config for tests

- integration/containerd/runk/runk-tests.sh
Low level container runtime like runk should allow kill --all regardless of the container state. This follows the implementation of runc.
Fixes: #5232
Signed-off-by: Chen Yiyang <cyyzero@qq.com>
> Runk: add test case for kill command with --all option

- integration/confidential/lib.sh
cosign support brought in a dependency that doesn't work on s390x so skip those tests for this architecture
Fixes: https://github.com/kata-containers/tests/issues/5241
Depends-on: github.com/https://github.com/kata-containers/kata-containers/pull/5600
> tests: skip s390x cosign tests

- integration/kubernetes/run_kubernetes_tests.sh
add k8s-expose-ip.bats, k8s-liveness-probes.bats and
k8s-nginx-connectivity.bats k8s CI tests into Dragonball CI.
fixes: https://github.com/kata-containers/tests/issues/5237
Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>
> Dragonball CI: add support for several k8s CI

- integration/confidential/lib.sh
The tests for confidential containers were implemented so that changes for the containerd configuration file are required. For example, the needed to pass the `cri_handler`. However, when those tests are ran from the operator CI, the containerd is already proper configured. Moreover, changing containerd's configuration can break it completely.
This commit changed the logic of configure_cc_containerd() so that if `TESTS_CONFIGURE_CC_CONTAINERD=no` is exported then the function simply does nothing.
Fixes #5077
> confidential/lib: allow to disable configure_cc_containerd()

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
- cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-sv-c1-small-x86-01.toml
This will fixed the metrics limits after they were affected by the golang bump to 1.19
e4406df1 metrics: Fix iperf3 bandwidth limit for clh
da102334 metrics: Fix blogbench write value for clh
278bf987 metrics: Fix read blogbench limit for qemu
11c9578d metrics: Fix write blogbench limit for qemu
447785f4  metrics: Fix boot time value for clh
75775446 metrics: Fix parallel bandwidth for clh
57bf2d64 metrics: Fix blogbench read value for clh
68d4780d metrics: Fix value for network jitter for clh
> metrics: Fix limits values

- integration/nydus/nydus_tests.sh
We can just use `nydusd` as the binary name for v2.1.0 and plus.
Depends-on: github.com/kata-containers/kata-containers#5638
Fixes: #5245
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
> integration: update nydusd binary name

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
This PR fixes the readbw FIO limit for clh due to the golang bump to 1.19
Fixes #5272
> metrics: Fix readbw FIO limit for clh

- .ci/static-checks.sh
- integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json.in
- integration/confidential/fixtures/offline-fs-kbc/auth.json.in
- integration/confidential/lib.sh
- integration/containerd/confidential/agent_image.bats
- integration/containerd/confidential/fixtures/container-config_authenticated.yaml
- integration/kubernetes/confidential/agent_image.bats
Add the three new test scenarios described in the issue for containerd w/ crictl and kubernetes 
Fixes: #5209
Depends-on: github.com/kata-containers/kata-containers#5680
> Authenticated registry tests

- integration/kubernetes/init.sh
The timeout threshold for flannel for s390x is a little bit tight. This is to relax it to 60 secs.
Fixes: #5288
> CI: Relax timeout threshold for flannel

- integration/containerd/confidential/fixtures/container-config_authenticated.yaml
- integration/kubernetes/confidential/agent_image.bats
Switch test image to use the multi-arch protected image
Fixes: #5291
> CC | ci: Enable s390x auth reg e2e tests

- metrics/lib/common.bash
- metrics/lib/json.bash
This PR defines general variables that are being used in the metrics CI to avoid the failure of undefined variable while running a benchmark locally.
Fixes #5309
> metrics: Defined general variables

- integration/kubernetes/cleanup_bare_metal_env.sh
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/run_kubernetes_tests.sh
This is to prevent [cleanup_bare_metal_env.sh](https://github.com/kata-containers/tests/blob/main/integration/kubernetes/cleanup_bare_metal_env.sh) from deleting cni plugin files on baremetal if it is triggered to re-initialize a k8s cluster.
You can find a detailed discussion in #5297.
The changes are verified to work with a [test](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-main-PR/1312/).
Fixes: #5295
> CI: Prevent removing cni plugins for retry on baremetal

- metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR deletes the daemonset used in iperf3 network metrics in order to ensure a clean environment after running the network metrics.
Fixes #5312
> metrics: Delete daemonset from network metrics

- .ci/ci_job_flags.sh
- .ci/install_kata_image.sh
- integration/confidential/lib.sh
- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/agent_image_encrypted.bats
- integration/kubernetes/confidential/lib.sh
Let's ensure we use the TDX specific image with the QEMU CI, as it uses the eaa_kbc as the aa_kbc.  For Cloud Hypervisor we still stick to using offline_fs_kbc and the "default" image as attestation is not yet implemented on its side.
Fixes: #5233
> CC | ci: Use TDX specific guest image for QEMU CI

- .ci/jenkins_job_build.sh
This is to remove `config-settings.go` at `jenkins_job_build.sh` and defer generating it at runtime installation for kata-container CI jobs on non-x86_64 architectures.
Fixes: #5314
> CC: defer configuring runtime config settings for kata-container CI

- lib/common.bash
This PR adds sudo to get the ctr list in order to have a consistency as all the functions are using sudo with ctr.
Fixes #5316
> lib: Add missing sudo for ctr list

- functional/sev/run.sh
sev: added rust installation on host
Needed to build sevctl
Fixes: [#5320](https://github.com/kata-containers/tests/issues/5320)
> Sev cargo sourcing

- .ci/install_runtime.sh
CC doesn't use agent-ctl for anything and its build time is quite expensive for us.
Fixes: #5318
> CC | install_runtime: Don't install agent-ctl for CC

- integration/kubernetes/init.sh
This PR fixes the parenthesis on the init.sh that is being used in k8s.
Fixes #5322
> k8s: Fix parenthesis on init.sh

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-sv-c1-small-x86-01.toml
This PR adjust the average for the write 95 percentile for the FIO metrics.
Fixes #5330
> metrics: Adjust write 95 percentile for FIO

- .ci/install_kata.sh
- .ci/install_kata_kernel.sh
upcall is a must feature for Dragonball to enable device hotplug, so in CI system we will add upcall patches into build kernel process to let Dragonball use the guest kernel with upcall server.
Depends-on: github.com/kata-containers/kata-containers#5712 
fixes: #5293
Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>
> runtime-rs: add upcall kernel patch into CI

- .ci/ci_job_flags.sh
This PR removes duplicated flags in some of the clh jobs as they repeat in order to make easier to read the ci_init_flags script.
Fixes #5166
> ci: Remove duplicated flags in clh jobs

- .ci/install_kata_kernel.sh
- .ci/install_runtime.sh
1. dragonball is mispelled as dragonabll for upcall kernel.
2. we need to update the config file for Dragonball in order to let
upcall kernel be used.
fixes: #5354
Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>
> test: update ci system to let dragonball use upcall 

- .ci/ci_entry_point.sh
Pass test_type to ci_entry_point.sh to adjust test range of jenkins CI.
Fixes: #5339
> ci: pass test_type to ci_entry_point.sh

- integration/kubernetes/init.sh
The extension for CNI config file has been modified in recent versions of cri-o, from "conf" to "conflist".
Fixes: #5362
> Fix CNI config file extension for cri-o testing.

- integration/containerd/cri/integration-tests.sh
After calling containerd's integration test script, then trap the error and print out containerd's log if the remain tests failed.
Fixes: #5348
> cri-containerd: avoid printing containerd log twice

- metrics/density/runtimeclass_workloads/sysbench-pod.yaml
This PR updates the sysbench pod yaml by removing the shareProcessNamespace configuration as this bench does not need that processes in the container are visible to all containers in the same pod.
Fixes #5370
> metrics: Update sysbench pod yaml

- .ci/ci_job_flags.sh
- functional/sev/run.sh
- integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml
- integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml
- integration/kubernetes/confidential/sev.bats
Docker fails to pull encrypted image to get labels. Use the unencrypted image (which has the same labels) instead.
Fixes: #5360
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>
cc: @ryansavino
> SEV: Fix pulling image labels

- cmd/check-spelling/data/projects.txt
This PR adds Tokio as part of our spell check dictionary as this is part of Rust.
Fixes #5378
> spellcheck: Add Tokio to dictionary

- functional/sev/run.sh
Let's see if removing the redundant containerd installation breaks stuff.
@ryansavino @fidencio @stevenhorsman
> SEV: Remove redundant containerd installation

- cmd/checkmetrics/history/history.sh
This PR adds support to gathered the latency metrics that we get from the artifacts when running the metrics CI.
Fixes #5387
> metrics: Support to gathered latency results

- .ci/configure_containerd_for_sgx.sh
Using Kata containers in a kubernetes cluster with SGX requires a pod annotation. Add script that configures and unconfigures this annotation.
Fixes #5374
> ci: add script to configure containerd for sgx

- cmd/check-spelling/data/projects.txt
This PR adds Cassandra as part of our spell check dictionary as this is part of the metrics benchmarks.
Fixes #5393
> spellcheck: Add Cassandra to dictionary

- cmd/check-spelling/data/projects.txt
- metrics/density/README.md
This PR adds the sysbench metrics information for the current sysbench that we have.
Fixes #5396
> docs: Add sysbench metrics information

- .ci/lib.sh
Fixes bug in CCv0 where Kata Containers repo wouldn't be updated
Fixes: github.com/https://github.com/kata-containers/kata-containers/issues/4806
Signed-off-by: Liam Wilkinson <liam.wilkinson@ibm.com>
> CC: Add check in function clone_katacontainers_repo for newer code

- stability/stressng_dockerfile/Dockerfile
- stability/stressng_dockerfile/stressng.sh
This PR adds stress-ng testing for stability tests for kata containers.
Fixes https://github.com/kata-containers/tests/issues/5398
> Add stress-ng testing

- versions.yaml
The images used in the flannel version for CI - `v0.20.2` doesn't support `ppc64le`. Use the latest yaml until the next release to fix the Power CI.
Fixes: #5403
> ci: use flannel from master for ppc64le

- .ci/lib.sh
This reverts commit 561f851e93163187c77ac6d050d036d70677d23c.
Checking out the 'kata_default_branch' overwrites necessary changes that may be in the repo under test.
Fixes: #5431
> CC: Revert "CC: Add check in function clone_katacontainers_repo for newer code"

- stability/stressng_dockerfile/stressng.sh
This PR adds the stressor and floating test for stress-ng.
Fixes #5427
> stability: Add floating and stressor test for stress-ng

- Makefile
This PR adds the stability baremetal rule at the makefile for the stressng that will run on the baremetal.
Fixes #5433
> makefile: Add stability baremetal tests

- cmd/checkmetrics/history/history.sh
This PR adds the collection for iperf3 parallel results that we got from metrics CI.
Fixes #5437
> metrics: Add collection for iperf3 parallel results

- integration/kubernetes/confidential/sev.bats
Change sev.bats to use env variable RUNTIMECLASS instead of OPERATOR=true to determine how to set the runtime class.
Fixes: #5414
> sev: Use RUNTIMECLASS instead of OPERATOR env variable

- integration/kubernetes/cleanup_bare_metal_env.sh
- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/init.sh
- integration/kubernetes/run_kubernetes_tests.sh
This is to relax timeout threshold for flannel and prevent removing cni plugins for retry on baremetal.
The timeout threshold for flannel for s390x is a little bit tight.
This is to relax it to 60 secs.
Fixes: #5288 and #5295 for stable-3.0
(cherry picked from commit 405637f)
(cherry picked from commit dff44db)
> CI: Stabilize kubernetes integration tests

- .ci/lib.sh
- .ci/static-checks.sh
- README.md
- cmd/github-labels/labels.yaml.in
- cmd/pmemctl/pmemctl.sh
- versions.yaml
This will allow tests to be run with the correct branch reference on the newly created stable-3.1 branch.
Fixes: #5455
> stable-3.1: Change references from main to stable-3.1

- integration/kubernetes/confidential/fixtures/service.yaml.in
- integration/kubernetes/confidential/sev.bats
Set KBS_URI via annotation and don't modify the kernel params if we're using a new config file.
Note that this is written to keep the tests from breaking before and after we merge https://github.com/kata-containers/kata-containers/pull/5665. This requires one extra conditional. Once we have 5665 merged I will remove it.
@jimcadden
> SEV: Add annotation support

- stability/stressng.sh
This PR adds a new stressor CPU test for stress-ng as well as puts the file of stressng.sh in the proper file path.
Fixes #5453
Signed-off-by: Gabriela Cervantes [gabriela.cervantes.tellez@intel.com](mailto:gabriela.cervantes.tellez@intel.com)
> stability: Add a new stressor CPU test

- .ci/run_metrics_PR_ci.sh
This PR adds the latency test for clh as test selector so it can be used for the kata dashboard.
Fixes #5445
> metrics: Add latency test as test selector

- cmd/checkmetrics/history/history.sh
This PR adds the collection for iperf3 jitter results that we got from metrics CI.
Fixes #5443
> metrics: Add collection for iperf3 jitter results

- .ci/ci_job_flags.sh
- .ci/run.sh
This PR adds metrics cloud hypervisor job so it only installs cloud hypervisor and run only cloud hypervisor metrics benchmarks.
Fixes #5463
> ci: Add metrics cloud hypervisor job

- .ci/.golangci.yml
The linters `deadcode`, `structcheck` and `varcheck` are deprecated since `v1.49.0`. `unused` can be used instead.
Fixes: #5471
> ci: remove deprecated linters

- .ci/lib.sh
When auto remove k8s, some important tools like curl git or make may be removed accordingly. Thus install them back.
Fixes: #5469
> ci: some tools missing when remove k8s

- stability/cassandra_stress.sh
This PR adds more write tests using CQL for the cassandra stress tool test.
Fixes #5478
> stability: Add more write tests for cassandra stress tool

- .ci/run_metrics_PR_ci.sh
This PR adds the iperf test for clh as test selector so it can be used in the kata dashboard.
Fixes #5481
> metrics: Add iperf test as test selector

- .ci/aarch64/configuration_aarch64.yaml
footloose test based on dragonball can't pass on Arm. Skip for now until we fix it.
Fixes: #5486
> k8s/arm64: skip footloose test for DB

- .gitignore
.gitignore has been updated to contain the line "cmd/check-markdown/kata-check-markdown".
Fixes #4790
Signed-off-by: Maxwell Wendlandt <maxjman101@gmail.com>
> gitignore: Added cmd/check-markdown/kata-check-markdown to .gitignore

- cmd/checkmetrics/history/history.sh
This PR enables the possibility gathered the bandwidth iperf3 results at the history.sh script.
Fixes #5500
> metrics: Add bandwidth iperf3 results to history.sh

- .ci/ppc64le/lib_install_qemu_ppc64le.sh
It would be optimal to verify virtiofsd installation before proceeding.
Fixes: #5465
> ppc64le: check if virtiofsd is installed

- metrics/time/launch_times.sh
This PR replaces ctr with CTR_EXE which is defined in the metric lib common.bash as well as it uses sudo to have uniformity across the metrics scripts.
Fixes #5504
> metrics: Use variables defined in common.bash

- metrics/network/nginx_kubernetes/runtimeclass_workloads/nginx-networking.yaml
This PR adds the deployment.yaml for nginx network metrics k8s test.
Fixes #5506
> metrics: Add nginx yaml for k8s test

- .ci/aarch64/install_rom_aarch64.sh
- .ci/aarch64/lib_install_qemu_aarch64.sh
- .ci/install_runtime.sh
Enable pflash in configuration after installation. Also, as nvdimm support for qemu on arm need ACPI support, uefi installation should be set to default when install runtime.
Fixes: #5467
> uefi/arm64: enable pflash after install it.

- .ci/.golangci.yml
This pretty much breaks a lot of things, interfaces, tests, initialization of structs, more annoying then helpfull.
Fixes: #3604
> tests: drop fieldaligment

- .ci/ci_job_flags.sh
- .ci/install_kata.sh
- .ci/install_kata_image.sh
- .ci/install_runtime.sh
- integration/confidential/lib.sh
- lib/common.bash
This is to run e2e tests differently based on TEE support for s390x. If the environment is detected, a secure image is built. Otherwise, kernel+rootfs is used for the test.
Fixes: #5429
> CC: Enable e2e tests for IBM Z secure execution (SE)

- metrics/density/memory_usage_inside_container.sh
This PR replaces ctr with CTR_EXE which is defined in the metrics lib common.bash as well as it uses sudo to have uniformity across the metrics scripts.
Fixes #5524
> metrics: Fix memory inside container test

- lib/common.bash
This PR adds extra steps to clean env properly for ctr with RunC in order to properly delete containers when we run with RunC.
Fixes #5529
> lib: Add extra steps to clean env for ctr with RunC

- .ci/setup.sh
- .github/workflows/main.yml
> CC | ci: replace $TRAVIS with $GITHUB_ACTION in setup

- metrics/density/fast_footprint.sh
This PR updates the fast footprint test to use the CTR_EXE variable that is being used in other metric tests and it is defined in metrics/lib/common to have uniformity across the tests.
Fixes #5535
> metrics: Update fast footprint test

- .ci/jenkins_job_build.sh
This is to remove config-settings.go and defer generating it at runtime installation for kata-container CI jobs on non-x86_64 architectures.
Fixes: #5314
(cherry picked from commit 66842c4a1edae5afe78dfef9200489e990c4b8db)
> tests: defer configuring runtime config settings for kata-container CI

- cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric7.toml
This PR updates latency value due the change that was introduced to stop building kata components and use kata deploy as part of the CI.
Fixes #5549
> metrics: Update latency value

- .ci/install_crio.sh
Recently we've changed the way we build our components in the CI, and with that change we've been forcing the usage of docker (instead of podman) with CRI-O.
This, however, introduced a regression and podman local registries are transparently understood by CRI-O, but the docker one must be explicitly configured.
Fixes: #6510
> cri-o: explicitly setup docker local registry

- versions.yaml
This PR updates the hadolint version to v2.12.0 which has a changes:
- Try a newer GHC version for valid MacOS Ventura builds
- build(deps): bump actions/cache from 3.0.4 to 3.0.11
- build(deps): bump cachix/install-nix-action from 17 to 18
- build(deps): bump cachix/cachix-action from 10 to 12
Fixes #5545
> versions: Update hadolint version

- metrics/README.md
- metrics/time/README.md
This PR adds a README for boot time metrics which are part of the kata metrics CI.
Fixes #5560
> docs: Readme for boot time metrics

- integration/kubernetes/init.sh
When starting the cri service, we need to stop/restart it.
We used to stop containerd, assuming it was the one being started anyway, but it is an error: when we test with cri-o, stopping containerd also stops docker, which is needed by cri-o to access its image repository.
Fixes: #5544
> ci: do not stop containerd when testing with crio

- integration/kubernetes/cleanup_env.sh
- integration/kubernetes/init.sh
Using the unix:// prefix, as the current form is deprecated.
Fixes: #5557
> ci: Update cri endpoint for kubernetes tests

- integration/kubernetes/confidential/fixtures/service.yaml.in
- integration/kubernetes/confidential/sev.bats
Adds a test for SEV-ES and some minor cleanup of `sev.bats`. 
In theory we could double the number of tests by running each with SEV and SEV-ES. I think that would be unnecessary use of resources. Instead, we just run the most strict test (encrypted container with check of launch measurement) with both SEV and SEV-ES. SEV-ES only differs slightly from SEV (mainly attestation) so I think this is appropriate. 
@ryansavino @dubek
I think the SEV CI might currently fail without https://github.com/confidential-containers/operator/pull/180. I have tested locally with that PR and it seems to work.
> Add SEV-ES Test

- metrics/network/nginx_kubernetes/nginx-network.sh
This PR deletes the nginx service in order to have a clean environment while running the nginx benchmark.
Fixes #5569
> metrics: Delete nginx service

- metrics/time/launch_times.sh
This PR updates the launch times test to grab dmesg boot time when we are using kata containers and do not use it when we are using the runc.
Fixes #5564
> metrics: Update launch times test

- metrics/disk/c-ray/cray.sh
This PR replaces ctr for the CTR_EXE variable to have uniformity across the metrics scripts.
Fixes #5588
> metrics: Use CTR_EXE variable in cray script

- functional/tracing/test-agent-shutdown.sh
- lib/error.sh
This PR adds two commts that will help to debug any future issue that we happen to have with the `test-agent-shutdown`, and fixes a false-positive that's been blocking github.com/kata-containers/kata-containers#6648 to be merged
> test-agent-shutdown: Fix false positive match

- metrics/lib/common.bash
This PR adds the http_proxy and https_proxy variables to the docker build arguments in order to avoid failures when building the images behind a proxy.
Fixes #5601
> metrics: Add http_proxy to docker build arguments

- cmd/check-spelling/data/projects.txt
- metrics/README.md
- metrics/machine_learning/README.md
This PR adds the Tensorflow documentation as we already have Tensorflow
benchmark as part of the Kata Containers metrics.
> docs: Add Tensorflow documentation

- .ci/vfio_jenkins_job_build.sh
Try upgrading from version 32 to 37 for the cloud image used in the vfio test.
Fixes: #5612
> vfio: Upgrade to newer version of fedora for vfio test

- .ci/kata-arch.sh
- .ci/lib.sh
This is to make `kata-arch.sh` return a given `ARCH` value when an environment variable `CROSS_BUILD` is set to true. It is necessary to add a proper rust toolchain target on a `x86_64` host machine.
Fixes: #5617
> CI: Support cross-compilation for rust installation

- .ci/static-checks.sh
One of the links we check fails with a 502 due to 'br' being in the list. The PR where this happen is kata-containers/community#326.  Remove 'br' from the list. 'None' was missing from the list so let's add it too.
Fixes: #6627
> static-checks: Accept-encoding 'none' instead of 'br'

- functional/vfio/run.sh
The PCI device entry for the modern virtio net device has been updated (https://pci-ids.ucw.cz/read/PC/1af4/1041), so make the matching less strict to find the new device. This hits VMs using an updated pci device database.
Fixes: #6790
> vfio: Match 'Virtio 1.0 network device' device name

- .ci/static-checks.sh
Some endpoints block HEAD requests while allowing GET. To prevent false positives from url check, switch to using GET, but still only read the header.
Fixes: #6627
> static-checks: Switch to GET for URL checks

- .ci/setup_env_alinux.sh
- .ci/setup_env_centos.sh
- .ci/setup_env_fedora.sh
- .ci/setup_env_rhel.sh
- .ci/setup_env_ubuntu.sh
- .ci/teardown.sh
Procenv has been regularly hanging in the teardown of vfio test, possibly since upgrading to fedora 37. The procenv output does not appear to be consumed or useful to anyone, so remove all traces of it.
Fixes: kata-containers/kata-containers#6790
> ci: Remove uses of procenv

- .ci/static-checks.sh
`*.bin` files are binary and cannot include a license or copyright header; skip them, similarly to other binary files (`*.jpg`, `*.png`, etc.).
Fixes: #5632
This PR was ported from branch CCv0 (original PR #5208) using:
```
git cherry-pick 5035fe8f199098658143e2526db42e1b73633d5a
```
and modifying the commit message to point to the new github issue.
> ci: Ignore license header check for *.bin files (main)

- .ci/static-checks.sh
Some websites <cough>twitter</cough> refuse to return any data without the request including a cookie. Activate cookie processing in curl so that we can retrieve the data and finally get url checks to work.
Fixes: #6627
> static-checks: Enable cookie store for curl

- cmd/check-spelling/data/projects.txt
- metrics/machine_learning/README.md
This PR includes Pytorch benchmark performance metrics that currently are part of the kata containers metrics scripts.
Fixes #5628
> docs: Include Pytorch benchmark metrics

- metrics/machine_learning/tensorflow.sh
This PR fixes the duplication of printing twice the nhwc tensorflow results in a json file.
Fixes #5635
> metrics: Fix tensorflow json results

- metrics/lib/common.bash
This PR adds the flag of --build-arg http_proxy and https_proxy for the docker build command to make it work when this is used behind a proxy.
Fixes #5638
> metrics: Add build arg with proxys for docker build command

- stability/cassandra_stress.sh
This PR allow us to use variables that are already defined in the common script  in the cassandra script like DOCKER_EXE and
CTR_EXE to have uniformity across the tests.
Fixes #5641
> stability: Use variables defined in common for cassandra script

- .ci/run.sh
Those tests are now covered as part of the GitHub actions we have, and currently we're duplicating those (and also spending the resources twice).
Let's stop running those for the cases we already cover with GitHub actions, and update those little by little as we progress on the GHA effort.
Fixes: #5643
> tests: Sstop running `make kubernetes` with containerd

- metrics/disk/c-ray/Dockerfile
This PR updates the c-ray dockerfile in order to avoid that when installing the packages we have an interactive mode.
Fixes #5649
> metrics: Update c-ray dockerfile

- .ci/install_qemu.sh
We're currently getting the following error when building QEMU for TDX as part of our Jenkins CI:
```sh
11:57:40 [install_qemu.sh:64] INFO: qemu type 'tdx' not supported
11:57:41 Overview:
11:57:41
11:57:41 	Build and install QEMU for Kata Containers
11:57:41
11:57:41 Usage:
11:57:41
11:57:41 	install_qemu.sh [options]
11:57:41
11:57:41 Options:
11:57:41     -d          : Enable bash debug.
11:57:41     -h          : Display this help.
11:57:41     -t <qemu> : qemu type, such as tdx, vanilla.
11:57:41 [jenkins_job_build.sh:252] ERROR: ci/setup.sh
```
This is happening because we try to proceed building other artefacts after the build of QEMU for CC is done, while we should simply stop there.
Fixes: #5651
Depends-on: github.com/kata-containers/kata-containers#6919
> qemu: Fix TDX build

- .ci/install_kubernetes.sh
The gpg key hosting at packages.cloud.google.com is known to fail regularly, and it is recommended[1] to use a different mirror for the gpg key. Switch to fetching apt gpg key from there, to reduce test failures.
> ci: Fetch k8s gpg key from dl.k8s.io

- .ci/run.sh
It seems that doing [[ cond ]] && foo && bar may return a failure when [[ cond ]] is not positive, which leads to the tests to fail after the changes added as part of 5ae859ba8be07f2896b268a3ff64581950993e8d.
Fixes: #5643
> ci: run.sh: Remove "&&" operators from tests conditionals

- stability/stressng_dockerfile/Dockerfile
This PR updates the stressng dockerfile in order to avoid that when installing the packages we have an interactive mode.
Fixes #5657
> stability: Update stressng dockerfile

- versions.yaml
This PR updates the xurls version to 2.5.0. This changes the following:
Add xurls -fix=all to replace URLs with temporary redirects as well 
xurls -fix now shows more detailed info on broken URLs 
xurls -fix now uses the method HEAD before falling back to GET
xurls -fix now provides a meaningful User-Agent header Add a xurls -version flag
Update lists of TLDs and schemes
Fixes #5659
> versions: Update xurls version to 2.5.0

- metrics/machine_learning/tensorflow_dockerfile/Dockerfile
This PR updates the Tensorflow Dockerfile in order to avoid that when installing the packages we have an interactive mode.
Fixes #5662
> metrics: Update tensorflow Dockerfile

- .ci/install_kubernetes.sh
SEV tests regularly fail with this error message:
Err:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.250.189.174 443]
It is likely, that the issue is caused by a TLS MITM proxy, that does network scanning. If we switch to the http version of the mirror, we might have more luck. This is safe to do because the mirror is verified using gpg signatures.
Fixes: #7039
> ci: Switch to http kubernetes mirror

- .ci/jenkins_job_build.sh
As we decided not to package a snap, it would make sense to remove a test accordingly. This redisual also affects a test failure for non-x86 CI baseline jobs.
Fixes: #5689
> tests: Remove a snap test

- .ci/run.sh
Let's do it as GHA is not really stable at the moment
Fixes: #5704
> run: Bring back k8s tests for dragonball

- .ci/ci_job_flags.sh
- .ci/install_kata.sh
- .ci/install_kata_image.sh
- .ci/install_kata_kernel.sh
- .ci/install_ovmf_sev.sh
- .ci/install_ovmf_x86_64.sh
- .ci/install_qemu.sh
- .ci/install_runtime.sh
- .ci/lib.sh
- .ci/run.sh
- Makefile
- integration/confidential/lib.sh
- integration/kubernetes/confidential/fixtures/service.yaml.in
- integration/kubernetes/confidential/lib.sh
- integration/kubernetes/confidential/sev.bats
- integration/kubernetes/confidential/snp.bats
- integration/kubernetes/lib.sh
- lib/common.bash
Fixes: [#5593](https://github.com/kata-containers/tests/issues/5593)
added makefile target as well
moved common functions out of sev.bats
few minor fixes in separate commits
> snp: added snp unencrypted test

- .ci/run_metrics_PR_ci.sh
- metrics/density/memory_usage_inside_container.sh
This PR make the metrics test repeats failed runs,
up to three times.
Removes csv output format, as it is not needed.
Fixes: #5694
> metrics: Fix non valid results on memory usage inside container

- integration/kubernetes/e2e_conformance/run.sh
- kata-webhook/README.md
- kata-webhook/main.go
- versions.yaml
> k8s-conformance: Add support to run tests in parallel

- cmd/check-spelling/data/acronyms.txt
- cmd/check-spelling/data/main.txt
Add commonly used words like mmio, APIC, upcall to Kata CI spelling check.
fixes: #5715
> spell: update spelling dictionary

- cmd/check-spelling/data/acronyms.txt
- cmd/check-spelling/data/main.txt
Add words like TDX, mptable, fdt and etc. to help enrich Kata spelling check.
fixes: #5719
> dict: add more words into kata-spell-check

- cmd/check-spelling/data/acronyms.txt
Add pio into acronyms.txt
fixes: #5722
> Dict: add pio into Kata CI spelling check

- .ci/static-checks.sh
Since .dtd is used in Dragonball for aarch64 unit test and .dtd is a binary file so it could not be added apache 2.0 license line of code.
So we should avoid checking license for *.dtd file in our CI.
fixes: #5724
> license: avoid checking license for *.dtd file

- functional/vfio/run.sh
Fix default port assignment with an explicit value in the TOML It was implicit before and now the runtime will bail out if we did not set it explicitly. Update the configuration and set it. This will make the intent more clear.
Fixes: #5726
> vfio: Fix default port assignment

- .ci/openshift-ci/smoke/http-server.yaml
- kata-webhook/deploy/webhook.yaml
- kata-webhook/webhook-check.sh
Modify the smoke_test container securityContext to work well with OCP 4.14.
Fixes: https://github.com/kata-containers/tests/issues/5671
@wainersm this is also required in order to allow OCP 4.14 pipelines
> ci/openshift-ci: Fix the smoke_test permissions

- .ci/lib.sh
the GOPATH variable is used by some variables before it gets initialized. Reorder the logic to work properly.
Fixes: #5713
@wainersm: This is a simple fix for running CI scripts locally
> ci: Initialize GOPATH before it's used

- .ci/install_kata_image.sh
- .ci/lib.sh
A few names must be changed, as we're using those as close from the `main` as possible.
* sev-rootfs-initrd -> rootfs-initrd-sev
* tdx-rootfs-image -> rootfs-image-tdx
Depends-on: github.com/kata-containers/kata-containers#7513
> cc: install_kata_image: Update to the Aug 1st kata-containers merge

- .ci/install_guest_component_dependencies.sh
- .ci/jenkins_job_build.sh
> guest-component depds: Install clang and devmapper libs

- .ci/setup_env_ubuntu.sh
Currently this script needs bc to run before installing dependencies.
Fixes: #5744
> ci: fix missing bc error during setup

- integration/kubernetes/confidential/sev.bats
- versions.yaml
bash (ls) regex in quotes was throwing errors and k8s services/pods were not getting cleaned up.
Service yamls weren't being deleted due to partial name including prefix file path, now trims using 'basename'.
Removed redundant TEST_DIR on the yaml file to be deleted.
The updated simple-kbs uses a openssl v3 supported rust docker image.
Fixes: #5760
> Sev ci fixes for `k8s_delete_all` and updating the simple-kbs

- integration/confidential/lib.sh
Adding -w iptables will wait for the lock on the xtables to be released.
Fixes: #5765
> CCv0: Add -w to iptables in configure_cc_containerd

- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/lib.sh
- integration/kubernetes/confidential/tests_common.sh
- Refactor out common functions into test_common.sh library. This libarary can be used in other bats test files and is prep for the pull_image with snapshotter tests
- Pattern similar to that used in containerd tests
Fixes: #5767
> tests: Refactor out common functions

- .ci/jenkins_job_build.sh
- integration/nydus/nydus_tests.sh
- integration/nydus/nydusd-config.json
- integration/nydus/snapshotter-config.toml
To support the v0.12.0 nydus-snapshotter, we need to update the config files and the commandline to start nydus-snapshotter.
Depends-on: github.com/kata-containers/kata-containers#7961
> integration: update nydus tests

- .ci/ci_job_flags.sh
- .ci/install_cri_containerd.sh
- integration/containerd/cri/integration-tests.sh
- integration/nydus/nydus_tests.sh
- integration/nydus/nydusd-config.json
- integration/nydus/snapshotter-config.toml
This will easily allow us to test against the forked and the upstream containerd.
As the tests had changed completely on main, and as the main branch should never ever see the forked containerd, we're doing this only for the CCv0 case.
> CC | Adapt to the containerd changes done on kata-containers repo

- integration/kubernetes/confidential/agent_image.bats
This PR is to skip a test `Test can pull an unencrypted image inside the guest` for IBM Z secure execution until the containerd is updated to `v1.7`.
Fixes: #5781
> CC: Skip test pulling image inside guest temporarily for IBM SE

- .ci/jenkins_job_build.sh
There was a recent change on the Kata Containers side that ended up breaking our CI here as yq is not automagically installed anymore.
(cherry picked from commit 6bf08c833e3663cdff81e75b446325326bec500c)
> stable-3.2 | ci: Ensure we have yq installed

- integration/kubernetes/confidential/agent_image.bats
- integration/kubernetes/confidential/fixtures/pod-config-secret.yaml.in
- integration/kubernetes/confidential/fixtures/pod-config.yaml.in
- integration/kubernetes/confidential/fixtures/service.yaml.in
- integration/kubernetes/confidential/lib.sh
The CRI PullImage does not have a "runtime class" input, and this is being discussed at the kubernetes level on:
* https://github.com/kubernetes/enhancements/pull/4217
* https://github.com/kubernetes/kubernetes/pull/118907
For now, we're forced to pass the specific annotation to containerd.
> CC | tests: Set io.containerd.cri.runtime-handler annotation

- integration/kubernetes/cleanup_env.sh
> nydus: add var directory cleanup

- integration/kubernetes/confidential/agent_image.bats
In the kubernetes agent_image test we currently have a check:
```
echo "Check the image was not pulled in the host"
local pod_id=$(kubectl get pods -o jsonpath='{.items..metadata.name}')
retrieve_sandbox_id
rootfs=($(find /run/kata-containers/shared/sandboxes/${sandbox_id}/shared \
-name rootfs))
[ ${#rootfs[@]} -eq 1 ]
```
to ensure that the image hasn't been pulled onto the host. The reason that the check is for a single rootfs is that we found that the pause image was always pulled on the host, presumably due to it being needed to create the pod sandbox.
With the introduction of the nydus-snapshotter code we've found that on some systems (SE and TDX) it appears to be in a different location with nydus-snapshotter, so check for 1, or 0. See an issue at …
> ci: test: k8s: agent_image rootfs check

- cmd/check-spelling/data/main.txt
Add gh to the dictionary as the project is references in the release process doc
Fixes: #5792
> check-spelling: Add gh project

- .ci/static-checks.sh
Add exceptions for READMEs from tools such as kata-check-markdown and for license headers in spellcheck dictionaries.
Fixes #5796
> static checks: Add exceptions for migration

- .ci/static-checks.sh
Port of 2 commits from https://github.com/kata-containers/kata-containers/pull/8592.
**Note**: there is no intention of maintaining 2 static checks scripts beyond this. It is for https://github.com/kata-containers/kata-containers/pull/6826 to pass before testing for (https://github.com/kata-containers/kata-containers/issues/8595) is complete.
> static-checks: Try multiple user agents

- .ci/openshift-ci/cluster/install_kata.sh
- .ci/openshift-ci/run_smoke_test.sh
- .ci/openshift-ci/smoke/service_kubernetes.yaml
Plain kubernetes do not support services and such, let's modify our test.sh (and related) to allow deploying and checking kata there, which might help testing things locally with kcli.
> ci/openshift-ci: Tweak test.sh to run with kubernetes

- .ci/openshift-ci/cluster/deployments/relabel_selinux.yaml
- .ci/openshift-ci/cluster/install_kata.sh
- .ci/openshift-ci/test.sh
as kata-deploy does not currently handles selinux, this requires manual relabel of the /opt/kata folder where custom binaries are deployed.
Fixes: https://github.com/kata-containers/tests/issues/5802
> ci/openshift-ci: Enable selinux in CI runs

- .ci/openshift-ci/run_smoke_test.sh
The --retry-all-errors argument is not supported on the CI runners, use a busy loop instead.
> ci/openshift-ci: Use loop instead of curl --retry-all-errors

- .ci/openshift-ci/run_smoke_test.sh
waiting for the first response is not sufficient as OCP returns html page without error even when the route is not yet established describing the issue (why it doesn't reply with 500?). Waiting for the correct output should do better.
> ci.ocp: Improve the service-up detection

- .ci/setup_env_ubuntu.sh
Builds with the latest qemu 8.2.1 are failing with a python venv and ensurepip error. Adding these packages as qemu dependencies should fix the issue.
Fixes: #5809
Python dependency packages pulled from here:
https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/static-build/qemu/Dockerfile
I believe @niteeshkd ran into this same issue in this PR:
https://github.com/kata-containers/kata-containers/pull/9086
Docker installation of packages updated in kata-containers, but looks like the `jenkins-ci-ARM-ubuntu-20.04-main` job installs the packages on bare-metal. Hence this PR.
> install: adding packages required by latest qemu 8.2.1 build

- .ci/install_kubernetes.sh
- .ci/setup_env_ubuntu.sh
The kubernetes repositories at packages.cloud.google.com have been removed as announced in [1]. Switch to the new infrastructure at pkgs.k8s.io. Use the latest available version (v1.29).
[1] https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ .
Fixes #5811
> ci: Switch to pkgs.k8s.io

- .ci/jenkins_job_build.sh
To test PR kata-containers/kata-containers#8484, the compilation process for the kata-agent relies on protoc. The unit tests failed on arm64:
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu20.04-ARM-unit/3424/console.
Fixes: #5815
> CI: Install protobuf-compiler in the ci environment
